10.10

diff --git a/Heimdal/tests/apple/check-apple-ad.in b/Heimdal/tests/apple/check-apple-ad.in
--- a/Heimdal/tests/apple/check-apple-ad.in
+++ b/Heimdal/tests/apple/check-apple-ad.in
@@ -104,6 +104,21 @@ ${http_client} --mech=ntlm --cred-mech=ntlm --client=ktestuser@ADS \
     dc03.ads.apple.com /negotiate/ | grep 'http negotiate' > /dev/null || \
     { echo "spnego/ntlm failed" ; exit 1; }
 
+echo "	check delegation (spnego w/ kerberos credentials delegate)"
+${http_client} --mech=spnego --cred-mech=krb5 --delegate --client=ktestuser@ADS.APPLE.COM \
+    dc03.ads.apple.com /authpage/ | grep 'ImpersonationLevel: Delegation' > /dev/null || \
+    { echo "spnego/kerberos delegate failed" ; exit 1; }
+
+echo "	check delegation (spnego w/ kerberos credentials policy)"
+${http_client} --mech=spnego --cred-mech=krb5 --policy --client=ktestuser@ADS.APPLE.COM \
+    dc03.ads.apple.com /authpage/ | grep 'ImpersonationLevel: Delegation' > /dev/null || \
+    { echo "spnego/kerberos delegate failed" ; exit 1; }
+
+echo "	check delegation (spnego w/ kerberos credentials, no delegate)"
+${http_client} --mech=spnego --cred-mech=krb5 --client=ktestuser@ADS.APPLE.COM \
+    dc03.ads.apple.com /authpage/ | grep 'ImpersonationLevel: Impersonation' > /dev/null || \
+    { echo "spnego/kerberos delgate (not) failed" ; exit 1;
+}
 
 echo "	destroy all cred"
 ${gsstool} destroy --all
@@ -196,28 +211,6 @@ ${kdestroy}
 #else
 #    echo "not running windows mount test since you are no on apple network"
 #fi
-
-# ------------------------------------------------------------------------------------
-
-echo "checking ktestuser in ADS (no domain)"
-${test_gssntlm} --user=ktestuser --password=foobar --domain='' --session-key-broken > /dev/null || \
-    { echo "test failed";  exit 1; }
-
-echo "checking ktestuser in ADS (domain)"
-${test_gssntlm} --user=ktestuser --password=foobar --domain=ADS --session-key-broken > /dev/null || \
-    { echo "test failed";  exit 1; }
-
-echo "checking ktestuser in ADS (no domain)"
-sudo ${test_gssntlm} --user=ktestuser --password=foobar --domain='' --session-key-broken > /dev/null || \
-    { echo "test failed";  exit 1; }
-
-echo "checking ktestuser in ADS (domain)"
-sudo ${test_gssntlm} --user=ktestuser --password=foobar --domain=ADS --session-key-broken > /dev/null || \
-    { echo "test failed";  exit 1; }
-
-echo "checking ktestuser in ADS (failure, wrong password)"
-sudo ${test_gssntlm} --user=ktestuser --password=foobar2 --domain=ADS 2>/dev/null --session-key-broken > /dev/null && \
-    { echo "test failed";  exit 1; }
 
 # ------------------------------------------------------------------------------------
 
diff --git a/Heimdal/tests/apple/check-apple-lkdc.in b/Heimdal/tests/apple/check-apple-lkdc.in
--- a/Heimdal/tests/apple/check-apple-lkdc.in
+++ b/Heimdal/tests/apple/check-apple-lkdc.in
@@ -47,6 +47,7 @@ mkdir -p $testdir 2> /dev/null
 hodadmin="/System/Library/PrivateFrameworks/Heimdal.framework/Helpers/hod-admin"
 
 u=heimdaltestuser
+v=heimdaltestusersrp
 uid=82367346
 o=heimdalother
 u2=heimdaltestuser2
@@ -54,7 +55,6 @@ s=heimdaltestservice
 mme="heimdaltestuser@me.com"
 mmeq="heimdaltestuser\\@me.com"
 r=WELLKNOWN:COM.APPLE.LKDC
-r2=HEIM-TEST-DOMAIN.APPLE.COM
 pw=foo
 
 . ${env_setup}
@@ -155,13 +155,52 @@ dscl . -append /Users/$u NFSHomeDirectory "${testdir}/smb"
 echo "    Password"
 dscl . -passwd /Users/$u $pw
 echo "    Check keys"
-(dscl . -read /Users/$u KerberosKeys | grep KerberosKeys > /dev/null) || \
+
+echo "Creating srp lkdc user"
+
+echo "    delete"
+dscl . -delete /Users/$v 2>/dev/null >/dev/null
+echo "    create"
+dscl . -create /Users/$v
+echo "    RealName"
+dscl . -append /Users/$v RealName "Heimdal testuser srp"
+dscl . -append /Users/$v RecordName "srp${mme}"
+dscl . -delete /Users/$v AuthenticationAuthority
+dscl . -append /Users/$v AuthenticationAuthority ';ShadowHash;HASHLIST:<SALTED-SHA1,SMB-NT>'
+dscl . -append /Users/$v UniqueID $(expr $uid + 1)
+dscl . -append /Users/$v PrimaryGroupID 20
+dscl . -append /Users/$v NFSHomeDirectory "${testdir}/smb"
+echo "    SRP verififer (no pw)"
+dscl . -passwd /Users/$u $pw
+$hodadmin . srp-verifier $v srp$pw
+
+
+# XXX opendirectory/plist backend should do this
+$hodadmin . password \
+    --encryption-types=aes256-cts-hmac-sha1-96 \
+    --encryption-types=aes128-cts-hmac-sha1-96 \
+    --encryption-types=des3-cbc-sha1 \
+    --encryption-types=arcfour-hmac-md5 \
+    /Users/$u $pw
+
+{ dscl . -read /Users/$u KerberosKeys 2>&1 | grep KerberosKeys: > /dev/null ; } || \
     { echo "KerberosKeys missing" ; exit 1; }
-(dscl . -read /Users/$u dsAttrTypeStandard:AltSecurityIdentities | grep pkinit > /dev/null) || { echo "asi missing" ; exit 1; }
+{ dscl . -read /Users/$u HeimdalSRPKey 2>&1 | grep HeimdalSRPKey: > /dev/null ; } || \
+     { echo "SRP verififer missing" ; exit 1; }
+
+{ dscl . -read /Users/$u dsAttrTypeStandard:AltSecurityIdentities | grep pkinit > /dev/null; } || \
+    { echo "asi missing" ; exit 1; }
+
+#{ dscl . -read /Users/$v KerberosKeys 2>&1 | grep KerberosKeys: > /dev/null ; } && \
+#    { echo "KerberosKey there when they should not be" ; exit 1; }
+{ dscl . -read /Users/$v HeimdalSRPKey 2>&1 | grep HeimdalSRPKey: > /dev/null ; } || \
+    { echo "SRP verifier missing" ; exit 1; }
+
 
 chown -R $u "${testdir}/smb"
 
 echo $pw > ${testdir}/foopassword
+echo srp$pw > ${testdir}/srpfoopassword
 
 echo "Server domain"
 
@@ -169,16 +208,14 @@ echo "    delete"
 dscl . -delete /Users/$o 2>/dev/null >/dev/null
 echo "    create"
 dscl . -create /Users/$o
-dscl . -append /Users/$o UniqueID $(expr $uid + 1)
+dscl . -append /Users/$o UniqueID $(expr $uid + 2)
 dscl . -append /Users/$o PrimaryGroupID 20
-dscl . -append /Users/$o dsAttrTypeNative:KerberosUserName krbtgt/$r2@$r2
 
 echo "    setflags"
 $hodadmin . principal-setflags $o Server Forwardable
 
 echo "    password"
 $hodadmin . password  $o domain || exit 1
-$hodadmin . alias-add $o krbtgt/$r2@$r2  || exit 1
 
 echo "Creating server user"
 
@@ -186,42 +223,19 @@ echo "    delete"
 dscl . -delete /Users/$u2 2>/dev/null >/dev/null
 echo "    create"
 dscl . -create /Users/$u2
-dscl . -append /Users/$u2 UniqueID $(expr $uid + 2)
+dscl . -append /Users/$u2 UniqueID $(expr $uid + 3)
 dscl . -append /Users/$u2 PrimaryGroupID 20
 echo "    password"
 dscl . -passwd /Users/$u2 $pw
 echo "    checking user"
 (dscl . -read /Users/$u KerberosKeys | grep KerberosKeys > /dev/null) || \
     { echo "KerberosKeys missing" ; exit 1; }
-dscl . -append /Users/$u2 dsAttrTypeNative:KerberosUserName $u2@$r2
-
-echo "Creating server service user"
-
-echo "    delete"
-dscl . -delete /Computers/$s 2>/dev/null >/dev/null
-echo "    create"
-dscl . -create /Computers/$s
-echo "    password"
-dscl . -passwd /Computers/$s $pw
-echo "    realname"
-dscl . -append /Computers/$s RealName "Heimdal test service"
-echo "    servername"
-dscl . -append /Computers/$s dsAttrTypeNative:KerberosServerName $s@$r2
 
 echo "    setflags"
 $hodadmin . principal-setflags /Computers/$s Server
 
 echo "    password"
 $hodadmin . password          /Computers/$s user-password
-#$hodadmin . password --append /Computers/$s host-pw host/$s.$r2@$r2
-#$hodadmin . password --append /Computers/$s cifs-pw cifs/$s.$r2@$r2
-#$hodadmin . password --append /Computers/$s http-pw HTTP/$s.$r2@$r2
-#$hodadmin . password --append /Computers/$s imap-pw imap/$s.$r2@$r2
-
-echo "    aliases"
-for a in host cifs HTTP imap ; do
-    $hodadmin . alias-add /Computers/$s $a/$s.$r2@$r2
-done
 
 foundlines=$(${kadmin} -l dump | wc -l)
 if [ "X${foundlines}" = "X" -o "X${foundlines}" = X0 ] ; then
@@ -258,18 +272,19 @@ echo "Getting client initial tickets";> ${logfile}
 ${kkdestroy} -A
 ${kkinit} --kdc-hostname=localhost --canon --password-file=${testdir}/foopassword ${u}@${r} || \
 	{ ec=1 ; eval "${testfailed}"; }
-${kkinit} --kdc-hostname=localhost --canon --password-file=${testdir}/foopassword ${u2}@${r2} || \
+${kkinit} --kdc-hostname=localhost --canon --password-file=${testdir}/srpfoopassword ${v}@${r} || \
 	{ ec=1 ; eval "${testfailed}"; }
+
 
 echo "Checking that credentials are stored"
 (${kklist} -l | grep ${u}) >/dev/null || { ec=1 ; eval "${testfailed}"; }
-(${kklist} -l | grep ${u2}) >/dev/null || { ec=1 ; eval "${testfailed}"; }
+(${kklist} -l | grep ${v}) >/dev/null || { ec=1 ; eval "${testfailed}"; }
 
 echo "checking that u2 is first" > ${logfile}
-(${kklist} | grep ${u2}) >/dev/null || { ec=1 ; eval "${testfailed}"; }
+(${kklist} | grep ${v}) >/dev/null || { ec=1 ; eval "${testfailed}"; }
 echo "checking that u2 still is first (sleep 20)" > ${logfile}
 sleep 20
-(${kklist} | grep ${u2}) >/dev/null || { ec=1 ; eval "${testfailed}"; }
+(${kklist} | grep ${v}) >/dev/null || { ec=1 ; eval "${testfailed}"; }
 
 ${kkdestroy} -A
 
@@ -281,15 +296,6 @@ echo "Getting tickets"; > ${logfile}
 ${kgetcred} host/${r}@${r} || { ec=1 ; eval "${testfailed}"; }
 echo "Listing tickets"; > ${logfile}
 ${klist} > /dev/null || { ec=1 ; eval "${testfailed}"; }
-
-${kinit} --password-file=${testdir}/foopassword ${u2}@${r2} || \
-	{ ec=1 ; eval "${testfailed}"; }
-
-echo "Checking alias principal";
-for a in host cifs HTTP imap ; do 
-    echo "   alias $a"; > ${logfile}
-   ${kgetcred} ${a}/${s}.${r2}@${r2} || { ec=1 ; eval "${testfailed}"; }
-done
 
 ${kdestroy}
 
@@ -504,6 +510,7 @@ toggle_launchd malloc-unset
 rm -rf "${testdir}/smb"
 dscl . -delete /Users/$u
 dscl . -delete /Users/$u2
+dscl . -delete /Users/$v
 dscl . -delete /Users/$s
 dscl . -delete /Users/$o
 
diff --git a/Heimdal/tests/apple/check-apple-od.in b/Heimdal/tests/apple/check-apple-od.in
--- a/Heimdal/tests/apple/check-apple-od.in
+++ b/Heimdal/tests/apple/check-apple-od.in
@@ -42,37 +42,42 @@ confdir="@confdir@"
 KRB5_CONFIG="${1-${confdir}/krb5.conf}"
 export KRB5_CONFIG
 
+logfile=${testdir}/messages.log
+
 echo "checking for od.apple.com"
-(dscl /LDAPv3/od.apple.com -read /Users/smbtest  | grep 'RealName: smbtest' > /dev/null ) || \
+(dscl /LDAPv3/nod.apple.com -read /Users/smbtest  | grep 'RealName: smbtest' > /dev/null ) || \
       { echo "no od.apple.com, skipping tests" ; exit 0; }
 
-echo "Interactive kinit for smbtest@OD.APPLE.COM"
+echo "Interactive kinit for smbtest@OD.APPLE.COM"; > ${logfile}
     kinitpty=${testdir}/foopassword.rkpty
 cat > ${kinitpty} <<EOF
 expect Password
 password smbtest\n
 EOF
-   ${rkpty} ${kinitpty} ${kinit} smbtest@OD.APPLE.COM >/dev/null || { echo "kinit failed with: $?" ; exit 1; }
+   ${rkpty} ${kinitpty} ${kinit} smbtest@OD.APPLE.COM >/dev/null || { echo "kinit failed with: $?" ; cat ${logfile}; exit 1; }
 ${kdestroy}
 
 
-echo "checking ntlm"
-${test_context} --mech-type=ntlm --cred-type=ntlm \
-	--client-name='smbtest@\targetname' --password='smbtest' service@host || \
-	{ echo "ntlm check failed with: $?" ; exit 1; }
+#
+# Disable NTLM tests since nod.apple.com doesn't support it
+#
+#echo "checking ntlm"; > ${logfile}
+#${test_context} --mech-type=ntlm --cred-type=ntlm \
+#	--client-name='smbtest@\targetname' --password='smbtest' service@host || \
+#	{ echo "ntlm check failed with: $?" ; cat ${logfile}; exit 1; }
+#
+#echo "checking signing is disabled"; > ${logfile}
+#${gsstool} supporte --opt| \
+#    grep -e 'NTLM session key.*no' > /dev/null || \
+#	{ echo "signing and joined to od.apple.com" ; cat ${logfile}; exit 1 ; }
 
-echo "checking signing is disabled"
-${gsstool} supporte --opt| \
-    grep -e 'NTLM session key.*no' > /dev/null || \
-	{ echo "signing and joined to od.apple.com" ; exit 1 ; }
-
-echo "checking mounting with NTLM"
+echo "checking mounting with NTLM"; > ${logfile}
 host=$(hostname)
 if expr "$host" : '.*\.apple\.com' > /dev/null ; then
     launchctl load -F /System/Library/LaunchDaemons/com.apple.smbd.plist
     killall smbd
     sleep 3
-    ${winmount} ${testbase}/apple/coswin7-od.plist ${host} || exit 1
+    ${winmount} ${testbase}/apple/coswin7-od.plist ${host} || { cat ${logfile}; exit 1; }
 else
     echo "not running windows mount test since you are no on apple network"
 fi
diff --git a/OpenLDAP/OpenLDAP/configure b/OpenLDAP/OpenLDAP/configure
--- a/OpenLDAP/OpenLDAP/configure
+++ b/OpenLDAP/OpenLDAP/configure
@@ -1618,7 +1618,7 @@ Optional Packages:
   --with-cyrus-sasl	  with Cyrus SASL support [auto]
   --with-fetch		  with fetch(3) URL support [auto]
   --with-threads	  with threads [auto]
-  --with-tls		  with TLS/SSL support auto|openssl|gnutls|moznss [auto]
+  --with-tls		  with TLS/SSL support auto|secure-transport|openssl|gnutls|moznss [auto]
   --with-yielding-select  with implicitly yielding select [auto]
   --with-mp               with multiple precision statistics auto|longlong|long|bignum|gmp [auto]
   --with-odbc             with specific ODBC support iodbc|unixodbc|odbc32|auto [auto]
@@ -2979,7 +2979,7 @@ fi
 if test "${with_tls+set}" = set; then
   withval=$with_tls;
 	ol_arg=invalid
-	for ol_val in auto openssl gnutls moznss yes no  ; do
+	for ol_val in auto secure-transport openssl gnutls moznss yes no  ; do
 		if test "$withval" = "$ol_val" ; then
 			ol_arg="$ol_val"
 		fi
@@ -4377,8 +4377,8 @@ fi
 
 if test $ol_enable_lmpasswd = yes ; then
 	if test $ol_with_tls = no ; then
-		{ { echo "$as_me:$LINENO: error: LAN Manager passwords require OpenSSL" >&5
-echo "$as_me: error: LAN Manager passwords require OpenSSL" >&2;}
+		{ { echo "$as_me:$LINENO: error: LAN Manager passwords require TLS" >&5
+echo "$as_me: error: LAN Manager passwords require TLS" >&2;}
    { (exit 1); exit 1; }; }
 	fi
 fi
@@ -19341,7 +19341,176 @@ if test $ol_with_tls = yes ; then
 fi
 
 ol_link_tls=no
-if test $ol_with_tls = openssl || test $ol_with_tls = auto ; then
+if test $ol_with_tls = secure-transport || test $ol_with_tls = auto ; then
+	save_CPPFLAGS="$CPPFLAGS"
+	CPPFLAGS="$CPPFLAGS -F/System/Library/PrivateFrameworks"
+
+
+
+for ac_header in Security/SecureTransport.h CoreDaemon/XSCipher.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  { echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6; }
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+ac_res=`eval echo '${'$as_ac_Header'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking $ac_header usability" >&5
+echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking $ac_header presence" >&5
+echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <$ac_header>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $ac_header:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: $ac_header: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: $ac_header: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## --------------------------------------------- ##
+## Report this to <http://www.openldap.org/its/> ##
+## --------------------------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6; }
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=\$ac_header_preproc"
+fi
+ac_res=`eval echo '${'$as_ac_Header'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+
+fi
+
+done
+
+	CPPFLAGS="$save_CPPFLAGS"
+	if test $ac_cv_header_Security_SecureTransport_h = yes &&
+	   test $ac_cv_header_CoreDaemon_XSCipher_h = yes ; then
+		ol_with_tls=secure-transport
+		ol_link_tls=yes
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SECURE_TRANSPORT 1
+_ACEOF
+
+		TLS_LIBS="-framework Security -framework CoreDaemon"
+	elif test $ol_with_tls = secure-transport ; then
+		{ { echo "$as_me:$LINENO: error: Can't build with SecureTransport: required header not found" >&5
+echo "$as_me: error: Can't build with SecureTransport: required header not found" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+fi
+
+if test $ol_link_tls = no ; then
+	if test $ol_with_tls = openssl || test $ol_with_tls = auto ; then
 
 for ac_header in openssl/ssl.h
 do
@@ -19488,8 +19657,8 @@ fi
 done
 
 
-	if test $ac_cv_header_openssl_ssl_h = yes ; then
-		{ echo "$as_me:$LINENO: checking for SSL_library_init in -lssl" >&5
+		if test $ac_cv_header_openssl_ssl_h = yes ; then
+			{ echo "$as_me:$LINENO: checking for SSL_library_init in -lssl" >&5
 echo $ECHO_N "checking for SSL_library_init in -lssl... $ECHO_C" >&6; }
 if test "${ac_cv_lib_ssl_SSL_library_init+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -19552,14 +19721,14 @@ fi
 echo "${ECHO_T}$ac_cv_lib_ssl_SSL_library_init" >&6; }
 if test $ac_cv_lib_ssl_SSL_library_init = yes; then
   have_openssl=yes
-			need_rsaref=no
+				need_rsaref=no
 else
   have_openssl=no
 fi
 
 
-		if test $have_openssl = no ; then
-			{ echo "$as_me:$LINENO: checking for ssl3_accept in -lssl" >&5
+			if test $have_openssl = no ; then
+				{ echo "$as_me:$LINENO: checking for ssl3_accept in -lssl" >&5
 echo $ECHO_N "checking for ssl3_accept in -lssl... $ECHO_C" >&6; }
 if test "${ac_cv_lib_ssl_ssl3_accept+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -19622,16 +19791,16 @@ fi
 echo "${ECHO_T}$ac_cv_lib_ssl_ssl3_accept" >&6; }
 if test $ac_cv_lib_ssl_ssl3_accept = yes; then
   have_openssl=yes
-				need_rsaref=yes
+					need_rsaref=yes
 else
   have_openssl=no
 fi
 
-		fi
+			fi
 
-		if test $have_openssl = yes ; then
-			ol_with_tls=openssl
-			ol_link_tls=yes
+			if test $have_openssl = yes ; then
+				ol_with_tls=openssl
+				ol_link_tls=yes
 
 
 cat >>confdefs.h <<\_ACEOF
@@ -19639,19 +19808,19 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 
-			if test $need_rsaref = yes; then
+				if test $need_rsaref = yes; then
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_RSAREF 1
 _ACEOF
 
 
-				TLS_LIBS="-lssl -lcrypto -lRSAglue -lrsaref"
-			else
-				TLS_LIBS="-lssl -lcrypto"
-			fi
+					TLS_LIBS="-lssl -lcrypto -lRSAglue -lrsaref"
+				else
+					TLS_LIBS="-lssl -lcrypto"
+				fi
 
-			{ echo "$as_me:$LINENO: checking OpenSSL library version (CRL checking capability)" >&5
+				{ echo "$as_me:$LINENO: checking OpenSSL library version (CRL checking capability)" >&5
 echo $ECHO_N "checking OpenSSL library version (CRL checking capability)... $ECHO_C" >&6; }
 if test "${ol_cv_ssl_crl_compat+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -19686,12 +19855,13 @@ fi
 { echo "$as_me:$LINENO: result: $ol_cv_ssl_crl_compat" >&5
 echo "${ECHO_T}$ol_cv_ssl_crl_compat" >&6; }
 
-			if test $ol_cv_ssl_crl_compat = yes ; then
+				if test $ol_cv_ssl_crl_compat = yes ; then
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_OPENSSL_CRL 1
 _ACEOF
 
+				fi
 			fi
 		fi
 	fi
@@ -19954,8 +20124,8 @@ fi
 
 if test $ol_enable_lmpasswd != no; then
 	if test $ol_link_tls != yes ; then
-		{ { echo "$as_me:$LINENO: error: LAN Manager passwords require OpenSSL" >&5
-echo "$as_me: error: LAN Manager passwords require OpenSSL" >&2;}
+		{ { echo "$as_me:$LINENO: error: LAN Manager passwords require TLS" >&5
+echo "$as_me: error: LAN Manager passwords require TLS" >&2;}
    { (exit 1); exit 1; }; }
 	fi
 
diff --git a/dtrace/DTTk/Disk/diskhits b/dtrace/DTTk/Disk/diskhits
--- a/dtrace/DTTk/Disk/diskhits
+++ b/dtrace/DTTk/Disk/diskhits
@@ -1,4 +1,4 @@
-#!/bin/ksh
+#!/bin/sh
 ##!/usr/bin/ksh
 #
 # diskhits - disk access by file offset.
@@ -63,7 +63,7 @@ if [[ $1 == "-h" ]]; then
 fi
 pathname=$1
 if [[ ! -e $pathname ]]; then
-	print "ERROR2: file $pathname not found" >&2
+	echo "ERROR2: file $pathname not found" >&2
 	exit 2
 fi
 
