10.9

diff --git a/Heimdal/tests/apple/check-apple-ad.in b/Heimdal/tests/apple/check-apple-ad.in
--- a/Heimdal/tests/apple/check-apple-ad.in
+++ b/Heimdal/tests/apple/check-apple-ad.in
@@ -51,6 +51,18 @@ if ! ping -c 1 dc03.ads.apple.com > /dev/null 2>&1 ; then
       { echo "no dc03 available, skipping tests" ; exit 0; }
 fi
 
+echo "checking for ADS"
+if odutil show nodenames | grep '/Active Directory/ADS' > /dev/null ; then
+    echo "already joined to ADS"
+    needed_unjoin=no
+else
+    echo "joining ads.apple.com"
+    dsconfigad -add $R -force -user bind -password apple || { echo "join failed" ; exit 1; }
+    killall -9 digest-service
+    needed_unjoin=yes
+fi
+
+
 echo "running http tests"
 echo "	destroy all cred"
 ${gsstool} destroy --all
@@ -60,13 +72,22 @@ expect Password:
 send foobar\n
 EOF
 
+echo "	removing all creds"
+${gsstool} destroy --all || exit 1
+
 echo "	acquire ntlm creds"
 ${rkpty} ${testdir}/acquire.tmp \
 	${gsstool} acquire-cred --mech=ntlm ktestuser@ADS >/dev/null || exit 1
 
+echo "	check ntlm creds"
+${gsstool} list --mech=ntlm | grep ktestuser@ADS >/dev/null || exit 1
+
 echo "	acquire krb5 creds"
 ${rkpty} ${testdir}/acquire.tmp \
 	${gsstool} acquire-cred --mech=krb5 ktestuser@ADS.APPLE.COM  > /dev/null || exit 1
+
+echo "	check krb5 creds"
+${gsstool} list --mech=krb5 | grep ktestuser@ADS >/dev/null || exit 1
 
 echo "	spnego/krb5"
 ${http_client} --mech=spnego --cred-mech=krb5 --client=ktestuser@ADS.APPLE.COM \
@@ -86,6 +107,8 @@ ${http_client} --mech=ntlm --cred-mech=ntlm --client=ktestuser@ADS \
 
 echo "	destroy all cred"
 ${gsstool} destroy --all
+
+# ------------------------------------------------------------------------------------
 
 echo "test change password"
 echo admin > ${testdir}/foopassword
@@ -147,48 +170,61 @@ ${rkpty} cpw.tmp env ${kpasswd} -c ${cache} --admin-principal=da3admin@${R} ktes
 
 ${kdestroy}
 
-echo "checking mounting with NTLM"
-host=$(hostname)
-if expr "$host" : '.*\.apple\.com' > /dev/null ; then
-    launchctl load -F /System/Library/LaunchDaemons/com.apple.smbd.plist
-    killall smbd
-    sleep 3
-    ${winmount} ${testbase}/apple/coswin7-ads.plist ${host} || exit 1
-    ${winmount} ${testbase}/apple/coswin7-ads-specific.plist ${host} || exit 1
-else
-    echo "not running windows mount test since you are no on apple network"
-fi
+# ------------------------------------------------------------------------------------
 
-echo "checking for ADS"
-if odutil show nodenames | grep '/Active Directory/ADS' > /dev/null ; then
-    
-    echo "checking ktestuser in ADS"
-    ${test_gssntlm} --user=ktestuser --password=foobar --domain=ADS | grep 'done:' > /dev/null || \
-        { echo "test failed";  exit 1; }
-    
-    ${test_gssntlm} --user=ktestuser --password=foobar2 --domain=ADS 2>/dev/null | grep 'done:' > /dev/null && \
-        { echo "test failed";  exit 1; }
-    
-    sudo ${test_gssntlm} --user=ktestuser --password=foobar --domain=ADS | grep 'done:' > /dev/null || \
-        { echo "test failed";  exit 1; }
-    
-    sudo ${test_gssntlm} --user=ktestuser --password=foobar2 --domain=ADS 2>/dev/null | grep 'done:' > /dev/null && \
-        { echo "test failed";  exit 1; }
+#echo "checking ldap"
+#echo foobar > ${testdir}/foopassword
+#    
+#${kinit} --password-file=${testdir}/foopassword ktestuser@ADS.APPLE.COM || exit 1
+#    
+#env KRB5CCNAME=${cache} \
+#    ldapsearch -h dc02.ads.apple.com -b "DC=ads,DC=apple,DC=com" -s base \+ || \
+#        { echo "ldap test failed"; exit 1; }
+#    
+#${kdestroy}
 
+# ------------------------------------------------------------------------------------
 
-    echo "checking ldap"
-    echo foobar > ${testdir}/foopassword
-    
-    ${kinit} --password-file=${testdir}/foopassword ktestuser@ADS.APPLE.COM || exit 1
-    
-    env KRB5CCNAME=${cache} \
-    ldapsearch -h dc02.ads.apple.com -b "DC=ads,DC=apple,DC=com" -s base \+ || \
-        { echo "ldap test failed"; exit 1; }
-    
-    ${kdestroy}
+#echo "checking mounting with NTLM"
+#host=$(hostname)
+#if expr "$host" : '.*\.apple\.com' > /dev/null ; then
+#    launchctl load -F /System/Library/LaunchDaemons/com.apple.smbd.plist
+#    killall smbd
+#    sleep 3
+#    ${winmount} ${testbase}/apple/coswin7-ads.plist ${host} || exit 1
+#    ${winmount} ${testbase}/apple/coswin7-ads-specific.plist ${host} || exit 1
+#else
+#    echo "not running windows mount test since you are no on apple network"
+#fi
 
-else
-      echo "no ADS, skipping NETR/NETLOGON tests"
+# ------------------------------------------------------------------------------------
+
+echo "checking ktestuser in ADS (no domain)"
+${test_gssntlm} --user=ktestuser --password=foobar --domain='' --session-key-broken > /dev/null || \
+    { echo "test failed";  exit 1; }
+
+echo "checking ktestuser in ADS (domain)"
+${test_gssntlm} --user=ktestuser --password=foobar --domain=ADS --session-key-broken > /dev/null || \
+    { echo "test failed";  exit 1; }
+
+echo "checking ktestuser in ADS (no domain)"
+sudo ${test_gssntlm} --user=ktestuser --password=foobar --domain='' --session-key-broken > /dev/null || \
+    { echo "test failed";  exit 1; }
+
+echo "checking ktestuser in ADS (domain)"
+sudo ${test_gssntlm} --user=ktestuser --password=foobar --domain=ADS --session-key-broken > /dev/null || \
+    { echo "test failed";  exit 1; }
+
+echo "checking ktestuser in ADS (failure, wrong password)"
+sudo ${test_gssntlm} --user=ktestuser --password=foobar2 --domain=ADS 2>/dev/null --session-key-broken > /dev/null && \
+    { echo "test failed";  exit 1; }
+
+# ------------------------------------------------------------------------------------
+
+if [ ${needed_unjoin} = yes ] ; then
+    echo "unjoin"
+    dsconfigad -remove $R -force -user bind -password apple
+    killall -9 digest-service
 fi
 
 
diff --git a/Heimdal/tests/apple/check-apple-lkdc.in b/Heimdal/tests/apple/check-apple-lkdc.in
--- a/Heimdal/tests/apple/check-apple-lkdc.in
+++ b/Heimdal/tests/apple/check-apple-lkdc.in
@@ -139,19 +139,25 @@ fi
 
 echo "Creating lkdc user"
 
+echo "    delete"
 dscl . -delete /Users/$u 2>/dev/null >/dev/null
+echo "    create"
 dscl . -create /Users/$u
+echo "    RealName"
 dscl . -append /Users/$u RealName "Heimdal testuser"
 dscl . -append /Users/$u RecordName "${mme}"
 dscl . -append /Users/$u dsAttrTypeStandard:AltSecurityIdentities 'X509:<T>C=SE,CN=hx509 Test Root CA<S>CN=pkinit,C=SE'
 dscl . -delete /Users/$u AuthenticationAuthority
 dscl . -append /Users/$u AuthenticationAuthority ';ShadowHash;HASHLIST:<SALTED-SHA1,SMB-NT>'
 dscl . -append /Users/$u UniqueID $uid
+dscl . -append /Users/$u PrimaryGroupID 20
 dscl . -append /Users/$u NFSHomeDirectory "${testdir}/smb"
+echo "    Password"
 dscl . -passwd /Users/$u $pw
+echo "    Check keys"
 (dscl . -read /Users/$u KerberosKeys | grep KerberosKeys > /dev/null) || \
     { echo "KerberosKeys missing" ; exit 1; }
-(dscl . -read /Users/$u dsAttrTypeStandard:AltSecurityIdentities | grep pkinit) || { echo "asi missing" ; exit 1; }
+(dscl . -read /Users/$u dsAttrTypeStandard:AltSecurityIdentities | grep pkinit > /dev/null) || { echo "asi missing" ; exit 1; }
 
 chown -R $u "${testdir}/smb"
 
@@ -159,40 +165,60 @@ echo $pw > ${testdir}/foopassword
 
 echo "Server domain"
 
+echo "    delete"
 dscl . -delete /Users/$o 2>/dev/null >/dev/null
+echo "    create"
 dscl . -create /Users/$o
+dscl . -append /Users/$o UniqueID $(expr $uid + 1)
+dscl . -append /Users/$o PrimaryGroupID 20
 dscl . -append /Users/$o dsAttrTypeNative:KerberosUserName krbtgt/$r2@$r2
 
+echo "    setflags"
 $hodadmin . principal-setflags $o Server Forwardable
 
+echo "    password"
 $hodadmin . password  $o domain || exit 1
 $hodadmin . alias-add $o krbtgt/$r2@$r2  || exit 1
 
 echo "Creating server user"
 
+echo "    delete"
 dscl . -delete /Users/$u2 2>/dev/null >/dev/null
+echo "    create"
 dscl . -create /Users/$u2
+dscl . -append /Users/$u2 UniqueID $(expr $uid + 2)
+dscl . -append /Users/$u2 PrimaryGroupID 20
+echo "    password"
 dscl . -passwd /Users/$u2 $pw
+echo "    checking user"
 (dscl . -read /Users/$u KerberosKeys | grep KerberosKeys > /dev/null) || \
     { echo "KerberosKeys missing" ; exit 1; }
 dscl . -append /Users/$u2 dsAttrTypeNative:KerberosUserName $u2@$r2
 
 echo "Creating server service user"
 
+echo "    delete"
 dscl . -delete /Computers/$s 2>/dev/null >/dev/null
+echo "    create"
 dscl . -create /Computers/$s
+echo "    password"
 dscl . -passwd /Computers/$s $pw
+echo "    realname"
 dscl . -append /Computers/$s RealName "Heimdal test service"
+echo "    servername"
 dscl . -append /Computers/$s dsAttrTypeNative:KerberosServerName $s@$r2
 
+echo "    setflags"
 $hodadmin . principal-setflags /Computers/$s Server
 
+echo "    password"
 $hodadmin . password          /Computers/$s user-password
 #$hodadmin . password --append /Computers/$s host-pw host/$s.$r2@$r2
 #$hodadmin . password --append /Computers/$s cifs-pw cifs/$s.$r2@$r2
 #$hodadmin . password --append /Computers/$s http-pw HTTP/$s.$r2@$r2
 #$hodadmin . password --append /Computers/$s imap-pw imap/$s.$r2@$r2
 
+echo "    aliases"
 for a in host cifs HTTP imap ; do
     $hodadmin . alias-add /Computers/$s $a/$s.$r2@$r2
 done
@@ -202,6 +228,8 @@ if [ "X${foundlines}" = "X" -o "X${foundlines}" = X0 ] ; then
     echo "dumpfile contained nothing"
     exit 1
 fi
+
+echo "done user creation"
 
 toogle_ntlm enable
 
@@ -299,14 +327,13 @@ ${test_context} \
 
 ${kdestroy}
 
-echo "testing IAKERB GSS mech"
-${test_context} \
-    --client-name=heimdaltestuser@WELLKNOWN:COM.APPLE.LKDC \
-    --password="$pw" \
-    --cred-type=iakerb \
-    --mech=iakerb --wrap --verbose \
-    service@localhost || { ec=1 ; eval "${testfailed}"; }
-
+#echo "testing IAKERB GSS mech"
+#${test_context} \
+#    --client-name=heimdaltestuser@WELLKNOWN:COM.APPLE.LKDC \
+#    --password="$pw" \
+#    --cred-type=iakerb \
+#    --mech=iakerb --wrap --verbose \
+#    service@localhost || { ec=1 ; eval "${testfailed}"; }
 
 echo "test_gssntlm"
 
@@ -325,11 +352,11 @@ defaults write /Library/Preferences/com.apple.GSS.NTLM AllowedHosts -array host.
 for a in \
     "0 host@host.local host.local" \
     "0 host@host.local" \
-    "0 host@host.local *.local" \
+    "0 host@host.local \*.local" \
     "1 host@host.local host2.local" \
     "1 host@host.local 2host.local" \
-    "1 host@host.local *.local2" \
-    "1 host@host.local *.2local"
+    "1 host@host.local \*.local2" \
+    "1 host@host.local \*.2local"
 do
     echo "---running test $a"
     set -- $a
@@ -353,7 +380,10 @@ do
         --ret-mech-type=ntlm \
         ${host} > /dev/null 2>&1
     res=$?
-    test "$res" = "$eres" || { echo "test failed"; exit 1; }
+    test "$res" = "$eres" || { \
+	defaults delete /Library/Preferences/com.apple.GSS.NTLM AllowedHosts ; \
+	echo "test failed"; exit 1; \
+    }
 
     echo "   NTLM GSS mech channel bindings"
     ${test_context} \
@@ -365,7 +395,10 @@ do
         --ret-mech-type=ntlm \
         ${host} > /dev/null 2>&1
     res=$?
-    test "$res" = "$eres" || { echo "test failed"; exit 1; }
+    test "$res" = "$eres" ||  { \
+	defaults delete /Library/Preferences/com.apple.GSS.NTLM AllowedHosts ; \
+	echo "test failed"; exit 1; \
+    }
 
 done
 
@@ -470,6 +503,7 @@ toggle_launchd malloc-unset
 
 rm -rf "${testdir}/smb"
 dscl . -delete /Users/$u
+dscl . -delete /Users/$u2
 dscl . -delete /Users/$s
 dscl . -delete /Users/$o
 
diff --git a/Heimdal/tests/apple/check-apple-od.in b/Heimdal/tests/apple/check-apple-od.in
--- a/Heimdal/tests/apple/check-apple-od.in
+++ b/Heimdal/tests/apple/check-apple-od.in
@@ -34,8 +34,13 @@
 # SUCH DAMAGE. 
 
 env_setup="@env_setup@"
+testdir="@testdir@"
+confdir="@confdir@"
 
 . ${env_setup}
+
+KRB5_CONFIG="${1-${confdir}/krb5.conf}"
+export KRB5_CONFIG
 
 echo "checking for od.apple.com"
 (dscl /LDAPv3/od.apple.com -read /Users/smbtest  | grep 'RealName: smbtest' > /dev/null ) || \
@@ -47,13 +52,14 @@ cat > ${kinitpty} <<EOF
 expect Password
 password smbtest\n
 EOF
-   ${rkpty} ${kinitpty} ${kinit} smbtest@OD.APPLE.COM >/dev/null || exit 1
+   ${rkpty} ${kinitpty} ${kinit} smbtest@OD.APPLE.COM >/dev/null || { echo "kinit failed with: $?" ; exit 1; }
 ${kdestroy}
 
 
 echo "checking ntlm"
 ${test_context} --mech-type=ntlm --cred-type=ntlm \
-	--client-name='smbtest@\targetname' --password='smbtest' service@host || exit 1
+	--client-name='smbtest@\targetname' --password='smbtest' service@host || \
+	{ echo "ntlm check failed with: $?" ; exit 1; }
 
 echo "checking signing is disabled"
 ${gsstool} supporte --opt| \
diff --git a/libxslt/libxslt/doc/Makefile.am b/libxslt/libxslt/doc/Makefile.am
--- a/libxslt/libxslt/doc/Makefile.am
+++ b/libxslt/libxslt/doc/Makefile.am
@@ -22,30 +22,122 @@ APIPAGES=APIconstructors.html APIfiles.html APIfunctions.html \
 EAPIPAGES=EXSLT/APIconstructors.html EXSLT/APIfiles.html \
 	 EXSLT/APIfunctions.html EXSLT/APIsymbols.html EXSLT/APIchunk0.html
 
-EXTRA_DIST =			\
-	api.xsl			\
-	apibuild.py		\
-	EXSLT/*.html		\
-	EXSLT/html/*.html	\
-	EXSLT/html/*.png	\
-	EXSLT/libexslt-api.xml	\
-	EXSLT/libexslt-refs.xml	\
-	libxslt-api.xml		\
-	libxslt-refs.xml	\
-	symbols.xml		\
-	checkapisym.xsl		\
-	syms.xsl		\
-	libxslt.xsa		\
-	newapi.xsl		\
-	news.xsl		\
-	search.xml		\
-	site.xsl		\
-	xslt.html		\
+EXTRA_DIST =				\
+	$(PAGES)			\
+	$(EPAGES)			\
+	$(EAPIPAGES)			\
+	APIchunk0.html			\
+	APIchunk1.html			\
+	APIchunk2.html			\
+	APIchunk3.html			\
+	APIchunk4.html			\
+	APIchunk5.html			\
+	APIchunk6.html			\
+	APIchunk7.html			\
+	APIchunk8.html			\
+	APIchunk9.html			\
+	APIchunk10.html			\
+	APIchunk11.html			\
+	APIchunk12.html			\
+	APIchunk13.html			\
+	APIconstructors.html		\
+	APIfiles.html			\
+	APIfunctions.html		\
+	APIsymbols.html			\
+	EXSLT/exslt.html		\
+	EXSLT/html/book1.html		\
+	EXSLT/html/home.png		\
+	EXSLT/html/index.html		\
+	EXSLT/html/left.png		\
+	EXSLT/html/libexslt-exslt.html	\
+	EXSLT/html/libexslt-exsltexports.html \
+	EXSLT/html/libexslt-lib.html	\
+	EXSLT/html/right.png		\
+	EXSLT/html/up.png		\
+	EXSLT/libexslt-api.xml		\
+	EXSLT/libexslt-refs.xml		\
+	Libxslt-Logo-180x168.gif	\
+	Libxslt-Logo-90x34.gif		\
+	api.xsl				\
+	apibuild.py			\
+	checkapisym.xsl			\
+	contexts.gif			\
+	docbook.html			\
+	duck.png			\
+	epatents.png			\
+	extensions.html			\
+	gnome2.png			\
+	html/book1.html			\
+	html/home.png			\
+	html/index.html			\
+	html/left.png			\
+	html/libxslt-attributes.html	\
+	html/libxslt-documents.html	\
+	html/libxslt-extensions.html	\
+	html/libxslt-extra.html		\
+	html/libxslt-functions.html	\
+	html/libxslt-imports.html	\
+	html/libxslt-keys.html		\
+	html/libxslt-lib.html		\
+	html/libxslt-namespaces.html	\
+	html/libxslt-numbersInternals.html \
+	html/libxslt-pattern.html	\
+	html/libxslt-preproc.html	\
+	html/libxslt-security.html	\
+	html/libxslt-templates.html	\
+	html/libxslt-transform.html	\
+	html/libxslt-variables.html	\
+	html/libxslt-xslt.html		\
+	html/libxslt-xsltInternals.html	\
+	html/libxslt-xsltexports.html	\
+	html/libxslt-xsltlocale.html	\
+	html/libxslt-xsltutils.html	\
+	html/right.png			\
+	html/up.png			\
+	images/callouts/1.png		\
+	images/callouts/10.png		\
+	images/callouts/2.png		\
+	images/callouts/3.png		\
+	images/callouts/4.png		\
+	images/callouts/5.png		\
+	images/callouts/6.png		\
+	images/callouts/7.png		\
+	images/callouts/8.png		\
+	images/callouts/9.png		\
+	internals.html			\
+	libxslt-api.xml			\
+	libxslt-refs.xml		\
+	libxslt.xsa			\
+	newapi.xsl			\
+	news.xsl			\
+	node.gif			\
+	object.gif			\
+	processing.gif			\
+	python.html			\
+	redhat.gif			\
+	search.xml			\
+	site.xsl			\
+	smallfootonly.gif		\
+	stylesheet.gif			\
+	symbols.xml			\
+	syms.xsl			\
+	templates.gif			\
+	tutorial/libxslt_tutorial.c	\
+	tutorial/libxslttutorial.html	\
+	tutorial/libxslttutorial.xml	\
+	tutorial2/libxslt_pipes.c	\
+	tutorial2/libxslt_pipes.html	\
+	tutorial2/libxslt_pipes.xml	\
+	w3c.png				\
+	xsa.xsl				\
+	xslt.html			\
+	xsltproc.1			\
+	xsltproc.html			\
 	xsltproc.xml
 
 man_MANS = xsltproc.1
 
-all:	web ../NEWS libxslt.xsa $(man_MANS)
+all-local:	web ../NEWS libxslt.xsa $(man_MANS)
 
 api:	libxslt-api.xml libxslt-refs.xml $(APIPAGES) search.php \
         html/index.html $(WIN32_DIR)/libxslt.def.src
@@ -55,147 +147,180 @@ eapi:	EXSLT/libexslt-api.xml EXSLT/libexslt-refs.xml $(EAPIPAGES) \
 
 web: $(PAGES) $(EPAGES)
 
-$(PAGES): xslt.html $(srcdir)/site.xsl
-	-@(if [ -x $(bindir)/xsltproc ] ; then \
+$(PAGES): $(srcdir)/xslt.html $(srcdir)/site.xsl
+	-@(if [ -x $(XSLTPROC) ] ; then \
 	  echo "Rebuilding the HTML Web pages from xslt.html" ; \
-	  $(bindir)/xsltproc --nonet --html $(srcdir)/site.xsl \
-	    xslt.html > index.html ; fi )
-	-@(if [ -x $(bindir)/xmllint ] ; then \
+	  $(XSLTPROC) --nonet --html $(srcdir)/site.xsl \
+	    $(srcdir)/xslt.html > index.html ; fi )
+	-@(if [ -x $(XMLLINT) ] ; then \
 	  echo "Validating the HTML Web pages" ; \
-	  $(bindir)/xmllint --nonet --valid --noout $(PAGES) ; fi );
+	  $(XMLLINT) --nonet --valid --noout $(PAGES) ; fi );
 
-$(EPAGES): EXSLT/exslt.html $(srcdir)/site.xsl
+$(EPAGES): $(srcdir)/EXSLT/exslt.html $(srcdir)/site.xsl
 	 -@(if [ ! -d EXSLT/html ] ; then \
 	   mkdir -p EXSLT/html ; fi )
-	 -@(if [ -x $(bindir)/xsltproc ] ; then \
+	 -@(if [ -x $(XSLTPROC) ] ; then \
 	   echo "Rebuilding the HTML Web pages from exslt.html" ; \
-	   $(bindir)/xsltproc --nonet --html \
+	   $(XSLTPROC) --nonet --html \
 		--stringparam dirname EXSLT/ \
 		--stringparam libname libexslt \
 		--stringparam logo_base ../ \
 		$(srcdir)/site.xsl \
-		EXSLT/exslt.html > EXSLT/index.html ; fi )
-	 -@(if [ -x $(bindir)/xmllint ] ; then \
+		$(srcdir)/EXSLT/exslt.html > EXSLT/index.html ; fi )
+	 -@(if [ -x $(XMLLINT) ] ; then \
 	   echo "Validating the HTML Web pages" ; \
-	   $(bindir)/xmllint --nonet --valid --noout $(EPAGES) ; fi );
+	   $(XMLLINT) --nonet --valid --noout $(EPAGES) ; fi );
 
-../NEWS: $(srcdir)/news.xsl news.html
-	-@(if [ -x $(bindir)/xsltproc ] ; then \
-	  $(bindir)/xsltproc --nonet $(srcdir)/news.xsl \
-	    news.html > ../NEWS ; fi );
+../NEWS: $(srcdir)/news.xsl $(srcdir)/news.html
+	-@(if [ -x $(XSLTPROC) ] ; then \
+	  $(XSLTPROC) --nonet $(srcdir)/news.xsl \
+	    $(srcdir)/news.html > ../NEWS ; fi );
 
-libxslt.xsa: $(srcdir)/xsa.xsl news.html
-	-@(if [ -x $(bindir)/xsltproc ] ; then \
-	  $(bindir)/xsltproc --nonet $(srcdir)/xsa.xsl \
+libxslt.xsa: $(srcdir)/xsa.xsl $(srcdir)/news.html
+	-@(if [ -x $(XSLTPROC) ] ; then \
+	  $(XSLTPROC) --nonet $(srcdir)/xsa.xsl \
 	    news.html > libxslt.xsa ; fi );
 
 $(APIPAGES): libxslt-refs.xml site.xsl api.xsl $(srcdir)/site.xsl \
 	     $(srcdir)/api.xsl
-	-@(if [ -x $(bindir)/xsltproc ] ; then \
+	-@(if [ -x $(XSLTPROC) ] ; then \
 	  echo "Rebuilding the HTML API pages from libxslt-refs.xml" ; \
-	  $(bindir)/xsltproc --nonet --html \
+	  $(XSLTPROC) --nonet --html \
 			     $(srcdir)/api.xsl \
-			     xslt.html ; fi );
-	-@(if [ -x $(bindir)/xmllint ] ; then \
+			     $(srcdir)/xslt.html ; fi );
+	-@(if [ -x $(XMLLINT) ] ; then \
 	  echo "Validating the HTML API pages" ; \
-	  $(bindir)/xmllint --nonet --valid --noout API*.html; fi );
+	  $(XMLLINT) --nonet --valid --noout API*.html; fi );
 
 $(EAPIPAGES): EXSLT/libexslt-refs.xml site.xsl api.xsl
-	-@(if [ -x $(bindir)/xsltproc ] ; then \
+	-@(if [ -x $(XSLTPROC) ] ; then \
 	  echo "Rebuilding the HTML API pages from libexslt-refs.xml" ; \
-	  $(bindir)/xsltproc --nonet --html --output EXSLT/ \
+	  $(XSLTPROC) --nonet --html --output EXSLT/ \
 			     --stringparam libname libexslt \
 			     --stringparam dirname EXSLT/ \
 			     --stringparam logo_base ../ \
 			     $(srcdir)/api.xsl \
-			     EXSLT/exslt.html ; fi );
+			     $(srcdir)/EXSLT/exslt.html ; fi );
 
 html/index.html: libxslt-api.xml $(srcdir)/newapi.xsl
-	-@(if [ -x $(bindir)/xsltproc ] ; then \
+	-@(if [ -x $(XSLTPROC) ] ; then \
 	  echo "Rebuilding the HTML pages from the XSLT API" ; \
-	  $(bindir)/xsltproc --nonet \
-			     $(srcdir)/newapi.xsl libxslt-api.xml ; fi );
-	-@(if [ -x $(bindir)/xmllint ] ; then \
+	  $(XSLTPROC) --nonet \
+			     $(srcdir)/newapi.xsl $(srcdir)/libxslt-api.xml ; fi );
+	-@(if [ -x $(XMLLINT) ] ; then \
 	  echo "Validating the resulting XHTML pages" ; \
-	  $(bindir)/xmllint --nonet --valid --noout html/*.html ; fi );
+	  $(XMLLINT) --nonet --valid --noout html/*.html ; fi );
 
 wiki: libxslt-api.xml $(srcdir)/wiki.xsl
-	-@(if [ -x $(bindir)/xsltproc ] ; then \
+	-@(if [ -x $(XSLTPROC) ] ; then \
 		echo "Rebuilding the wiki HTML pages from the XSLT API" ; \
-		$(bindir)/xsltproc --nonet $(srcdir)/wiki.xsl libxslt-api.xml; fi )
+		$(XSLTPROC) --nonet $(srcdir)/wiki.xsl $(srcdir)/libxslt-api.xml; fi )
 
 EXSLT/html/index.html: EXSLT/libexslt-api.xml \
 	$(srcdir)/newapi.xsl
-	-@(if [ -x $(bindir)/xsltproc ] ; then \
+	-@(if [ -x $(XSLTPROC) ] ; then \
 	  echo "Rebuilding the HTML pages from the EXSLT API" ; \
-	  $(bindir)/xsltproc --nonet --output EXSLT/ \
+	  $(XSLTPROC) --nonet --output EXSLT/ \
 			     --stringparam libname libexslt \
 			     --stringparam dirname EXSLT/ \
 			     --stringparam logo_base ../../ \
 			     $(srcdir)/newapi.xsl \
-			     EXSLT/libexslt-api.xml ; fi );
-	-@(if [ -x $(bindir)/xmllint ] ; then \
+			     $(srcdir)/EXSLT/libexslt-api.xml ; fi );
+	-@(if [ -x $(XMLLINT) ] ; then \
 	  echo "Validating the resulting XHTML pages" ; \
-	  $(bindir)/xmllint --nonet --valid --noout EXSLT/html/*.html ; fi );
+	  $(XMLLINT) --nonet --valid --noout EXSLT/html/*.html ; fi );
 
 
 libxslt-api.xml libxslt-refs.xml EXSLT/libexslt-api.xml \
   EXSLT/libexslt-refs.xml ../libxslt/libxslt.syms : $(srcdir)/apibuild.py $(top_srcdir)/libxslt/*.h \
 		$(top_srcdir)/libxslt/*.c $(top_srcdir)/libexslt/*.h \
 		$(top_srcdir)/libexslt/*.c
-	-($(srcdir)/apibuild.py)
-	($(XSLTPROC) checkapisym.xsl libxslt-api.xml)
-	($(XSLTPROC) -o ../libxslt/libxslt.syms syms.xsl symbols.xml)
+	-(cd $(srcdir) && ./apibuild.py)
+	($(XSLTPROC) $(srcdir)/checkapisym.xsl $(srcdir)/libxslt-api.xml)
+	($(XSLTPROC) -o ../libxslt/libxslt.syms $(srcdir)/syms.xsl $(srcdir)/symbols.xml)
 
-xsltproc.1: xsltproc.xml
-	-@(xsltproc --nonet xsltproc.xml)
+xsltproc.1: $(srcdir)/xsltproc.xml
+	-@$(XSLTPROC) --nonet $(srcdir)/xsltproc.xml
 
 # Note that in the following, xmllint output is piped to xsltproc
 search.php: $(srcdir)/api.xsl $(srcdir)/site.xsl $(srcdir)/search.templ \
             $(srcdir)/search.xml $(srcdir)/search.php.inc
-	-@(if test -x $(bindir)/xmllint -a -x $(bindir)/xsltproc; then \
+	-@(if test -x $(XMLLINT) -a -x $(XSLTPROC); then \
 	   echo "Rebuilding search.php" ; \
-	   $(bindir)/xmllint --xinclude --nonet \
+	   $(XMLLINT) --xinclude --nonet \
 	                      $(srcdir)/search.xml | \
-	   $(bindir)/xsltproc --nonet - search.templ \
+	   $(XSLTPROC) --nonet - search.templ \
 			      > search.php ; else \
 	   echo "Unable to find xmllint or xsltproc in $(bindir)" ; fi)
 
 $(WIN32_DIR)/libxslt.def.src: libxslt-api.xml
-	-@(if [ -x $(bindir)/xsltproc ] ; then \
-	  $(bindir)/xsltproc -o $(WIN32_DIR)/libxslt.def.src \
-	  --nonet $(WIN32_DIR)/defgen.xsl libxslt-api.xml ; fi )
+	-@(if [ -x $(XSLTPROC) ] ; then \
+	  $(XSLTPROC) -o $(WIN32_DIR)/libxslt.def.src \
+	  --nonet $(WIN32_DIR)/defgen.xsl $(srcdir)/libxslt-api.xml ; fi )
 
 $(WIN32_DIR)/libexslt.def.src: EXSLT/libexslt-api.xml
-	-@(if [ -x $(bindir)/xsltproc ] ; then \
-	  $(bindir)/xsltproc -o $(WIN32_DIR)/libexslt.def.src \
-	  --nonet $(WIN32_DIR)/defgen.xsl EXSLT/libexslt-api.xml ; fi )
+	-@(if [ -x $(XSLTPROC) ] ; then \
+	  $(XSLTPROC) -o $(WIN32_DIR)/libexslt.def.src \
+	  --nonet $(WIN32_DIR)/defgen.xsl $(srcdir)/EXSLT/libexslt-api.xml ; fi )
 
 clean-local:
-	rm -f *~ *.bak *.hierarchy *.signals *-unused.txt
+	rm -f *~ *.1 *.bak *.hierarchy *.signals *-unused.txt
 
-maintainer-clean-local: clean
+distclean-local:
+	if test ! -r Makefile.am ; then \
+		rm -f *.html *.templ *.xsa ; \
+		rm -rf EXSLT html ; \
+	fi
 
 rebuild: api eapi all
 
+wildcards =			\
+	*.1			\
+	*.gif			\
+	*.html			\
+	*.png			\
+	*.xsl			\
+	EXSLT/*.html		\
+	EXSLT/html/*.html	\
+	EXSLT/html/*.png	\
+	html/*.html		\
+	html/*.png		\
+	images/callouts/*.png	\
+	tutorial*/libxslt*
+
+# This target verifies that EXTRA_DIST contains all the files matched by
+# the above list of wildcards. Note that this will only work properly when
+# srcdir = builddir.
+#
+check-extra-dist:
+	@for a in $(wildcards) ; do \
+		if test ! -f "$$a" ; then \
+			echo "not found: $$a" ; \
+			continue ; \
+		fi ; \
+		present= ; \
+		for b in $(EXTRA_DIST) ; do \
+			test "$$a" = "$$b" && present=1 && break ; \
+		done ; \
+		test -n "$$present" || echo "not in EXTRA_DIST: $$a" ; \
+	done
+
 install-data-local:
-	$(mkinstalldirs) $(DESTDIR)$(HTML_DIR)
-	-@INSTALL@ -m 0644 $(srcdir)/*.html $(DESTDIR)$(HTML_DIR)
-	-@INSTALL@ -m 0644 $(srcdir)/*.gif $(DESTDIR)$(HTML_DIR)
-	$(mkinstalldirs) $(DESTDIR)$(HTML_DIR)/html
-	-@INSTALL@ -m 0644 $(srcdir)/html/*.html $(DESTDIR)$(HTML_DIR)/html
-	-@INSTALL@ -m 0644 $(srcdir)/html/*.png $(DESTDIR)$(HTML_DIR)/html
-	-@INSTALL@ -m 0644 $(srcdir)/html/index.sgml $(DESTDIR)$(HTML_DIR)/html
-	$(mkinstalldirs) $(DESTDIR)$(HTML_DIR)/EXSLT
-	-@INSTALL@ -m 0644 $(srcdir)/EXSLT/*.html $(DESTDIR)$(HTML_DIR)/EXSLT
-	$(mkinstalldirs) $(DESTDIR)$(HTML_DIR)/tutorial
-	-@INSTALL@ -m 0644 $(srcdir)/tutorial/* $(DESTDIR)$(HTML_DIR)/tutorial
-	$(mkinstalldirs) $(DESTDIR)$(HTML_DIR)/tutorial2
-	-@INSTALL@ -m 0644 $(srcdir)/tutorial2/* $(DESTDIR)$(HTML_DIR)/tutorial2
+	$(MKDIR_P) $(DESTDIR)$(HTML_DIR)
+	-$(INSTALL) -m 0644 $(srcdir)/*.html $(DESTDIR)$(HTML_DIR)
+	-$(INSTALL) -m 0644 $(srcdir)/*.gif $(DESTDIR)$(HTML_DIR)
+	$(MKDIR_P) $(DESTDIR)$(HTML_DIR)/html
+	-$(INSTALL) -m 0644 $(srcdir)/html/*.html $(DESTDIR)$(HTML_DIR)/html
+	-$(INSTALL) -m 0644 $(srcdir)/html/*.png $(DESTDIR)$(HTML_DIR)/html
+	-$(INSTALL) -m 0644 $(srcdir)/html/index.sgml $(DESTDIR)$(HTML_DIR)/html
+	$(MKDIR_P) $(DESTDIR)$(HTML_DIR)/EXSLT
+	-$(INSTALL) -m 0644 $(srcdir)/EXSLT/*.html $(DESTDIR)$(HTML_DIR)/EXSLT
+	$(MKDIR_P) $(DESTDIR)$(HTML_DIR)/tutorial
+	-$(INSTALL) -m 0644 $(srcdir)/tutorial/* $(DESTDIR)$(HTML_DIR)/tutorial
+	$(MKDIR_P) $(DESTDIR)$(HTML_DIR)/tutorial2
+	-$(INSTALL) -m 0644 $(srcdir)/tutorial2/* $(DESTDIR)$(HTML_DIR)/tutorial2
 
-dist-hook:
-	(cd $(srcdir) ; tar cvf - *.1 *.html site.xsl news.xsl xsa.xsl \
-	  *.gif *.png images html/*.html html/*.png tutorial*/libxslt*) | \
-	  (cd $(distdir); tar xf -)
+uninstall-local:
+	rm -rf $(DESTDIR)$(HTML_DIR)
 
-.PHONY : html EXSLT EXSLT/html
+.PHONY : api eapi web wiki rebuild check-extra-dist
diff --git a/lsof/lsof/Configure b/lsof/lsof/Configure
--- a/lsof/lsof/Configure
+++ b/lsof/lsof/Configure
@@ -14,7 +14,7 @@
 # shell script, named $LSOF_MK, that places its source modules in this
 # directory.
 #
-# $Id: Configure,v 1.160 2011/09/27 17:27:20 abe Exp $
+# $Id: Configure,v 1.161 2012/04/10 16:35:46 abe Exp abe $
 
 # LSOF_CFLAGS_OVERRIDE=1 may be introduced through the environment to cause
 #	the library Makefile's CFLAGS definition to override any in the
@@ -883,13 +883,16 @@ case $LSOF_TGT in	# {
       11.*)			# Mac OS X 10.7 (Lion)
  	LSOF_VERS=1100
  	;;
-      12.*)			# a coming version of Mac OS?
+      12.*)			# Mac OS X 10.8 (Mountain Lion)
  	LSOF_VERS=1200
+ 	;;
+      13.*)			# Next Mac OS X
+ 	LSOF_VERS=1300
  	;;
       *)
 	echo Unknown Darwin release: `uname -r`
-	echo Assuming Darwin 11.0
-	LSOF_VERS=1100
+	echo Assuming Darwin 12.0
+	LSOF_VERS=1200
 	;;
       esac	# }
     fi	# }
@@ -918,13 +921,17 @@ case $LSOF_TGT in	# {
       LSOF_CFGF="$LSOF_CFGF -DHASIPv6"
       LSOF_TMP1="net/ndrv_var.h net/raw_cb.h netinet/ip_var.h netinet/tcp_var.h sys/eventvar.h sys/file_internal.h sys/mount_internal.h sys/proc_internal.h sys/vnode_internal.h"
       ;;
-    900|1000|1100)
+    900|1000|1100|1200)
       LSOF_CFGF="$LSOF_CFGF -DHASIPv6"
       LSOF_TMP1=""
       LSOF_UNSUP=""
       LSOF_TSTBIGF=" "			# enable LTbigf test
+      if test $LSOF_VERS -eq 900	# {
+      then
+	LSOF_CFGF="$LSOF_CFGF -DNEEDS_MACH_PORT_T"
+      fi	# }
       ;;
-    1200)
+    1300)
       LSOF_CFGF="$LSOF_CFGF -DHASIPv6"
       LSOF_TMP1=""
       ;;
@@ -1587,20 +1594,22 @@ kernel generation process.
 	LSOF_TSTBIGF=" "
 	LSOF_VERS=8020
 	;;
+      8.3*)
+	LSOF_TSTBIGF=" "
+	LSOF_VERS=8030
+	;;
       9*)
 	LSOF_TSTBIGF=" "
 	LSOF_VERS=9000
 	;;
+      10*)
+	LSOF_TSTBIGF=" "
+	LSOF_VERS=10000
+	;;
       *)
 	echo Unknown FreeBSD release: `uname -r`
-	echo Assuming FreeBSD 2.x
-	LSOF_CFGL="$LSOF_CFGL -lkvm"
-	LSOF_VERS=2000
-	LSOF_N_UNIXV=`/usr/sbin/sysctl -n kern.bootfile`
-	if test "X$LSOF_N_UNIXV" = "X"	# {
-	then
-	  LSOF_N_UNIXV="/kernel"
-	fi	# }
+	rm -f $LSOF_HLP
+	exit 1
 	;;
       esac	# }
     fi	# }
@@ -1608,7 +1617,7 @@ kernel generation process.
     # Clear LSOF_UNSUP message for supported versions of FreeBSD.
     
     case $LSOF_VERS in  # {
-    4090|6040|8000|8020|9000)
+    4090|8020|8030|9000|10000)
       LSOF_UNSUP=""
       ;;
     esac	# }
@@ -1659,6 +1668,21 @@ kernel generation process.
       fi	# }
     fi	# }
 
+    # Test for thread (task) support.
+
+    if test -r ${LSOF_INCLUDE}/sys/user.h	# {
+    then
+      grep -q ki_numthreads ${LSOF_INCLUDE}/sys/user.h
+      if test $? -eq 0	# {
+      then
+	LSOF_CFGF="$LSOF_CFGF -DHASTASKS"
+      fi	# }
+    else
+      echo "FATAL: can't find sys/user.h"
+      rm -f $LSOF_HLP
+      exit 1
+    fi	# }
+
     # Do FreeBSD version-specific stuff.
 
     case $LSOF_VERS in	# {
@@ -1694,7 +1718,7 @@ kernel generation process.
 	LSOF_CFGF="$LSOF_CFGF -DHASVMLOCKH"
       fi	# }
       ;;
-    4000|4010|4020|4030|4040|4050|4060|4070|4080|4090|4100|4110|5000|5010|5020|5030|5040|5050|6000|6010|6020|6030|6040|7000|7010|7020|7030|7040|8000|8010|8020|9000)
+    *)
       if test -r ${LSOF_INCLUDE}/nfs/rpcv2.h	# {
       then
 	LSOF_CFGF="$LSOF_CFGF -DHASRPCV2H"
@@ -1744,6 +1768,7 @@ kernel generation process.
 		echo "          in ${LSOF_INCLUDE}/fs/devfs/devfs.h or"
 		echo "          ${FREEBSD_SYS}/fs/devfs/devfs.h.  Consult"
 		echo "          00FAQ for an explanation."
+		rm -f $LSOF_HLP
 		exit 1
 	      fi	# }
 	    fi	# }
@@ -2039,11 +2064,6 @@ LOCKF_OWNER4
 	  fi	# }
 	fi	# }
       fi	# }
-      ;;
-    *)
-      echo "Unknown FreeBSD release: $LSOF_VERS"
-      rm -f $LSOF_HLP
-      exit 1
       ;;
     esac	# }
     LSOF_CFGF="$LSOF_CFGF -DFREEBSDV=$LSOF_VERS"
@@ -4815,7 +4835,15 @@ return(0); }
     esac	# }
     LSOF_CFGF="$LSOF_CFGF -Dsolaris=$LSOF_VERS"
 
+    # Test for <sys/fs/cachefs_fs.h>.
+
+    if test -r ${LSOF_INCLUDE}/sys/fs/cachefs_fs.h	# {
+    then
+      LSOF_CFGF="$LSOF_CFGF -DHASCACHEFS"
+    fi	# }
+
     # Test for <utmpx.h>
+
     if test -r ${LSOF_INCLUDE}/utmpx.h	# {
     then
       LSOF_CFGF="$LSOF_CFGF -DHASUTMPX"
