10.7

diff --git a/ICU/icuSources/config/icu-config-bottom b/ICU/icuSources/config/icu-config-bottom
--- a/ICU/icuSources/config/icu-config-bottom
+++ b/ICU/icuSources/config/icu-config-bottom
@@ -1,9 +1,10 @@
 ## -*-sh-*-
 ## BEGIN of icu-config-bottom.
-## Copyright (c) 2002-2007, International Business Machines Corporation and
+## Copyright (c) 2002-2010, International Business Machines Corporation and
 ## others. All Rights Reserved.
 
-ICUUC_FILE=${libdir}/${ICULIBS_COMMON_LIB_NAME}
+ICUUC_FILE="${libdir}/${ICULIBS_COMMON_LIB_NAME}"
+ICUUC_FILE_A="${libdir}/${ICULIBS_COMMON_LIB_NAME_A}"
     
 #  echo ENABLE RPATH $ENABLE_RPATH and RPATHLDFLAGS=${RPATH_LDFLAGS}
 if [ "x$PKGDATA_MODE" = "x" ]; then
@@ -18,6 +19,7 @@ ME=`basename "$0"`
 
 allflags()
 {
+    echo "  --noverify             Don't verify that ICU is actually installed."
     echo "  --bindir               Print binary directory path (bin)"
     echo "  --cc                   Print C compiler used [CC]"
     echo "  --cflags               Print C compiler flags [CFLAGS]"
@@ -58,9 +60,10 @@ allflags()
     echo "  --sysconfdir           Print system config (etc) path"
     echo "  --unicode-version      Print version of Unicode data used in ICU ($UNICODE_VERSION)"
     echo "  --version              Print ICU version ($VERSION)"
-    echo "  --incfile              Print path to Makefile.inc (for -O option of pkgdata)"
+    echo "  --incfile              Print path to Makefile.inc"
+    echo "  --incpkgdatafile       Print path to pkgdata.inc (for -O option of pkgdata)"
     echo "  --install              Print path to install-sh"
-    echo "  --mkinstalldirs              Print path to mkinstalldirs"
+    echo "  --mkinstalldirs        Print path to mkinstalldirs"
 }
 
 ## Print the normal usage message
@@ -91,11 +94,12 @@ usage()
 ## Check the sanity of current variables
 sanity()
 {
-    if [ ! -f ${ICUUC_FILE} ];
+    if [ ! -f "${ICUUC_FILE}" -a ! -f "${ICUUC_FILE_A}" ] && [ ${IGNORE_ICUUC_FILE_CHECK} = "no" ] && [ ${SANITY} = "sane" ];
     then
 	echo "### $ME: Can't find ${ICUUC_FILE} - ICU prefix is wrong."  1>&2
-	echo "###      Try the --prefix= or --exec-prefix= options " 1>&2
-	echo "###      or --detect-prefix"
+	echo "###      Try the --prefix= option " 1>&2
+	echo "###      or --detect-prefix" 1>&2
+        echo "###      (If you want to disable this check, use  the --noverify option)" 1>&2
 	echo "### $ME: Exitting." 1>&2
 	exit 2
     fi
@@ -108,11 +112,37 @@ if [ $# -lt 1 ]; then
     exit 1
 fi
 
+# For certain options (e.g. --detect-prefix) don't check for icuuc library file.
+
+IGNORE_ICUUC_FILE_CHECK="no";
+
+SANITY="sane"
+
+case "$1" in
+--noverify)
+    SANITY="nosanity"
+    shift
+    ;;
+esac
+
+case "$1" in 
+*prefix*)
+    IGNORE_ICUUC_FILE_CHECK="yes"
+    ;;
+esac
 
 # Load our variables from autoconf
 # ALWAYS load twice because of dependencies
 loaddefs
 loaddefs
+
+if [ $# -gt 0 -a $1 = "--selfcheck" ];
+then
+	echo "passed"
+	exit 
+	# EXIT for self check
+fi
+
 sanity
 
 while [ $# -gt 0 ];
@@ -123,13 +153,18 @@ do
     case "$arg" in
 
         # undocumented.
-	--debug)
+        --debug)
 	    set -x
 	    ;;
-
-        --so)
-            echo $SO
+        
+        --noverify)
+            echo "### $ME: Error: --noverify must be the first argument." 1>&2
+            exit 1
             ;;
+            
+    --so)
+        echo $SO
+        ;;
 
 	--bindir)
 	    echo $bindir
@@ -179,84 +214,83 @@ do
 	    ;;
 
 	--cflags)
-	    echo $CFLAGS
+	    echo $ECHO_N "${CFLAGS} ${ECHO_C}"
 	    ;;
 	    
 	--cc)
-	    echo $CC
+	    echo $ECHO_N "${CC} ${ECHO_C}"
 	    ;;
 	    
 	--cxx)
-	    echo $CXX
+	    echo $ECHO_N "${CXX} ${ECHO_C}"
 	    ;;
 
 	--cxxflags)
-	    echo $CXXFLAGS
+	    echo $ECHO_N "${CXXFLAGS} ${ECHO_C}"
 	    ;;
 
 	--cppflags)
 	    # Don't echo the -I. - it's unneeded.
-	    echo $CPPFLAGS | sed -e 's/-I. //'
+	    echo $ECHO_N "${CPPFLAGS} ${ECHO_C}" | sed -e 's/-I. //'
 	    ;;
 
 	--cppflags-searchpath)
-	    echo -I${prefix}/include
+	    echo $ECHO_N "-I${prefix}/include ${ECHO_C}"
 	    ;;
 
 	--cppflags-dynamic)
-	    echo $SHAREDLIBCPPFLAGS
+	    echo $ECHO_N "${SHAREDLIBCPPFLAGS} ${ECHO_C}"
 	    ;;
 
 	--cxxflags-dynamic)
-	    echo $SHAREDLIBCXXFLAGS
+	    echo $ECHO_N "${SHAREDLIBCXXFLAGS} ${ECHO_C}"
 	    ;;
 
 	--cflags-dynamic)
-	    echo $SHAREDLIBCFLAGS
+	    echo $ECHO_N "${SHAREDLIBCFLAGS} ${ECHO_C}"
 	    ;;
 
 	--ldflags-system)
-	    echo $LIBS
+	    echo $ECHO_N "${LIBS} ${ECHO_C}"
 	    ;;
 
 	--ldflags)
-	    echo $LDFLAGS $ICULIBS $LIBS 
+	    echo $ECHO_N "${LDFLAGS} ${ICULIBS} ${LIBS} ${ECHO_C}"
 # $RPATH_LDFLAGS
 	    ;;
 
 	--ldflags-libsonly)
-	    echo $ICULIBS_I18N $ICULIBS_COMMON $ICULIBS_DATA 
+	    echo $ECHO_N "${ICULIBS_I18N} ${ICULIBS_COMMON} ${ICULIBS_DATA} ${ECHO_C}"
 	    ;;
 
 	--ldflags-icuio)
-	    echo $ICULIBS_ICUIO
+	    echo $ECHO_N " ${ICULIBS_ICUIO} ${ECHO_C}"
 	    ;;
 
 	--ldflags-obsolete)
-	    echo $ICULIBS_OBSOLETE
+	    echo $ECHO_N "${ICULIBS_OBSOLETE} ${ECHO_C}"
 	    ;;
 
 	--ldflags-toolutil)
-	    echo $ICULIBS_TOOLUTIL
+	    echo $ECHO_N " ${ICULIBS_TOOLUTIL} ${ECHO_C}"
 	    ;;
 
 	--ldflags-layout)
-	    echo $ICULIBS_LAYOUT $ICULIBS_LAYOUTEX
+	    echo $ECHO_N "${ICULIBS_LAYOUT} ${ICULIBS_LAYOUTEX} ${ECHO_C}"
 	    ;;
 
 	--ldflags-searchpath)
-	    echo -L${libdir}
+	    echo $ECHO_N "-L${libdir} ${ECHO_C}"
 	    ;;
 
 	--detect-prefix)
 	    HERE=`echo $0 | sed -e "s/$ME//g"`
-	    if [ -f $HERE/../lib/${ICULIBS_COMMON_LIB_NAME} ]; then
-		prefix=$HERE/..
+	    if [ -f "${HERE}/../lib/${ICULIBS_COMMON_LIB_NAME}" -o -f  "${HERE}/../lib/${ICULIBS_COMMON_LIB_NAME_A}"  ]; then
+		prefix="${HERE}/.."
 		echo "## Using --prefix=${prefix}" 1>&2
 	    fi
 	    loaddefs
 	    loaddefs
-	    sanity
 	    ;;
 
 	--exec-prefix)
@@ -271,7 +305,6 @@ do
 	    prefix=$var
 	    loaddefs
 	    loaddefs
-	    sanity
 	    ;;
 
 	--sysconfdir)
@@ -283,44 +316,48 @@ do
 	    ;;
 
 	--shared-datadir)
-	    echo $datadir
+	    echo $ECHO_N "${datadir} ${ECHO_C}"
 	    ;;
 
         --incfile)
-	    echo $pkglibdir/Makefile.inc
+	    echo $ECHO_N "${pkglibdir}/Makefile.inc ${ECHO_C}"
+	    ;;
+
+	--incpkgdatafile)
+	    echo $ECHO_N "${pkglibdir}/pkgdata.inc ${ECHO_C}"
 	    ;;
 
 	--icudata)
-	    echo $ICUDATA_NAME
+	    echo $ECHO_N "${ICUDATA_NAME} ${ECHO_C}"
 	    ;;
 
 	--icudata-mode)
-	    echo $PKGDATA_MODE
+	    echo $ECHO_N "${PKGDATA_MODE} ${ECHO_C}"
 	    ;;
 
 	--icudata-install-dir)
-            echo $ICUPKGDATA_DIR
+        echo $ECHO_N "${ICUPKGDATA_DIR} ${ECHO_C}"
 	    ;;
 	    
 	--icudatadir)
-	    echo $ICUDATA_DIR
+	    echo $ECHO_N "${ICUDATA_DIR} ${ECHO_C}"
 	    ;;
 
 	--shlib-c)
-	    echo $SHLIB_c
+	    echo $ECHO_N "${SHLIB_c} ${ECHO_C}"
 	    ;;
 
 	--shlib-cc)
-	    echo $SHLIB_cc
+	    echo $ECHO_N "${SHLIB_cc} ${ECHO_C}"
 	    ;;
 
 	--version)
-            echo $VERSION
-            ;;
+        echo $ECHO_N $VERSION
+        ;;
 
-        --unicode-version)
-            echo $UNICODE_VERSION
-            ;;
+    --unicode-version)
+        echo $ECHO_N $UNICODE_VERSION
+        ;;
 
 	--help)
 	    usage
@@ -351,8 +388,14 @@ do
             ;;
     esac
     shift
+    
+    # Reset the ignore icuuc file check flag
+    if [ $IGNORE_ICUUC_FILE_CHECK = "yes" ]; then
+        IGNORE_ICUUC_FILE_CHECK="no"
+        sanity
+    fi
 done
-
+echo
 # Check once before we quit (will check last used prefix)
 sanity
 ## END of icu-config-bottom
diff --git a/ICU/icuSources/runConfigureICU b/ICU/icuSources/runConfigureICU
--- a/ICU/icuSources/runConfigureICU
+++ b/ICU/icuSources/runConfigureICU
@@ -1,5 +1,5 @@
 #!/bin/sh
-# Copyright (c) 1999-2008, International Business Machines Corporation and
+# Copyright (c) 1999-2010, International Business Machines Corporation and
 # others. All Rights Reserved.
 
 # runConfigureICU: This script will run the "configure" script for the appropriate platform
@@ -125,7 +125,13 @@ case $platform in
         THE_OS=AIX
         THE_COMP="xlC_r"
         CC=`which xlc_r`; export CC
+        if [ ! -x $CC ]; then
+           echo "ERROR: xlc_r was not found, please check the PATH to make sure it is correct."; exit 1
+        fi
         CXX=`which xlC_r`; export CXX
+        if [ ! -x $CXX ]; then
+           echo "ERROR: xlC_r was not found, please check the PATH to make sure it is correct."; exit 1
+        fi
         RELEASE_CFLAGS="-O2 -qmaxmem=-1"
         RELEASE_CXXFLAGS="-O2 -qmaxmem=-1"
         ;;
@@ -134,6 +140,8 @@ case $platform in
         THE_COMP="the GNU C++"
         CC=gcc; export CC
         CXX=g++; export CXX
+        DEBUG_CFLAGS='-g -O0'
+        DEBUG_CXFLAGS='-g -O0'
         ;;
     Solaris)
         THE_OS=SOLARIS
@@ -173,6 +181,7 @@ case $platform in
         THE_COMP="the iCC C++"
         CC=/usr/bin/icc; export CC
         CXX=/usr/bin/icc; export CXX
+        CPP="$CC -c -qpponly"; export CPP
         MAKE=/usr/bin/gmake; export MAKE
         RELEASE_CFLAGS='-O4'
         RELEASE_CXXFLAGS='-O4'
@@ -187,11 +196,21 @@ case $platform in
         ;;
     Linux/ICC)
         THE_OS="Linux"
-        THE_COMP="Intel ICC 9.0"
         CC=`which icc`; export CC
         CXX=`which icpc`; export CXX
+	ICC_VER=`${CC} -v 2>&1`
         RELEASE_CFLAGS='-O'
         RELEASE_CXXFLAGS='-O'
+        export CFLAGS="-fp-model precise"
+        export CXXFLAGS="-fp-model precise"
+	if [ "${ICC_VER}" = "Version 9.0 " ]; then
+		RELEASE_CFLAGS=''
+		RELEASE_CXXFLAGS=''
+		export CFLAGS="${CFLAGS} -O0"
+		export CXXFLAGS="${CXXFLAGS} -O0"
+		echo "ICC 9.0 does not work with optimization- disabling optimizations"
+	fi
+        THE_COMP="Intel ${ICC_VER}"
         ;;
     Linux/VA)
         THE_OS="Linux"
@@ -206,6 +225,8 @@ case $platform in
         THE_COMP="the GNU C++"
         CC=gcc; export CC
         CXX=g++; export CXX
+        DEBUG_CFLAGS='-g -O0'
+        DEBUG_CXFLAGS='-g -O0'
         ;;
     Cygwin)
         THE_OS="Cygwin"
@@ -218,10 +239,10 @@ case $platform in
         THE_COMP="Microsoft Visual C++"
         CC=cl; export CC
         CXX=cl; export CXX
-        RELEASE_CFLAGS='/O2 /Ob2 /Op'
-        RELEASE_CXXFLAGS='/O2 /Ob2 /Op'
-        DEBUG_CFLAGS='/Zi'
-        DEBUG_CXXFLAGS='/Zi'
+        RELEASE_CFLAGS='/Gy /MD'
+        RELEASE_CXXFLAGS='/Gy /MD'
+        DEBUG_CFLAGS='/Zi /MDd'
+        DEBUG_CXXFLAGS='/Zi /MDd'
         DEBUG_LDFLAGS='/DEBUG'
         ;;
     Cygwin/MSVC2005)
@@ -229,10 +250,10 @@ case $platform in
         THE_COMP="Microsoft Visual C++ 2005"
         CC=cl; export CC
         CXX=cl; export CXX
-        RELEASE_CFLAGS='/O2 /Ob2'
-        RELEASE_CXXFLAGS='/O2 /Ob2'
-        DEBUG_CFLAGS='/Zi'
-        DEBUG_CXXFLAGS='/Zi'
+        RELEASE_CFLAGS='/Gy /MD'
+        RELEASE_CXXFLAGS='/Gy /MD'
+        DEBUG_CFLAGS='/Zi /MDd'
+        DEBUG_CXXFLAGS='/Zi /MDd'
         DEBUG_LDFLAGS='/DEBUG'
         ;;
     Cygwin/ICL)
@@ -252,12 +273,16 @@ case $platform in
         THE_COMP="the GNU C++"
         RELEASE_CFLAGS='-O2'
         RELEASE_CXXFLAGS='-O2'
+        DEBUG_CFLAGS='-g -O0'
+        DEBUG_CXXFLAGS='-g -O0'
         ;;
     *BSD)
         THE_OS="BSD"
         THE_COMP="the GNU C++"
         CC=gcc; export CC
         CXX=g++; export CXX
+        DEBUG_CFLAGS='-g -O0'
+        DEBUG_CXFLAGS='-g -O0'
         ;;
     TRU64V5.1/CXX)
         THE_OS="OSF1"
@@ -284,13 +309,13 @@ case $platform in
         THE_COMP="z/OS 1.2 C/C++"
         CC=cc; export CC
         CXX=cxx; export CXX
-        export COMPILE_LINK_ENVVAR='_CXX_CVERSION=0x41020000 _C89_CVERSION=0x41020000 _CC_CVERSION=0x41020000 _CXX_PVERSION=0x41020000 _C89_PVERSION=0x41020000 _CC_PVERSION=0x41020000'
+        export COMPILE_LINK_ENVVAR='_CXX_CICC_VER}=0x41020000 _C89_CVERSION=0x41020000 _CC_CVERSION=0x41020000 _CXX_PVERSION=0x41020000 _C89_PVERSION=0x41020000 _CC_PVERSION=0x41020000'
         export _CXX_CVERSION=0x41020000 _C89_CVERSION=0x41020000 _CC_CVERSION=0x41020000 _CXX_PVERSION=0x41020000 _C89_PVERSION=0x41020000 _CC_PVERSION=0x41020000
         export LDFLAGS="-Wl,'compat=pm3'"
         export CFLAGS="-Wc,'target(zOSV1R2)'"
         export CXXFLAGS="-Wc,'target(zOSV1R2)'"
-        export RELEASE_CFLAGS="-2 -Wc,'inline(auto,noreport,500,4000)'"
-        export RELEASE_CXXFLAGS="-2 -Wc,'inline(auto,noreport,500,4000)'"
+        RELEASE_CFLAGS="-2 -Wc,'inline(auto,noreport,500,4000)'"
+        RELEASE_CXXFLAGS="-2 -Wc,'inline(auto,noreport,500,4000)'"
         ;;
     *)
         >&2 echo "$me: unrecognized platform \"$platform\" (use --help for help)"
@@ -318,7 +343,7 @@ then
     then
         case $CXX in
             g++|*/g++|*-g++-*|*/*-g++-*)
-                RELEASE_CXXFLAGS=-O
+                RELEASE_CXXFLAGS=-O3
                 ;;
         esac
     fi
@@ -354,10 +379,16 @@ export LDFLAGS
 
 # Run configure
 
+echo "export CPP=$CPP CC=$CC CXX=$CXX CPPFLAGS=$CPPFLAGS CFLAGS=$CFLAGS CXXFLAGS=$CXXFLAGS LDFLAGS=$LDFLAGS MAKE=$MAKE"
 echo "Running ./configure $OPTS $@ for $THE_OS using $THE_COMP compiler"
 echo
-$configure $OPTS $@
-echo
-echo If the result of the above commands looks okay to you, go to the directory
-echo source in the ICU distribution to build ICU. Please remember that ICU needs
-echo GNU make to build properly...
+if $configure $OPTS $@
+then
+	echo
+	echo If the result of the above commands looks okay to you, go to the directory
+	echo source in the ICU distribution to build ICU. Please remember that ICU needs
+	echo GNU make to build properly...
+else
+	echo $0: ./configure failed
+	exit 1
+fi
diff --git a/ICU/icuSources/test/testdata/Makefile.in b/ICU/icuSources/test/testdata/Makefile.in
--- a/ICU/icuSources/test/testdata/Makefile.in
+++ b/ICU/icuSources/test/testdata/Makefile.in
@@ -1,6 +1,6 @@
 #******************************************************************************
 #
-#   Copyright (C) 1998-2008, International Business Machines
+#   Copyright (C) 1998-2010, International Business Machines
 #   Corporation and others.  All Rights Reserved.
 #
 #******************************************************************************
@@ -29,7 +29,9 @@ SUBDIRS =
 .PHONY : all all-local all-recursive install install-local	\
 install-recursive clean clean-local clean-recursive distclean	\
 distclean-local distclean-recursive doc dist dist-local dist-recursive	\
-check check-local check-recursive build-dir java-output
+check check-local check-recursive build-dir testdata.jar xcheck
+
+xcheck: all-local
 
 .NOTPARALLEL: build-dir
 
@@ -63,21 +65,20 @@ Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
 	cd $(top_builddir) \
 	&& CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
 
-pkgdata.inc: $(srcdir)/pkgdata.inc.in Makefile $(top_builddir)/config.status
+pkgdata.inc: pkgdataMakefile
+	$(MAKE) -f pkgdataMakefile
+
+pkgdataMakefile:
 	cd $(top_builddir) \
 	&& CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
-
 
 #########################################################################
 ############################## Test ## stuff ############################
 
-ifeq ($(PKGDATA_OPTS),)
-PKGDATA_OPTS = -O $(top_builddir)/test/testdata/pkgdata.inc
-endif
-
 # relative lib links from pkgdata are the same as for tmp
 GENRBOPTS=-k
-TOOLDIR=$(top_builddir)/tools
+# use the cross root, in case we are cross compiling. Otherwise it is equal to top_builddir
+TOOLDIR=$(cross_buildroot)/tools
 SRCDATADIR=$(top_srcdir)/data
 UNICODEDATADIR=$(SRCDATADIR)/unidata
 OUTDIR=$(top_builddir)/data/out
@@ -86,6 +87,7 @@ BUILDDIR=$(OUTDIR)/build/$(ICUDATA_PLATFORM_NAME)
 TESTSRCDATADIR=$(top_srcdir)/test/testdata
 TESTOUTDIR=$(top_builddir)/test/testdata/out
 BUILD_DIRS = $(TESTOUTDIR) $(TESTBUILDDIR) $(TESTOUTDIR)/$(TESTDT)
+GENTEST=$(TOOLDIR)/gentest/gentest$(TOOLEXEEXT)
 
 ifeq ($(PKGDATA_MODE),common)
 ICU_DATA_OPT = -i $(OUTDIR)
@@ -101,7 +103,13 @@ ICU_DATA_OPT = -i $(BUILDDIR)
 endif
 endif
 
-PKGDATA = $(BINDIR)/pkgdata $(PKGDATA_OPTS) -q -c -s $(CURDIR)/out/build/$(ICUDATA_PLATFORM_NAME)
+CURDIR:=$(CURR_FULL_DIR)
+# current directory should not be blank
+ifeq ($(CURDIR),)
+CURDIR=.
+endif
+
+PKGDATA = $(TOOLBINDIR)/pkgdata -q -c -s $(CURDIR)/out/build/$(ICUDATA_PLATFORM_NAME)
 PKGDATA_INVOKE:=$(INVOKE) $(PKGDATA_INVOKE_OPTS)
 
 # Contains all 'intermediate' files (and temp files) except for 'unpackaged data' below
@@ -119,9 +127,11 @@ TESTDT=$(TESTDATA)
 TEST_DAT_FILES=$(TESTBUILDDIR)/test.icu
 TEST_SPP_FILES=$(TESTBUILDDIR)/nfscsi.spp $(TESTBUILDDIR)/nfscss.spp $(TESTBUILDDIR)/nfscis.spp $(TESTBUILDDIR)/nfsmxs.spp $(TESTBUILDDIR)/nfsmxp.spp
 
-TEST_UCM_SOURCE= test1.ucm test1bmp.ucm test3.ucm test4.ucm test4x.ucm ibm9027.ucm
+TEST_UCM_SOURCE= test1.ucm test1bmp.ucm test3.ucm test4.ucm test4x.ucm test5.ucm ibm9027.ucm
 TEST_UCM_FILES=$(TEST_UCM_SOURCE:%=$(TESTSRCDATADIR)/data/%)
 TEST_CNV_FILES=$(TEST_UCM_SOURCE:%.ucm=$(TESTBUILDDIR)/%.cnv)
+
+TEST_NRM_FILES=$(TESTBUILDDIR)/testnorm.nrm
 
 # import the shared .mk file
 include $(TESTSRCDATADIR)/tstfiles.mk
@@ -129,16 +139,16 @@ include $(TESTSRCDATADIR)/tstfiles.mk
 
 # TEST_RES_SOURCE comes from tstfiles.mk
 TEST_RES = $(TEST_RES_SOURCE) $(TEST_RES_LOCAL) casing.txt mc.txt root.txt sh.txt sh_YU.txt te.txt te_IN.txt te_IN_REVISED.txt testtypes.txt testaliases.txt testempty.txt structLocale.txt idna_rules.txt conversion.txt icuio.txt testtable32.txt
-TEST_RES_FILES=$(TEST_RES:%.txt=$(TESTBUILDDIR)/%.res) $(TESTBUILDDIR)/iscii.res $(TESTBUILDDIR)/icu26_testtypes.res $(TESTBUILDDIR)/icu26e_testtypes.res
+TEST_RES_FILES=$(TEST_RES:%.txt=$(TESTBUILDDIR)/%.res) $(TESTBUILDDIR)/iscii.res $(TESTBUILDDIR)/old_l_testtypes.res $(TESTBUILDDIR)/old_e_testtypes.res
 
-ALL_TEST_FILES = $(TEST_DAT_FILES) $(TEST_SPP_FILES) $(TEST_BRK_FILES) $(TEST_CNV_FILES) $(TEST_RES_FILES) $(TESTOUTDIR)/$(TESTDT)/nam.typ
+ALL_TEST_FILES = $(TEST_DAT_FILES) $(TEST_SPP_FILES) $(TEST_BRK_FILES) $(TEST_CNV_FILES) $(TEST_NRM_FILES) $(TEST_RES_FILES) $(TESTOUTDIR)/$(TESTDT)/nam.typ
 
 # list
 
 $(TESTBUILDDIR)/testdata.lst: $(SRCLISTDEPS)
 	@echo "generating $@ (list of data files)"
 	@-$(RMV) $@
-	@for file in $(TEST_RES_FILES:$(TESTBUILDDIR)/%.res=%.res) $(TEST_DAT_FILES:$(TESTBUILDDIR)/%.icu=%.icu) $(TEST_SPP_FILES:$(TESTBUILDDIR)/%.spp=%.spp) $(TEST_CNV_FILES:$(TESTBUILDDIR)/%.cnv=%.cnv); do \
+	@for file in $(TEST_RES_FILES:$(TESTBUILDDIR)/%.res=%.res) $(TEST_DAT_FILES:$(TESTBUILDDIR)/%.icu=%.icu) $(TEST_SPP_FILES:$(TESTBUILDDIR)/%.spp=%.spp) $(TEST_CNV_FILES:$(TESTBUILDDIR)/%.cnv=%.cnv) $(TEST_NRM_FILES:$(TESTBUILDDIR)/%.nrm=%.nrm); do \
 	  echo $$file >> $@; \
 	done;
 
@@ -146,57 +156,52 @@ $(TESTBUILDDIR)/testdata.lst: $(SRCLISTDEPS)
 build-testdata: build-dir $(ALL_TEST_FILES) $(TESTBUILDDIR)/testdata.lst $(TESTBUILDDIR)/iscii.res
 
 # test.icu
-$(TESTBUILDDIR)/test.icu: $(TOOLDIR)/gentest/gentest$(EXEEXT)
-	$(INVOKE) $(TOOLDIR)/gentest/gentest -d $(TESTBUILDDIR) 
+$(TESTBUILDDIR)/test.icu: $(GENTEST)
+	$(INVOKE) $(GENTEST) -d $(TESTBUILDDIR) 
 
-$(TESTBUILDDIR)/testtable32.txt:  $(TOOLDIR)/gentest/gentest$(EXEEXT)
-	$(INVOKE) $(TOOLDIR)/gentest/gentest -r -d $(TESTBUILDDIR) 
+$(TESTBUILDDIR)/testtable32.txt:  $(GENTEST)
+	$(INVOKE) $(GENTEST) -r -d $(TESTBUILDDIR) 
 
-# java output
-java-output: $(JAVA_OUT_DIR)/DebugUtilitiesData.java
-
-$(JAVA_OUT_DIR)/DebugUtilitiesData.java:  $(TOOLDIR)/gentest/gentest$(EXEEXT)
-	$(MKINSTALLDIRS) $(JAVA_OUT_DIR)
-	$(INVOKE) $(TOOLDIR)/gentest/gentest -j -d $(JAVA_OUT_DIR)
-
-
-$(TESTBUILDDIR)/testtable32.res: $(TESTBUILDDIR)/testtable32.txt $(BINDIR)/genrb$(EXEEXT)
-	$(INVOKE) $(BINDIR)/genrb $(GENRBOPTS) -s $(TESTBUILDDIR) $(ICU_DATA_OPT) -d $(TESTBUILDDIR) $(<F)
+$(TESTBUILDDIR)/testtable32.res: $(TESTBUILDDIR)/testtable32.txt $(TOOLBINDIR)/genrb$(EXEEXT)
+	$(INVOKE) $(TOOLBINDIR)/genrb $(GENRBOPTS) -s $(TESTBUILDDIR) $(ICU_DATA_OPT) -d $(TESTBUILDDIR) $(<F)
 
 # Targets for nfscsi.spp
-$(TESTBUILDDIR)/nfscsi.spp: $(BINDIR)/gensprep$(EXEEXT) $(TESTSRCDATADIR)/nfs4_cs_prep_ci.txt
+$(TESTBUILDDIR)/nfscsi.spp: $(TOOLBINDIR)/gensprep$(EXEEXT) $(TESTSRCDATADIR)/nfs4_cs_prep_ci.txt
 	@echo Building nfscsi.icu
-	$(INVOKE) $(BINDIR)/gensprep -s $(TESTSRCDATADIR) $(ICU_DATA_OPT) -d $(TESTBUILDDIR) -b nfscsi -u 3.2.0 nfs4_cs_prep_ci.txt
+	$(INVOKE) $(TOOLBINDIR)/gensprep -s $(TESTSRCDATADIR) $(ICU_DATA_OPT) -d $(TESTBUILDDIR) -b nfscsi -u 3.2.0 nfs4_cs_prep_ci.txt
 
 # Targets for nfscss.spp
-$(TESTBUILDDIR)/nfscss.spp: $(BINDIR)/gensprep$(EXEEXT) $(TESTSRCDATADIR)/nfs4_cs_prep_cs.txt
+$(TESTBUILDDIR)/nfscss.spp: $(TOOLBINDIR)/gensprep$(EXEEXT) $(TESTSRCDATADIR)/nfs4_cs_prep_cs.txt
 	@echo Building nfscss.icu
-	$(INVOKE) $(BINDIR)/gensprep -s $(TESTSRCDATADIR) $(ICU_DATA_OPT) -d $(TESTBUILDDIR) -b nfscss -u 3.2.0 nfs4_cs_prep_cs.txt
+	$(INVOKE) $(TOOLBINDIR)/gensprep -s $(TESTSRCDATADIR) $(ICU_DATA_OPT) -d $(TESTBUILDDIR) -b nfscss -u 3.2.0 nfs4_cs_prep_cs.txt
 
 # Targets for nfscis.spp
-$(TESTBUILDDIR)/nfscis.spp: $(BINDIR)/gensprep$(EXEEXT) $(TESTSRCDATADIR)/nfs4_cis_prep.txt
+$(TESTBUILDDIR)/nfscis.spp: $(TOOLBINDIR)/gensprep$(EXEEXT) $(TESTSRCDATADIR)/nfs4_cis_prep.txt
 	@echo Building nfscis.spp
-	$(INVOKE) $(BINDIR)/gensprep -s $(TESTSRCDATADIR) $(ICU_DATA_OPT) -d $(TESTBUILDDIR) -b nfscis -k -n $(UNICODEDATADIR) -u 3.2.0 nfs4_cis_prep.txt
+	$(INVOKE) $(TOOLBINDIR)/gensprep -s $(TESTSRCDATADIR) $(ICU_DATA_OPT) -d $(TESTBUILDDIR) -b nfscis -k -n $(UNICODEDATADIR) -u 3.2.0 nfs4_cis_prep.txt
 
 # Targets for nfsmxs.spp
-$(TESTBUILDDIR)/nfsmxs.spp: $(BINDIR)/gensprep$(EXEEXT) $(TESTSRCDATADIR)/nfs4_mixed_prep_s.txt
+$(TESTBUILDDIR)/nfsmxs.spp: $(TOOLBINDIR)/gensprep$(EXEEXT) $(TESTSRCDATADIR)/nfs4_mixed_prep_s.txt
 	@echo Building nfsmxs.spp
-	$(INVOKE) $(BINDIR)/gensprep -s $(TESTSRCDATADIR) $(ICU_DATA_OPT) -d $(TESTBUILDDIR) -b nfsmxs -k -n $(UNICODEDATADIR) -u 3.2.0 nfs4_mixed_prep_s.txt
+	$(INVOKE) $(TOOLBINDIR)/gensprep -s $(TESTSRCDATADIR) $(ICU_DATA_OPT) -d $(TESTBUILDDIR) -b nfsmxs -k -n $(UNICODEDATADIR) -u 3.2.0 nfs4_mixed_prep_s.txt
 
 # Targets for nfsmxp.spp
-$(TESTBUILDDIR)/nfsmxp.spp: $(BINDIR)/gensprep$(EXEEXT) $(TESTSRCDATADIR)/nfs4_mixed_prep_p.txt
+$(TESTBUILDDIR)/nfsmxp.spp: $(TOOLBINDIR)/gensprep$(EXEEXT) $(TESTSRCDATADIR)/nfs4_mixed_prep_p.txt
 	@echo Building nfsmxp.spp
-	$(INVOKE) $(BINDIR)/gensprep -s $(TESTSRCDATADIR) $(ICU_DATA_OPT) -d $(TESTBUILDDIR) -b nfsmxp -k -n $(UNICODEDATADIR) -u 3.2.0 nfs4_mixed_prep_p.txt
+	$(INVOKE) $(TOOLBINDIR)/gensprep -s $(TESTSRCDATADIR) $(ICU_DATA_OPT) -d $(TESTBUILDDIR) -b nfsmxp -k -n $(UNICODEDATADIR) -u 3.2.0 nfs4_mixed_prep_p.txt
 
-$(TESTBUILDDIR)/%.cnv: $(TESTSRCDATADIR)/%.ucm $(BINDIR)/makeconv$(EXEEXT)
-	$(INVOKE) $(BINDIR)/makeconv --small -c -d $(TESTBUILDDIR) $(TESTSRCDATADIR)/$(<F)
+$(TESTBUILDDIR)/%.cnv: $(TESTSRCDATADIR)/%.ucm $(TOOLBINDIR)/makeconv$(EXEEXT)
+	$(INVOKE) $(TOOLBINDIR)/makeconv --small -c -d $(TESTBUILDDIR) $(TESTSRCDATADIR)/$(<F)
 
-$(TESTBUILDDIR)/%.res: $(TESTSRCDATADIR)/%.txt $(BINDIR)/genrb$(EXEEXT) $(DAT_FILES)
-	$(INVOKE) $(BINDIR)/genrb $(GENRBOPTS) -q -s $(TESTSRCDATADIR) $(ICU_DATA_OPT) -d $(TESTBUILDDIR) $(<F)
+$(TESTBUILDDIR)/%.nrm: $(TESTSRCDATADIR)/%.txt $(TOOLBINDIR)/gennorm2$(EXEEXT)
+	$(INVOKE) $(TOOLBINDIR)/gennorm2 -s $(TESTSRCDATADIR) $(<F) -o $@
 
-$(TESTBUILDDIR)/iscii.res:  $(TESTSRCDATADIR)/iscii.bin $(BINDIR)/genrb$(EXEEXT)
+$(TESTBUILDDIR)/%.res: $(TESTSRCDATADIR)/%.txt $(TOOLBINDIR)/genrb$(EXEEXT) $(DAT_FILES)
+	$(INVOKE) $(TOOLBINDIR)/genrb $(GENRBOPTS) -q -s $(TESTSRCDATADIR) $(ICU_DATA_OPT) -d $(TESTBUILDDIR) $(<F)
+
+$(TESTBUILDDIR)/iscii.res:  $(TESTSRCDATADIR)/iscii.bin $(TOOLBINDIR)/genrb$(EXEEXT)
 	@echo Testing genrb -e option
-	@ICU_DATA=$(BUILDDIR) $(INVOKE) $(BINDIR)/genrb $(GENRBOPTS) -s $(TESTSRCDATADIR) -eISCII,version=0 -d $(TESTBUILDDIR) $(<F) >/dev/null  || ( echo "WARNING: could not open ISCII - it may have been disabled." | tee $@ )
+	@ICU_DATA=$(BUILDDIR) $(INVOKE) $(TOOLBINDIR)/genrb $(GENRBOPTS) -s $(TESTSRCDATADIR) -eISCII,version=0 -d $(TESTBUILDDIR) $(<F) >/dev/null  || ( echo "WARNING: could not open ISCII - it may have been disabled." | tee $@ )
 	@echo Finished testing genrb -e option
 
 ################################################################### TYP
@@ -204,9 +209,9 @@ $(TESTBUILDDIR)/iscii.res:  $(TESTSRCDATADIR)/iscii.bin $(BINDIR)/genrb$(EXEEXT)
 
 $(TESTOUTDIR)/$(TESTDT)/nam.typ: $(TESTBUILDDIR)/te_IN.res
 	cp $< $@
-$(TESTBUILDDIR)/icu26_testtypes.res: $(TESTSRCDATADIR)/icu26_testtypes.res
+$(TESTBUILDDIR)/old_l_testtypes.res: $(TESTSRCDATADIR)/old_l_testtypes.res
 	cp $< $@
-$(TESTBUILDDIR)/icu26e_testtypes.res: $(TESTSRCDATADIR)/icu26e_testtypes.res
+$(TESTBUILDDIR)/old_e_testtypes.res: $(TESTSRCDATADIR)/old_e_testtypes.res
 	cp $< $@
 
 testdata: build-dir $(ALL_TEST_FILES) $(UNPACKAGEDTESTDATA)
@@ -220,4 +225,53 @@ build-dir: $(BUILD_DIRS)
 $(BUILD_DIRS):
 	-$(MKINSTALLDIRS) $(BUILD_DIRS)
 
+# Build the ICU4J testdata.jar.
+# Command line:
+#   (Run this from the output testdata folder which may not be .../source/test/testdata in an out-of-source build.)
+#   ~/svn.icu/trunk/source/test/testdata> make JAR=jar ICU4J_ROOT=~/svn.icu4j/trunk testdata.jar
+# You can omit the ICU4J_ROOT for just building the .jar files without copying them.
+# You can omit the JAR if it's just jar.
+JAR=jar
 
+# Build testdata.jar:
+# - swap the test data
+# - extract all data items
+# - package them into the .jar file
+$(OUTDIR)/icu4j/testdata.jar: build-dir testdata $(TESTOUTDIR)/testdata.dat
+	mkdir -p $(OUTDIR)/icu4j/com/ibm/icu/dev/data/testdata
+	$(INVOKE) $(TOOLBINDIR)/icupkg $(TESTOUTDIR)/testdata.dat -r test.icu -x '*' -tb -d $(OUTDIR)/icu4j/com/ibm/icu/dev/data/testdata
+	$(JAR) cf $(OUTDIR)/icu4j/testdata.jar -C $(OUTDIR)/icu4j com/ibm/icu/dev/data/testdata
+
+
+DEBUGUTILITIESDATA_DIR=main/tests/core/src/com/ibm/icu/dev/test/util
+DEBUGUTILITIESDATA_SRC=DebugUtilitiesData.java
+
+ICU4J_DATA=$(OUTDIR)/icu4j/src/$(DEBUGUTILITIESDATA_SRC) $(OUTDIR)/icu4j/testdata.jar
+
+$(OUTDIR)/icu4j/src/$(DEBUGUTILITIESDATA_SRC): $(GENTEST)
+	mkdir -p $(OUTDIR)/icu4j/src
+	$(INVOKE) $(GENTEST) -j -d $(OUTDIR)/icu4j/src
+
+ifdef ICU4J_ROOT
+
+icu4j-data-install: $(ICU4J_ROOT)/main/shared/data/testdata.jar $(ICU4J_ROOT)/$(DEBUGUTILITIESDATA_DIR)/$(DEBUGUTILITIESDATA_SRC)
+	@echo ICU4J test data installed in $(ICU4J_ROOT)
+
+$(ICU4J_ROOT)/main/shared/data/testdata.jar: $(OUTDIR)/icu4j/testdata.jar
+	mkdir -p $(ICU4J_ROOT)/main/shared/data
+	cp $(OUTDIR)/icu4j/testdata.jar $(ICU4J_ROOT)/main/shared/data
+
+$(ICU4J_ROOT)/$(DEBUGUTILITIESDATA_DIR)/$(DEBUGUTILITIESDATA_SRC): $(OUTDIR)/icu4j/src/$(DEBUGUTILITIESDATA_SRC)
+	mkdir -p $(ICU4J_ROOT)/$(DEBUGUTILITIESDATA_DIR)
+	cp $^ $@
+
+else
+
+icu4j-data-install: $(ICU4J_DATA)
+	@echo ICU4J data was built into $(OUTDIR)/icu4j
+	@echo '** Error:' ICU4J_ROOT was not set, could not install
+	exit 1
+
+endif
+
+icu4j-data: $(ICU4J_DATA)
diff --git a/Libsystem/Makefile b/Libsystem/Makefile
--- a/Libsystem/Makefile
+++ b/Libsystem/Makefile
@@ -6,27 +6,55 @@ NAME = $(NAME0).$(VersionLetter)
 
 # for now, use the default compiler
 MYCC := $(CC)
+.if $(RC_TARGET_CONFIG) == iPhone
 MYCCLIBS = -lgcc
-RTLIBS = -lcompiler_rt
-NARCHS != $(ECHO) $(RC_ARCHS) | $(WC) -w
-.ifdef ALTUSRLOCALLIBSYSTEM
-LIBSYS = $(ALTUSRLOCALLIBSYSTEM)
-.else
-LIBSYS = $(SDKROOT)/usr/local/lib/system
 .endif
+RTLIBS =
+NARCHS != $(ECHO) $(RC_ARCHS) | $(WC) -w
 SLFS_F_PH = $(SDKROOT)/System/Library/Frameworks/System.framework/PrivateHeaders
+CODESIGN != xcrun -find codesign
 .ifdef SDKROOT
 SDKROOTCFLAGS = -isysroot '$(SDKROOT)'
 SDKROOTLDFLAGS = -Wl,-syslibroot,'$(SDKROOT)'
 .endif
 ORDERFILES = -Wl,-order_file,$(SRCROOT)/SystemInit.order -Wl,-order_file,$(PLATFORM_ORDER_FILE)
-LIBS = -lc -lcommonCrypto -ldyldapis\
-       -linfo -ldns_sd -lm -lmacho\
-       -lnotify -lkeymgr -llaunch \
-       -lcopyfile -lremovefile
-CONDITIONALLIBS = unc sandbox quarantine closure cache dispatch unwind \
-	dnsinfo
-LIBSCONDITIONAL != for L in $(CONDITIONALLIBS); do tconf -q --test usr_local_lib_system_Archive:lib$$L && $(ECHO) -l$$L; done
+
+.ifdef ALTUSRLOCALLIBSYSTEM
+LIBSYS = $(ALTUSRLOCALLIBSYSTEM)
+.else
+LIBSYS = $(SDKROOT)/usr/local/lib/system
+.endif
+.ifdef ALTUSRLIBSYSTEM
+LSYS = $(ALTUSRLIBSYSTEM)
+.else
+LSYS = $(SDKROOT)/usr/lib/system
+.endif
+
+ACTUALLIBS = $(SYMROOT)/actuallibs
+ALLLIBS = $(SYMROOT)/alllibs
+FROMUSRLIBSYSTEM = $(SYMROOT)/fromusrlibsystem
+FROMUSRLOCALLIBSYSTEM = $(SYMROOT)/fromusrlocallibsystem
+INUSRLIBSYSTEM = $(SYMROOT)/inusrlibsystem
+INUSRLOCALLIBSYSTEM = $(SYMROOT)/inusrlocallibsystem
+MISSINGLIBS = $(SYMROOT)/missinglibs
+OPTIONALLIBS = $(SRCROOT)/optionallibs
+POSSIBLEUSRLOCALLIBSYSTEM = $(SYMROOT)/possibleusrlocallibsystem
+REQUIREDLIBS = $(SRCROOT)/requiredlibs
+
+$(MISSINGLIBS):
+	cat $(REQUIREDLIBS) $(OPTIONALLIBS) | sort > $(ALLLIBS)
+	cd $(LSYS) && ls lib*.dylib | sed -E -e 's/^lib//' -e 's/\..*$$//' -e 's/_(debug|profile|static)$$//' | sort -u > $(INUSRLIBSYSTEM)
+	cd $(LIBSYS) && ls lib*.a | sed -E -e 's/^lib//' -e 's/\..*$$//' -e 's/_(debug|profile|static)$$//' | sort -u > $(INUSRLOCALLIBSYSTEM)
+	comm -12 $(ALLLIBS) $(INUSRLIBSYSTEM) > $(FROMUSRLIBSYSTEM)
+	comm -12 $(ALLLIBS) $(INUSRLOCALLIBSYSTEM) > $(POSSIBLEUSRLOCALLIBSYSTEM)
+	comm -13 $(FROMUSRLIBSYSTEM) $(POSSIBLEUSRLOCALLIBSYSTEM) > $(FROMUSRLOCALLIBSYSTEM)
+	cat $(FROMUSRLIBSYSTEM) $(FROMUSRLOCALLIBSYSTEM) | sort > $(ACTUALLIBS)
+	comm -23 $(REQUIREDLIBS) $(ACTUALLIBS) > $(MISSINGLIBS)
+	@if [ -s $(MISSINGLIBS) ]; then \
+	    echo '*** missing required libs ***' && \
+	    cat $(MISSINGLIBS) && \
+	    exit 1; \
+	fi ;
 
 # These variables are to guarantee that the left-hand side of an expression is
 # always a variable
@@ -48,7 +76,7 @@ install: BI-install-$(F)
 .endif # RC_ProjectName
 
 .for A in $(RC_ARCHS)
-OBJS-$(A) = $(OBJROOT)/$(A)/SystemMath.o $(OBJROOT)/$(A)/System_vers.o
+OBJS-$(A) = $(OBJROOT)/$(A)/SystemMath.o $(OBJROOT)/$(A)/CompatibilityHacks.o $(OBJROOT)/$(A)/System_vers.o $(OBJROOT)/$(A)/init.o
 .endfor # RC_ARCHS
 
 .for F in $(FORMS)
@@ -56,9 +84,6 @@ OBJS-$(A) = $(OBJROOT)/$(A)/SystemMath.o $(OBJROOT)/$(A)/System_vers.o
 SUFFIX$(F) =
 .else
 SUFFIX$(F) = _$(F)
-.endif
-.if !empty(FEATURE_LIBMATHCOMMON)
-LIBMATHCOMMON$(F) = -L/usr/lib/system -sub_library libmathCommon$(SUFFIX$(F)) -lmathCommon$(SUFFIX$(F))
 .endif
 LIPOARGS$(F) != $(PERL) -e 'printf "%s\n", join(" ", map(qq(-arch $$_ \"$(OBJROOT)/$$_/$(F)/$(NAME)$(SUFFIX$(F)).dylib\"), qw($(RC_ARCHS))))'
 
@@ -74,25 +99,22 @@ build-$(F):
 	$(DSYMUTIL) "$(SYMROOT)/$(NAME)$(SUFFIX$(F)).dylib"
 
 .for A in $(RC_ARCHS)
+# Hardcode libc.a for now.  This will have to be changed when libc becomes
+# its own dylib.
 LINKDYLIB-$(F)-$(A) = $(MYCC) -dynamiclib -arch $(A) -pipe $(SDKROOTLDFLAGS) \
 	-o '$(OBJROOT)/$(A)/$(F)/$(NAME)$(SUFFIX$(F)).dylib' \
 	-compatibility_version 1 -current_version $(Version) \
 	-install_name /usr/lib/$(NAME)$(SUFFIX$(F)).dylib \
-	-nodefaultlibs -all_load -multi_module -Wl,-search_paths_first \
-	-segcreate __DATA __commpage $(OBJROOT)/$(A)/CommPageSymbols.o \
+	-nodefaultlibs -Wl,-search_paths_first \
 	$(ORDERFILES) $(SKDROOTLDFLAGS) $(OBJS-$(A)) \
-	-L$(DSTROOT)/usr/local/lib/system -L$(LIBSYS) $(LIBMATHCOMMON$(F)) \
-	$(LIBS:C/$/$(SUFFIX$(F))/) $(LIBSCONDITIONAL:C/$/$(SUFFIX$(F))/)
+	-L$(LSYS) -L$(LIBSYS) $(LIBMATHCOMMON$(F)) \
+	`sed 's/.*/-Wl,-reexport-l&/' $(FROMUSRLIBSYSTEM)` \
+	`sed -e '/^c$$/d' -e 's|.*|-Wl,-force_load,$(LIBSYS)/lib&$(SUFFIX$(F)).a|' $(FROMUSRLOCALLIBSYSTEM)`
 
-build-$(A)-$(F): $(OBJROOT)/$(A)/$(F) $(OBJROOT)/$(A)/CommPageSymbols.o $(OBJS-$(A))
-	@$(ECHO) $(LINKDYLIB-$(F)-$(A)) $(RTLIBS) && \
-	if $(LINKDYLIB-$(F)-$(A)) $(RTLIBS); then \
-	    $(ECHO) -n; \
-	else \
-	    $(ECHO) '*** Failed.  Retrying with -lgcc ***' && \
-	    $(ECHO) $(LINKDYLIB-$(F)-$(A)) $(MYCCLIBS) && \
-	    $(LINKDYLIB-$(F)-$(A)) $(MYCCLIBS); \
-	fi
+build-$(A)-$(F): $(OBJROOT)/$(A)/$(F) $(OBJS-$(A)) $(MISSINGLIBS)
+	@$(ECHO) '========================================='
+	@$(ECHO) $(LINKDYLIB-$(F)-$(A)) $(RTLIBS) $(MYCCLIBS)
+	@$(LINKDYLIB-$(F)-$(A)) $(RTLIBS) $(MYCCLIBS)
 
 $(OBJROOT)/$(A)/$(F):
 	$(MKDIR) '$(.TARGET)'
@@ -113,14 +135,16 @@ $(OBJROOT)/System_vers.c:
 	$(SED) -e 's/SGS_VERS/SYSTEM_VERS_STRING/' -e 's/VERS_NUM/SYSTEM_VERS_NUM/' > $(.TARGET)
 
 .for A in $(RC_ARCHS)
-$(OBJROOT)/$(A)/CommPageSymbols.o: $(SRCROOT)/CommPageSymbols.st
-	$(MYCC) -c -o '$(.TARGET:R)_intermediate.$(.TARGET:E)' -arch $(A) -x assembler-with-cpp $(CFLAGS) '$(.ALLSRC)'
-	$(LD) -arch $(A) -r -seg1addr $(SEG1ADDR_$(A:C/^armv.*$/arm/)) '$(.TARGET:R)_intermediate.$(.TARGET:E)' -o '$(.TARGET)'
-
 $(OBJROOT)/$(A)/SystemMath.o: $(SRCROOT)/SystemMath.s
 	$(MYCC) -c -o '$(.TARGET)' -arch $(A) $(CFLAGS) '$(.ALLSRC)'
 
+$(OBJROOT)/$(A)/CompatibilityHacks.o: $(SRCROOT)/CompatibilityHacks.c
+	$(MYCC) -c -o '$(.TARGET)' -arch $(A) $(CFLAGS) '$(.ALLSRC)'
+
 $(OBJROOT)/$(A)/System_vers.o: $(OBJROOT)/System_vers.c
+	$(MYCC) -c -o '$(.TARGET)' -arch $(A) $(CFLAGS) '$(.ALLSRC)'
+
+$(OBJROOT)/$(A)/init.o: $(SRCROOT)/init.c
 	$(MYCC) -c -o '$(.TARGET)' -arch $(A) $(CFLAGS) '$(.ALLSRC)'
 
 .endfor # RC_ARCHS
@@ -135,6 +159,7 @@ BI-install-$(F): build-$(F)
 	$(STRIP) -S "$(DSTROOT)/usr/lib/$(NAME)$(SUFFIX$(F)).dylib"
 	$(CHMOD) a-w "$(DSTROOT)/usr/lib/$(NAME)$(SUFFIX$(F)).dylib"
 	$(LN) -sf "$(NAME)$(SUFFIX$(F)).dylib" "$(DSTROOT)/usr/lib/$(NAME0)$(SUFFIX$(F)).dylib"
+	$(CODESIGN) -s - "$(DSTROOT)/usr/lib/$(NAME)$(SUFFIX$(F)).dylib"
 .endfor # FORMS
 
 install-all: build
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test018-syncreplication-persist b/OpenLDAP/OpenLDAP/tests/scripts/test018-syncreplication-persist
--- a/OpenLDAP/OpenLDAP/tests/scripts/test018-syncreplication-persist
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test018-syncreplication-persist
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test018-syncreplication-persist,v 1.38.2.3 2008/02/11 23:26:51 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test018-syncreplication-persist,v 1.38.2.13 2010/04/19 19:24:42 quanah Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2008 The OpenLDAP Foundation.
+## Copyright 1998-2010 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -13,13 +13,10 @@
 ## top-level directory of the distribution or, alternatively, at
 ## <http://www.OpenLDAP.org/license.html>.
 
-if test "$BACKEND" != "bdb" && test "$BACKEND" != "hdb" ; then
-	echo "Test does not support $BACKEND"
-	exit 0
-fi
-
 echo "running defines.sh"
 . $SRCDIR/scripts/defines.sh
+
+OPATTRS="entryUUID creatorsName createTimestamp modifiersName modifyTimestamp"
 
 if test $SYNCPROV = syncprovno; then 
 	echo "Syncrepl provider overlay not available, test skipped"
@@ -118,8 +115,44 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-echo "Waiting 15 seconds for syncrepl to receive changes..."
-sleep 15
+echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
+sleep $SLEEP1
+
+echo "Using ldapsearch to read all the entries from the producer..."
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
+	'(objectclass=*)' '*' $OPATTRS > $MASTEROUT 2>&1
+RC=$?
+
+if test $RC != 0 ; then
+	echo "ldapsearch failed at producer ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "Using ldapsearch to read all the entries from the consumer..."
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT4 \
+	'(objectclass=*)' '*' $OPATTRS > $SLAVEOUT 2>&1
+RC=$?
+
+if test $RC != 0 ; then
+	echo "ldapsearch failed at consumer ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "Filtering producer results..."
+$LDIFFILTER < $MASTEROUT > $MASTERFLT
+echo "Filtering consumer results..."
+$LDIFFILTER < $SLAVEOUT > $SLAVEFLT
+
+echo "Comparing retrieved entries from producer and consumer..."
+$CMP $MASTERFLT $SLAVEFLT > $CMPOUT
+
+if test $? != 0 ; then
+	echo "test failed - producer and consumer databases differ"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+fi
 
 echo "Stopping the provider, sleeping 10 seconds and restarting it..."
 kill -HUP "$PID"
@@ -147,6 +180,9 @@ for i in 0 1 2 3 4 5; do
 	echo "Waiting 5 seconds for slapd to start..."
 	sleep 5
 done
+
+echo "Waiting $SLEEP1 seconds for consumer to reconnect..."
+sleep $SLEEP1
 
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
@@ -205,9 +241,31 @@ drink: Coffee
 homepostaladdress: 844 Brown St. Apt. 4 $ Ann Arbor, MI 48104
 description: Very odd
 facsimiletelephonenumber: +1 313 555 7557
+facsimiletelephonenumber: +1 313 555 9998
+facsimiletelephonenumber: +1 313 555 9999
 telephonenumber: +1 313 555 8343
 mail: gjensen@mailgw.example.com
 homephone: +1 313 555 8844
+
+# modify attribute with no matching rule (ITS#6458)
+dn: cn=Gern Jensen, ou=Information Technology Division, ou=People, dc=example,dc=com
+changetype: modify
+replace: facsimiletelephonenumber
+facsimiletelephonenumber: +1 313 555 9998
+facsimiletelephonenumber: +1 313 555 9999
+
+dn: cn=Gern Jensen, ou=Information Technology Division, ou=People, dc=example,dc=com
+changetype: modify
+replace: facsimiletelephonenumber
+facsimiletelephonenumber: +1 313 555 9998
+facsimiletelephonenumber: +1 313 555 9999
+facsimiletelephonenumber: +1 313 555 7557
+
+dn: cn=Gern Jensen, ou=Information Technology Division, ou=People, dc=example,dc=com
+changetype: modify
+replace: facsimiletelephonenumber
+facsimiletelephonenumber: +1 313 555 9998
+facsimiletelephonenumber: +1 313 555 9999
 
 dn: ou=Retired, ou=People, dc=example,dc=com
 changetype: add
@@ -231,6 +289,21 @@ newsuperior: ou=Retired, ou=People, dc=example,dc=com
 dn: cn=James A Jones 2, ou=Information Technology Division, ou=People, dc=example,dc=com
 changetype: delete
 
+dn: dc=testdomain1,dc=example,dc=com
+changetype: modrdn
+newrdn: dc=itsdomain1
+deleteoldrdn: 1
+
+dn: dc=itsdomain1,dc=example,dc=com
+changetype: modify
+replace: description
+description: Example, Inc. ITS test domain
+
+dn: dc=testdomain2,dc=example,dc=com
+changetype: modrdn
+newrdn: dc=itsdomain2
+deleteoldrdn: 1
+
 EOMODS
 
 RC=$?
@@ -251,8 +324,44 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-echo "Waiting 15 seconds for syncrepl to receive changes..."
-sleep 15
+echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
+sleep $SLEEP1
+
+echo "Using ldapsearch to read all the entries from the producer..."
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
+	'(objectclass=*)' '*' $OPATTRS > $MASTEROUT 2>&1
+RC=$?
+
+if test $RC != 0 ; then
+	echo "ldapsearch failed at producer ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "Using ldapsearch to read all the entries from the consumer..."
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT4 \
+	'(objectclass=*)' '*' $OPATTRS > $SLAVEOUT 2>&1
+RC=$?
+
+if test $RC != 0 ; then
+	echo "ldapsearch failed at consumer ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "Filtering producer results..."
+$LDIFFILTER < $MASTEROUT > $MASTERFLT
+echo "Filtering consumer results..."
+$LDIFFILTER < $SLAVEOUT > $SLAVEFLT
+
+echo "Comparing retrieved entries from producer and consumer..."
+$CMP $MASTERFLT $SLAVEFLT > $CMPOUT
+
+if test $? != 0 ; then
+	echo "test failed - producer and consumer databases differ"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+fi
 
 echo "Stopping consumer to test recovery..."
 kill -HUP $SLAVEPID
@@ -276,7 +385,31 @@ sn: Coltrane
 uid: rosco
 cn: Rosco P. Coltrane
 
+dn: dc=itsdomain2,dc=example,dc=com
+changetype: modify
+replace: description
+description: Example, Inc. itsdomain2 test domain
+
+# rename with a newly added newSuperior while the consumer is down (ITS#6472)
+dn: ou=New Branch,dc=example,dc=com
+changetype: add
+objectClass: organizationalUnit
+ou: New Branch
+
+dn: cn=Dorothy Stevens, ou=Alumni Association, ou=People, dc=example,dc=com
+changetype: modrdn
+newrdn: cn=Dorothy Stevens
+deleteoldrdn: 0
+newsuperior: ou=New Branch,dc=example,dc=com
+
 EOMODS
+
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
 
 echo "Restarting consumer..."
 echo "RESTART" >> $LOG4
@@ -288,8 +421,44 @@ if test $WAIT != 0 ; then
 fi
 KILLPIDS="$PID $SLAVEPID"
 
-echo "Waiting 25 seconds for syncrepl to receive changes..."
-sleep 25
+echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
+sleep $SLEEP1
+
+echo "Using ldapsearch to read all the entries from the producer..."
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
+	'(objectclass=*)' '*' $OPATTRS > $MASTEROUT 2>&1
+RC=$?
+
+if test $RC != 0 ; then
+	echo "ldapsearch failed at producer ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "Using ldapsearch to read all the entries from the consumer..."
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT4 \
+	'(objectclass=*)' '*' $OPATTRS > $SLAVEOUT 2>&1
+RC=$?
+
+if test $RC != 0 ; then
+	echo "ldapsearch failed at consumer ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "Filtering producer results..."
+$LDIFFILTER < $MASTEROUT > $MASTERFLT
+echo "Filtering consumer results..."
+$LDIFFILTER < $SLAVEOUT > $SLAVEFLT
+
+echo "Comparing retrieved entries from producer and consumer..."
+$CMP $MASTERFLT $SLAVEFLT > $CMPOUT
+
+if test $? != 0 ; then
+	echo "test failed - producer and consumer databases differ"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+fi
 
 if test ! $BACKLDAP = "ldapno" ; then
 	echo "Try updating the consumer slapd..."
@@ -322,11 +491,9 @@ EOMODS
 		exit $RC
 	fi
 
-	echo "Waiting 15 seconds for syncrepl to receive changes..."
-	sleep 15
+	echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
+	sleep $SLEEP1
 fi
-
-OPATTRS="entryUUID creatorsName createTimestamp modifiersName modifyTimestamp"
 
 echo "Using ldapsearch to read all the entries from the producer..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
@@ -350,20 +517,21 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-test $KILLSERVERS != no && kill -HUP $KILLPIDS
-
 echo "Filtering producer results..."
-. $LDIFFILTER < $MASTEROUT > $MASTERFLT
+$LDIFFILTER < $MASTEROUT > $MASTERFLT
 echo "Filtering consumer results..."
-. $LDIFFILTER < $SLAVEOUT > $SLAVEFLT
+$LDIFFILTER < $SLAVEOUT > $SLAVEFLT
 
 echo "Comparing retrieved entries from producer and consumer..."
 $CMP $MASTERFLT $SLAVEFLT > $CMPOUT
 
 if test $? != 0 ; then
 	echo "test failed - producer and consumer databases differ"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit 1
 fi
+
+test $KILLSERVERS != no && kill -HUP $KILLPIDS
 
 echo ">>>>> Test succeeded"
 
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test019-syncreplication-cascade b/OpenLDAP/OpenLDAP/tests/scripts/test019-syncreplication-cascade
--- a/OpenLDAP/OpenLDAP/tests/scripts/test019-syncreplication-cascade
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test019-syncreplication-cascade
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test019-syncreplication-cascade,v 1.19.2.3 2008/02/11 23:26:51 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test019-syncreplication-cascade,v 1.19.2.11 2010/04/19 19:14:34 quanah Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2008 The OpenLDAP Foundation.
+## Copyright 1998-2010 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -12,11 +12,6 @@
 ## A copy of this license is available in the file LICENSE in the
 ## top-level directory of the distribution or, alternatively, at
 ## <http://www.OpenLDAP.org/license.html>.
-
-if test "$BACKEND" != "bdb" && test "$BACKEND" != "hdb" ; then
-	echo "Test does not support $BACKEND"
-	exit 0
-fi
 
 echo "running defines.sh"
 . $SRCDIR/scripts/defines.sh
@@ -237,8 +232,8 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-echo "Waiting 25 seconds for syncrepl to receive changes..."
-sleep 25
+echo "Waiting $SLEEP2 seconds for syncrepl to receive changes..."
+sleep $SLEEP2
 
 echo "Using ldapmodify to modify master directory..."
 
@@ -317,6 +312,21 @@ newsuperior: ou=Retired, ou=People, dc=example,dc=com
 dn: cn=James A Jones 2, ou=Information Technology Division, ou=People, dc=example,dc=com
 changetype: delete
 
+dn: dc=testdomain1,dc=example,dc=com
+changetype: modrdn
+newrdn: dc=itsdomain1
+deleteoldrdn: 1
+
+dn: dc=itsdomain1,dc=example,dc=com
+changetype: modify
+replace: description
+description: Example, Inc. ITS test domain
+
+dn: dc=testdomain2,dc=example,dc=com
+changetype: modrdn
+newrdn: dc=itsdomain2
+deleteoldrdn: 1
+
 EOMODS
 
 RC=$?
@@ -326,12 +336,32 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-echo "Waiting 25 seconds for syncrepl to receive changes..."
-sleep 25
+echo "Waiting $SLEEP2 seconds for syncrepl to receive changes..."
+sleep $SLEEP2
+
+echo "Performing modify alone on provider..."
+$LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD > \
+        $TESTOUT 2>&1 << EOMODS
+dn: dc=itsdomain2,dc=example,dc=com
+changetype: modify
+replace: description
+description: Example, Inc. itsdomain2 test domain
+
+EOMODS
+
+RC=$?   
+if test $RC != 0 ; then
+        echo "ldapmodify failed ($RC)!"
+        test $KILLSERVERS != no && kill -HUP $KILLPIDS
+        exit $RC
+fi      
+
+echo "Waiting $SLEEP2 seconds for syncrepl to receive changes..."
+sleep $SLEEP2 
 
 echo "Using ldapsearch to read all the entries from the master..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
-	'objectclass=*' > $MASTEROUT 2>&1
+	'(objectClass=*)' '*' entryCSN > $MASTEROUT 2>&1
 RC=$?
 
 if test $RC != 0 ; then
@@ -342,7 +372,7 @@ fi
 
 echo "Using ldapsearch to read all the entries from the R1 slave..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
-	'objectclass=*' > $SERVER2OUT 2>&1
+	'(objectClass=*)' '*' entryCSN > $SERVER2OUT 2>&1
 RC=$?
 
 if test $RC != 0 ; then
@@ -353,7 +383,7 @@ fi
 
 echo "Using ldapsearch to read all the entries from the R2 slave..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT3 \
-	'objectclass=*' > $SERVER3OUT 2>&1
+	'(objectClass=*)' '*' entryCSN > $SERVER3OUT 2>&1
 RC=$?
 
 if test $RC != 0 ; then
@@ -364,7 +394,7 @@ fi
 
 echo "Using ldapsearch to read all the entries from the P1 slave..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT4 \
-	'objectclass=*' > $SERVER4OUT 2>&1
+	'(objectClass=*)' '*' entryCSN > $SERVER4OUT 2>&1
 RC=$?
 
 if test $RC != 0 ; then
@@ -375,7 +405,7 @@ fi
 
 echo "Using ldapsearch to read all the entries from the P2 slave..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT5 \
-	'objectclass=*' > $SERVER5OUT 2>&1
+	'(objectClass=*)' '*' entryCSN > $SERVER5OUT 2>&1
 RC=$?
 
 if test $RC != 0 ; then
@@ -386,7 +416,7 @@ fi
 
 echo "Using ldapsearch to read all the entries from the P3 slave..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT6 \
-	'objectclass=*' > $SERVER6OUT 2>&1
+	'(objectClass=*)' '*' entryCSN > $SERVER6OUT 2>&1
 RC=$?
 
 if test $RC != 0 ; then
@@ -398,17 +428,17 @@ fi
 test $KILLSERVERS != no && kill -HUP $KILLPIDS
 
 echo "Filtering master ldapsearch results..."
-. $LDIFFILTER < $MASTEROUT > $MASTERFLT
+$LDIFFILTER < $MASTEROUT > $MASTERFLT
 echo "Filtering R1 slave ldapsearch results..."
-. $LDIFFILTER < $SERVER2OUT > $SERVER2FLT
+$LDIFFILTER < $SERVER2OUT > $SERVER2FLT
 echo "Filtering R2 slave ldapsearch results..."
-. $LDIFFILTER < $SERVER3OUT > $SERVER3FLT
+$LDIFFILTER < $SERVER3OUT > $SERVER3FLT
 echo "Filtering P1 slave ldapsearch results..."
-. $LDIFFILTER < $SERVER4OUT > $SERVER4FLT
+$LDIFFILTER < $SERVER4OUT > $SERVER4FLT
 echo "Filtering P2 slave ldapsearch results..."
-. $LDIFFILTER < $SERVER5OUT > $SERVER5FLT
+$LDIFFILTER < $SERVER5OUT > $SERVER5FLT
 echo "Filtering P3 slave ldapsearch results..."
-. $LDIFFILTER < $SERVER6OUT > $SERVER6FLT
+$LDIFFILTER < $SERVER6OUT > $SERVER6FLT
 
 echo "Comparing retrieved entries from master and R1 slave..."
 $CMP $MASTERFLT $SERVER2FLT > $CMPOUT
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test024-unique b/OpenLDAP/OpenLDAP/tests/scripts/test024-unique
--- a/OpenLDAP/OpenLDAP/tests/scripts/test024-unique
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test024-unique
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test024-unique,v 1.8.2.5 2008/02/11 23:26:51 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test024-unique,v 1.8.2.9 2010/04/19 19:14:34 quanah Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 2004-2008 The OpenLDAP Foundation.
+## Copyright 2004-2010 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -20,6 +20,9 @@ if test $UNIQUE = uniqueno; then
 	echo "Attribute Uniqueness overlay not available, test skipped"
 	exit 0
 fi
+
+RCODEconstraint=19
+test $BACKEND = null && RCODEconstraint=0
 
 mkdir -p $TESTDIR $DBDIR1
 
@@ -107,7 +110,7 @@ employeeType: contractor
 givenName: Bill
 EOTUNIQ2
 RC=$?
-if test $RC != 19 ; then
+if test $RC != $RCODEconstraint ; then
 	echo "unique check failed ($RC)!"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit -1
@@ -223,7 +226,7 @@ employeeType: contractor
 givenName: Bill
 EOTUNIQ2
 RC=$?
-if test $RC != 19 ; then
+if test $RC != $RCODEconstraint ; then
 	echo "unique check failed ($RC)!"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit -1
@@ -280,7 +283,7 @@ employeeType: contractor
 givenName: Bill
 EOTUNIQ2
 RC=$?
-if test $RC != 19 ; then
+if test $RC != $RCODEconstraint ; then
 	echo "olcUniqueAttribtue single deletion hit the wrong value"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit -1
@@ -340,7 +343,7 @@ employeeType: contractor
 givenName: Bill
 EOTUNIQ2
 RC=$?
-if test $RC != 19 ; then
+if test $RC != $RCODEconstraint ; then
 	echo "unique check failed ($RC)!"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit -1
@@ -425,6 +428,7 @@ dn: olcOverlay={0}unique,olcDatabase={1}$BACKEND,cn=config
 changetype: modify
 add: olcUniqueURI
 olcUniqueURI: ldap:///?sn?sub?(cn=e*)
+olcUniqueURI: ldap:///?uid?sub?(cn=edgar)
 -
 delete: olcUniqueURI
 olcUniqueURI: ldap:///?description?one
@@ -445,6 +449,7 @@ objectClass: olcUniqueConfig
 olcOverlay: {0}unique
 olcUniqueURI: ldap:///?employeeNumber,displayName?sub
 olcUniqueURI: ldap:///?sn?sub?(cn=e*)
+olcUniqueURI: ldap:///?uid?sub?(cn=edgar)
 
 EOF
 diff $TESTDIR/third-config.ldif $TESTDIR/third-reference.ldif > /dev/null 2>&1
@@ -473,6 +478,24 @@ if test $RC != 0 ; then
 	exit -1
 fi
 
+echo "Adding a record unique in all domains because of filter conditions "
+$LDAPADD -D "$UNIQUEDN" -h $LOCALHOST -p $PORT1 -w $PASSWD > \
+	 $TESTOUT 2>&1 << EOF
+dn: uid=empty,ou=users,o=unique
+objectClass: inetOrgPerson
+uid: edgar
+cn: empty
+sn: empty
+EOF
+
+RC=$?
+if test $RC != 0 ; then
+	echo "spurious unique error ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit -1
+fi
+
+
 echo "Adding a record unique in one domain, non-unique in the filtered domain..."
 
 $LDAPADD -D "$UNIQUEDN" -h $LOCALHOST -p $PORT1 -w $PASSWD > \
@@ -485,7 +508,7 @@ cn: elvis
 EOF
 
 RC=$?
-if test $RC != 19 ; then
+if test $RC != $RCODEconstraint ; then
 	echo "unique check failed ($RC)!"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit -1
@@ -557,7 +580,7 @@ description: left the building
 EOF
 
 RC=$?
-if test $RC != 19 ; then
+if test $RC != $RCODEconstraint ; then
 	echo "unique check failed ($RC)!"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit -1
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test046-dds b/OpenLDAP/OpenLDAP/tests/scripts/test046-dds
--- a/OpenLDAP/OpenLDAP/tests/scripts/test046-dds
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test046-dds
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test046-dds,v 1.4.2.3 2008/02/11 23:26:51 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test046-dds,v 1.4.2.8 2010/04/19 19:14:36 quanah Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 2005-2008 The OpenLDAP Foundation.
+## Copyright 2005-2010 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -15,6 +15,12 @@
 
 echo "running defines.sh"
 . $SRCDIR/scripts/defines.sh
+
+case $BACKEND in ldif | null)
+	# LDIF lacks ACL support, NULL cannot hold dynamic entries
+        echo "Test does not support $BACKEND backend, test skipped"
+        exit 0
+esac
 
 if test $DDS = ddsno; then 
 	echo "Dynamic Directory Services overlay not available, test skipped"
@@ -391,7 +397,7 @@ member: $BJORNSDN
 dn: $MEETINGDN
 changetype: modify
 add: member
-member: $JAJDN
+member: $JOHNDDN
 EOMODS
 RC=$?
 if test $RC != 0 ; then
@@ -439,7 +445,7 @@ case $RC in
 0)
 	echo "ldapmodify should have failed ($RC)!"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit $RC
+	exit -1
 	;;
 50)
 	echo "ldapmodify failed ($RC)"
@@ -470,7 +476,18 @@ RC=$?
 if test $RC = 0 ; then
 	echo "ldapexop should have failed ($RC)!"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit $RC
+	exit -1
+fi
+
+echo "Trying to refresh the meeting as $JAJDN (should fail)..."
+$LDAPEXOP -D "$JAJDN" -w "jaj" -h $LOCALHOST -p $PORT1 \
+	"refresh" "$MEETINGDN" "240" \
+	>> $TESTOUT 2>&1
+RC=$?
+if test $RC = 0 ; then
+	echo "ldapexop should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit -1
 fi
 
 echo "Trying to delete the meeting as $BABSDN (should fail)..."
@@ -484,7 +501,7 @@ case $RC in
 0)
 	echo "ldapdelete should have failed ($RC)!"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit $RC
+	exit -1
 	;;
 50)
 	echo "ldapdelete failed ($RC)"
@@ -514,9 +531,9 @@ test $KILLSERVERS != no && kill -HUP $KILLPIDS
 LDIF=$DDSOUT
 
 echo "Filtering ldapsearch results..."
-. $LDIFFILTER < $SEARCHOUT > $SEARCHFLT
+$LDIFFILTER < $SEARCHOUT > $SEARCHFLT
 echo "Filtering original ldif used to create database..."
-. $LDIFFILTER < $LDIF > $LDIFFLT
+$LDIFFILTER < $LDIF > $LDIFFLT
 echo "Comparing filter output..."
 $CMP $SEARCHFLT $LDIFFLT > $CMPOUT
 
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test052-memberof b/OpenLDAP/OpenLDAP/tests/scripts/test052-memberof
--- a/OpenLDAP/OpenLDAP/tests/scripts/test052-memberof
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test052-memberof
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test052-memberof,v 1.4.2.2 2008/02/11 23:26:51 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test052-memberof,v 1.4.2.6 2010/04/19 19:14:36 quanah Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2008 The OpenLDAP Foundation.
+## Copyright 1998-2010 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -72,26 +72,51 @@ EOF
 	fi
 fi
 
+bdbInclude="# " nullExclude=""
+case $BACKEND in
+bdb | hdb) bdbInclude="" ;;
+null) nullExclude="# " ;;
+esac
+
 echo "Running ldapadd to build slapd config database..."
 $LDAPADD -h $LOCALHOST -p $PORT1 -D 'cn=config' -w `cat $CONFIGPWF` \
 	>> $TESTOUT 2>&1 <<EOF
+dn: cn=symas group example,cn=schema,cn=config
+objectClass: olcSchemaConfig
+cn: symas group example
+olcAttributeTypes: ( 1.3.6.1.4.1.4754.31.1.1 
+ NAME 'memberA' SUP distinguishedName )
+olcAttributeTypes: ( 1.3.6.1.4.1.4754.31.1.2
+ NAME 'memberOfA' SUP distinguishedName )
+olcAttributeTypes: ( 1.3.6.1.4.1.4754.31.1.3 
+ NAME 'memberB' SUP distinguishedName )
+olcAttributeTypes: ( 1.3.6.1.4.1.4754.31.1.4 
+ NAME 'memberOfB' SUP distinguishedName )
+olcObjectClasses: ( 1.3.6.1.4.1.4754.31.2.1 
+ NAME 'groupA' SUP top STRUCTURAL MUST cn MAY memberA )
+olcObjectClasses: ( 1.3.6.1.4.1.4754.31.2.2 
+ NAME 'groupMemberA' SUP top AUXILIARY MAY memberOfA )
+olcObjectClasses: ( 1.3.6.1.4.1.4754.31.2.3 
+ NAME 'groupB' SUP top STRUCTURAL MUST cn MAY memberB )
+olcObjectClasses: ( 1.3.6.1.4.1.4754.31.2.4 
+ NAME 'groupMemberB' SUP top AUXILIARY MAY memberOfB )
+
 dn: olcDatabase={1}$BACKEND,cn=config
 objectClass: olcDatabaseConfig
-objectClass: olc${BACKEND}Config
+${nullExclude}objectClass: olc${BACKEND}Config
 olcDatabase: {1}$BACKEND
 olcSuffix: $BASEDN
 olcRootDN: cn=Manager,$BASEDN
 olcRootPW:: c2VjcmV0
 olcMonitoring: TRUE
-olcDbDirectory: $TESTDIR/db.1.a/
-olcDbCacheSize: 1000
-olcDbIndex: objectClass eq
-olcDbIndex: cn pres,eq,sub
-olcDbIndex: uid pres,eq,sub
-olcDbIndex: sn pres,eq,sub
-olcDbMode: 384
+${nullExclude}olcDbDirectory: $TESTDIR/db.1.a/
+${bdbInclude}olcDbCacheSize: 1000
+${bdbInclude}olcDbIndex: objectClass eq
+${bdbInclude}olcDbIndex: cn pres,eq,sub
+${bdbInclude}olcDbIndex: uid pres,eq,sub
+${bdbInclude}olcDbIndex: sn pres,eq,sub
+${bdbInclude}olcDbMode: 384"
 
-# {0}memberof, {1}$BACKEND, config
 dn: olcOverlay={0}memberof,olcDatabase={1}$BACKEND,cn=config
 objectClass: olcOverlayConfig
 objectClass: olcMemberOf
@@ -100,6 +125,25 @@ olcMemberOfRefInt: TRUE
 olcMemberOfGroupOC: groupOfNames
 olcMemberOfMemberAD: member
 olcMemberOfMemberOfAD: memberOf
+
+dn: olcOverlay={1}memberof,olcDatabase={1}$BACKEND,cn=config
+objectClass: olcOverlayConfig
+objectClass: olcMemberOf
+olcOverlay: {1}memberof
+olcMemberOfRefInt: TRUE
+olcMemberOfGroupOC: groupA
+olcMemberOfMemberAD: memberA
+olcMemberOfMemberOfAD: memberOfA
+
+dn: olcOverlay={2}memberof,olcDatabase={1}$BACKEND,cn=config
+objectClass: olcOverlayConfig
+objectClass: olcMemberOf
+olcOverlay: {2}memberof
+olcMemberOfRefInt: TRUE
+olcMemberOfGroupOC: groupB
+olcMemberOfMemberAD: memberB
+olcMemberOfMemberOfAD: memberOfB
+
 EOF
 RC=$?
 if test $RC != 0 ; then
@@ -227,14 +271,74 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
+echo "Adding groups with MAY member type schemas..."
+$LDAPMODIFY -h $LOCALHOST -p $PORT1 \
+	-D "cn=Manager,$BASEDN" -w secret \
+	>> $TESTOUT 2>&1 <<EOF
+dn: cn=Roger Rabbit,ou=People,$BASEDN
+changetype: delete
+
+dn: cn=Jessica Rabbit,ou=People,$BASEDN
+changetype: delete
+
+dn: cn=Cartoonia,ou=Groups,$BASEDN
+changetype: delete
+
+dn: cn=person1,ou=People,$BASEDN
+changetype: add
+objectClass: person
+objectClass: groupMemberA
+objectClass: groupMemberB
+cn: person1
+sn: person1
+
+dn: cn=person2,ou=People,$BASEDN
+changetype: add
+objectClass: person
+objectClass: groupMemberA
+objectClass: groupMemberB
+cn: person2
+sn: person2
+
+dn: cn=group1,ou=Groups,$BASEDN
+changetype: add
+objectclass: groupA
+cn: group1
+memberA: cn=person1,ou=People,$BASEDN
+memberA: cn=person2,ou=People,$BASEDN
+
+dn: cn=group2,ou=Groups,$BASEDN
+changetype: add
+objectclass: groupB
+cn: group2
+memberB: cn=person1,ou=People,$BASEDN
+memberB: cn=person2,ou=People,$BASEDN
+
+dn: cn=group1,ou=Groups,$BASEDN
+changetype: modify
+delete: memberA
+
+EOF
+
+echo "Re-search the entire database..."
+echo "# Re-search the entire database..." >> $SEARCHOUT
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
+	'(objectClass=*)' '*' memberOf >> $SEARCHOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
 test $KILLSERVERS != no && kill -HUP $KILLPIDS
 
 LDIF=$MEMBEROFOUT
 
 echo "Filtering ldapsearch results..."
-. $LDIFFILTER < $SEARCHOUT > $SEARCHFLT
+$LDIFFILTER < $SEARCHOUT > $SEARCHFLT
 echo "Filtering original ldif used to create database..."
-. $LDIFFILTER < $LDIF > $LDIFFLT
+$LDIFFILTER < $LDIF > $LDIFFLT
 echo "Comparing filter output..."
 $CMP $SEARCHFLT $LDIFFLT > $CMPOUT
 
diff --git a/OpenSSH/openssh/regress/Makefile b/OpenSSH/openssh/regress/Makefile
--- a/OpenSSH/openssh/regress/Makefile
+++ b/OpenSSH/openssh/regress/Makefile
@@ -1,7 +1,9 @@
-#	$OpenBSD: Makefile,v 1.48 2008/06/28 13:57:25 djm Exp $
+#	$OpenBSD: Makefile,v 1.54 2010/06/27 19:19:56 phessler Exp $
 
 REGRESS_TARGETS=	t1 t2 t3 t4 t5 t6 t7 t-exec
 tests:		$(REGRESS_TARGETS)
+CURDIR=.
+SUDO=/usr/bin/sudo
 
 # Interop tests are not run by default
 interop interop-tests: t-exec-interop
@@ -31,9 +33,9 @@ LTESTS= 	connect \
 		agent \
 		agent-getpeereid \
 		agent-timeout \
-		agent-ptrace \
 		keyscan \
 		keygen-change \
+		keygen-convert \
 		key-options \
 		scp \
 		sftp \
@@ -50,7 +52,12 @@ LTESTS= 	connect \
 		cfgmatch \
 		addrmatch \
 		localcommand \
-		forcecommand
+		forcecommand \
+		utmpx-osx \
+		gssapi \
+		portnum \
+		cert-hostkey \
+		cert-userkey
 
 INTEROP_TESTS=	putty-transfer putty-ciphers putty-kex conch-ciphers
 #INTEROP_TESTS+=ssh-com ssh-com-client ssh-com-keygen ssh-com-sftp
@@ -64,32 +71,37 @@ CLEANFILES=	t2.out t6.out1 t6.out2 t7.out t7.out.pub copy.1 copy.2 \
 		ls.copy banner.in banner.out empty.in \
 		scp-ssh-wrapper.scp ssh_proxy_envpass remote_pid \
 		sshd_proxy_bak rsa_ssh2_cr.prv rsa_ssh2_crnl.prv \
-		putty.rsa2
+		known_hosts-cert host_ca_key* cert_host_key* \
+		putty.rsa2 sshd_proxy_orig \
+		authorized_principals_${USER}
+
+# Enable all malloc(3) randomisations and checks
+TEST_ENV=      "MALLOC_OPTIONS=AFGJPRX"
 
 t1:
-	ssh-keygen -if ${.CURDIR}/rsa_ssh2.prv | diff - ${.CURDIR}/rsa_openssh.prv
+	ssh-keygen -if $(CURDIR)/rsa_ssh2.prv | diff - $(CURDIR)/rsa_openssh.prv
 
 t2:
-	cat ${.CURDIR}/rsa_openssh.prv > $(OBJ)/t2.out
+	cat $(CURDIR)/rsa_openssh.prv > $(OBJ)/t2.out
 	chmod 600 $(OBJ)/t2.out
-	ssh-keygen -yf $(OBJ)/t2.out | diff - ${.CURDIR}/rsa_openssh.pub
+	ssh-keygen -yf $(OBJ)/t2.out | diff - $(CURDIR)/rsa_openssh.pub
 
 t3:
-	ssh-keygen -ef ${.CURDIR}/rsa_openssh.pub >$(OBJ)/rsa_secsh.pub
-	ssh-keygen -if $(OBJ)/rsa_secsh.pub | diff - ${.CURDIR}/rsa_openssh.pub
-	rm -f ${.CURDIR}/rsa_secsh.pub
+	ssh-keygen -ef $(CURDIR)/rsa_openssh.pub >$(OBJ)/rsa_secsh.pub
+	ssh-keygen -if $(OBJ)/rsa_secsh.pub | diff - $(CURDIR)/rsa_openssh.pub
+	rm -f $(CURDIR)/rsa_secsh.pub
 
 t4:
-	ssh-keygen -lf ${.CURDIR}/rsa_openssh.pub |\
-		awk '{print $$2}' | diff - ${.CURDIR}/t4.ok
+	ssh-keygen -lf $(CURDIR)/rsa_openssh.pub |\
+		awk '{print $$2}' | diff - $(CURDIR)/t4.ok
 
 t5:
-	ssh-keygen -Bf ${.CURDIR}/rsa_openssh.pub |\
-		awk '{print $$2}' | diff - ${.CURDIR}/t5.ok
+	ssh-keygen -Bf $(CURDIR)/rsa_openssh.pub |\
+		awk '{print $$2}' | diff - $(CURDIR)/t5.ok
 
 t6:
-	ssh-keygen -if ${.CURDIR}/dsa_ssh2.prv > $(OBJ)/t6.out1
-	ssh-keygen -if ${.CURDIR}/dsa_ssh2.pub > $(OBJ)/t6.out2
+	ssh-keygen -if $(CURDIR)/dsa_ssh2.prv > $(OBJ)/t6.out1
+	ssh-keygen -if $(CURDIR)/dsa_ssh2.pub > $(OBJ)/t6.out2
 	chmod 600 $(OBJ)/t6.out1
 	ssh-keygen -yf $(OBJ)/t6.out1 | diff - $(OBJ)/t6.out2
 
@@ -103,14 +115,27 @@ t7: $(OBJ)/t7.out
 t-exec:	${LTESTS:=.sh}
 	@if [ "x$?" = "x" ]; then exit 0; fi; \
 	for TEST in ""$?; do \
-		echo "run test $${TEST}" ... 1>&2; \
-		(env SUDO=${SUDO} sh ${.CURDIR}/test-exec.sh ${.OBJDIR} ${.CURDIR}/$${TEST}) || exit $$?; \
+		echo "[BEGIN] $${TEST}"; \
+		(env SUDO="${SUDO}" TEST_ENV=${TEST_ENV} sh $(CURDIR)/test-exec.sh $(OBJ) $(CURDIR)/$${TEST}); \
+		ret=$$?; \
+		if [[ 0 -eq $${ret} ]]; then \
+			echo "[PASS] $${TEST}"; \
+		else\
+			echo "[FAIL] $${TEST}"; \
+			exit $${ret};\
+		fi;\
 	done
 
 t-exec-interop:	${INTEROP_TESTS:=.sh}
 	@if [ "x$?" = "x" ]; then exit 0; fi; \
 	for TEST in ""$?; do \
-		echo "run test $${TEST}" ... 1>&2; \
-		(env SUDO=${SUDO} sh ${.CURDIR}/test-exec.sh ${.OBJDIR} ${.CURDIR}/$${TEST}) || exit $$?; \
+		echo "[BEGIN] $${TEST}"; \
+		(env SUDO="${SUDO}" TEST_ENV=${TEST_ENV} sh $(CURDIR)/test-exec.sh $(OBJDIR) $(CURDIR)/$${TEST}); \
+		ret=$$?; \
+		if [[ 0 -eq $${ret} ]]; then \
+			echo "[PASS] $${TEST}"; \
+		else\
+			echo "[FAIL] $${TEST}"; \
+		fi;\
 	done
 
diff --git a/swig/swig/Makefile.in b/swig/swig/Makefile.in
--- a/swig/swig/Makefile.in
+++ b/swig/swig/Makefile.in
@@ -1,6 +1,8 @@
 #######################################################################
-# $Header: /cvsroot/swig/SWIG/Makefile.in,v 1.109 2006/10/24 20:15:26 wsfulton Exp $
+# $Id: Makefile.in 11602 2009-08-17 01:10:04Z wsfulton $
 #######################################################################
+
+.PHONY: ccache source swig
 
 prefix      = @prefix@
 exec_prefix = @exec_prefix@
@@ -14,19 +16,39 @@ datarootdir = @datarootdir@
 SHELL       = /bin/sh
 SWIG_LIB    = @swig_lib@
 BIN_DIR     = @bindir@
+ENABLE_CCACHE = @ENABLE_CCACHE@
 TARGET_NOEXE= swig
 TARGET      = $(TARGET_NOEXE)@EXEEXT@
 SOURCE      = Source
+CCACHE      = CCache
 DOCS        = Doc/Manual
 
-swig: libfiles source
+swig: libfiles source ccache
 
 source:
 	@cd $(SOURCE) && $(MAKE)
 
+ccache:
+	test -z "$(ENABLE_CCACHE)" || (cd $(CCACHE) && $(MAKE))
+
 libfiles: Lib/swigwarn.swg
 
-.PHONY: source libfiles
+# Files required just for the tarball
+maintainer: libfiles
+	@cd $(SOURCE) && $(MAKE) CParse/parser.h
+
+#####################################################################
+# Documentation
+#####################################################################
+
+docs: docs-main docs-ccache
+
+docs-main:
+	@echo making docs
+	@test -d $(DOCS) || exit 0; cd $(DOCS) && $(MAKE) all clean-baks
+
+docs-ccache:
+	test -z "$(ENABLE_CCACHE)" || (cd $(CCACHE) && $(MAKE) docs)
 
 #####################################################################
 # All the languages SWIG speaks (when it wants to)
@@ -40,8 +62,9 @@ skip-guilescm   = test -n "@SKIP_GUILESCM@"
 skip-guile	= test -n "@SKIP_GUILE@"
 skip-mzscheme	= test -n "@SKIP_MZSCHEME@"
 skip-ruby	= test -n "@SKIP_RUBY@"
-skip-php4	= test -n "@SKIP_PHP4@"
+skip-php	= test -n "@SKIP_PHP@"
 skip-ocaml      = test -n "@SKIP_OCAML@"
+skip-octave     = test -n "@SKIP_OCTAVE@"
 skip-pike       = test -n "@SKIP_PIKE@"
 skip-chicken	= test -n "@SKIP_CHICKEN@"
 skip-csharp	= test -n "@SKIP_CSHARP@"
@@ -61,12 +84,11 @@ skip-gcj        = test -n "@SKIP_GCJ@"
 #####################################################################
 
 ACTION = check
+NOSKIP =
 
 chk-set-swiglib		= SWIG_LIB=@ROOT_DIR@/Lib
 chk-set-swig		= SWIG=@ROOT_DIR@/$(TARGET)
 chk-set-env = $(chk-set-swiglib) $(chk-set-swig)
-
-chk = $(MAKE) -k -s $(chk-set-env) $(ACTION)
 
 check-aliveness:
 	test -x ./$(TARGET)
@@ -80,13 +102,17 @@ check-aliveness:
 	@$(skip-mzscheme) || ./$(TARGET) -mzscheme -help
 	@$(skip-ruby)     || ./$(TARGET) -ruby     -help
 	@$(skip-ocaml)    || ./$(TARGET) -ocaml    -help
-	@$(skip-php4)     || ./$(TARGET) -php4     -help
+	@$(skip-octave)   || ./$(TARGET) -octave   -help
+	@$(skip-php)      || ./$(TARGET) -php      -help
 	@$(skip-pike)     || ./$(TARGET) -pike     -help
 	@$(skip-chicken)  || ./$(TARGET) -chicken  -help
 	@$(skip-csharp)   || ./$(TARGET) -csharp   -help
 	@$(skip-modula3)  || ./$(TARGET) -modula3  -help
 	@$(skip-lua)      || ./$(TARGET) -lua      -help
 	@$(skip-r) 	  || ./$(TARGET) -r        -help
+
+check-ccache:
+	test -z "$(ENABLE_CCACHE)" || (cd $(CCACHE) && $(MAKE) check)
 
 # Checks examples for compilation (does not run them)
 check-examples:					\
@@ -98,7 +124,8 @@ check-examples:					\
 	check-mzscheme-examples			\
 	check-ruby-examples			\
 	check-ocaml-examples			\
-	check-php4-examples			\
+	check-octave-examples			\
+	check-php-examples			\
 	check-pike-examples			\
 	check-chicken-examples                  \
 	check-csharp-examples                   \
@@ -110,26 +137,52 @@ check-examples:					\
 	check-cffi-examples			\
 	check-r-examples
 
-check-%-examples:
-	@passed=true;						\
-	dir="Examples/$*";					\
-	if $(skip-$*); then					\
+tcl_examples       :=$(shell sed '/^\#/d' $(srcdir)/Examples/tcl/check.list)
+perl5_examples     :=$(shell sed '/^\#/d' $(srcdir)/Examples/perl5/check.list)
+python_examples    :=$(shell sed '/^\#/d' $(srcdir)/Examples/python/check.list)
+java_examples      :=$(shell sed '/^\#/d' $(srcdir)/Examples/java/check.list)
+guile_examples     :=$(shell sed '/^\#/d' $(srcdir)/Examples/guile/check.list)
+mzscheme_examples  :=$(shell sed '/^\#/d' $(srcdir)/Examples/mzscheme/check.list)
+ruby_examples      :=$(shell sed '/^\#/d' $(srcdir)/Examples/ruby/check.list)
+ocaml_examples     :=$(shell sed '/^\#/d' $(srcdir)/Examples/ocaml/check.list)
+octave_examples    :=$(shell sed '/^\#/d' $(srcdir)/Examples/octave/check.list)
+php_examples       :=$(shell sed '/^\#/d' $(srcdir)/Examples/php/check.list)
+pike_examples      :=$(shell sed '/^\#/d' $(srcdir)/Examples/pike/check.list)
+chicken_examples   :=$(shell sed '/^\#/d' $(srcdir)/Examples/chicken/check.list)
+csharp_examples    :=$(shell sed '/^\#/d' $(srcdir)/Examples/csharp/check.list)
+modula3_examples   :=$(shell sed '/^\#/d' $(srcdir)/Examples/modula3/check.list)
+lua_examples       :=$(shell sed '/^\#/d' $(srcdir)/Examples/lua/check.list)
+allegrocl_examples :=
+clisp_examples     :=
+uffi_examples      :=
+cffi_examples      :=
+r_examples         :=$(shell sed '/^\#/d' $(srcdir)/Examples/r/check.list)
+
+# all examples
+check-%-examples :
+	@if test -z "$(skip-$*)"; then				\
+	  echo $* unknown;					\
+	  exit 1;						\
+	fi
+	@if $(skip-$*); then					\
 	  echo skipping $* $(ACTION);				\
-	elif [ ! -f $$dir/check.list ]; then			\
-	  echo skipping $* $(ACTION) "(no $$dir/check.list)";	\
 	else							\
-	  all=`sed '/^#/d' $$dir/check.list`;			\
-	  for a in $$all; do					\
-            if $(skip-gcj) && test $$a = "java"; then		\
-              echo "skipping $* $$dir/$$a $(ACTION) (gcj test)";\
-            else						\
-	    echo $(ACTION)ing $$dir/$$a;			\
-	    (cd $$dir/$$a && $(chk))				\
-	    || passed=false;					\
-	    fi;							\
-	  done;							\
-	fi;							\
-	test $$passed = true
+	  $(MAKE) -k -s $($*_examples:=.actionexample) LANGUAGE=$* ACTION=$(ACTION); \
+	fi
+
+# individual example
+%.actionexample:
+	@echo $(ACTION)ing Examples/$(LANGUAGE)/$*
+	@(cd Examples/$(LANGUAGE)/$* && $(MAKE) -s $(chk-set-env) $(ACTION))
+
+# gcj individual example
+java.actionexample:
+	@if $(skip-gcj); then					\
+          echo "skipping Examples/$(LANGUAGE)/java $(ACTION) (gcj test)";	\
+        else							\
+	  echo $(ACTION)ing Examples/$(LANGUAGE)/java;		\
+	  (cd Examples/$(LANGUAGE)/java && $(MAKE) -s $(chk-set-env) $(ACTION)) \
+	fi
 
 gifplot-library:
 	@echo $(ACTION)ing Examples/GIFPlot/Lib
@@ -144,7 +197,8 @@ check-gifplot:					\
 	check-mzscheme-gifplot			\
 	check-ruby-gifplot			\
 	check-ocaml-gifplot			\
-	check-php4-gifplot			\
+	check-octave-gifplot			\
+	check-php-gifplot			\
 	check-pike-gifplot			\
 	check-chicken-gifplot                   \
 #	check-lua-gifplot                  	\
@@ -152,6 +206,10 @@ check-gifplot:					\
 #	check-modula3-gifplot
 
 check-%-gifplot: gifplot-library
+	@if test -z "$(skip-$*)"; then				\
+	  echo $* unknown;					\
+	  exit 1;						\
+	fi
 	@passed=true;						\
 	up=`$(srcdir)/Tools/capitalize $*`;			\
 	dir="Examples/GIFPlot/$$up";				\
@@ -163,7 +221,8 @@ check-%-gifplot: gifplot-library
 	  all=`sed '/^#/d' $$dir/check.list`;			\
 	  for a in $$all; do					\
 	    echo $(ACTION)ing $$dir/$$a;			\
-	    (cd $$dir/$$a && $(chk))				\
+	    (cd $$dir/$$a &&					\
+	    $(MAKE) -k -s $(chk-set-env) $(ACTION))		\
 	    || passed=false;					\
 	  done;							\
 	fi;							\
@@ -180,7 +239,8 @@ check-test-suite:				\
 	check-mzscheme-test-suite		\
 	check-ruby-test-suite			\
 	check-ocaml-test-suite			\
-	check-php4-test-suite			\
+	check-octave-test-suite			\
+	check-php-test-suite			\
 	check-pike-test-suite			\
 	check-csharp-test-suite			\
 	check-modula3-test-suite		\
@@ -193,9 +253,13 @@ check-test-suite:				\
 	check-r-test-suite
 
 check-%-test-suite:
+	@if test -z "$(skip-$*)"; then					\
+	  echo $* unknown;						\
+	  exit 1;							\
+	fi
 	@passed=true;							\
 	dir="Examples/test-suite/$*";					\
-	if $(skip-$*); then						\
+	if $(skip-$*) -a "$(NOSKIP)" != "1"; then			\
 	  echo skipping $* test-suite $(ACTION);			\
 	elif [ ! -d $$dir ]; then					\
 	  echo warning: cannot $(ACTION) $* test-suite "(no dir $$dir)";\
@@ -206,7 +270,14 @@ check-%-test-suite:
 	fi;								\
 	test $$passed = true
 
-check: check-aliveness check-examples check-gifplot check-test-suite
+# Partial test-suite check - it only invokes SWIG, ie no compilation and no runtime testing
+partialcheck-test-suite:
+	@$(MAKE) -k -s check-test-suite ACTION=partialcheck NOSKIP=1
+
+partialcheck-%-test-suite:
+	@$(MAKE) -k -s check-$*-test-suite ACTION=partialcheck NOSKIP=1
+
+check: check-aliveness check-ccache check-examples check-gifplot check-test-suite
 
 # Run known-to-be-broken as well as not broken testcases in the test-suite
 all-test-suite:					\
@@ -219,7 +290,8 @@ all-test-suite:					\
 	all-mzscheme-test-suite			\
 	all-ruby-test-suite			\
 	all-ocaml-test-suite			\
-	all-php4-test-suite			\
+	all-octave-test-suite			\
+	all-php-test-suite			\
 	all-pike-test-suite			\
 	all-csharp-test-suite			\
 	all-modula3-test-suite			\
@@ -245,7 +317,8 @@ broken-test-suite:				\
 	broken-mzscheme-test-suite		\
 	broken-ruby-test-suite			\
 	broken-ocaml-test-suite			\
-	broken-php4-test-suite			\
+	broken-octave-test-suite		\
+	broken-php-test-suite			\
 	broken-pike-test-suite			\
 	broken-csharp-test-suite		\
 	broken-modula3-test-suite		\
@@ -266,7 +339,7 @@ broken-%-test-suite:
 
 clean: clean-objects clean-libfiles clean-examples clean-gifplot clean-test-suite clean-docs
 
-clean-objects: clean-source
+clean-objects: clean-source clean-ccache
 
 clean-source:
 	@echo cleaning Source
@@ -283,20 +356,31 @@ clean-gifplot:
 	@$(MAKE) -k -s check-gifplot ACTION=clean
 
 clean-test-suite:
-	@$(MAKE) -k -s check-test-suite ACTION=clean
+	@$(MAKE) -k -s check-test-suite ACTION=clean NOSKIP=1
 
 clean-%-examples:
 	@$(MAKE) -k -s check-$*-examples ACTION=clean
 
 clean-%-test-suite:
-	@$(MAKE) -k -s check-$*-test-suite ACTION=clean
+	@$(MAKE) -k -s check-$*-test-suite ACTION=clean NOSKIP=1
 
 clean-%-gifplot:
 	@$(MAKE) -k -s check-$*-gifplot ACTION=clean
 
-clean-docs:
+clean-ccache:
+	test -z "$(ENABLE_CCACHE)" || (cd $(CCACHE) && $(MAKE) -s clean)
+
+clean-docs: clean-docs-main clean-docs-ccache
+
+clean-docs-main:
 	@echo cleaning Docs
-	@test -d $(DOCS) || exit 0; cd $(DOCS) && $(MAKE) -s clean
+	@test -d $(DOCS) || exit 0; cd $(DOCS) && $(MAKE) clean
+
+clean-docs-ccache:
+	@# Use distclean-docs-ccache, else a user requires the yodl tools to generate the docs after a clean
+
+maintainer-clean: clean-libfiles
+	@cd $(SOURCE) && $(MAKE) maintainer-clean
 
 #####################################################################
 # DISTCLEAN
@@ -304,7 +388,7 @@ clean-docs:
 
 DISTCLEAN-DEAD = config.status config.log config.cache swig.spec Makefile mkmf.log libtool
 
-distclean: distclean-objects clean-examples clean-gifplot distclean-test-suite clean-docs distclean-dead
+distclean: distclean-objects clean-examples clean-gifplot distclean-test-suite clean-docs distclean-dead distclean-ccache
 
 distclean-objects: distclean-source
 
@@ -315,37 +399,13 @@ distclean-source:
 
 distclean-test-suite:
 	@echo distcleaning Examples/test-suite
-	@$(MAKE) -k -s noskip-test-suite ACTION=distclean
+	@$(MAKE) -k -s check-test-suite ACTION=distclean NOSKIP=1
 
-noskip-test-suite:				\
-	noskip-tcl-test-suite			\
-	noskip-perl5-test-suite			\
-	noskip-python-test-suite		\
-	noskip-java-test-suite			\
-	noskip-guilescm-test-suite		\
-	noskip-guile-test-suite			\
-	noskip-mzscheme-test-suite		\
-	noskip-ruby-test-suite			\
-	noskip-ocaml-test-suite			\
-	noskip-php4-test-suite			\
-	noskip-pike-test-suite			\
-	noskip-csharp-test-suite		\
-	noskip-lua-test-suite			\
-	noskip-allegrocl-test-suite		\
-	noskip-clisp-test-suite			\
-	noskip-uffi-test-suite			\
-	noskip-cffi-test-suite			\
-	noskip-chicken-test-suite		\
-	noskip-r-test-suite
+distclean-ccache:
+	test -z "$(ENABLE_CCACHE)" || (cd $(CCACHE) && $(MAKE) -s distclean)
 
-noskip-%-test-suite:
-	dir="Examples/test-suite/$*";					\
-	if [ ! -d $$dir ]; then						\
-	  echo warning: cannot $(ACTION) $* test-suite "(no dir $$dir)";\
-	else								\
-	  echo $(ACTION)ing $$dir;					\
-	  (cd $$dir && $(MAKE) -k -s $(ACTION))				\
-	fi;
+distclean-docs-ccache:
+	@test -z "$(ENABLE_CCACHE)" || (cd $(CCACHE) && $(MAKE) distclean-docs)
 
 distclean-dead:
 	rm -f $(DISTCLEAN-DEAD)
@@ -375,7 +435,7 @@ MKINSTDIRS      = @abs_srcdir@/Tools/config/install-sh -m 0755 -d
 # Use standard autoconf approach to transform executable name using --program-prefix and --program-suffix
 transform	= @program_transform_name@
 
-install: install-main install-lib
+install: install-main install-lib install-ccache
 	@echo "Installation complete"
 
 install-main:
@@ -384,7 +444,7 @@ install-main:
 	@echo "Installing $(DESTDIR)$(BIN_DIR)/`echo $(TARGET_NOEXE) | sed '$(transform)'`@EXEEXT@"
 	@$(INSTALL_PROGRAM) $(TARGET) $(DESTDIR)$(BIN_DIR)/`echo $(TARGET_NOEXE) | sed '$(transform)'`@EXEEXT@
 
-lib-languages = gcj typemaps tcl perl5 python guile java mzscheme ruby php4 ocaml \
+lib-languages = gcj typemaps tcl perl5 python guile java mzscheme ruby php ocaml octave \
 	pike chicken csharp modula3 allegrocl clisp lua cffi uffi r
 
 lib-modules = std
@@ -419,12 +479,15 @@ install-lib:
 	      fi) ; 						\
 	done
 
+install-ccache:
+	test -z "$(ENABLE_CCACHE)" || (cd $(CCACHE) && $(MAKE) install)
+
 
 #####################################################################
 # TARGETS: uninstall & friends
 #####################################################################
 
-uninstall: uninstall-main uninstall-lib
+uninstall: uninstall-main uninstall-lib uninstall-ccache
 	@echo "Uninstall complete"
 
 uninstall-main:
@@ -435,6 +498,9 @@ uninstall-lib:
 	@echo "Uninstalling the SWIG library"
 	rm -rf $(DESTDIR)$(SWIG_LIB)/
 
+uninstall-ccache:
+	test -z "$(ENABLE_CCACHE)" || (cd $(CCACHE) && $(MAKE) uninstall)
+
 ############################################################################
 # DIST and other maintenance
 ############################################################################
@@ -444,19 +510,12 @@ dd = @PACKAGE_NAME@-@PACKAGE_VERSION@
 srpm = @PACKAGE_NAME@-@PACKAGE_VERSION@
 
 dist:
-	@echo 'Dave, what do you want to do w/ "make dist"?'
-	@echo 'See Makefile.in target "dist-suggested" for an idea.'
-	@echo '    --thi'
+	@echo "not implemented"
 	false
-
-dist-suggested:
-	rm -rf $(dd) $(dd).tar.gz
-	cvs export -d $(dd) -r HEAD SWIG
-	tar cf - $(dd) | gzip --best > $(dd).tar.gz
-	rm -rf $(dd)
 
 srcrpm:
 	rm -fr $(srpm) $(srpm).src.rpm
+	echo "TODO: update to use svn instead of cvs"
 	cvs export -d $(srpm) -r HEAD SWIG
 	cp swig.spec $(srpm)
 	tar -cf - $(srpm) | gzip --best > $(srpm).tar.gz
@@ -472,10 +531,17 @@ configfiles:
 	wget ftp://ftp.gnu.org/pub/gnu/config/config.sub -O Tools/config/config.sub
 	chmod a+x Tools/config/config.sub
 
-# This target is usually called from Source/Makefile when configure.in has changed
-am--refresh:
-	@echo "Build system is out of date. Please reconfigure (rerun: ./autogen.sh && ./configure)"
-	@exit 1
+# Regenerate Makefile if Makefile.in or config.status have changed.
+Makefile: $(srcdir)/Makefile.in config.status
+	$(SHELL) ./config.status
+
+# This target is usually called from Source/Makefile when configure.in has
+# changed.
+am--refresh: $(srcdir)/configure
+
+$(srcdir)/configure: $(srcdir)/configure.in
+	@echo "Build system is out of date.  If the following commands fail, please reconfigure by hand (rerun: ./autogen.sh && ./configure)"
+	cd $(srcdir) && ./autogen.sh
+	$(SHELL) ./config.status --recheck
 
 # Makefile ends here
-
