10.15.3

diff --git a/sudo/sudo/Makefile.in b/sudo/sudo/Makefile.in
--- a/sudo/sudo/Makefile.in
+++ b/sudo/sudo/Makefile.in
@@ -1,5 +1,7 @@
 #
-# Copyright (c) 2010-2015 Todd C. Miller <Todd.Miller@courtesan.com>
+# SPDX-License-Identifier: ISC
+#
+# Copyright (c) 2010-2015, 2017-2018 Todd C. Miller <Todd.Miller@sudo.ws>
 #
 # Permission to use, copy, modify, and distribute this software for any
 # purpose with or without fee is hereby granted, provided that the above
@@ -12,7 +14,6 @@
 # WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 # ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 # OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
-# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
 
 srcdir = @srcdir@
@@ -89,6 +90,11 @@ CPPCHECK_OPTS = -q --force --enable=warning,performance,portability --suppress=c
 # Default splint options when run from the top-level Makefile
 SPLINT_OPTS = -D__restrict= -checks
 
+# Default PVS-studio options when run from the top-level Makefile
+PVS_CFG = $(top_builddir)/PVS-Studio.cfg
+PVS_IGNORE = 'V707,V011,V002,V536'
+PVS_LOG_OPTS = -a 'GA:1,2' -e -t errorfile -d $(PVS_IGNORE)
+
 all: config.status
 	for d in $(SUBDIRS); do \
 	    (cd $$d && exec $(MAKE) $@) && continue; \
@@ -116,6 +122,36 @@ splint: config.status
 	    (cd $$d && exec $(MAKE) SPLINT_OPTS="$(SPLINT_OPTS)" $@) || rval=`expr $$rval + $$?`; \
 	done; \
 	exit $$rval
+
+cov-build:
+	make clean
+	cov-build --dir cov-int make ${MFLAGS} all
+
+cov-upload:
+	tar zcf cov-int.tgz cov-int
+	curl --form token=$$COVERITY_SUDO_TOKEN \
+	    --form email=todd.miller@sudo.ws \
+	    --form file=@cov-int.tgz \
+	    --form version="$(VERSION)" \
+	    https://scan.coverity.com/builds?project=sudo
+
+cov-analyze: cov-upload
+
+pvs-studio: config.status
+	files=; \
+	rval=0; \
+	for d in $(SUBDIRS); do \
+	    (cd $$d && exec $(MAKE) PVS_IGNORE="$(PVS_IGNORE)" pvs-log-files) || rval=`expr $$rval + $$?`; \
+	    for f in $$d/*.plog; do \
+		if test "$$f" != "$$d/*.plog"; then \
+		    files="$$files $$f"; \
+		fi; \
+	    done; \
+	done; \
+	if test $$rval -ne 0; then \
+	    exit $$rval; \
+	fi; \
+	plog-converter $(PVS_LOG_OPTS) $$files
 
 install-dirs install-binaries install-includes install-plugin: config.status pre-install
 	for d in $(SUBDIRS); do \
@@ -148,33 +184,33 @@ uninstall-nls:
 	done
 
 siglist.c signame.c:
-	(cd lib/util && exec $(MAKE) $@)
+	cd lib/util && exec $(MAKE) $@
 
 depend: siglist.c signame.c
-	@if test "$(srcdir)" != "."; then \
-	    echo "make depend only supported in the source directory"; \
-	    exit 1; \
-	fi; \
-	$(srcdir)/mkdep.pl $(srcdir)/lib/util/Makefile.in \
-	    $(srcdir)/plugins/sample/Makefile.in \
-	    $(srcdir)/plugins/group_file/Makefile.in \
-	    $(srcdir)/plugins/sudoers/Makefile.in \
-	    $(srcdir)/plugins/system_group/Makefile.in \
-	    $(srcdir)/src/Makefile.in $(srcdir)/lib/zlib/Makefile.in; \
-	./config.status --file $(srcdir)/lib/util/Makefile \
-	    --file $(srcdir)/plugins/sample/Makefile \
-	    --file $(srcdir)/plugins/group_file/Makefile \
-	    --file $(srcdir)/plugins/sudoers/Makefile \
-	    --file $(srcdir)/plugins/system_group/Makefile \
-	    --file $(srcdir)/src/Makefile --file $(srcdir)/lib/zlib/Makefile
+	$(top_srcdir)/mkdep.pl --builddir=`pwd` --srcdir=$(top_srcdir) \
+	    lib/util/Makefile.in lib/zlib/Makefile.in \
+	    plugins/group_file/Makefile.in plugins/sample/Makefile.in \
+	    plugins/sudoers/Makefile.in plugins/system_group/Makefile.in \
+	    src/Makefile.in && \
+	$(top_builddir)/config.status --file $(top_builddir)/lib/util/Makefile \
+	    --file $(top_builddir)/plugins/sample/Makefile \
+	    --file $(top_builddir)/plugins/group_file/Makefile \
+	    --file $(top_builddir)/plugins/sudoers/Makefile \
+	    --file $(top_builddir)/plugins/system_group/Makefile \
+	    --file $(top_builddir)/src/Makefile \
+	    --file $(top_builddir)/lib/zlib/Makefile
 
 ChangeLog:
 	if test -d $(srcdir)/.hg && cd $(srcdir); then \
-	    if hg log --style=changelog -b default > $@.tmp; then \
+	    if hg log --style=changelog -r "sort(branch(.) or follow(), -date)" > $@.tmp; then \
 		mv -f $@.tmp $@; \
 	    else \
 		rm -f $@.tmp; \
 	    fi; \
+	elif test -d $(srcdir)/.git && cd $(srcdir); then \
+	    $(top_srcdir)/log2cl.pl -b master > $@; \
+	else \
+	    echo "ChangeLog data not available" > $@; \
 	fi
 
 config.status:
@@ -224,6 +260,8 @@ update-pot:
 		    rm -f $$pot.tmp; \
 		fi; \
 	    done; \
+	else \
+	    echo "Unable to update .pot files: $(XGETTEXT) not found" 1>&2; \
 	fi
 
 update-po: update-pot
@@ -237,6 +275,8 @@ update-po: update-pot
 		    $(MSGFMT) --output /dev/null --check-format $$po || exit 1; \
 		done; \
 	    done; \
+	else \
+	    echo "Unable to update .po files: $(MSGFMT) not found" 1>&2; \
 	fi
 
 compile-po:
@@ -259,6 +299,8 @@ compile-po:
 	    done; \
 	    $(MAKE) -f Makefile.$$$$; \
 	    rm -f Makefile.$$$$; \
+	else \
+	    echo "Unable to compile message catalogs: $(MSGFMT) not found" 1>&2; \
 	fi
 
 install-nls:
@@ -284,7 +326,7 @@ install-nls:
 	fi
 
 check-dist: update-pot compile-po
-	@if [ -d .hg ]; then \
+	@if test -d $(srcdir)/.hg && cd $(srcdir); then \
 	    if test `hg stat -am | wc -l` -ne 0; then \
 		echo "Uncommitted changes" 1>&2; \
 		hg stat -am 1>&2; \
@@ -295,10 +337,11 @@ check-dist: update-pot compile-po
 dist: check-dist force-dist
 
 force-dist: ChangeLog $(srcdir)/MANIFEST
+	cd $(top_srcdir) && \
 	pax -w -x ustar -s '/^/$(PACKAGE_TARNAME)-$(VERSION)\//' \
 	    -f ../$(PACKAGE_TARNAME)-$(VERSION).tar \
-	    `$(SED) 's/[ 	].*//' $(srcdir)/MANIFEST`
-	gzip -9f ../$(PACKAGE_TARNAME)-$(VERSION).tar
+	    `$(SED) 's/[ 	].*//' $(srcdir)/MANIFEST` && \
+	gzip -9f ../$(PACKAGE_TARNAME)-$(VERSION).tar && \
 	ls -l ../$(PACKAGE_TARNAME)-$(VERSION).tar.gz
 
 package: $(srcdir)/sudo.pp
@@ -330,6 +373,7 @@ clean: config.status
 	for d in $(SUBDIRS) $(SAMPLES); do \
 	    (cd $$d && exec $(MAKE) $@); \
 	done
+	-rm -rf cov-int cov-int.tgz
 
 mostlyclean: clean
 
diff --git a/sudo/sudo/mkpkg b/sudo/sudo/mkpkg
--- a/sudo/sudo/mkpkg
+++ b/sudo/sudo/mkpkg
@@ -1,6 +1,8 @@
 #!/bin/sh
 #
-# Copyright (c) 2010-2015 Todd C. Miller <Todd.Miller@courtesan.com>
+# SPDX-License-Identifier: ISC
+#
+# Copyright (c) 2010-2018 Todd C. Miller <Todd.Miller@sudo.ws>
 #
 # Permission to use, copy, modify, and distribute this software for any
 # purpose with or without fee is hereby granted, provided that the above
@@ -91,10 +93,50 @@ top_srcdir=`dirname $0`
 : ${osversion="`$top_srcdir/pp --probe`"}
 test -n "$osversion" || exit 1
 osrelease=`echo "$osversion" | sed -e 's/^[^0-9]*//' -e 's/-.*$//'`
+: ${MAKE=make}
+
+# If using GNU make, set number of jobs
+if ${MAKE} --version 2>&1 | grep GNU >/dev/null; then
+    NJOBS=0
+    case "`uname`" in
+	Darwin)
+	    # macOS
+	    NJOBS=`sysctl -n hw.ncpu`
+	    ;;
+	Linux)
+	    if [ -r /proc/cpuinfo ]; then
+		for c in `sed -n 's/^cpu cores[	 ]*: *//p' /proc/cpuinfo`; do
+		    NJOBS=`expr $NJOBS + $c`
+		done
+	    fi
+	    ;;
+	SunOS)
+	    # Solaris
+	    if [ -x /usr/sbin/psrinfo ]; then
+		NJOBS=`/usr/sbin/psrinfo | wc -l`
+	    fi
+	    ;;
+	HP-UX)
+	    NJOBS=`sar -Mu 1 1 | awk 'END {print NR-5}'`
+	    ;;
+	AIX)
+	    NJOBS=`bindprocessor -q | awk '{print NF-4}'`
+	    ;;
+    esac
+    if [ $NJOBS -gt 1 ]; then
+	make_opts="-j$NJOBS"
+    fi
+fi
 
 # Choose compiler options by osversion if not cross-compiling.
 if [ "$crossbuild" = "false" ]; then
     case "$osversion" in
+	macos*)
+	    # Use clang on macOS if present
+	    if [ -z "$CC" -a -x /usr/bin/clang ]; then
+		CC=/usr/bin/clang; export CC
+	    fi
+	    ;;
 	sol[0-9]*)
 	    # Use the Sun Studio C compiler on Solaris if possible
 	    if [ -z "$CC" -a -x /usr/bin/cc ]; then
@@ -107,21 +149,26 @@ if [ "$crossbuild" = "false" ]; then
     esac
 fi
 
+# Give configure a hint that we are building a package.
+# Some libc functions are only available on certain OS revisions.
+configure_opts="${configure_opts}${configure_opts+$tab}--enable-package-build"
+
 # Choose configure options by osversion.
 # We use the same configure options as vendor packages when possible.
 case "$osversion" in
     centos*|rhel*|f[0-9]*)
 	case "$osversion" in
 	    centos*|rhel*)
-		if [ $osrelease -ge 40 ]; then
+		osmajor=`sed -n -e 's/^.*release \([0-9]*\)[^0-9].*$/\1/p' /etc/redhat-release`
+		if [ $osmajor -ge 4 ]; then
 		    # RHEL 4 and up support SELinux
 		    with_selinux=true
-		    if [ $osrelease -ge 50 ]; then
+		    if [ $osmajor -ge 5 ]; then
 			# RHEL 5 and up has audit support and uses a
 			# separate PAM config file for "sudo -i".
 			with_linux_audit=true
 			with_pam_login=true
-			if [ $osrelease -ge 60 ]; then
+			if [ $osmajor -ge 6 ]; then
 			    # RHEL 6 and above builds sudo with SSSD support
 			    with_sssd=true
 			    # RHEL 6 and above use /etc/sudo-ldap.conf
@@ -136,7 +183,6 @@ case "$osversion" in
 		with_linux_audit=true
 		with_pam_login=true
 		with_sssd=true
-		with_sudo_ldap_conf=true
 		;;
 	esac
 
@@ -207,7 +253,7 @@ case "$osversion" in
 		--with-sendmail=/usr/sbin/sendmail
 		$configure_opts"
 
-	make_opts='docdir=$(datarootdir)/doc/packages/$(PACKAGE_TARNAME)'
+	make_opts="${make_opts}${make_opts+ }"'docdir=$(datarootdir)/doc/packages/$(PACKAGE_TARNAME)'
 	;;
     deb*|ubu*)
 	# Man pages should be compressed in .deb files
@@ -258,7 +304,7 @@ case "$osversion" in
 		test -n "$linux_audit" && break;
 	    fi
 	done
-	if [ -z "linux_audit" ]; then
+	if [ -z "$linux_audit" ]; then
 	    echo "unable to determine package for libaudit" 1>&2
 	    exit 1
 	fi
@@ -273,14 +319,22 @@ case "$osversion" in
 	esac
 	if test "${osversion}" != "`$top_srcdir/pp --probe`"; then
 	    sdkvers=`echo "${osversion}" | sed 's/^macos\([0-9][0-9]\)\([0-9]*\)-.*$/\1.\2/'`
-	    # Newer Xcode puts /Developer under the app Contents dir.
-	    SDK_DIR="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs"
-	    if test -d "${SDK_DIR}/MacOSX${sdkvers}.sdk"; then
-		SDK_DIR="${SDK_DIR}/MacOSX${sdkvers}.sdk"
-	    elif test -d "/Developer/SDKs/MacOSX${sdkvers}.sdk"; then
-		SDK_DIR="/Developer/SDKs/MacOSX${sdkvers}.sdk"
+	    # SDKs may be under Xcode.app or CommandLineTools (for non-Xcode)
+	    if [ -d "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs" ]; then
+		SDK_DIR="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs"
+	    elif [ -d "/Library/Developer/CommandLineTools/SDKs" ]; then
+		SDK_DIR="/Library/Developer/CommandLineTools/SDKs"
+	    else
+		echo "unable to find macOS SDKs directory" 1>&2
+		exit 1
 	    fi
-	    SDK_FLAGS="-isysroot ${SDK_DIR} -mmacosx-version-min=${sdkvers}"
+	    SDK_DIR="${SDK_DIR}/MacOSX${sdkvers}.sdk"
+	    if test -d "${SDK_DIR}"; then
+		SDK_FLAGS="-isysroot ${SDK_DIR} -mmacosx-version-min=${sdkvers}"
+	    else
+		echo "unable to find SDKs directory for macOS $sdkvers" 1>&2
+		exit 1
+	    fi
 	fi
 	export CFLAGS="-O2 -g $ARCH_FLAGS $SDK_FLAGS"
 	export LDFLAGS="$ARCH_FLAGS $SDK_FLAGS"
@@ -300,7 +354,7 @@ case "$osversion" in
     aix*)
 	# Use -gxcoff with gcc instead of -g for dbx-style debugging symbols.
 	if test -z "$CC" && gcc -v >/dev/null 2>&1; then
-	    CFLAGS=-gxcoff; export CFLAGS
+	    CFLAGS="-O2 -gxcoff"; export CFLAGS
 	fi
 	# Note, must indent with tabs, not spaces due to IFS trickery
 	# Note: we include our own zlib instead of relying on the
@@ -357,8 +411,8 @@ IFS="	$nl"
 set -- $configure_opts $extra_opts
 IFS="$OIFS"
 if [ -r Makefile ]; then
-    make $make_opts distclean
+    ${MAKE} $make_opts distclean
 fi
 $top_srcdir/configure "$@" || exit 1
-make $make_opts && make $make_opts PPFLAGS="$PPFLAGS" PPVARS="$PPVARS" package
+${MAKE} $make_opts && ${MAKE} $make_opts PPFLAGS="$PPFLAGS" PPVARS="$PPVARS" package
 test $debug -eq 0 && rm -rf destdir
