13.3

diff --git a/zsh/zsh/Functions/Prompts/promptinit b/zsh/zsh/Functions/Prompts/promptinit
--- a/zsh/zsh/Functions/Prompts/promptinit
+++ b/zsh/zsh/Functions/Prompts/promptinit
@@ -14,6 +14,8 @@ prompt_themes=()
 promptinit () {
   emulate -L zsh
   setopt extendedglob
+  autoload -Uz add-zsh-hook add-zle-hook-widget
+
   local ppath='' name theme
   local -a match mbegin mend
 
@@ -32,9 +34,6 @@ promptinit () {
     fi
   done
 
-  # To manipulate precmd and preexec hooks...
-  autoload -Uz add-zsh-hook
-
   # Variables common to all prompt styles
   prompt_newline=$'\n%{\r%}'
 }
@@ -47,36 +46,23 @@ prompt_preview_safely() {
     return
   fi
 
-  # This handles all the stuff from the default :prompt-theme cleanup
-  local +h PS1=$PS1 PS2=$PS2 PS3=$PS3 PS4=$PS4 RPS1=$RPS1 RPS2=$RPS2
-  local +h PROMPT=$PROMPT RPROMPT=$RPOMPT RPROMPT2=$RPROMPT2 PSVAR=$PSVAR
-  local -a precmd_functions preexec_functions prompt_preview_cleanup
-  local -aLl +h zle_highlight
+  # Run this in a subshell, so we don't need to clean up afterwards.
+  (
+    # Execute current theme's cleanup sequence, if any.
+    zstyle -t :prompt-theme cleanup
 
-  {
-    # Save and clear current restore-point if any
-    zstyle -g prompt_preview_cleanup :prompt-theme cleanup
-    {
-      zstyle -d :prompt-theme cleanup
-
-      # The next line is a bit ugly.  It (perhaps unnecessarily)
-      # runs the prompt theme setup function to ensure that if
-      # the theme has a _preview function that it's been autoloaded.
+    # If we can't find a _preview function, run the _setup function to see if
+    # it will create one.
+    typeset +f prompt_${1}_preview >&/dev/null ||
       prompt_${1}_setup
 
-      if typeset +f prompt_${1}_preview >&/dev/null; then
-        prompt_${1}_preview "$@[2,-1]"
-      else
-        prompt_preview_theme "$@"
-      fi
-    } always {
-      # Run any theme-specific cleanup, then reset restore point
-      zstyle -t :prompt-theme cleanup
-    }
-  } always {
-    (( $#prompt_preview_cleanup )) &&
-      zstyle -e :prompt-theme cleanup "${prompt_preview_cleanup[@]}"
-  }
+    # ...then try again.
+    if typeset +f prompt_${1}_preview >&/dev/null; then
+      prompt_${1}_preview "$@[2,-1]"
+    else
+      prompt_preview_theme "$@"
+    fi
+  )
 }
 
 set_prompt() {
@@ -87,7 +73,7 @@ set_prompt() {
 Options:
     -c              Show currently selected theme and parameters
     -l              List currently available prompt themes
-    -p [<themes>]   Preview given themes (defaults to all)
+    -p [<themes>]   Preview given themes (defaults to all except current theme)
     -h [<theme>]    Display help (for given theme)
     -s <theme>      Set and save theme
     <theme>         Switch to new theme immediately (changes not saved)
@@ -95,19 +81,6 @@ Options:
 Use prompt -h <theme> for help on specific themes.'
 
   getopts "chlps:" opt
-  case "$opt" in
-    (h|p)
-      setopt localtraps
-      if [[ -z "$prompt_theme[1]" ]]; then
-        # Not using a prompt theme; save settings
-        local +h PS1=$PS1 PS2=$PS2 PS3=$PS3 PS4=$PS4 RPS1=$RPS1 RPS2=$RPS2
-        local +h PROMPT=$PROMPT RPROMPT=$RPOMPT RPROMPT2=$RPROMPT2 PSVAR=$PSVAR
-        local -a precmd_functions preexec_functions
-      else
-        trap 'prompt_${prompt_theme[1]}_setup "${(@)prompt_theme[2,-1]}"' 0
-      fi
-      ;;
-  esac
   case "$opt" in
     c) if [[ -n $prompt_theme ]]; then
          print -n "Current prompt theme"
@@ -119,20 +92,26 @@ Use prompt -h <theme> for help on specific themes.'
        return
        ;;
     h) if [[ -n "$2" && -n $prompt_themes[(r)$2] ]]; then
-         if functions prompt_$2_setup >/dev/null; then
-           # The next line is a bit ugly.  It (perhaps unnecessarily)
-           # runs the prompt theme setup function to ensure that if
-           # the theme has a _help function that it's been autoloaded.
-           prompt_$2_setup
-         fi
-         if functions prompt_$2_help >/dev/null; then
-           print "Help for $2 theme:\n"
-           prompt_$2_help
-         else
-           print "No help available for $2 theme."
-         fi
-         print "\nType \`prompt -p $2' to preview the theme, \`prompt $2'"
-         print "to try it out, and \`prompt -s $2' to use it in future sessions."
+         # Run this in a subshell, so we don't need to clean up afterwards.
+         (
+           # Execute current theme's cleanup sequence, if any.
+           zstyle -t :prompt-theme cleanup
+
+           # If we can't find a _help function, run the _setup function to see
+           # if it will create one.
+           typeset +f prompt_$2_help >/dev/null ||
+               prompt_$2_setup
+
+           # ...then try again.
+           if typeset +f prompt_$2_help >/dev/null; then
+             print "Help for $2 theme:\n"
+             prompt_$2_help
+           else
+             print "No help available for $2 theme."
+           fi
+           print "\nType \`prompt -p $2' to preview the theme, \`prompt $2'"
+           print "to try it out, and \`prompt -s $2' to use it in future sessions."
+         )
        else
          print "$usage"
        fi
@@ -141,10 +120,9 @@ Use prompt -h <theme> for help on specific themes.'
        print $prompt_themes
        return
        ;;
-    p) preview=( $prompt_themes )
+    p) preview=( ${prompt_themes:#$prompt_theme} )
        (( $#* > 1 )) && preview=( "$@[2,-1]" )
        for theme in $preview; do
-         [[ "$theme" == "$prompt_theme[*]" ]] && continue
          prompt_preview_safely "$=theme"
        done
        print -P "%b%f%k"
@@ -173,34 +151,46 @@ Use prompt -h <theme> for help on specific themes.'
 
        # Reset some commonly altered bits to the default
        local hook
-       for hook in chpwd precmd preexec periodic zshaddhistory zshexit; do
-         add-zsh-hook -D "${hook}" "prompt_*_${hook}"
+       for hook in chpwd precmd preexec periodic zshaddhistory zshexit \
+           zsh_directory_name; do
+         add-zsh-hook -D "$hook" "prompt_*_$hook"
+       done
+       for hook in isearch-exit isearch-update line-pre-redraw line-init \
+           line-finish history-line-set keymap-select; do
+         add-zle-hook-widget -D "$hook" "prompt_*_$hook"
        done
        typeset -ga zle_highlight=( ${zle_highlight:#default:*} )
        (( ${#zle_highlight} )) || unset zle_highlight
 
+       zstyle -t :prompt-theme cleanup
        prompt_$1_setup "$@[2,-1]" && prompt_theme=( "$@" )
        ;;
   esac
 }
 
 prompt_cleanup () {
-  local -a cleanup_hooks
-  if zstyle -g cleanup_hooks :prompt-theme cleanup
-  then
-    cleanup_hooks+=(';' "$@")
-    zstyle -e :prompt-theme cleanup "${cleanup_hooks[@]}"
-  elif (( $+prompt_preview_cleanup == 0 ))
-  then
-    print -u2 "prompt_cleanup: no prompt theme active"
-    return 1
+  local -a cleanup_hooks theme_active
+  if ! zstyle -g cleanup_hooks :prompt-theme cleanup; then
+    if ! zstyle -g theme_active :prompt-theme restore; then
+      print -u2 "prompt_cleanup: no prompt theme active"
+      return 1
+    fi
+
+    # Set the cleanup sequence up.
+    zstyle -e :prompt-theme cleanup \
+        'zstyle -d :prompt-theme cleanup;' \
+        'reply=(yes)'
+    zstyle -g cleanup_hooks :prompt-theme cleanup
   fi
+
+  cleanup_hooks+=(';' "$@")
+  zstyle -e :prompt-theme cleanup "${cleanup_hooks[@]}"
 }
 
 prompt () {
   local -a prompt_opts theme_active
 
-  zstyle -g theme_active :prompt-theme cleanup || {
+  zstyle -g theme_active :prompt-theme restore || {
     # This is done here rather than in set_prompt so that it
     # is safe and sane for set_prompt to setopt localoptions,
     # which will be cleared before we arrive back here again.
@@ -210,22 +200,21 @@ prompt () {
     [[ -o promptpercent ]] && prompt_opts+=(percent)
     [[ -o promptsp ]] && prompt_opts+=(sp)
     [[ -o promptsubst ]] && prompt_opts+=(subst)
-    zstyle -e :prompt-theme cleanup \
-        'zstyle -d :prompt-theme cleanup;' \
-	'prompt_default_setup;' \
-        ${PS1+PS1="${(q)PS1}"} \
-        ${PS2+PS2="${(q)PS2}"} \
-        ${PS3+PS3="${(q)PS3}"} \
-        ${PS4+PS4="${(q)PS4}"} \
-        ${RPS1+RPS1="${(q)RPS1}"} \
-        ${RPS2+RPS2="${(q)RPS2}"} \
-        ${RPROMPT+RPROMPT="${(q)RPROMPT}"} \
-        ${RPROMPT2+RPROMPT2="${(q)RPROMPT2}"} \
-        ${PSVAR+PSVAR="${(q)PSVAR}"} \
-        "precmd_functions=(${(q)precmd_functions[@]})" \
-        "preexec_functions=(${(q)preexec_functions[@]})" \
-        "prompt_opts=( ${prompt_opts[*]} )" \
-        'reply=(yes)'
+    zstyle -e :prompt-theme restore "
+        zstyle -d :prompt-theme restore
+        prompt_default_setup
+        ${PS1+PS1=${(q+)PS1}}
+        ${PS2+PS2=${(q+)PS2}}
+        ${PS3+PS3=${(q+)PS3}}
+        ${PS4+PS4=${(q+)PS4}}
+        ${RPS1+RPS1=${(q+)RPS1}}
+        ${RPS2+RPS2=${(q+)RPS2}}
+        ${RPROMPT+RPROMPT=${(q+)RPROMPT}}
+        ${RPROMPT2+RPROMPT2=${(q+)RPROMPT2}}
+        ${PSVAR+PSVAR=${(q+)PSVAR}}
+        prompt_opts=( $prompt_opts[*] )
+        reply=( yes )
+    "
   }
   set_prompt "$@"
 
@@ -238,26 +227,29 @@ prompt () {
 prompt_preview_theme () {
   emulate -L zsh
 
-  # Check for proper state handling
-  (( $+prompt_preview_cleanup )) || {
-    prompt_preview_safely "$@"
-    return
-  }
-
   # Minimal preview for prompts that don't supply one
   local -a prompt_opts
   print -n "$1 theme"
   (( $#* > 1 )) && print -n " with parameters \`$*[2,-1]'"
   print ":"
+  zstyle -t :prompt-theme cleanup
   prompt_${1}_setup "$@[2,-1]"
   (( ${#prompt_opts} )) &&
       setopt noprompt{bang,cr,percent,sp,subst} "prompt${^prompt_opts[@]}"
+
+  [[ -n ${chpwd_functions[(r)prompt_${1}_chpwd]} ]] &&
+      prompt_${1}_chpwd
   [[ -n ${precmd_functions[(r)prompt_${1}_precmd]} ]] &&
-    prompt_${1}_precmd
-  [[ -o promptcr ]] && print -n $'\r'; :
-  print -P "${PS1}command arg1 arg2 ... argn"
+      prompt_${1}_precmd
+
+  # We'd like to call zle-line-init/finish hooks, too, but that's not possible
+  # while the ZLE is not active.
+
+  [[ -o promptcr ]] && print -n $'\r'
+  :; print -P -- "${PS1}command arg1 arg2 ... argn"
+
   [[ -n ${preexec_functions[(r)prompt_${1}_preexec]} ]] &&
-    prompt_${1}_preexec
+      prompt_${1}_preexec
 }
 
 [[ -o kshautoload ]] || promptinit "$@"
