10.6.8

diff --git a/cups/cups/configure b/cups/cups/configure
--- a/cups/cups/configure
+++ b/cups/cups/configure
@@ -680,6 +680,7 @@ XDGOPEN
 CUPS_HTMLVIEW
 INSTALL
 INSTALLSTATIC
+PKGCONFIG
 LIBMALLOC
 LIBPAPER
 GREP
@@ -689,7 +690,6 @@ LIBWRAP
 ARFLAGS
 BACKLIBS
 CUPSDLIBS
-PKGCONFIG
 DBUSDIR
 DBUS_NOTIFIER
 DBUS_NOTIFIERLIBS
@@ -1989,7 +1989,7 @@ esac
 ac_config_headers="$ac_config_headers config.h"
 
 
-CUPS_VERSION="1.4.6"
+CUPS_VERSION="1.4.7"
 CUPS_REVISION=""
 #if test -z "$CUPS_REVISION" -a -d .svn; then
 #	CUPS_REVISION="-r`svnversion . | awk -F: '{print $NF}' | sed -e '1,$s/[[a-zA-Z]]*//g'`"
@@ -4106,6 +4106,47 @@ fi
 if test x$enable_static = xyes; then
 	echo Installing static libraries...
 	INSTALLSTATIC="installstatic"
+fi
+
+
+
+# Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_PKGCONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PKGCONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKGCONFIG="$PKGCONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_PKGCONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+PKGCONFIG=$ac_cv_path_PKGCONFIG
+if test -n "$PKGCONFIG"; then
+  { echo "$as_me:$LINENO: result: $PKGCONFIG" >&5
+echo "${ECHO_T}$PKGCONFIG" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
 fi
 
 
@@ -8088,9 +8129,9 @@ else
 fi
 
 if test $check_libusb = yes; then
-	{ echo "$as_me:$LINENO: checking for usb_init in -lusb" >&5
-echo $ECHO_N "checking for usb_init in -lusb... $ECHO_C" >&6; }
-if test "${ac_cv_lib_usb_usb_init+set}" = set; then
+	{ echo "$as_me:$LINENO: checking for usb_get_string_simple in -lusb" >&5
+echo $ECHO_N "checking for usb_get_string_simple in -lusb... $ECHO_C" >&6; }
+if test "${ac_cv_lib_usb_usb_get_string_simple+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
@@ -8108,11 +8149,11 @@ cat >>conftest.$ac_ext <<_ACEOF
 #ifdef __cplusplus
 extern "C"
 #endif
-char usb_init ();
+char usb_get_string_simple ();
 int
 main ()
 {
-return usb_init ();
+return usb_get_string_simple ();
   ;
   return 0;
 }
@@ -8135,21 +8176,21 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_usb_usb_init=yes
+  ac_cv_lib_usb_usb_get_string_simple=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	ac_cv_lib_usb_usb_init=no
+	ac_cv_lib_usb_usb_get_string_simple=no
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_usb_usb_init" >&5
-echo "${ECHO_T}$ac_cv_lib_usb_usb_init" >&6; }
-if test $ac_cv_lib_usb_usb_init = yes; then
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_usb_usb_get_string_simple" >&5
+echo "${ECHO_T}$ac_cv_lib_usb_usb_get_string_simple" >&6; }
+if test $ac_cv_lib_usb_usb_get_string_simple = yes; then
 
 		if test "${ac_cv_header_usb_h+set}" = set; then
   { echo "$as_me:$LINENO: checking for usb.h" >&5
@@ -8635,74 +8676,49 @@ fi
 DBUS_NOTIFIER=""
 DBUS_NOTIFIERLIBS=""
 
-if test "x$enable_dbus" != xno; then
-	# Extract the first word of "pkg-config", so it can be a program name with args.
-set dummy pkg-config; ac_word=$2
-{ echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_PKGCONFIG+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $PKGCONFIG in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_PKGCONFIG="$PKGCONFIG" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_PKGCONFIG="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-IFS=$as_save_IFS
-
-  ;;
-esac
-fi
-PKGCONFIG=$ac_cv_path_PKGCONFIG
-if test -n "$PKGCONFIG"; then
-  { echo "$as_me:$LINENO: result: $PKGCONFIG" >&5
-echo "${ECHO_T}$PKGCONFIG" >&6; }
-else
-  { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-fi
-
-
-	if test "x$PKGCONFIG" != x; then
-		{ echo "$as_me:$LINENO: checking for DBUS" >&5
+if test "x$enable_dbus" != xno -a "x$PKGCONFIG" != x; then
+	{ echo "$as_me:$LINENO: checking for DBUS" >&5
 echo $ECHO_N "checking for DBUS... $ECHO_C" >&6; }
-		if $PKGCONFIG --exists dbus-1; then
-			{ echo "$as_me:$LINENO: result: yes" >&5
+	if $PKGCONFIG --exists dbus-1; then
+		{ echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
-			cat >>confdefs.h <<\_ACEOF
+		cat >>confdefs.h <<\_ACEOF
 #define HAVE_DBUS 1
 _ACEOF
 
-			CFLAGS="$CFLAGS `$PKGCONFIG --cflags dbus-1` -DDBUS_API_SUBJECT_TO_CHANGE"
-			CUPSDLIBS="$CUPSDLIBS `$PKGCONFIG --libs dbus-1`"
-			DBUS_NOTIFIER="dbus"
-			DBUS_NOTIFIERLIBS="`$PKGCONFIG --libs dbus-1`"
-			{ echo "$as_me:$LINENO: checking for dbus_message_iter_init_append in -ldbus-1" >&5
-echo $ECHO_N "checking for dbus_message_iter_init_append in -ldbus-1... $ECHO_C" >&6; }
-if test "${ac_cv_lib_dbus_1_dbus_message_iter_init_append+set}" = set; then
+		CFLAGS="$CFLAGS `$PKGCONFIG --cflags dbus-1` -DDBUS_API_SUBJECT_TO_CHANGE"
+		CUPSDLIBS="$CUPSDLIBS `$PKGCONFIG --libs dbus-1`"
+		DBUS_NOTIFIER="dbus"
+		DBUS_NOTIFIERLIBS="`$PKGCONFIG --libs dbus-1`"
+		SAVELIBS="$LIBS"
+		LIBS="$LIBS $DBUS_NOTIFIERLIBS"
+		{ echo "$as_me:$LINENO: checking for dbus_message_iter_init_append" >&5
+echo $ECHO_N "checking for dbus_message_iter_init_append... $ECHO_C" >&6; }
+if test "${ac_cv_func_dbus_message_iter_init_append+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-ldbus-1 `$PKGCONFIG --libs dbus-1` $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
+  cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
+/* Define dbus_message_iter_init_append to an innocuous variant, in case <limits.h> declares dbus_message_iter_init_append.
+   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
+#define dbus_message_iter_init_append innocuous_dbus_message_iter_init_append
+
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char dbus_message_iter_init_append (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef dbus_message_iter_init_append
 
 /* Override any GCC internal prototype to avoid an error.
    Use char because int might match the return type of a GCC
@@ -8711,6 +8727,13 @@ cat >>conftest.$ac_ext <<_ACEOF
 extern "C"
 #endif
 char dbus_message_iter_init_append ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined __stub_dbus_message_iter_init_append || defined __stub___dbus_message_iter_init_append
+choke me
+#endif
+
 int
 main ()
 {
@@ -8737,31 +8760,30 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_dbus_1_dbus_message_iter_init_append=yes
+  ac_cv_func_dbus_message_iter_init_append=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	ac_cv_lib_dbus_1_dbus_message_iter_init_append=no
+	ac_cv_func_dbus_message_iter_init_append=no
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
 fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_dbus_1_dbus_message_iter_init_append" >&5
-echo "${ECHO_T}$ac_cv_lib_dbus_1_dbus_message_iter_init_append" >&6; }
-if test $ac_cv_lib_dbus_1_dbus_message_iter_init_append = yes; then
+{ echo "$as_me:$LINENO: result: $ac_cv_func_dbus_message_iter_init_append" >&5
+echo "${ECHO_T}$ac_cv_func_dbus_message_iter_init_append" >&6; }
+if test $ac_cv_func_dbus_message_iter_init_append = yes; then
   cat >>confdefs.h <<\_ACEOF
 #define HAVE_DBUS_MESSAGE_ITER_INIT_APPEND 1
 _ACEOF
 
 fi
 
-		else
-			{ echo "$as_me:$LINENO: result: no" >&5
+		LIBS="$SAVELIBS"
+	else
+		{ echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
-		fi
 	fi
 fi
 
@@ -17527,7 +17549,7 @@ SSLLIBS=""
 have_ssl=0
 
 if test x$enable_ssl != xno; then
-        if test $have_ssl = 0 -a "x${enable_cdsassl}" != "xno"; then
+        if test $have_ssl = 0 -a "x$enable_cdsassl" != "xno"; then
 	if test $uname = Darwin; then
 	    if test "${ac_cv_header_Security_SecureTransport_h+set}" = set; then
   { echo "$as_me:$LINENO: checking for Security/SecureTransport.h" >&5
@@ -17666,7 +17688,140 @@ _ACEOF
 _ACEOF
 
 
-				if test "${ac_cv_header_Security_SecItemPriv_h+set}" = set; then
+				if test "${ac_cv_header_Security_SecItem_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for Security/SecItem.h" >&5
+echo $ECHO_N "checking for Security/SecItem.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_Security_SecItem_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_Security_SecItem_h" >&5
+echo "${ECHO_T}$ac_cv_header_Security_SecItem_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking Security/SecItem.h usability" >&5
+echo $ECHO_N "checking Security/SecItem.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <Security/SecItem.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking Security/SecItem.h presence" >&5
+echo $ECHO_N "checking Security/SecItem.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <Security/SecItem.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: Security/SecItem.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: Security/SecItem.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: Security/SecItem.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: Security/SecItem.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: Security/SecItem.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: Security/SecItem.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: Security/SecItem.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: Security/SecItem.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: Security/SecItem.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: Security/SecItem.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: Security/SecItem.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: Security/SecItem.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: Security/SecItem.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: Security/SecItem.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: Security/SecItem.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: Security/SecItem.h: in the future, the compiler will take precedence" >&2;}
+
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for Security/SecItem.h" >&5
+echo $ECHO_N "checking for Security/SecItem.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_Security_SecItem_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_Security_SecItem_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_Security_SecItem_h" >&5
+echo "${ECHO_T}$ac_cv_header_Security_SecItem_h" >&6; }
+
+fi
+if test $ac_cv_header_Security_SecItem_h = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_SECITEM_H 1
+_ACEOF
+
+fi
+
+
+		if test "${ac_cv_header_Security_SecItemPriv_h+set}" = set; then
   { echo "$as_me:$LINENO: checking for Security/SecItemPriv.h" >&5
 echo $ECHO_N "checking for Security/SecItemPriv.h... $ECHO_C" >&6; }
 if test "${ac_cv_header_Security_SecItemPriv_h+set}" = set; then
@@ -18365,7 +18520,7 @@ fi
 	fi
     fi
 
-        if test $have_ssl = 0 -a "x${enable_gnutls}" != "xno" -a "x$PKGCONFIG" != x; then
+        if test $have_ssl = 0 -a "x$enable_gnutls" != "xno" -a "x$PKGCONFIG" != x; then
     	# Extract the first word of "libgnutls-config", so it can be a program name with args.
 set dummy libgnutls-config; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -18493,7 +18648,7 @@ _ACEOF
 	fi
     fi
 
-        if test $have_ssl = 0 -a "x${enable_openssl}" != "xno"; then
+        if test $have_ssl = 0 -a "x$enable_openssl" != "xno"; then
 	if test "${ac_cv_header_openssl_ssl_h+set}" = set; then
   { echo "$as_me:$LINENO: checking for openssl/ssl.h" >&5
 echo $ECHO_N "checking for openssl/ssl.h... $ECHO_C" >&6; }
@@ -18721,6 +18876,10 @@ if test $have_ssl = 1; then
 echo "${ECHO_T}    Using SSLLIBS=\"$SSLLIBS\"" >&6; }
     { echo "$as_me:$LINENO: result:     Using SSLFLAGS=\"$SSLFLAGS\"" >&5
 echo "${ECHO_T}    Using SSLFLAGS=\"$SSLFLAGS\"" >&6; }
+elif test x$enable_cdsa = xyes -o x$enable_gnutls = xyes -o x$enable_openssl = xyes; then
+    { { echo "$as_me:$LINENO: error: Unable to enable SSL support." >&5
+echo "$as_me: error: Unable to enable SSL support." >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 
@@ -22619,6 +22778,7 @@ XDGOPEN!$XDGOPEN$ac_delim
 CUPS_HTMLVIEW!$CUPS_HTMLVIEW$ac_delim
 INSTALL!$INSTALL$ac_delim
 INSTALLSTATIC!$INSTALLSTATIC$ac_delim
+PKGCONFIG!$PKGCONFIG$ac_delim
 LIBMALLOC!$LIBMALLOC$ac_delim
 LIBPAPER!$LIBPAPER$ac_delim
 GREP!$GREP$ac_delim
@@ -22628,7 +22788,6 @@ LIBWRAP!$LIBWRAP$ac_delim
 ARFLAGS!$ARFLAGS$ac_delim
 BACKLIBS!$BACKLIBS$ac_delim
 CUPSDLIBS!$CUPSDLIBS$ac_delim
-PKGCONFIG!$PKGCONFIG$ac_delim
 DBUSDIR!$DBUSDIR$ac_delim
 DBUS_NOTIFIER!$DBUS_NOTIFIER$ac_delim
 DBUS_NOTIFIERLIBS!$DBUS_NOTIFIERLIBS$ac_delim
