10.7.4

diff --git a/cups/cups/configure b/cups/cups/configure
--- a/cups/cups/configure
+++ b/cups/cups/configure
@@ -669,6 +669,7 @@ ac_ct_CXX
 RANLIB
 AR
 CHMOD
+GZIP
 HTMLDOC
 LD
 LN
@@ -776,6 +777,7 @@ LIBJPEG
 LIBPNG
 LIBTIFF
 LIBZ
+INSTALL_GZIP
 EXPORT_LIBJPEG
 EXPORT_LIBPNG
 EXPORT_LIBTIFF
@@ -2001,7 +2003,7 @@ esac
 ac_config_headers="$ac_config_headers config.h"
 
 
-CUPS_VERSION="1.5.1"
+CUPS_VERSION="1.5.3"
 CUPS_REVISION=""
 #if test -z "$CUPS_REVISION" -a -d .svn; then
 #	CUPS_REVISION="-r`svnversion . | awk -F: '{print $NF}' | sed -e '1,$s/[[a-zA-Z]]*//g'`"
@@ -3757,6 +3759,46 @@ CHMOD=$ac_cv_path_CHMOD
 if test -n "$CHMOD"; then
   { echo "$as_me:$LINENO: result: $CHMOD" >&5
 echo "${ECHO_T}$CHMOD" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+# Extract the first word of "gzip", so it can be a program name with args.
+set dummy gzip; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_GZIP+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $GZIP in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_GZIP="$GZIP" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_GZIP="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+GZIP=$ac_cv_path_GZIP
+if test -n "$GZIP"; then
+  { echo "$as_me:$LINENO: result: $GZIP" >&5
+echo "${ECHO_T}$GZIP" >&6; }
 else
   { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
@@ -8528,214 +8570,28 @@ fi
 LIBUSB=""
 
 
-if test x$enable_libusb = xyes; then
-	check_libusb=yes
-elif test x$enable_libusb != xno -a $uname != Darwin; then
-	check_libusb=yes
-else
-	check_libusb=no
-fi
-
-if test $check_libusb = yes; then
-	{ echo "$as_me:$LINENO: checking for usb_get_string_simple in -lusb" >&5
-echo $ECHO_N "checking for usb_get_string_simple in -lusb... $ECHO_C" >&6; }
-if test "${ac_cv_lib_usb_usb_get_string_simple+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lusb  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-char usb_get_string_simple ();
-int
-main ()
-{
-return usb_get_string_simple ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_c_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext &&
-       $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_usb_usb_get_string_simple=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	ac_cv_lib_usb_usb_get_string_simple=no
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_usb_usb_get_string_simple" >&5
-echo "${ECHO_T}$ac_cv_lib_usb_usb_get_string_simple" >&6; }
-if test $ac_cv_lib_usb_usb_get_string_simple = yes; then
-
-		if test "${ac_cv_header_usb_h+set}" = set; then
-  { echo "$as_me:$LINENO: checking for usb.h" >&5
-echo $ECHO_N "checking for usb.h... $ECHO_C" >&6; }
-if test "${ac_cv_header_usb_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_header_usb_h" >&5
-echo "${ECHO_T}$ac_cv_header_usb_h" >&6; }
-else
-  # Is the header compilable?
-{ echo "$as_me:$LINENO: checking usb.h usability" >&5
-echo $ECHO_N "checking usb.h usability... $ECHO_C" >&6; }
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-$ac_includes_default
-#include <usb.h>
-_ACEOF
-rm -f conftest.$ac_objext
-if { (ac_try="$ac_compile"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_compile") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_c_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest.$ac_objext; then
-  ac_header_compiler=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	ac_header_compiler=no
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
-{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
-echo "${ECHO_T}$ac_header_compiler" >&6; }
-
-# Is the header present?
-{ echo "$as_me:$LINENO: checking usb.h presence" >&5
-echo $ECHO_N "checking usb.h presence... $ECHO_C" >&6; }
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <usb.h>
-_ACEOF
-if { (ac_try="$ac_cpp conftest.$ac_ext"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } >/dev/null && {
-	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
-	 test ! -s conftest.err
-       }; then
-  ac_header_preproc=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-  ac_header_preproc=no
-fi
-
-rm -f conftest.err conftest.$ac_ext
-{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
-echo "${ECHO_T}$ac_header_preproc" >&6; }
-
-# So?  What about this header?
-case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
-  yes:no: )
-    { echo "$as_me:$LINENO: WARNING: usb.h: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: usb.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: usb.h: proceeding with the compiler's result" >&5
-echo "$as_me: WARNING: usb.h: proceeding with the compiler's result" >&2;}
-    ac_header_preproc=yes
-    ;;
-  no:yes:* )
-    { echo "$as_me:$LINENO: WARNING: usb.h: present but cannot be compiled" >&5
-echo "$as_me: WARNING: usb.h: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: usb.h:     check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: usb.h:     check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: usb.h: see the Autoconf documentation" >&5
-echo "$as_me: WARNING: usb.h: see the Autoconf documentation" >&2;}
-    { echo "$as_me:$LINENO: WARNING: usb.h:     section \"Present But Cannot Be Compiled\"" >&5
-echo "$as_me: WARNING: usb.h:     section \"Present But Cannot Be Compiled\"" >&2;}
-    { echo "$as_me:$LINENO: WARNING: usb.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: usb.h: proceeding with the preprocessor's result" >&2;}
-    { echo "$as_me:$LINENO: WARNING: usb.h: in the future, the compiler will take precedence" >&5
-echo "$as_me: WARNING: usb.h: in the future, the compiler will take precedence" >&2;}
-
-    ;;
-esac
-{ echo "$as_me:$LINENO: checking for usb.h" >&5
-echo $ECHO_N "checking for usb.h... $ECHO_C" >&6; }
-if test "${ac_cv_header_usb_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_cv_header_usb_h=$ac_header_preproc
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_header_usb_h" >&5
-echo "${ECHO_T}$ac_cv_header_usb_h" >&6; }
-
-fi
-if test $ac_cv_header_usb_h = yes; then
-  cat >>confdefs.h <<\_ACEOF
-#define HAVE_USB_H 1
+if test "x$PKGCONFIG" != x; then
+	if test x$enable_libusb = xyes -o $uname != Darwin; then
+		{ echo "$as_me:$LINENO: checking for libusb-1.0" >&5
+echo $ECHO_N "checking for libusb-1.0... $ECHO_C" >&6; }
+		if $PKGCONFIG --exists libusb-1.0; then
+			{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+			cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBUSB 1
 _ACEOF
 
-			LIBUSB="-lusb"
-fi
-
-
-fi
-
+			CFLAGS="$CFLAGS `$PKGCONFIG --cflags libusb-1.0`"
+			LIBUSB="`$PKGCONFIG --libs libusb-1.0`"
+		else
+			{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+		fi
+	fi
+elif test x$enable_libusb = xyes; then
+	{ { echo "$as_me:$LINENO: error: Need pkg-config to enable libusb support." >&5
+echo "$as_me: error: Need pkg-config to enable libusb support." >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 # Check whether --enable-tcp_wrappers was given.
@@ -13617,6 +13473,7 @@ else
 echo "$as_me: JPEG support disabled with --disable-jpeg." >&6;}
 fi
 
+INSTALL_GZIP=""
 if test "${ac_cv_header_zlib_h+set}" = set; then
   { echo "$as_me:$LINENO: checking for zlib.h" >&5
 echo $ECHO_N "checking for zlib.h... $ECHO_C" >&6; }
@@ -13811,9 +13668,13 @@ _ACEOF
 
 	LIBZ="-lz"
 	LIBS="$LIBS -lz"
+	if test "x$GZIP" != x; then
+		INSTALL_GZIP="-z"
+	fi
 fi
 
 fi
+
 
 
 
@@ -23665,6 +23526,7 @@ ac_ct_CXX!$ac_ct_CXX$ac_delim
 RANLIB!$RANLIB$ac_delim
 AR!$AR$ac_delim
 CHMOD!$CHMOD$ac_delim
+GZIP!$GZIP$ac_delim
 HTMLDOC!$HTMLDOC$ac_delim
 LD!$LD$ac_delim
 LN!$LN$ac_delim
@@ -23706,7 +23568,6 @@ XINETD!$XINETD$ac_delim
 CUPS_CACHEDIR!$CUPS_CACHEDIR$ac_delim
 CUPS_DATADIR!$CUPS_DATADIR$ac_delim
 ICONDIR!$ICONDIR$ac_delim
-MENUDIR!$MENUDIR$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -23748,6 +23609,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+MENUDIR!$MENUDIR$ac_delim
 CUPS_DOCROOT!$CUPS_DOCROOT$ac_delim
 CUPS_FONTPATH!$CUPS_FONTPATH$ac_delim
 CUPS_LOCALEDIR!$CUPS_LOCALEDIR$ac_delim
@@ -23813,6 +23675,7 @@ LIBJPEG!$LIBJPEG$ac_delim
 LIBPNG!$LIBPNG$ac_delim
 LIBTIFF!$LIBTIFF$ac_delim
 LIBZ!$LIBZ$ac_delim
+INSTALL_GZIP!$INSTALL_GZIP$ac_delim
 EXPORT_LIBJPEG!$EXPORT_LIBJPEG$ac_delim
 EXPORT_LIBPNG!$EXPORT_LIBPNG$ac_delim
 EXPORT_LIBTIFF!$EXPORT_LIBTIFF$ac_delim
@@ -23843,8 +23706,6 @@ LAUNCHDLIBS!$LAUNCHDLIBS$ac_delim
 LANGUAGES!$LANGUAGES$ac_delim
 CUPS_BUNDLEDIR!$CUPS_BUNDLEDIR$ac_delim
 CUPS_CONFIG_FILE_PERM!$CUPS_CONFIG_FILE_PERM$ac_delim
-CUPS_LOG_FILE_PERM!$CUPS_LOG_FILE_PERM$ac_delim
-CUPS_FATAL_ERRORS!$CUPS_FATAL_ERRORS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -23886,6 +23747,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+CUPS_LOG_FILE_PERM!$CUPS_LOG_FILE_PERM$ac_delim
+CUPS_FATAL_ERRORS!$CUPS_FATAL_ERRORS$ac_delim
 CUPS_LOG_LEVEL!$CUPS_LOG_LEVEL$ac_delim
 CUPS_ACCESS_LOG_LEVEL!$CUPS_ACCESS_LOG_LEVEL$ac_delim
 CUPS_BROWSING!$CUPS_BROWSING$ac_delim
@@ -23928,7 +23791,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 40; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 42; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
