10.5.2

diff --git a/cups/cups/configure b/cups/cups/configure
--- a/cups/cups/configure
+++ b/cups/cups/configure
@@ -1944,7 +1944,7 @@ esac
 ac_config_headers="$ac_config_headers config.h"
 
 
-CUPS_VERSION="1.3.3"
+CUPS_VERSION="1.3.5"
 CUPS_REVISION=""
 #if test -z "$CUPS_REVISION" -a -d .svn; then
 #	CUPS_REVISION="-r`svnversion . | awk -F: '{print $NF}' | sed -e '1,$s/[[a-zA-Z]]*//g'`"
@@ -13152,14 +13152,93 @@ fi
 
 
 	if test "x$KRB5CONFIG" != x; then
-		if test "x$uname" = "xDarwin"; then
-			# Mac OS X weak-links to the Kerberos framework...
-			LIBGSSAPI="-weak_framework Kerberos"
-		else
-			CFLAGS="`$KRB5CONFIG --cflags gssapi` $CFLAGS"
-			CPPFLAGS="`$KRB5CONFIG --cflags gssapi` $CPPFLAGS"
-			LIBGSSAPI="`$KRB5CONFIG --libs gssapi`"
-		fi
+		case "$uname" in
+			Darwin)
+				# Mac OS X weak-links to the Kerberos framework...
+				LIBGSSAPI="-weak_framework Kerberos"
+				;;
+			SunOS*)
+				# Solaris has a non-standard krb5-config, don't use it!
+				{ echo "$as_me:$LINENO: checking for gss_display_status in -lgss" >&5
+echo $ECHO_N "checking for gss_display_status in -lgss... $ECHO_C" >&6; }
+if test "${ac_cv_lib_gss_gss_display_status+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgss  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char gss_display_status ();
+int
+main ()
+{
+return gss_display_status ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_gss_gss_display_status=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_gss_gss_display_status=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_gss_gss_display_status" >&5
+echo "${ECHO_T}$ac_cv_lib_gss_gss_display_status" >&6; }
+if test $ac_cv_lib_gss_gss_display_status = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_GSSAPI 1
+_ACEOF
+
+					CFLAGS="`$KRB5CONFIG --cflags` $CFLAGS"
+					CPPFLAGS="`$KRB5CONFIG --cflags` $CPPFLAGS"
+					LIBGSSAPI="-lgss `$KRB5CONFIG --libs`"
+fi
+
+				;;
+			*)
+				# Other platforms just ask for GSSAPI
+				CFLAGS="`$KRB5CONFIG --cflags gssapi` $CFLAGS"
+				CPPFLAGS="`$KRB5CONFIG --cflags gssapi` $CPPFLAGS"
+				LIBGSSAPI="`$KRB5CONFIG --libs gssapi`"
+				;;
+		esac
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_GSSAPI 1
