10.6.3

diff --git a/cups/cups/configure b/cups/cups/configure
--- a/cups/cups/configure
+++ b/cups/cups/configure
@@ -1985,7 +1985,7 @@ esac
 ac_config_headers="$ac_config_headers config.h"
 
 
-CUPS_VERSION="1.4.2"
+CUPS_VERSION="1.4.3"
 CUPS_REVISION=""
 #if test -z "$CUPS_REVISION" -a -d .svn; then
 #	CUPS_REVISION="-r`svnversion . | awk -F: '{print $NF}' | sed -e '1,$s/[[a-zA-Z]]*//g'`"
@@ -6663,7 +6663,7 @@ fi
 
 
 
-for ac_func in random mrand48 lrand48
+for ac_func in random lrand48 arc4random
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 { echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -8005,6 +8005,8 @@ _ACEOF
 
 			CFLAGS="$CFLAGS `$PKGCONFIG --cflags dbus-1` -DDBUS_API_SUBJECT_TO_CHANGE"
 			CUPSDLIBS="$CUPSDLIBS `$PKGCONFIG --libs dbus-1`"
+			DBUS_NOTIFIER="dbus"
+			DBUS_NOTIFIERLIBS="`$PKGCONFIG --libs dbus-1`"
 			{ echo "$as_me:$LINENO: checking for dbus_message_iter_init_append in -ldbus-1" >&5
 echo $ECHO_N "checking for dbus_message_iter_init_append in -ldbus-1... $ECHO_C" >&6; }
 if test "${ac_cv_lib_dbus_1_dbus_message_iter_init_append+set}" = set; then
@@ -19521,6 +19523,12 @@ echo "${ECHO_T}no password file" >&6; }
 fi
 
 
+if test "x$CUPS_USER" = "xroot" -o "x$CUPS_USER" = "x0"; then
+	{ { echo "$as_me:$LINENO: error: The default user for CUPS cannot be root!" >&5
+echo "$as_me: error: The default user for CUPS cannot be root!" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 
 # Check whether --with-cups_group was given.
 if test "${with_cups_group+set}" = set; then
@@ -19560,6 +19568,12 @@ echo "${ECHO_T}no group file" >&6; }
 	fi
 fi
 
+
+if test "x$CUPS_GROUP" = "xroot" -o "x$CUPS_GROUP" = "xwheel" -o "x$CUPS_GROUP" = "x0"; then
+	{ { echo "$as_me:$LINENO: error: The default group for CUPS cannot be root!" >&5
+echo "$as_me: error: The default group for CUPS cannot be root!" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 
 # Check whether --with-system_groups was given.
@@ -19601,8 +19615,15 @@ echo "${ECHO_T}no group file" >&6; }
 fi
 
 
-
 CUPS_PRIMARY_SYSTEM_GROUP="`echo $CUPS_SYSTEM_GROUPS | awk '{print $1}'`"
+
+for group in $CUPS_SYSTEM_GROUPS; do
+	if test "x$CUPS_GROUP" = "x$group"; then
+		{ { echo "$as_me:$LINENO: error: The default system groups cannot contain the default CUPS group!" >&5
+echo "$as_me: error: The default system groups cannot contain the default CUPS group!" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+done
 
 
 
diff --git a/libiconv/libiconv/tests/check-stateless b/libiconv/libiconv/tests/check-stateless
--- a/libiconv/libiconv/tests/check-stateless
+++ b/libiconv/libiconv/tests/check-stateless
@@ -15,7 +15,7 @@ charsetf=`echo "$charset" | sed -e 's,:,-,g'`
 ./table-to "$charset" | sort > tmp-"$charsetf".INVERSE.TXT
 
 # Check 1: charmap and iconv forward should be identical.
-cmp "${srcdir}"/"$charsetf".TXT tmp-"$charsetf".TXT 2> /dev/null
+cmp "${srcdir}"/"$charsetf".TXT tmp-"$charsetf".TXT 2> /dev/null && echo '[PASS]' $charset 1 || echo '[FAIL]' $charset 1
 
 # Check 2: the difference between the charmap and iconv backward.
 sed -e '/	.* 0x/d' < "${srcdir}"/"$charsetf".TXT > tmp-noprecomposed-"$charsetf".TXT
@@ -24,7 +24,7 @@ if test -f "${srcdir}"/"$charsetf".IRREVERSIBLE.TXT; then
 else
   cp tmp-noprecomposed-"$charsetf".TXT tmp-orig-"$charsetf".INVERSE.TXT
 fi
-cmp tmp-orig-"$charsetf".INVERSE.TXT tmp-"$charsetf".INVERSE.TXT 2> /dev/null
+cmp tmp-orig-"$charsetf".INVERSE.TXT tmp-"$charsetf".INVERSE.TXT 2> /dev/null && echo '[PASS]' $charset 2 || echo '[FAIL]' $charset 2
 
 rm -f tmp-"$charsetf".TXT tmp-"$charsetf".INVERSE.TXT tmp-noprecomposed-"$charsetf".TXT tmp-orig-"$charsetf".INVERSE.TXT
 exit 0
diff --git a/libiconv/libiconv/tests/check-subst b/libiconv/libiconv/tests/check-subst
--- a/libiconv/libiconv/tests/check-subst
+++ b/libiconv/libiconv/tests/check-subst
@@ -15,7 +15,7 @@ $iconv $options_ascii -f ASCII -t ASCII < tmp-in > tmp-out
 cat > tmp-ok <<\EOF
 B<0xc3><0xb6>se B<0xc3><0xbc>bchen
 EOF
-cmp tmp-out tmp-ok
+cmp tmp-out tmp-ok && echo '[PASS]' $(basename $0) 1 || echo '[FAIL]' $(basename $0) 1
 
 # Test of --byte-subst with a non-ASCII substitution.
 
@@ -27,7 +27,7 @@ EOF
   cat > tmp-ok <<\EOF
 B«0xc3»«0xb6»se B«0xc3»«0xbc»bchen
 EOF
-  cmp tmp-out tmp-ok
+  cmp tmp-out tmp-ok && echo '[PASS]' $(basename $0) 2 || echo '[FAIL]' $(basename $0) 2
 fi
 
 if test "`(locale charmap) 2>/dev/null`" = UTF-8; then
@@ -39,7 +39,7 @@ EOF
   cat > tmp-ok <<\EOF
 B«0xc3»«0xb6»se B«0xc3»«0xbc»bchen
 EOF
-  cmp tmp-out2 tmp-ok
+  cmp tmp-out2 tmp-ok  && echo '[PASS]' $(basename $0) 3 || echo '[FAIL]' $(basename $0) 3
 fi
 
 # Test of --byte-subst with a very long substitution.
@@ -49,7 +49,7 @@ Böse Bübchen
 EOF
 $iconv --byte-subst='<0x%010000x>' -f ASCII -t ASCII < tmp-in > tmp-out
 printf 'B<0x%010000x><0x%010000x>se B<0x%010000x><0x%010000x>bchen\n' 0xC3 0xB6 0xC3 0xBC > tmp-ok
-cmp tmp-out tmp-ok
+cmp tmp-out tmp-ok && echo '[PASS]' $(basename $0) 4 || echo '[FAIL]' $(basename $0) 4
 
 # Test of --unicode-subst with an ASCII substitution.
 
@@ -60,7 +60,7 @@ $iconv $options_ascii -f UTF-8 -t ASCII < tmp-in > tmp-out
 cat > tmp-ok <<\EOF
 B<U+00F6>se B<U+00FC>bchen
 EOF
-cmp tmp-out tmp-ok
+cmp tmp-out tmp-ok && echo '[PASS]' $(basename $0) 5 || echo '[FAIL]' $(basename $0) 5
 
 cat > tmp-in <<\EOF
 Russian (Русский)
@@ -69,7 +69,7 @@ $iconv $options_ascii -f UTF-8 -t ISO-8859-1 2>/dev/null < tmp-in | $iconv -f IS
 cat > tmp-ok <<\EOF
 Russian (<U+0420><U+0443><U+0441><U+0441><U+043A><U+0438><U+0439>)
 EOF
-cmp tmp-out tmp-ok
+cmp tmp-out tmp-ok && echo '[PASS]' $(basename $0) 6 || echo '[FAIL]' $(basename $0) 6
 
 # Test of --unicode-subst with a non-ASCII substitution.
 
@@ -82,7 +82,7 @@ EOF
   cat > tmp-ok <<\EOF
 Russian («U+0420»«U+0443»«U+0441»«U+0441»«U+043A»«U+0438»«U+0439»)
 EOF
-  cmp tmp-out2 tmp-ok
+  cmp tmp-out2 tmp-ok && echo '[PASS]' $(basename $0) 7 || echo '[FAIL]' $(basename $0) 7
 fi
 
 # Test of --unicode-subst with a very long substitution.
@@ -92,14 +92,14 @@ Böse Bübchen
 EOF
 $iconv --unicode-subst='<U+%010000X>' -f UTF-8 -t ASCII < tmp-in > tmp-out
 printf 'B<U+%010000X>se B<U+%010000X>bchen\n' 0x00F6 0x00FC > tmp-ok
-cmp tmp-out tmp-ok
+cmp tmp-out tmp-ok && echo '[PASS]' $(basename $0) 8 || echo '[FAIL]' $(basename $0) 8
 
 cat > tmp-in <<\EOF
 Böse Bübchen
 EOF
 $iconv --byte-subst='<0x%010000x>' -f ASCII -t ASCII < tmp-in > tmp-out
 printf 'B<0x%010000x><0x%010000x>se B<0x%010000x><0x%010000x>bchen\n' 0xC3 0xB6 0xC3 0xBC > tmp-ok
-cmp tmp-out tmp-ok
+cmp tmp-out tmp-ok && echo '[PASS]' $(basename $0) 9 || echo '[FAIL]' $(basename $0) 9
 
 # Test of --widechar-subst:
 # wcrtomb() doesn't exist on FreeBSD 4.0 and is broken on MacOS X 10.3.
@@ -115,15 +115,15 @@ EOF
   cat > tmp-ok <<\EOF
 Russian (<00000420><00000443><00000441><00000441><0000043a><00000438><00000439>)
 EOF
-  cmp tmp-out1 tmp-ok
-  cmp tmp-out2 tmp-ok
+  cmp tmp-out1 tmp-ok && echo '[PASS]' $(basename $0) 10 || echo '[FAIL]' $(basename $0) 10
+  cmp tmp-out2 tmp-ok && echo '[PASS]' $(basename $0) 11 || echo '[FAIL]' $(basename $0) 11
   if test "`(LC_ALL=de_DE.ISO-8859-1 locale charmap) 2>/dev/null`" = ISO-8859-1; then
     options_latin1=`echo " $options_utf8" | $iconv -f UTF-8 -t ISO-8859-1`
     LC_ALL=de_DE.ISO-8859-1 $iconv $options_latin1 -f wchar_t -t UTF-8 < tmp-inw > tmp-out1
     cat > tmp-ok <<\EOF
 Russian («00000420»«00000443»«00000441»«00000441»«0000043a»«00000438»«00000439»)
 EOF
-    cmp tmp-out1 tmp-ok
+    cmp tmp-out1 tmp-ok && echo '[PASS]' $(basename $0) 12 || echo '[FAIL]' $(basename $0) 12
   fi
 fi
 
diff --git a/ruby/ruby/configure b/ruby/ruby/configure
--- a/ruby/ruby/configure
+++ b/ruby/ruby/configure
@@ -10293,7 +10293,7 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        }; then
 
-		    test "x$target_cpu" = xppc && ac_cv_header_ucontext_h=no
+		    test "x$target_cpu" = xpowerpc && ac_cv_header_ucontext_h=no
 
 else
   echo "$as_me: failed program was:" >&5
@@ -10772,6 +10772,77 @@ _ACEOF
 
 fi
 	# Dynamic linking for HP-UX
+
+{ echo "$as_me:$LINENO: checking for clock_gettime in -lrt" >&5
+echo $ECHO_N "checking for clock_gettime in -lrt... $ECHO_C" >&6; }
+if test "${ac_cv_lib_rt_clock_gettime+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lrt  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char clock_gettime ();
+int
+main ()
+{
+return clock_gettime ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_rt_clock_gettime=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_rt_clock_gettime=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_rt_clock_gettime" >&5
+echo "${ECHO_T}$ac_cv_lib_rt_clock_gettime" >&6; }
+if test $ac_cv_lib_rt_clock_gettime = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBRT 1
+_ACEOF
+
+  LIBS="-lrt $LIBS"
+
+fi
+	# GNU/Linux
 
 case "$target_cpu" in
 alpha*)		case "$target_os"::"$GCC" in
@@ -13222,11 +13293,11 @@ done
 # Debian GNU/Linux Lenny's libc6.1 2.7-10 has no problem.
 { echo "$as_me:$LINENO: checking for broken erfc of glibc-2.3.6 on IA64" >&5
 echo $ECHO_N "checking for broken erfc of glibc-2.3.6 on IA64... $ECHO_C" >&6; }
-if test "${rb_broken_glibc_ia64_erfc+set}" = set; then
+if test "${rb_cv_broken_glibc_ia64_erfc+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   if test "$cross_compiling" = yes; then
-  rb_broken_glibc_ia64_erfc=no
+  rb_cv_broken_glibc_ia64_erfc=no
 else
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -13264,23 +13335,23 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  rb_broken_glibc_ia64_erfc=no
+  rb_cv_broken_glibc_ia64_erfc=no
 else
   echo "$as_me: program exited with status $ac_status" >&5
 echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
 ( exit $ac_status )
-rb_broken_glibc_ia64_erfc=yes
+rb_cv_broken_glibc_ia64_erfc=yes
 fi
 rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 
 
 fi
-{ echo "$as_me:$LINENO: result: $rb_broken_glibc_ia64_erfc" >&5
-echo "${ECHO_T}$rb_broken_glibc_ia64_erfc" >&6; }
-case $rb_broken_glibc_ia64_erfc in
+{ echo "$as_me:$LINENO: result: $rb_cv_broken_glibc_ia64_erfc" >&5
+echo "${ECHO_T}$rb_cv_broken_glibc_ia64_erfc" >&6; }
+case $rb_cv_broken_glibc_ia64_erfc in
   yes) ac_cv_func_erf=no;;
 esac
 
