10.4.8

diff --git a/OpenSSH/openssh/contrib/cygwin/ssh-host-config b/OpenSSH/openssh/contrib/cygwin/ssh-host-config
--- a/OpenSSH/openssh/contrib/cygwin/ssh-host-config
+++ b/OpenSSH/openssh/contrib/cygwin/ssh-host-config
@@ -449,12 +449,10 @@ then
 	  echo "Should this script create a new local account 'sshd_server' which has"
 	  if request "the required privileges?"
 	  then
-	    _admingroup=`awk -F: '{if ( $2 == "S-1-5-32-544" ) print $1;}' ${SYSCONFDIR}/group`
+	    _admingroup=`mkgroup -l | awk -F: '{if ( $2 == "S-1-5-32-544" ) print $1;}' `
 	    if [ -z "${_admingroup}" ]
 	    then
-	      echo "There's no group with SID S-1-5-32-544 (Local administrators group) in"
-	      echo "your ${SYSCONFDIR}/group file.  Please regenerate this entry using 'mkgroup -l'"
-	      echo "and restart this script."
+	      echo "mkgroup -l produces no group with SID S-1-5-32-544 (Local administrators group)."
 	      exit 1
 	    fi
 	    dos_var_empty=`cygpath -w ${LOCALSTATEDIR}/empty`
@@ -584,6 +582,16 @@ then
       then
 	chown "${_user}".544 ${LOCALSTATEDIR}/log/sshd.log
       fi
+    fi
+    if ! ( mount | egrep -q 'on /(|usr/(bin|lib)) type system' )
+    then
+      echo
+      echo "Warning: It appears that you have user mode mounts (\"Just me\""
+      echo "chosen during install.)  Any daemons installed as services will"
+      echo "fail to function unless system mounts are used.  To change this,"
+      echo "re-run setup.exe and choose \"All users\"."
+      echo
+      echo "For more information, see http://cygwin.com/faq/faq0.html#TOC33"
     fi
   fi
 fi
diff --git a/fetchmail/Makefile b/fetchmail/Makefile
--- a/fetchmail/Makefile
+++ b/fetchmail/Makefile
@@ -1,27 +1,48 @@
-##
-# Makefile for fetchmail
-##
-
-# Project info
-Project  = fetchmail
-UserType = Administration
-ToolType = Services
-Extra_Configure_Flags = --disable-nls --enable-inet6 --with-ssl \
+Project               = fetchmail
+UserType              = Administration
+ToolType              = Services
+GnuAfterInstall       = post-install install-plist
+Extra_Configure_Flags = --disable-nls --with-ssl \
                        --with-kerberos5=/usr --with-kerberos=/usr \
                        --with-gssapi=/usr/include
-GnuAfterInstall = strip remove-fetchmailconf
-Extra_CC_Flags = -DBIND_8_COMPAT -mdynamic-no-pic
+Extra_CC_Flags = -mdynamic-no-pic
 
-# It's a GNU Source project
 include $(MAKEFILEPATH)/CoreOS/ReleaseControl/GNUSource.make
-Install_Target = install
 
-strip::
-	$(STRIP) $(DSTROOT)/usr/bin/fetchmail
-	chgrp mail $(DSTROOT)/usr/bin/fetchmail
-	chmod g+s $(DSTROOT)/usr/bin/fetchmail
+Install_Target  = install
+Install_Flags   = DESTDIR=$(DSTROOT)
 
-# fetchmailconf is a python script, and we don't have python.
-remove-fetchmailconf:
-	$(RM) $(DSTROOT)/usr/bin/fetchmailconf
+# Post-install cleanup
+post-install:
+	@for binary in fetchmail; do \
+		$(CP) $(DSTROOT)/usr/bin/$${binary} $(SYMROOT); \
+		$(STRIP) -x $(DSTROOT)/usr/bin/$${binary}; \
+	done
 	$(RM) $(DSTROOT)/usr/share/man/man1/fetchmailconf.1
+	$(LN) -s $(DSTROOT)/usr/share/man/man1/fetchmail.1.gz $(DSTROOT)/usr/share/man/man1/fetchmailconf.1.gz
+
+# Automatic Extract & Patch
+AEP_Project    = fetchmail
+AEP_Version    = 6.3.4
+AEP_ProjVers   = $(AEP_Project)-$(AEP_Version)
+AEP_Filename   = $(AEP_ProjVers).tar.bz2
+AEP_ExtractDir = $(AEP_ProjVers)
+AEP_Patches    = python_config_patch
+
+# Extract the source.
+install_source::
+	$(TAR) -C $(SRCROOT) -jxf $(SRCROOT)/$(AEP_Filename)
+	$(RMDIR) $(SRCROOT)/$(Project)
+	$(MV) $(SRCROOT)/$(AEP_ExtractDir) $(SRCROOT)/$(Project)
+	for patchfile in $(AEP_Patches); do \
+		(cd $(SRCROOT)/$(Project) && patch -p0 < $(SRCROOT)/files/$$patchfile) || exit 1; \
+	done
+
+OSV = $(DSTROOT)/usr/local/OpenSourceVersions
+OSL = $(DSTROOT)/usr/local/OpenSourceLicenses
+
+install-plist:
+	$(MKDIR) $(OSV)
+	$(INSTALL_FILE) $(SRCROOT)/$(Project).plist $(OSV)/$(Project).plist
+	$(MKDIR) $(OSL)
+	$(INSTALL_FILE) $(Sources)/COPYING $(OSL)/$(Project).txt
