10.1.5

diff --git a/sendmail/sendmail/devtools/bin/Build b/sendmail/sendmail/devtools/bin/Build
--- a/sendmail/sendmail/devtools/bin/Build
+++ b/sendmail/sendmail/devtools/bin/Build
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright (c) 1998-2000 Sendmail, Inc. and its suppliers.
+# Copyright (c) 1998-2002 Sendmail, Inc. and its suppliers.
 #	All rights reserved.
 # Copyright (c) 1993, 1996-1997 Eric P. Allman.  All rights reserved.
 # Copyright (c) 1993
@@ -11,7 +11,7 @@
 # the sendmail distribution.
 #
 #
-#       $Id: Build,v 1.1.1.1 2000/06/10 00:40:46 wsanchez Exp $
+#	$Id: Build,v 1.1.1.2 2002/03/12 18:00:11 zarzycki Exp $
 #
 
 #
@@ -61,6 +61,29 @@ while [ ! -z "$1" ]
 do
 	case $1
 	in
+	  -src)	# Specify pathname of source directory relative to
+		# root of cvs tree.  This relative pathname may have
+		# multiple components, as in 'foo/bar/baz', and will also
+		# be used to form the pathname of the object directory.
+		shift
+		arg=$1
+		if [ -z "$arg" ]
+		then
+			echo "Missing arg for -src" >&2
+			exit $EX_USAGE
+		fi
+		case $arg
+		in
+		  /*)	echo "Arg for -src must not begin with / ($arg)" >&2
+			exit $EX_USAGE
+			;;
+		esac
+		src_dir="$arg"
+		absolute_base_dir=`echo ${full_src_dir} | sed "s;/${src_dir}$;;"`
+		obj_rel_base_dir=`echo x/${src_dir} | sed "s;[^/][^/]*;..;g"`
+		SMROOT=${absolute_base_dir}
+		shift
+		;;
 	  -c)	# clean out existing $obj tree
 		cflag=1
 		SENDMAIL_BUILD_FLAGS="$SENDMAIL_BUILD_FLAGS $1"
@@ -86,8 +109,8 @@ do
 		arg=`echo $1 | sed 's/^-E//'`
 		if [ -z "$arg" ]
 		then
-		    shift   # move to argument
-		    arg=$1
+			shift   # move to argument
+			arg=$1
 		fi
 		if [ -z "$arg" ]
 		then
@@ -126,8 +149,8 @@ do
 		arg=`echo $1 | sed 's/^-f//'`
 		if [ -z "$arg" ]
 		then
-		    shift   # move to argument
-		    arg=$1
+			shift   # move to argument
+			arg=$1
 		fi
 		if [ "$pfx" ]
 		then
@@ -167,8 +190,8 @@ do
 		arg="`echo $1 | sed 's/^-O//'`"
 		if [ -z "$arg" ]
 		then
-		    shift   # move to argument
-		    arg="$1"
+			shift   # move to argument
+			arg="$1"
 		fi
 		case $arg
 		in
@@ -195,8 +218,8 @@ do
 		arg=`echo $1 | sed 's/^-Q//'`
 		if [ -z "$arg" ]
 		then
-		    shift   # move to argument
-		    arg=$1
+			shift   # move to argument
+			arg=$1
 		fi
 		if [ -z "$arg" ]
 		then
@@ -221,17 +244,17 @@ do
 		shift
 		build_variant=$1
 		if [ -z "$build_variant" ]
-		then 
-		    echo "Usage error with \"-v\" <build_variant>"  >&2
-		    echo "You must specify exactly one build variant of debug|optimized|purify"  >&2
-		    exit $EX_USAGE
+		then
+			echo "Usage error with \"-v\" <build_variant>"  >&2
+			echo "You must specify exactly one build variant of debug|optimized|purify"  >&2
+			exit $EX_USAGE
 		fi
 		shift
 		;;
 
 	  *)	# pass argument to make
 		makeargs="$makeargs \"$1\""
-		SENDMAIL_BUILD_FLAGS="$SENDMAIL_BUILD_FLAGS \"$1\""
+		#SENDMAIL_BUILD_FLAGS="$SENDMAIL_BUILD_FLAGS \"$1\""
 		shift
 		;;
 	esac
@@ -239,20 +262,20 @@ done
 
 # process selected build variant.
 case $build_variant in
-    debug)
-	M4_BLDVARIANT_FLAGS="-DconfBLDVARIANT=DEBUG"
-	;;
-    optimized)
-	M4_BLDVARIANT_FLAGS="-DconfBLDVARIANT=OPTIMIZED"
-	;;
-    purify)
-	M4_BLDVARIANT_FLAGS="-DconfBLDVARIANT=PURIFY"
-	echo "Sorry, the purify build variant has not been plumbed yet. (Bummer.)"  >&2
-	exit $EX_USAGE
-	;;
-    *)
-	exit $EX_USAGE
-	;;
+	debug)
+		M4_BLDVARIANT_FLAGS="-DconfBLDVARIANT=DEBUG"
+		;;
+	optimized)
+		M4_BLDVARIANT_FLAGS="-DconfBLDVARIANT=OPTIMIZED"
+		;;
+	purify)
+		M4_BLDVARIANT_FLAGS="-DconfBLDVARIANT=PURIFY"
+		echo "Sorry, the purify build variant has not been plumbed yet. (Bummer.)"  >&2
+		exit $EX_USAGE
+		;;
+	*)
+		exit $EX_USAGE
+		;;
 esac
 
 
@@ -294,12 +317,6 @@ then
 	os=DomainOS
 	arch=$ISP
 	rel=`/usr/apollo/bin/bldt | grep Domain | awk '{ print $4 }' | sed -e 's/,//g'`
-elif [ `uname` = "CYGWIN_NT-4.0" -o `uname` = "CYGWIN_NT-5.0" ]
-then
-	# Windows NT 4.0 or Windows 2000
-	arch=`uname -m | sed -e 's/ //g' -e 's/\//-/g'`
-	os=`uname -s | sed -e 's/CYG//g' -e 's/ //g' -e 's/[_-]//g'`
-	rel=`uname -r | sed -e 's/(/_/g' -e 's/)//g' -e 's/ //g' -e 's/\//-/g'` 
 fi
 
 if [ ! "$arch" -a ! "$os" -a ! "$rel" ]
@@ -366,10 +383,26 @@ in
   DYNIX-ptx)	os=PTX;;
   Paragon*)	os=Paragon;;
   HP-UX)	rel=`echo $rel | sed -e 's/^[^.]*\.0*//'`;;
-  AIX)		rela=$rel
-		rel=`uname -v`
+  AIX)		osl=""
+		if [ -x /bin/lslpp ]
+		then
+			osl=`/bin/lslpp -Lcq bos.rte | cut -f3 -d: | cut -f1-3 -d. 2>/dev/null`
+			if [ $? = 0  -a -n "$osl" ]
+			then 
+				rel=$osl
+			else
+				# command failed; fall back to old method
+				osl=""
+			fi
+		fi
+		# check whether it worked
+		if [ -z "$osl" ]
+		then
+			rela=$rel
+			rel=`uname -v`
+			rel=$rel.$rela
+		fi
 		arch=PPC
-		rel=$rel.$rela
 		;;
   BSD-386)	os=BSD-OS;;
   SCO_SV)	os=SCO; rel=`uname -X | sed -n 's/Release = 3.2v//p'`;;
@@ -445,7 +478,7 @@ then
 	echo "Configuration: pfx=$pfx, os=$os, rel=$rel, rbase=$rbase, rroot=$rroot, arch=$arch, sfx=$sfx, variant=$build_variant"
 fi
 
-SMROOT=${SMROOT-..}
+SMROOT=${SMROOT-`(cd ..;pwd)`}
 BUILDTOOLS=${BUILDTOOLS-$SMROOT/devtools}
 export SMROOT BUILDTOOLS
 
@@ -477,34 +510,34 @@ fi
 
 # now try to find a reasonable object directory
 if [ -r ${OBJ_ROOT}/obj${prefix}.$os.$rel.$arch$sfx ]; then
-	obj=${OBJ_ROOT}/obj${prefix}.$os.$rel.$arch$sfx
+	abs_obj_dir=${OBJ_ROOT}/obj${prefix}.$os.$rel.$arch$sfx
 elif [ -r ${OBJ_ROOT}/obj${prefix}.$os.$rroot.$arch$sfx ]; then
-	obj=${OBJ_ROOT}/obj${prefix}.$os.$rroot.$arch$sfx
+	abs_obj_dir=${OBJ_ROOT}/obj${prefix}.$os.$rroot.$arch$sfx
 elif [ -r ${OBJ_ROOT}/obj${prefix}.$os.$rbase.x.$arch$sfx ]; then
-	obj=${OBJ_ROOT}/obj${prefix}.$os.$rbase.x.$arch$sfx
+	abs_obj_dir=${OBJ_ROOT}/obj${prefix}.$os.$rbase.x.$arch$sfx
 elif [ -r ${OBJ_ROOT}/obj${prefix}.$os.$rel$sfx ]; then
-	obj=${OBJ_ROOT}/obj${prefix}.$os.$rel$sfx
+	abs_obj_dir=${OBJ_ROOT}/obj${prefix}.$os.$rel$sfx
 elif [ -r ${OBJ_ROOT}/obj${prefix}.$os.$rbase.x$sfx ]; then
-	obj=${OBJ_ROOT}/obj${prefix}.$os.$rbase.x$sfx
+	abs_obj_dir=${OBJ_ROOT}/obj${prefix}.$os.$rbase.x$sfx
 elif [ -r ${OBJ_ROOT}/obj${prefix}.$os.$arch$sfx ]; then
-	obj=${OBJ_ROOT}/obj${prefix}.$os.$arch$sfx
+	abs_obj_dir=${OBJ_ROOT}/obj${prefix}.$os.$arch$sfx
 elif [ -r ${OBJ_ROOT}/obj${prefix}.$rel.$arch$sfx ]; then
-	obj=${OBJ_ROOT}/obj${prefix}.$rel.$arch$sfx
+	abs_obj_dir=${OBJ_ROOT}/obj${prefix}.$rel.$arch$sfx
 elif [ -r ${OBJ_ROOT}/obj${prefix}.$rbase.x.$arch$sfx ]; then
-	obj=${OBJ_ROOT}/obj${prefix}.$rbase.x.$arch$sfx
+	abs_obj_dir=${OBJ_ROOT}/obj${prefix}.$rbase.x.$arch$sfx
 elif [ -r ${OBJ_ROOT}/obj${prefix}.$os$sfx ]; then
-	obj=${OBJ_ROOT}/obj${prefix}.$os$sfx
+	abs_obj_dir=${OBJ_ROOT}/obj${prefix}.$os$sfx
 elif [ -r ${OBJ_ROOT}/obj${prefix}.$arch$sfx ]; then
-	obj=${OBJ_ROOT}/obj${prefix}.$arch$sfx
+	abs_obj_dir=${OBJ_ROOT}/obj${prefix}.$arch$sfx
 elif [ -r ${OBJ_ROOT}/obj${prefix}.$rel$sfx ]; then
-	obj=${OBJ_ROOT}/obj${prefix}.$rel$sfx
+	abs_obj_dir=${OBJ_ROOT}/obj${prefix}.$rel$sfx
 elif [ -r ${OBJ_ROOT}/obj${prefix}.$sfx ]; then
-	obj=${OBJ_ROOT}/obj${prefix}.$sfx
+	abs_obj_dir=${OBJ_ROOT}/obj${prefix}.$sfx
 fi
 
-if [ -n "$obj" ]
+if [ -n "$abs_obj_dir" ]
 then
-	obj=${obj}/${src_dir}
+	obj=${abs_obj_dir}/${src_dir}
 fi
 
 # Print the directory which would be used for the build and exit
@@ -550,7 +583,8 @@ fi
 # If we didn't detect an existing obj directory, makeup a new obj name.
 if [ -z "$obj" ]
 then
-	obj=${OBJ_ROOT}/obj${prefix}.$os.$rel.$arch$sfx/${src_dir}
+	abs_obj_dir=${OBJ_ROOT}/obj${prefix}.$os.$rel.$arch$sfx
+	obj=${abs_obj_dir}/${src_dir}
 fi
 
 # Check if obj directory exists
@@ -611,7 +645,7 @@ then
 	elif [ -r $BUILDTOOLS/OS/$rel$sfx ]; then
 		oscf=$rel$sfx
 	else
-		echo "Cannot determine how to support $arch.$os.$rel" >&2
+		echo "Cannot determine how to support $os.$rel.$arch" >&2
 		exit $EX_UNAVAILABLE
 	fi
 	M4=`sh $BUILDTOOLS/bin/find_m4.sh`
@@ -631,63 +665,48 @@ then
 	echo "Creating $obj using $BUILDTOOLS/OS/$oscf"
 	${mkdir} $obj
 
-	# If this is WINNT then compile with relative paths
-	# (based on REL_SRC_DIR), so we don't need to do any "linking"
-	if [ ! $os = "WINNT4.0" -a ! $os = "WINNT5.0" -a ! $os = "WINNT" ]
-	then
 		ln="ln -s"
-		(cd $obj; $ln ${obj_rel_base_dir}/${src_dir}/*.[ch13458] .)
 		(cd $obj
 		# This glob doesn't actually glob to something everywhere,
 		# thus the protective measures.
-		for i in ${obj_rel_base_dir}/${src_dir}/*.0 
-		do 
-			if [ -f $i ] 
-			then 
-				$ln $i `basename $i`.dist 
-			fi 
+		for i in ${obj_rel_base_dir}/${src_dir}/*.[ch13458]
+		do
+			if [ -f $i ]
+			then
+				$ln $i .
+			fi
+		done
+		# This glob doesn't actually glob to something everywhere,
+		# thus the protective measures.
+		for i in ${obj_rel_base_dir}/${src_dir}/*.0
+		do
+			if [ -f $i ]
+			then
+				$ln $i `basename $i`.dist
+			fi
 		done)
 		if [ -f helpfile ]
 		then
 			(cd $obj; $ln ${obj_rel_base_dir}/${src_dir}/helpfile .)
 		fi
-	fi
 
 	rm -f $obj/.settings$$
 	echo 'divert(-1)' > $obj/.settings$$
 	cat $BUILDTOOLS/M4/header.m4 >> $obj/.settings$$
+	echo "define(\`bldOS', \`\`$os'')" >> $obj/.settings$$
+	echo "define(\`bldREL', \`\`$rel'')" >> $obj/.settings$$
+	echo "define(\`bldARCH', \`\`$arch'')" >> $obj/.settings$$
 	cat $BUILDTOOLS/OS/$oscf >> $obj/.settings$$
 
-	if [ $os = "WINNT4.0" -o $os = "WINNT5.0" -o $os = "WINNT" ]
-	then
-		# Append C: onto pwd's which don't have the preceding //
-		# so that we can compile on non-network drives.
-		# (Is there a way to get the real drive letter?)
+	cur_dir=`pwd`
+	cd $obj/..
+	absolute_obj_dir=`pwd`
 
-		dir_prefix=`echo $absolute_base_dir | sed 's#\(..\).*#\1#'`
-		if [ ! $dir_prefix = "//" ]
-		then
-			absolute_base_dir="//C$absolute_base_dir"
-		fi
 
-	        # Convert sh's //X to X: drive letters to make make (and cl) happy
-		obj_rel_base_dir=`echo $absolute_base_dir | sed 's#^//\([a-zA-Z]\)#\1:#'`
-		cur_dir=`pwd`
-		cd $obj/..
-		absolute_obj_dir=`pwd | sed 's#/#\\\\\\\\#g'`
-		cd $cur_dir
-		echo "ifdef(\`bldABS_OBJ_DIR',,\`define(\`bldABS_OBJ_DIR', \`$absolute_obj_dir')')" >> $obj/.settings$$
-		rel_src_dir="$obj_rel_base_dir/$src_dir"
-		echo "define(\`bldREL_SRC_DIR', \`$rel_src_dir')" >> $obj/.settings$$
-	else
-		cur_dir=`pwd`
-		cd $obj/..
-		absolute_obj_dir=`pwd`
-		cd $cur_dir
-		echo "ifdef(\`bldABS_OBJ_DIR',,\`define(\`bldABS_OBJ_DIR', \`$absolute_obj_dir')')" >> $obj/.settings$$
-		rel_src_dir="$obj_rel_base_dir/$src_dir"
-		echo "define(\`bldREL_SRC_DIR', \`$rel_src_dir')" >> $obj/.settings$$
-	fi
+	cd $cur_dir
+	echo "ifdef(\`bldABS_OBJ_DIR',,\`define(\`bldABS_OBJ_DIR', \`$absolute_obj_dir')')" >> $obj/.settings$$
+	rel_src_dir="$obj_rel_base_dir/$src_dir"
+	echo "define(\`bldREL_SRC_DIR', \`$rel_src_dir')" >> $obj/.settings$$
 
 	if [ ! -z "$pfx" ]
 	then
