10.5

diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test000-rootdse b/OpenLDAP/OpenLDAP/tests/scripts/test000-rootdse
--- a/OpenLDAP/OpenLDAP/tests/scripts/test000-rootdse
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test000-rootdse
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test000-rootdse,v 1.14.2.4 2004/01/01 18:16:43 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test000-rootdse,v 1.22.2.5 2006/01/03 22:16:28 kurt Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2004 The OpenLDAP Foundation.
+## Copyright 1998-2006 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -16,7 +16,7 @@
 echo "running defines.sh"
 . $SRCDIR/scripts/defines.sh
 
-mkdir -p $TESTRUN $DBDIR1
+mkdir -p $TESTDIR $DBDIR1
 
 echo "Starting slapd on TCP/IP port $PORT1..."
 . $CONFFILTER $BACKEND $MONITORDB < $SCHEMACONF > $CONF1
@@ -28,9 +28,12 @@ if test $WAIT != 0 ; then
 fi
 KILLPIDS="$PID"
 
+sleep 1
+
 echo "Using ldapsearch to retrieve the root DSE..."
 for i in 0 1 2 3 4 5; do
-	$LDAPSEARCH -b "" -s base -h $LOCALHOST -p $PORT1 '+extensibleObject' > $SEARCHOUT 2>&1
+	$LDAPSEARCH -b "" -s base -h $LOCALHOST -p $PORT1 \
+		'+extensibleObject' > $SEARCHOUT 2>&1
 	RC=$?
 	if test $RC = 0 ; then
 		break
@@ -39,23 +42,42 @@ for i in 0 1 2 3 4 5; do
 	sleep 5
 done
 
-if test $RC = 0 -a $MONITORDB = yes ; then
-	echo "Using ldapsearch to retrieve the cn=Monitor..."
-	$LDAPSEARCH -b "cn=Monitor" -s base -h $LOCALHOST -p $PORT1 '+extensibleObject' >> $SEARCHOUT 2>&1
+if test $RC = 0 ; then
+	echo "Using ldapsearch to retrieve the cn=Subschema..."
+	$LDAPSEARCH -b "cn=Subschema" -s base -h $LOCALHOST -p $PORT1 \
+		'(&(objectClasses=top)(objectClasses=2.5.6.0))' cn objectClass \
+		>> $SEARCHOUT  2>&1
 	RC=$?
+
+fi
+
+count=2
+if test $RC = 0 ; then
+	case $MONITORDB in yes | mod)
+		count=3
+		echo "Using ldapsearch to retrieve the cn=Monitor..."
+		$LDAPSEARCH -b "cn=Monitor" -s base -h $LOCALHOST -p $PORT1 \
+			'+extensibleObject' >> $SEARCHOUT 2>&1
+		RC=$?
+		;;
+	esac
 fi
 
 test $KILLSERVERS != no && kill -HUP $KILLPIDS
 
 cat $SEARCHOUT
 
+
 if test $RC != 0 ; then
 	echo ">>>>> Test failed"
 else
-	if grep "TLS:" $SEARCHOUT; then
-		RC=-1
+	RC=`grep '^dn:' $SEARCHOUT | wc -l`
+	if test $RC != $count ; then
+		echo ">>>>> Test failed: expected $count entries, got" $RC
+		RC=1
 	else
-	    echo ">>>>> Test succeeded"
+		echo ">>>>> Test succeeded"
+		RC=0
 	fi
 fi
 
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test004-modify b/OpenLDAP/OpenLDAP/tests/scripts/test004-modify
--- a/OpenLDAP/OpenLDAP/tests/scripts/test004-modify
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test004-modify
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test004-modify,v 1.43.2.4 2004/01/01 18:16:43 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test004-modify,v 1.53.2.5 2006/01/03 22:16:28 kurt Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2004 The OpenLDAP Foundation.
+## Copyright 1998-2006 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -36,6 +36,8 @@ if test $WAIT != 0 ; then
 fi
 KILLPIDS="$PID"
 
+sleep 1
+
 echo "Testing slapd modify operations..."
 for i in 0 1 2 3 4 5; do
 	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT1 \
@@ -61,7 +63,7 @@ version: 1
 
 # LEADING COMMENT AND WHITE SPACE
 
-dn: cn=James A Jones 1,ou=Alumni Association,ou=People,o=University of Michigan,c=US
+dn: cn=James A Jones 1,ou=Alumni Association,ou=People,dc=example,dc=com
 # EMBEDDED COMMENT
 changetype: modify
 add: drink
@@ -79,7 +81,7 @@ sn: Jones
 add: sn
 sn: Jones
 
-dn: cn=Bjorn Jensen,ou=Information Technology Division,ou=People,o=University of Michigan,c=US
+dn: cn=Bjorn Jensen,ou=Information Technology Division,ou=People,dc=example,dc=com
 changetype: modify
 # EMBEDDED COMMENT
  CONTINUED
@@ -90,57 +92,82 @@ replace: drink
 drink: Iced Tea
 drink: Mad Dog 20/20
 
-dn: cn=ITD Staff,ou=Groups,o=University of Michigan,c=US
+dn: cn=ITD Staff,ou=Groups,dc=example,dc=com
 changetype: modify
 delete: uniquemember
 uniquemember: cn=James A Jones 2,ou=Information Technology Division,
- ou=People,o=University of Michigan,c=US
+ ou=People,dc=example,dc=com
 uniquemember: cn=Bjorn Jensen,ou=Information Technology Division,
- ou=People,o=University of Michigan,c=US
+ ou=People,dc=example,dc=com
 -
 add: uniquemember
 uniquemember: cn=Dorothy Stevens,ou=Alumni Association,
- ou=People,o=University of Michigan,c=US
+ ou=People,dc=example,dc=com
 uniquemember: cn=James A Jones 1,ou=Alumni Association,
- ou=People,o=University of Michigan,c=US
+ ou=People,dc=example,dc=com
+-
+add: objectClass
+objectClass: OpenLDAPdisplayableObject
+objectClass: pkiUser
+objectClass: userSecurityInformation
+-
+delete: objectClass
+objectClass: userSecurityInformation
+objectClass: pkiUser
+objectClass: OpenLDAPdisplayableObject
 
-dn: cn=All Staff,ou=Groups,o=University of Michigan,c=US
+dn: cn=All Staff,ou=Groups,dc=example,dc=com
 changetype: modify
 delete: member
 -
 add: member
-member: cn=Dorothy Stevens,ou=Alumni Association,ou=People,o=University of Michigan,c=US
+member: cn=Dorothy Stevens,ou=Alumni Association,ou=People,dc=example,dc=com
 -
 delete: description
+-
+add: objectClass
+objectClass: OpenLDAPdisplayableObject
+objectClass: pkiUser
+objectClass: userSecurityInformation
+-
+delete: objectClass
+objectClass: OpenLDAPdisplayableObject
+objectClass: pkiUser
+objectClass: userSecurityInformation
 
-dn: cn=Gern Jensen,ou=Information Technology Division,ou=People,o=University of Michigan,c=US
+dn: cn=Gern Jensen,ou=Information Technology Division,ou=People,dc=example,dc=com
 changetype: add
-objectclass: OpenLDAPperson
+objectclass: testPerson
 cn: Gern Jensen
 sn: Jensen
 uid: gjensen
 title: Chief Investigator, ITD
-postaladdress: ITD $ 535 W. William St $ Ann Arbor, MI 48103
-seealso: cn=All Staff,ou=Groups,o=University of Michigan,c=US
+postaladdress: ITD $ 535 W. William St $ Anytown, MI 48103
+seealso: cn=All Staff,ou=Groups,dc=example,dc=com
 drink: Coffee
-homepostaladdress: 844 Brown St. Apt. 4 $ Ann Arbor, MI 48104
+homepostaladdress: 844 Brown St. Apt. 4 $ Anytown, MI 48104
 description: Very odd
 facsimiletelephonenumber: +1 313 555 7557
 telephonenumber: +1 313 555 8343
 mail: gjensen@mailgw.example.com
 homephone: +1 313 555 8844
+testTime: 20050304001801.234Z
 
-dn: cn=James A Jones 2,ou=Information Technology Division,ou=People,o=University of Michigan,c=US
+dn: cn=James A Jones 2,ou=Information Technology Division,ou=People,dc=example,dc=com
 changetype: delete
 # TRAILING COMMENT AND WHITE SPACE
 
-dn: ou=People,o=University of Michigan,c=US
+dn: ou=People,dc=example,dc=com
 changetype: modify
 increment: uidNumber
 uidNumber: 1
 -
 increment: gidNumber
 gidNumber: -1
+
+dn: dc=example,dc=com
+changetype: modify
+# EMPTY SEQUENCE OF CHANGE
 
 EOMODS
 
@@ -150,6 +177,31 @@ if test $RC != 0 ; then
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
 fi
+
+echo "Using ldapmodify to add an empty entry (should fail with protocolError)..."
+$LDAPMODIFY -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD \
+	 >> $TESTOUT 2>&1 << EOMODS
+dn: cn=Foo Bar,dc=example,dc=com
+changetype: add
+# EMPTY SEQUENCE OF ATTRS
+EOMODS
+
+RC=$?
+case $RC in
+2)
+	echo "	ldapmodify failed ($RC)"
+	;;
+0)
+	echo "	ldapmodify should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit -1
+	;;
+*)
+	echo "	ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
 
 echo "Using ldapsearch to retrieve all the entries..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test005-modrdn b/OpenLDAP/OpenLDAP/tests/scripts/test005-modrdn
--- a/OpenLDAP/OpenLDAP/tests/scripts/test005-modrdn
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test005-modrdn
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test005-modrdn,v 1.35.2.4 2004/01/01 18:16:43 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test005-modrdn,v 1.41.2.6 2006/01/03 22:16:28 kurt Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2004 The OpenLDAP Foundation.
+## Copyright 1998-2006 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -36,6 +36,8 @@ if test $WAIT != 0 ; then
 fi
 KILLPIDS="$PID"
 
+sleep 1
+
 echo "Testing slapd modrdn operations..."
 
 # Make sure we can search the database
@@ -52,7 +54,7 @@ done
 
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
-	kill -HUP $PID
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
 fi
 
@@ -60,23 +62,23 @@ fi
 
 echo "Testing modrdn(deleteoldrdn=0)..."
 $LDAPMODRDN -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD > \
-	$TESTOUT 2>&1 'cn=James A Jones 1, ou=Alumni Association, ou=People, o=University of Michigan, c=US' 'cn=James A Jones III'
+	$TESTOUT 2>&1 'cn=James A Jones 1, ou=Alumni Association, ou=People, dc=example, dc=com' 'cn=James A Jones III'
 
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapmodrdn failed ($RC)!"
-	kill -HUP $PID
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
 fi
 
 echo "Testing modrdn(deleteoldrdn=1)..."
 $LDAPMODRDN -D "$MANAGERDN" -r -h $LOCALHOST -p $PORT1 -w $PASSWD >> \
-	$TESTOUT 2>&1 'cn=James A Jones 2, ou=Information Technology Division, ou=People, o=University of Michigan, c=US' 'cn=James A Jones II'
+	$TESTOUT 2>&1 'cn=James A Jones 2, ou=Information Technology Division, ou=People, dc=example, dc=com' 'cn=James A Jones II'
 
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapmodrdn failed ($RC)!"
-	kill -HUP $PID
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
 fi
 
@@ -179,10 +181,12 @@ if test $? != 0 ; then
 	exit 1
 fi
 
+# Test that you can use modrdn with an attribute value which was previously
+# present
 
 echo "Testing modrdn(deleteoldrdn=1), modrdn with new rdn already an att val..."
 $LDAPMODRDN -D "$MANAGERDN" -r -h $LOCALHOST -p $PORT1 -w $PASSWD > \
-	/dev/null 2>&1 'cn=James A Jones III, ou=Alumni Association, ou=People, o=University of Michigan, c=US' 'cn=James A Jones 1'
+	/dev/null 2>&1 'cn=James A Jones III, ou=Alumni Association, ou=People, dc=example, dc=com' 'cn=James A Jones 1'
 
 RC=$?
 if test $RC != 0 ; then
@@ -191,18 +195,14 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-# Test that you can use modrdn with an attribute value which was previously
-# present
-
 echo "Using ldapsearch to retrieve entries using new rdn (cn=James A Jones 1)..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
 	    'cn=James A Jones 1' > $SEARCHOUT 2>&1
 RC=$?
 
-test $KILLSERVERS != no && kill -HUP $KILLPIDS
-
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
 fi
 
@@ -217,8 +217,23 @@ $CMP $SEARCHFLT $LDIFFLT > $CMPOUT
 
 if test $? != 0 ; then
 	echo "comparison failed - modrdn operations did not complete correctly"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit 1
 fi
+
+echo "Testing modrdn with newSuperior as child of target "
+$LDAPMODRDN -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD > \
+	$TESTOUT 2>&1  -s 'cn=Sub1, ou=FooBar, cn=James A Jones 1, ou=Alumni Association, ou=People, dc=example, dc=com' \
+	'cn=James A Jones 1, ou=Alumni Association, ou=People, dc=example, dc=com' 'cn=James A Jones 1'
+
+RC=$?
+if test $RC -eq 0 ; then
+	echo "ldapmodrdn succeeded, should have failed!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+fi
+
+test $KILLSERVERS != no && kill -HUP $KILLPIDS
 
 echo ">>>>> Test succeeded"
 exit 0
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test006-acls b/OpenLDAP/OpenLDAP/tests/scripts/test006-acls
--- a/OpenLDAP/OpenLDAP/tests/scripts/test006-acls
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test006-acls
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test006-acls,v 1.37.2.4 2004/01/01 18:16:43 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test006-acls,v 1.47.2.6 2006/07/31 22:38:44 quanah Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2004 The OpenLDAP Foundation.
+## Copyright 1998-2006 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -12,6 +12,14 @@
 ## A copy of this license is available in the file LICENSE in the
 ## top-level directory of the distribution or, alternatively, at
 ## <http://www.OpenLDAP.org/license.html>.
+
+case "$BACKEND" in
+bdb|hdb|ldbm)
+	;;
+*)
+	echo "Test does not support $BACKEND backend"
+	exit 0
+esac
 
 echo "running defines.sh"
 . $SRCDIR/scripts/defines.sh
@@ -36,6 +44,8 @@ if test $WAIT != 0 ; then
 fi
 KILLPIDS="$PID"
 
+sleep 1
+
 echo "Testing slapd access control..."
 for i in 0 1 2 3 4 5; do
 	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT1 \
@@ -56,16 +66,149 @@ fi
 
 cat /dev/null > $SEARCHOUT
 
-#
-# Try to read an entry inside the Alumni Association container.  It should
-# give us nothing if we're not bound, and should return all attributes
-# if we're bound as anyone under UM.
-#
-$LDAPSEARCH -b "$JAJDN" -h $LOCALHOST -p $PORT1 "objectclass=*" \
-	>> $SEARCHOUT 2>&1
+echo "# Try to read an entry inside the Alumni Association container.
+# It should give us noSuchObject if we're not bound..." \
+>> $SEARCHOUT
+# FIXME: temporarily remove the "No such object" message to make
+# the test succeed even if SLAP_ACL_HONOR_DISCLOSE is not #define'd
+$LDAPSEARCH -b "$JAJDN" -h $LOCALHOST -p $PORT1 "(objectclass=*)" \
+	2>&1 | grep -v "^No such object" >> $SEARCHOUT
 
+echo "# ... and should return all attributes if we're bound as anyone
+# under Example." \
+>> $SEARCHOUT
 $LDAPSEARCH -b "$JAJDN" -h $LOCALHOST -p $PORT1 \
-	-D "$BABSDN" -w bjensen "objectclass=*"  >> $SEARCHOUT 2>&1
+	-D "$BABSDN" -w bjensen "(objectclass=*)"  >> $SEARCHOUT 2>&1
+
+# check selfwrite access (ITS#4587).  6 attempts are made:
+# 1) delete someone else (should fail)
+# 2) delete self (should succeed)
+# 3) add someone else (should fail)
+# 4) add someone else and self (should fail)
+# 5) add self and someone else (should fail)
+# 6) add self (should succeed)
+#
+$LDAPMODIFY -D "$JAJDN" -h $LOCALHOST -p $PORT1 -w jaj >> \
+	$TESTOUT 2>&1 << EOMODS
+dn: cn=All Staff,ou=Groups,dc=example,dc=com
+changetype: modify
+delete: member
+member: $BABSDN
+EOMODS
+RC=$?
+case $RC in
+50)
+	;;
+0)
+	echo "ldapmodify should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit -1
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+
+$LDAPMODIFY -D "$JAJDN" -h $LOCALHOST -p $PORT1 -w jaj >> \
+	$TESTOUT 2>&1 << EOMODS
+dn: cn=All Staff,ou=Groups,dc=example,dc=com
+changetype: modify
+delete: member
+member: $JAJDN
+EOMODS
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+ 	 
+$LDAPMODIFY -D "$JAJDN" -h $LOCALHOST -p $PORT1 -w jaj >> \
+	$TESTOUT 2>&1 << EOMODS
+dn: cn=All Staff,ou=Groups,dc=example,dc=com
+changetype: modify
+add: member
+member: cn=Foo,ou=Bar
+EOMODS
+RC=$?
+case $RC in
+50)
+	;;
+0)
+	echo "ldapmodify should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit -1
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+ 	 
+$LDAPMODIFY -D "$JAJDN" -h $LOCALHOST -p $PORT1 -w jaj >> \
+	$TESTOUT 2>&1 << EOMODS
+dn: cn=All Staff,ou=Groups,dc=example,dc=com
+changetype: modify
+add: member
+member: cn=Foo,ou=Bar
+member: $JAJDN
+EOMODS
+RC=$?
+case $RC in
+50)
+	;;
+0)
+	echo "ldapmodify should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit -1
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+ 	 
+$LDAPMODIFY -D "$JAJDN" -h $LOCALHOST -p $PORT1 -w jaj >> \
+	$TESTOUT 2>&1 << EOMODS
+dn: cn=All Staff,ou=Groups,dc=example,dc=com
+changetype: modify
+add: member
+member: $JAJDN
+member: cn=Foo,ou=Bar
+EOMODS
+RC=$?
+case $RC in
+50)
+	;;
+0)
+	echo "ldapmodify should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit -1
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+ 	 
+$LDAPMODIFY -D "$JAJDN" -h $LOCALHOST -p $PORT1 -w jaj >> \
+	$TESTOUT 2>&1 << EOMODS
+dn: cn=All Staff,ou=Groups,dc=example,dc=com
+changetype: modify
+add: member
+member: $JAJDN
+EOMODS
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
 
 #
 # Check group access. Try to modify Babs' entry. Two attempts:
@@ -92,17 +235,17 @@ homephone: +1 313 555 5444
 EOMODS6
 
 #
-# Try to add a "member" attribute to the "All Staff" group.  It should
+# Try to add a "member" attribute to the "ITD Staff" group.  It should
 # fail when we add some DN other than our own, and should succeed when
 # we add our own DN.
 # bjensen
 $LDAPMODIFY -D "$JAJDN" -h $LOCALHOST -p $PORT1 -w jaj > \
 	$TESTOUT 2>&1 << EOMODS1
 version: 1
-dn: cn=ITD Staff, ou=Groups, o=University of Michigan, c=US
+dn: cn=ITD Staff, ou=Groups, dc=example, dc=com
 changetype: modify
 add: uniquemember
-uniquemember: cn=Barbara Jensen,ou=Information Technology Division,ou=People,o=University of Michigan,c=US
+uniquemember: cn=Barbara Jensen,ou=Information Technology Division,ou=People,dc=example,dc=com
 
 EOMODS1
 
@@ -110,21 +253,21 @@ $LDAPMODIFY -D "$JAJDN" -h $LOCALHOST -p $PORT1 -w jaj >> \
 	$TESTOUT 2>&1 << EOMODS2
 version: 1
 
-dn: cn=ITD Staff, ou=Groups, o=University of Michigan, c=US
+dn: cn=ITD Staff, ou=Groups, dc=example, dc=com
 changetype: modify
 add: uniquemember
-uniquemember: cn=James A Jones 1, ou=Alumni Association, ou=People, o=University of Michigan, c=US
+uniquemember: cn=James A Jones 1, ou=Alumni Association, ou=People, dc=example, dc=com
 EOMODS2
 
 #
-# Try to modify the "All Staff" group.  Two attempts are made:
+# Try to modify the "ITD Staff" group.  Two attempts are made:
 # 1) bound as "James A Jones 1" - should fail
-# 2) bound as "Barbara Jensen" - should succeed
+# 2) bound as "Bjorn Jensen" - should succeed
 #
 $LDAPMODIFY -D "$JAJDN" -h $LOCALHOST -p $PORT1 -w jaj >> \
 	$TESTOUT 2>&1 << EOMODS3
 
-dn: cn=ITD Staff, ou=Groups, o=University of Michigan, c=US
+dn: cn=ITD Staff, ou=Groups, dc=example, dc=com
 changetype: modify
 delete: description
 
@@ -135,7 +278,7 @@ $LDAPMODIFY -D "$BJORNSDN" -h $LOCALHOST -p $PORT1 -w bjorn >> \
 # COMMENT
 version: 1
 # comment
-dn: cn=ITD Staff, ou=Groups, o=University of Michigan, c=US
+dn: cn=ITD Staff, ou=Groups, dc=example, dc=com
 # comment
 changetype: modify
 # comment
@@ -145,7 +288,129 @@ ou: Groups
 # comment
 EOMODS4
 
+#
+# Try to modify the "ITD Staff" group.  Two attempts are made:
+# 1) bound as "James A Jones 1" - should succeed
+# 2) bound as "Barbara Jensen" - should fail
+# should exploit sets
+#
+$LDAPMODIFY -D "$JAJDN" -h $LOCALHOST -p $PORT1 -w jaj >> \
+	$TESTOUT 2>&1 << EOMODS5
+dn: cn=Alumni Assoc Staff, ou=Groups, dc=example, dc=com
+changetype: modify
+add: description
+description: added by jaj (should succeed)
+-
+EOMODS5
+
+$LDAPMODIFY -D "$BABSDN" -h $LOCALHOST -p $PORT1 -w bjensen >> \
+	$TESTOUT 2>&1 << EOMODS6
+dn: cn=Alumni Assoc Staff, ou=Groups, dc=example, dc=com
+changetype: modify
+add: description
+description: added by bjensen (should fail)
+-
+EOMODS6
+
+$LDAPMODIFY -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD >> \
+	$TESTOUT 2>&1 << EOMODS7
+dn: ou=Add & Delete,dc=example,dc=com
+changetype: add
+objectClass: organizationalUnit
+ou: Add & Delete
+EOMODS7
+
+$LDAPMODIFY -D "$BABSDN" -h $LOCALHOST -p $PORT1 -w bjensen >> \
+	$TESTOUT 2>&1 << EOMODS8
+dn: cn=Added by Babs (must fail),ou=Add & Delete,dc=example,dc=com
+changetype: add
+objectClass: inetOrgPerson
+cn: Added by Babs (must fail)
+sn: None
+EOMODS8
+
+$LDAPMODIFY -D "$BJORNSDN" -h $LOCALHOST -p $PORT1 -w bjorn >> \
+	$TESTOUT 2>&1 << EOMODS9
+dn: cn=Added by Bjorn (must succeed),ou=Add & Delete,dc=example,dc=com
+changetype: add
+objectClass: inetOrgPerson
+cn: Added by Bjorn (must succeed)
+sn: None
+
+dn: cn=Added by Bjorn (will be deleted),ou=Add & Delete,dc=example,dc=com
+changetype: add
+objectClass: inetOrgPerson
+cn: Added by Bjorn (will be deleted)
+sn: None
+
+dn: cn=Added by Bjorn (will be renamed),ou=Add & Delete,dc=example,dc=com
+changetype: add
+objectClass: inetOrgPerson
+cn: Added by Bjorn (will be renamed)
+sn: None
+
+dn: cn=Added by Bjorn (must succeed),ou=Add & Delete,dc=example,dc=com
+changetype: modify
+add: description
+description: this attribute value has been added __after__entry creation
+description: this attribute value will be deleted by Babs (must succeed)
+description: Bjorn will try to delete this attribute value (should fail)
+-
+EOMODS9
+
+$LDAPMODIFY -D "$BJORNSDN" -h $LOCALHOST -p $PORT1 -w bjorn >> \
+	$TESTOUT 2>&1 << EOMODS10
+dn: cn=Added by Bjorn (will be deleted),ou=Add & Delete,dc=example,dc=com
+changetype: delete
+EOMODS10
+
+$LDAPMODIFY -D "$BJORNSDN" -h $LOCALHOST -p $PORT1 -w bjorn >> \
+	$TESTOUT 2>&1 << EOMODS11
+dn: cn=Added by Bjorn (will be renamed),ou=Add & Delete,dc=example,dc=com
+changetype: modrdn
+newrdn: cn=Added by Bjorn (renamed by Bjorn)
+deleteoldrdn: 1
+EOMODS11
+
+$LDAPMODIFY -D "$BABSDN" -h $LOCALHOST -p $PORT1 -w bjensen >> \
+	$TESTOUT 2>&1 << EOMODS12
+dn: cn=Added by Bjorn (will be renamed),ou=Add & Delete,dc=example,dc=com
+changetype: modrdn
+newrdn: cn=Added by Bjorn (renamed by Babs)
+deleteoldrdn: 1
+EOMODS12
+
+$LDAPMODIFY -D "$JAJDN" -h $LOCALHOST -p $PORT1 -w jaj >> \
+	$TESTOUT 2>&1 << EOMODS13
+dn: cn=Added by Bjorn (will be renamed),ou=Add & Delete,dc=example,dc=com
+changetype: modrdn
+newrdn: cn=Added by Bjorn (renamed by Jaj)
+deleteoldrdn: 1
+EOMODS13
+
+$LDAPMODIFY -D "$BJORNSDN" -h $LOCALHOST -p $PORT1 -w bjorn >> \
+	$TESTOUT 2>&1 << EOMODS14
+dn: cn=Added by Bjorn (must succeed),ou=Add & Delete,dc=example,dc=com
+changetype: modify
+delete: description
+description: Bjorn will try to delete this attribute value (should fail)
+-
+EOMODS14
+
+$LDAPMODIFY -D "$BABSDN" -h $LOCALHOST -p $PORT1 -w bjensen >> \
+	$TESTOUT 2>&1 << EOMODS15
+dn: cn=Added by Bjorn (will be deleted),ou=Add & Delete,dc=example,dc=com
+changetype: delete
+
+dn: cn=Added by Bjorn (must succeed),ou=Add & Delete,dc=example,dc=com
+changetype: modify
+delete: description
+description: this attribute value will be deleted by Babs (must succeed)
+-
+EOMODS15
+
 echo "Using ldapsearch to retrieve all the entries..."
+echo "# Using ldapsearch to retrieve all the entries..." >> $SEARCHOUT
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
 	    'objectClass=*' >> $SEARCHOUT 2>&1
 RC=$?
@@ -165,7 +430,7 @@ echo "Comparing filter output..."
 $CMP $SEARCHFLT $LDIFFLT > $CMPOUT
 
 if test $? != 0 ; then
-	echo "comparison failed - modify operations did not complete correctly"
+	echo "comparison failed - operations did not complete correctly"
 	exit 1
 fi
 
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test010-passwd b/OpenLDAP/OpenLDAP/tests/scripts/test010-passwd
--- a/OpenLDAP/OpenLDAP/tests/scripts/test010-passwd
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test010-passwd
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test010-passwd,v 1.13.2.4 2004/01/01 18:16:43 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test010-passwd,v 1.18.2.6 2006/01/03 22:16:29 kurt Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2004 The OpenLDAP Foundation.
+## Copyright 1998-2006 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -27,6 +27,8 @@ if test $WAIT != 0 ; then
     read foo
 fi
 KILLPIDS="$PID"
+
+sleep 1
 
 echo "Using ldapsearch to check that slapd is running..."
 for i in 0 1 2 3 4 5; do
@@ -59,6 +61,36 @@ $LDAPSEARCH -h $LOCALHOST -p $PORT1 \
 	-D "$MANAGERDN" -w $PASSWD \
 	-b "$BASEDN" \
 	'objectclass=*' >> $SEARCHOUT 2>&1
+
+echo "Using ldappasswd to test a few error conditions ..."
+echo "Pass 0" >> $TESTOUT
+$LDAPPASSWD -h $LOCALHOST -p $PORT1 \
+	-w secret -a "" -s newsecret \
+	-D "cn=md5, $BASEDN" >> $TESTOUT 2>&1
+RC=$?
+if test $RC = 0 ; then
+	echo "ldappasswd unexpectantly passed ($RC)! old empty"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+fi
+$LDAPPASSWD -h $LOCALHOST -p $PORT1 \
+	-w secret -a oldsecret -s "" \
+	-D "cn=md5, $BASEDN" >> $TESTOUT 2>&1
+RC=$?
+if test $RC = 0 ; then
+	echo "ldappasswd unexpectantly passed ($RC)! new empty"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+fi
+$LDAPPASSWD -h $LOCALHOST -p $PORT1 \
+	-w secret -a oldsecret -s newsecret \
+	-D "cn=md5, $BASEDN" >> $TESTOUT 2>&1
+RC=$?
+if test $RC = 0 ; then
+	echo "ldappasswd unexpectantly passed ($RC)! wrong old"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+fi
 
 echo "Using ldappasswd (PASS 1)  ..."
 echo "Pass 1" >> $TESTOUT
@@ -138,6 +170,15 @@ if test $RC != 0 ; then
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
 fi
+
+echo "Logging end state with ldapsearch..."
+echo "" >> $TESTOUT
+echo "++ End search" >> $TESTOUT
+$LDAPSEARCH -h $LOCALHOST -p $PORT1 \
+	-D "$MANAGERDN" -w $PASSWD \
+	-b "$BASEDN" \
+	'objectclass=*' >> $TESTOUT 2>&1
+
 
 test $KILLSERVERS != no && kill -HUP $KILLPIDS
 
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test015-xsearch b/OpenLDAP/OpenLDAP/tests/scripts/test015-xsearch
--- a/OpenLDAP/OpenLDAP/tests/scripts/test015-xsearch
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test015-xsearch
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test015-xsearch,v 1.8.2.5 2004/04/12 18:21:08 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test015-xsearch,v 1.17.2.5 2006/01/03 22:16:29 kurt Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2004 The OpenLDAP Foundation.
+## Copyright 1998-2006 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -45,6 +45,8 @@ if test $WAIT != 0 ; then
 fi
 KILLPIDS="$PID"
 
+sleep 1
+
 echo "Testing slapd searching..."
 for i in 0 1 2 3 4 5; do
 	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT1 \
@@ -66,6 +68,7 @@ fi
 cat /dev/null > $SEARCHOUT
 
 echo "Testing exact searching..."
+echo "# Testing exact searching..." >> $SEARCHOUT
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
 	'(sn:=jensen)' >> $SEARCHOUT 2>&1
 RC=$?
@@ -76,6 +79,7 @@ if test $RC != 0 ; then
 fi
 
 echo "Testing approximate searching..."
+echo "# Testing approximate searching..." >> $SEARCHOUT
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
 	'(sn~=jensen)' name >> $SEARCHOUT 2>&1
 RC=$?
@@ -86,6 +90,7 @@ if test $RC != 0 ; then
 fi
 
 echo "Testing OR searching..."
+echo "# Testing OR searching..." >> $SEARCHOUT
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
 	'(|(givenName=XX*YY*Z)(cn=)(undef=*)(objectclass=groupofnames)(objectclass=groupofuniquenames)(sn:caseExactMatch:=Jones))' >> $SEARCHOUT 2>&1
 RC=$?
@@ -96,6 +101,7 @@ if test $RC != 0 ; then
 fi
 
 echo "Testing AND matching and ends-with searching..."
+echo "# Testing AND matching and ends-with searching..." >> $SEARCHOUT
 $LDAPSEARCH -S "" -b "ou=groups,$BASEDN" -s one -h $LOCALHOST -p $PORT1 \
 	'(&(|(objectclass=groupofnames)(objectclass=groupofuniquenames))(cn=A*))' >> $SEARCHOUT 2>&1
 RC=$?
@@ -106,6 +112,7 @@ if test $RC != 0 ; then
 fi
 
 echo "Testing NOT searching..."
+echo "# Testing NOT searching..." >> $SEARCHOUT
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
 	'(!(objectclass=pilotPerson))' >> $SEARCHOUT 2>&1
 RC=$?
@@ -116,6 +123,7 @@ if test $RC != 0 ; then
 fi
 
 echo "Testing objectClass/attributeType inheritance ..."
+echo "# Testing objectClass/attributeType inheritance ..." >> $SEARCHOUT
 $LDAPSEARCH -M -a never -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
 	'(&(objectClass=inetorgperson)(userid=uham))' \
 	"2.5.4.0" "userid" >> $SEARCHOUT 2>&1
@@ -126,9 +134,14 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-echo "Testing extended RFC2254 searching..."
+echo "Testing extended RFC2254 searching:"
+echo "# Testing extended RFC2254 searching:" >> $SEARCHOUT
+
+FILTER="(:dn:caseIgnoreIA5Match:=example)"
+echo "        f=$FILTER ..."
+echo "#         f=$FILTER ..." >> $SEARCHOUT
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
-	'(:dn:caseExactMatch:=University of Michigan)' >> $SEARCHOUT 2>&1
+	"$FILTER" >> $SEARCHOUT 2>&1
 
 RC=$?
 if test $RC != 0 ; then
@@ -137,10 +150,65 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-echo "Testing values return filter searching..."
+FILTER="(:dn:caseExactMatch:=Information Technology Division)"
+echo "        f=$FILTER ..."
+echo "#         f=$FILTER ..." >> $SEARCHOUT
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
-	-E '!mv=(o=University of Michigan)' \
-	'(o=University of Michigan)' >> $SEARCHOUT 2>&1
+	"$FILTER" >> $SEARCHOUT 2>&1
+
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+FILTER="(name:dn:=whatever)"
+echo "        f=$FILTER ..."
+echo "#         f=$FILTER ..." >> $SEARCHOUT
+$LDAPSEARCH -S "" -b "" -s base -h $LOCALHOST -p $PORT1 \
+	"$FILTER" >> $SEARCHOUT 2>&1
+
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "Testing values return filter searching:"
+echo "# Testing values return filter searching:" >> $SEARCHOUT
+
+FILTER="(o=Example, Inc.)"
+echo "        f=$FILTER ..."
+echo "#         f=$FILTER ..." >> $SEARCHOUT
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
+	-E '!mv='"$FILTER" "$FILTER" >> $SEARCHOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+FILTER="(dc=example)"
+VRFILTER="((o:caseExactMatch:=Example, Inc.)(dc=example))"
+echo "        f=$FILTER mv=$VRFILTER ..."
+echo "#         f=$FILTER mv=$VRFILTER ..." >> $SEARCHOUT
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
+	-E '!mv='"$VRFILTER" "$FILTER" >> $SEARCHOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+FILTER="(attributeTypes=0.9.2342.19200300.100.1.25)"
+echo "        f=$FILTER ..."
+echo "#         f=$FILTER ..." >> $SEARCHOUT
+$LDAPSEARCH -S "" -b "cn=Subschema" -s "base" -h $LOCALHOST -p $PORT1 \
+	-E '!mv='"$FILTER" "$FILTER" "attributeTypes" >> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test017-syncreplication-refresh b/OpenLDAP/OpenLDAP/tests/scripts/test017-syncreplication-refresh
--- a/OpenLDAP/OpenLDAP/tests/scripts/test017-syncreplication-refresh
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test017-syncreplication-refresh
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test017-syncreplication-refresh,v 1.4.2.8 2004/01/01 18:16:43 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test017-syncreplication-refresh,v 1.24.2.3 2006/01/03 22:16:29 kurt Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2004 The OpenLDAP Foundation.
+## Copyright 1998-2006 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -13,15 +13,15 @@
 ## top-level directory of the distribution or, alternatively, at
 ## <http://www.OpenLDAP.org/license.html>.
 
-if test "$BACKEND" != "bdb" -a "$BACKEND" != "hdb" ; then
-	echo "Test does not support $BACKEND"
-	exit 0
-fi
-
 echo "running defines.sh"
 . $SRCDIR/scripts/defines.sh
 
-mkdir -p $TESTDIR $DBDIR1 $DBDIR2 $DBDIR3
+if test $SYNCPROV = syncprovno; then 
+	echo "Syncrepl provider overlay not available, test skipped"
+	exit 0
+fi 
+
+mkdir -p $TESTDIR $DBDIR1 $DBDIR2
 
 #
 # Test replication:
@@ -29,6 +29,7 @@ mkdir -p $TESTDIR $DBDIR1 $DBDIR2 $DBDIR3
 # - start slave
 # - populate over ldap
 # - perform some modifies and deleted
+# - attempt to modify the slave (referral)
 # - retrieve database over ldap and compare against expected results
 #
 
@@ -41,6 +42,8 @@ if test $WAIT != 0 ; then
     read foo
 fi
 KILLPIDS="$PID"
+
+sleep 1
 
 echo "Using ldapsearch to check that master slapd is running..."
 for i in 0 1 2 3 4 5; do
@@ -79,6 +82,8 @@ if test $WAIT != 0 ; then
     read foo
 fi
 KILLPIDS="$KILLPIDS $SLAVEPID"
+
+sleep 1
 
 echo "Using ldapsearch to check that slave slapd is running..."
 for i in 0 1 2 3 4 5; do
@@ -119,7 +124,7 @@ echo "Using ldapmodify to modify master directory..."
 
 $LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD > \
 	$TESTOUT 2>&1 << EOMODS
-dn: cn=James A Jones 1, ou=Alumni Association, ou=People, o=University of Michigan, c=US
+dn: cn=James A Jones 1, ou=Alumni Association, ou=People, dc=example,dc=com
 changetype: modify
 add: drink
 drink: Orange Juice
@@ -130,27 +135,27 @@ sn: Jones
 add: sn
 sn: Jones
 
-dn: cn=Bjorn Jensen, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
+dn: cn=Bjorn Jensen, ou=Information Technology Division, ou=People, dc=example,dc=com
 changetype: modify
 replace: drink
 drink: Iced Tea
 drink: Mad Dog 20/20
 
-dn: cn=ITD Staff,ou=Groups,o=University of Michigan,c=US
+dn: cn=ITD Staff,ou=Groups,dc=example,dc=com
 changetype: modify
 delete: uniquemember
-uniquemember: cn=James A Jones 2, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
-uniquemember: cn=Bjorn Jensen, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
+uniquemember: cn=James A Jones 2, ou=Information Technology Division, ou=People, dc=example,dc=com
+uniquemember: cn=Bjorn Jensen, ou=Information Technology Division, ou=People, dc=example,dc=com
 -
 add: uniquemember
-uniquemember: cn=Dorothy Stevens, ou=Alumni Association, ou=People, o=University of Michigan, c=US
-uniquemember: cn=James A Jones 1, ou=Alumni Association, ou=People, o=University of Michigan, c=US
+uniquemember: cn=Dorothy Stevens, ou=Alumni Association, ou=People, dc=example,dc=com
+uniquemember: cn=James A Jones 1, ou=Alumni Association, ou=People, dc=example,dc=com
 
-dn: cn=All Staff,ou=Groups,o=University of Michigan,c=US
+dn: cn=All Staff,ou=Groups,dc=example,dc=com
 changetype: modify
 delete: description
 
-dn: cn=Gern Jensen, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
+dn: cn=Gern Jensen, ou=Information Technology Division, ou=People, dc=example,dc=com
 changetype: add
 objectclass: OpenLDAPperson
 cn: Gern Jensen
@@ -158,7 +163,7 @@ sn: Jensen
 uid: gjensen
 title: Chief Investigator, ITD
 postaladdress: ITD $ 535 W. William St $ Ann Arbor, MI 48103
-seealso: cn=All Staff, ou=Groups, o=University of Michigan, c=US
+seealso: cn=All Staff, ou=Groups, dc=example,dc=com
 drink: Coffee
 homepostaladdress: 844 Brown St. Apt. 4 $ Ann Arbor, MI 48104
 description: Very odd
@@ -167,25 +172,25 @@ telephonenumber: +1 313 555 8343
 mail: gjensen@mailgw.example.com
 homephone: +1 313 555 8844
 
-dn: ou=Retired, ou=People, o=University of Michigan, c=US
+dn: ou=Retired, ou=People, dc=example,dc=com
 changetype: add
 objectclass: organizationalUnit
 ou: Retired
 
-dn: cn=Rosco P. Coltrane, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
+dn: cn=Rosco P. Coltrane, ou=Information Technology Division, ou=People, dc=example,dc=com
 changetype: add
 objectclass: OpenLDAPperson
 cn: Rosco P. Coltrane
 sn: Coltrane
 uid: rosco
 
-dn: cn=Rosco P. Coltrane, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
+dn: cn=Rosco P. Coltrane, ou=Information Technology Division, ou=People, dc=example,dc=com
 changetype: modrdn
 newrdn: cn=Rosco P. Coltrane
 deleteoldrdn: 1
-newsuperior: ou=Retired, ou=People, o=University of Michigan, c=US
+newsuperior: ou=Retired, ou=People, dc=example,dc=com
 
-dn: cn=James A Jones 2, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
+dn: cn=James A Jones 2, ou=Information Technology Division, ou=People, dc=example,dc=com
 changetype: delete
 
 EOMODS
@@ -199,6 +204,26 @@ fi
 
 echo "Waiting 15 seconds for syncrepl to receive changes..."
 sleep 15
+
+echo "Try updating the slave slapd..."
+$LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT2 -w $PASSWD > \
+	$TESTOUT 2>&1 << EOMODS
+dn: cn=James A Jones 1, ou=Alumni Association, ou=People, dc=example, dc=com
+changetype: modify
+add: description
+description: This write must fail because directed to a shadow context,
+description: unless the chain overlay is configured appropriately ;)
+
+EOMODS
+
+RC=$?
+
+# expect 10 (LDAP_REFERRAL)...
+if test $RC != 10 ; then
+	echo "ldapmodify should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
 
 echo "Using ldapsearch to read all the entries from the master..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test018-syncreplication-persist b/OpenLDAP/OpenLDAP/tests/scripts/test018-syncreplication-persist
--- a/OpenLDAP/OpenLDAP/tests/scripts/test018-syncreplication-persist
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test018-syncreplication-persist
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test018-syncreplication-persist,v 1.4.2.8 2004/01/01 18:16:43 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test018-syncreplication-persist,v 1.25.2.5 2006/01/03 22:16:29 kurt Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2004 The OpenLDAP Foundation.
+## Copyright 1998-2006 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -13,13 +13,18 @@
 ## top-level directory of the distribution or, alternatively, at
 ## <http://www.OpenLDAP.org/license.html>.
 
-if test "$BACKEND" != "bdb" -a "$BACKEND" != "hdb" ; then
+if test "$BACKEND" != "bdb" && test "$BACKEND" != "hdb" ; then
 	echo "Test does not support $BACKEND"
 	exit 0
 fi
 
 echo "running defines.sh"
 . $SRCDIR/scripts/defines.sh
+
+if test $SYNCPROV = syncprovno; then 
+	echo "Syncrepl provider overlay not available, test skipped"
+	exit 0
+fi 
 
 mkdir -p $TESTDIR $DBDIR1 $DBDIR4
 
@@ -29,6 +34,7 @@ mkdir -p $TESTDIR $DBDIR1 $DBDIR4
 # - start slave
 # - populate over ldap
 # - perform some modifies and deleted
+# - attempt to modify the slave (referral or chain)
 # - retrieve database over ldap and compare against expected results
 #
 
@@ -41,6 +47,8 @@ if test $WAIT != 0 ; then
     read foo
 fi
 KILLPIDS="$PID"
+
+sleep 1
 
 echo "Using ldapsearch to check that master slapd is running..."
 for i in 0 1 2 3 4 5; do
@@ -80,6 +88,8 @@ if test $WAIT != 0 ; then
 fi
 KILLPIDS="$KILLPIDS $SLAVEPID"
 
+sleep 1
+
 echo "Using ldapsearch to check that slave slapd is running..."
 for i in 0 1 2 3 4 5; do
 	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT4 \
@@ -111,6 +121,38 @@ fi
 echo "Waiting 15 seconds for syncrepl to receive changes..."
 sleep 15
 
+echo "Stopping the provider, sleeping 10 seconds and restarting it..."
+kill -HUP "$PID"
+sleep 10
+echo "RESTART" >> $LOG1
+$SLAPD -f $CONF1 -h $URI1 -d $LVL $TIMING >> $LOG1 2>&1 &
+PID=$!
+if test $WAIT != 0 ; then
+    echo PID $PID
+    read foo
+fi
+KILLPIDS="$PID $SLAVEPID"
+
+sleep 1
+
+echo "Using ldapsearch to check that master slapd is running..."
+for i in 0 1 2 3 4 5; do
+	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT1 \
+		'objectclass=*' > /dev/null 2>&1
+	RC=$?
+	if test $RC = 0 ; then
+		break
+	fi
+	echo "Waiting 5 seconds for slapd to start..."
+	sleep 5
+done
+
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
 echo "Using ldapmodify to modify master directory..."
 
 #
@@ -119,7 +161,7 @@ echo "Using ldapmodify to modify master directory..."
 
 $LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD > \
 	$TESTOUT 2>&1 << EOMODS
-dn: cn=James A Jones 1, ou=Alumni Association, ou=People, o=University of Michigan, c=US
+dn: cn=James A Jones 1, ou=Alumni Association, ou=People, dc=example,dc=com
 changetype: modify
 add: drink
 drink: Orange Juice
@@ -130,27 +172,26 @@ sn: Jones
 add: sn
 sn: Jones
 
-dn: cn=Bjorn Jensen, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
+dn: cn=Bjorn Jensen, ou=Information Technology Division, ou=People, dc=example,dc=com
 changetype: modify
 replace: drink
 drink: Iced Tea
-drink: Mad Dog 20/20
 
-dn: cn=ITD Staff,ou=Groups,o=University of Michigan,c=US
+dn: cn=ITD Staff,ou=Groups,dc=example,dc=com
 changetype: modify
 delete: uniquemember
-uniquemember: cn=James A Jones 2, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
-uniquemember: cn=Bjorn Jensen, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
+uniquemember: cn=James A Jones 2, ou=Information Technology Division, ou=People, dc=example,dc=com
+uniquemember: cn=Bjorn Jensen, ou=Information Technology Division, ou=People, dc=example,dc=com
 -
 add: uniquemember
-uniquemember: cn=Dorothy Stevens, ou=Alumni Association, ou=People, o=University of Michigan, c=US
-uniquemember: cn=James A Jones 1, ou=Alumni Association, ou=People, o=University of Michigan, c=US
+uniquemember: cn=Dorothy Stevens, ou=Alumni Association, ou=People, dc=example,dc=com
+uniquemember: cn=James A Jones 1, ou=Alumni Association, ou=People, dc=example,dc=com
 
-dn: cn=All Staff,ou=Groups,o=University of Michigan,c=US
+dn: cn=All Staff,ou=Groups,dc=example,dc=com
 changetype: modify
 delete: description
 
-dn: cn=Gern Jensen, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
+dn: cn=Gern Jensen, ou=Information Technology Division, ou=People, dc=example,dc=com
 changetype: add
 objectclass: OpenLDAPperson
 cn: Gern Jensen
@@ -158,7 +199,7 @@ sn: Jensen
 uid: gjensen
 title: Chief Investigator, ITD
 postaladdress: ITD $ 535 W. William St $ Ann Arbor, MI 48103
-seealso: cn=All Staff, ou=Groups, o=University of Michigan, c=US
+seealso: cn=All Staff, ou=Groups, dc=example,dc=com
 drink: Coffee
 homepostaladdress: 844 Brown St. Apt. 4 $ Ann Arbor, MI 48104
 description: Very odd
@@ -167,25 +208,26 @@ telephonenumber: +1 313 555 8343
 mail: gjensen@mailgw.example.com
 homephone: +1 313 555 8844
 
-dn: ou=Retired, ou=People, o=University of Michigan, c=US
+dn: ou=Retired, ou=People, dc=example,dc=com
 changetype: add
 objectclass: organizationalUnit
 ou: Retired
 
-dn: cn=Rosco P. Coltrane, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
+dn: cn=Rosco P. Coltrane, ou=Information Technology Division, ou=People, dc=example,dc=com
 changetype: add
 objectclass: OpenLDAPperson
 cn: Rosco P. Coltrane
 sn: Coltrane
 uid: rosco
+description: Fat tycoon
 
-dn: cn=Rosco P. Coltrane, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
+dn: cn=Rosco P. Coltrane, ou=Information Technology Division, ou=People, dc=example,dc=com
 changetype: modrdn
 newrdn: cn=Rosco P. Coltrane
 deleteoldrdn: 1
-newsuperior: ou=Retired, ou=People, o=University of Michigan, c=US
+newsuperior: ou=Retired, ou=People, dc=example,dc=com
 
-dn: cn=James A Jones 2, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
+dn: cn=James A Jones 2, ou=Information Technology Division, ou=People, dc=example,dc=com
 changetype: delete
 
 EOMODS
@@ -199,6 +241,66 @@ fi
 
 echo "Waiting 15 seconds for syncrepl to receive changes..."
 sleep 15
+
+echo "Stopping consumer to test recovery..."
+kill -HUP $SLAVEPID
+sleep 10
+
+echo "Modifying more entries on the master..."
+$LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD >> \
+	$TESTOUT 2>&1 << EOMODS
+dn: cn=Rosco P. Coltrane, ou=Retired, ou=People, dc=example,dc=com
+changetype: delete
+
+dn: cn=Bjorn Jensen, ou=Information Technology Division, ou=People, dc=example,dc=com
+changetype: modify
+add: drink
+drink: Mad Dog 20/20
+
+dn: cn=Rosco P. Coltrane, ou=Retired, ou=People, dc=example,dc=com
+changetype: add
+objectclass: OpenLDAPperson
+sn: Coltrane
+uid: rosco
+cn: Rosco P. Coltrane
+
+EOMODS
+
+echo "Restarting consumer..."
+echo "RESTART" >> $LOG4
+$SLAPD -f $CONF4 -h $URI4 -d $LVL $TIMING >> $LOG4 2>&1 &
+SLAVEPID=$!
+if test $WAIT != 0 ; then
+    echo SLAVEPID $SLAVEPID
+    read foo
+fi
+KILLPIDS="$PID $SLAVEPID"
+
+echo "Waiting 25 seconds for syncrepl to receive changes..."
+sleep 25
+
+if test ! $BACKLDAP = "ldapno" ; then
+	echo "Try updating the slave slapd..."
+	$LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT4 -w $PASSWD > \
+		$TESTOUT 2>&1 << EOMODS
+dn: cn=James A Jones 1, ou=Alumni Association, ou=People, dc=example, dc=com
+changetype: modify
+add: description
+description: This write must fail because directed to a shadow context,
+description: unless the chain overlay is configured appropriately ;)
+
+EOMODS
+
+	RC=$?
+	if test $RC != 0 ; then
+		echo "ldapmodify failed ($RC)!"
+		test $KILLSERVERS != no && kill -HUP $KILLPIDS
+		exit $RC
+	fi
+
+	echo "Waiting 15 seconds for syncrepl to receive changes..."
+	sleep 15
+fi
 
 echo "Using ldapsearch to read all the entries from the master..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test020-proxycache b/OpenLDAP/OpenLDAP/tests/scripts/test020-proxycache
--- a/OpenLDAP/OpenLDAP/tests/scripts/test020-proxycache
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test020-proxycache
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test020-proxycache,v 1.4.2.5 2004/01/01 18:16:43 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test020-proxycache,v 1.11.2.13 2006/05/11 17:04:27 kurt Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2004 The OpenLDAP Foundation.
+## Copyright 1998-2006 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -13,13 +13,18 @@
 ## top-level directory of the distribution or, alternatively, at
 ## <http://www.OpenLDAP.org/license.html>.
 
-CACHETTL=60
+CACHETTL="1m"
 CACHE_ENTRY_LIMIT=10
 
 . $SRCDIR/scripts/defines.sh
 
 if test $PROXYCACHE = pcacheno; then 
 	echo "Proxy cache overlay not available, test skipped"
+	exit 0
+fi 
+
+if test $BACKLDAP = "ldapno" ; then 
+	echo "LDAP backend not available, test skipped"
 	exit 0
 fi 
 
@@ -43,6 +48,8 @@ if test $WAIT != 0 ; then
 	read foo
 fi
 KILLPIDS="$PID"
+
+sleep 1
 
 echo "Using ldapsearch to check that master slapd is running..."
 for i in 0 1 2 3 4 5; do
@@ -74,13 +81,15 @@ fi
 
 echo "Starting proxy cache on TCP/IP port $PORT2..."
 . $CONFFILTER < $PROXYCACHECONF > $CONF2
-$SLAPD -f $CONF2 -h $URI2 -d $LVL > $LOG2 2>&1 &
+$SLAPD -f $CONF2 -h $URI2 -d $LVL -d pcache > $LOG2 2>&1 &
 CACHEPID=$!
 if test $WAIT != 0 ; then
 	echo CACHEPID $CACHEPID
 	read foo
 fi
 KILLPIDS="$KILLPIDS $CACHEPID"
+
+sleep 1
 
 echo "Using ldapsearch to check that proxy slapd is running..."
 for i in 0 1 2 3 4 5; do
@@ -94,10 +103,19 @@ for i in 0 1 2 3 4 5; do
 	sleep 5
 done
 
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+cat /dev/null > $SLAVEOUT
+
 echo "Making queries on the proxy cache..." 
 echo "Query 1: filter:(sn=Jon) attrs: all" 
+echo "# Query 1: filter:(sn=Jon) attrs: all" >> $SLAVEOUT
 $LDAPSEARCH -x -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
-	'sn=Jon' > $SLAVEOUT 2>&1
+	'sn=Jon' >> $SLAVEOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
@@ -105,7 +123,17 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
+# ITS#4491, if debug messages are unavailable, we can't verify the tests.
+grep "query template" $LOG2 > /dev/null
+RC=$?
+if test $RC != 0 ; then
+	echo "Debug messages unavailable, test aborted..."
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS && wait
+	exit 0
+fi
+
 echo "Query 2: filter:(|(cn=*Jon*)(sn=Jon*)) attrs:cn sn title uid"  
+echo "# Query 2: filter:(|(cn=*Jon*)(sn=Jon*)) attrs:cn sn title uid" >> $SLAVEOUT
 $LDAPSEARCH -x -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
 	'(|(cn=*Jon*)(sn=Jon*))' cn sn title uid >> $SLAVEOUT 2>&1
 RC=$?
@@ -115,9 +143,10 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-echo "Query 3: filter:(sn=Smith*) attrs:cn sn title uid"  
+echo "Query 3: filter:(sn=Smith*) attrs:cn sn uid"  
+echo "# Query 3: filter:(sn=Smith*) attrs:cn sn uid" >> $SLAVEOUT
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
-	'sn=Smith*' cn sn title uid >> $SLAVEOUT 2>&1
+	'sn=Smith*' cn sn uid >> $SLAVEOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
@@ -126,6 +155,7 @@ if test $RC != 0 ; then
 fi
 
 echo "Query 4: filter:(sn=Doe*) attrs:cn sn title uid"  
+echo "# Query 4: filter:(sn=Doe*) attrs:cn sn title uid" >> $SLAVEOUT
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
 	'sn=Doe' cn sn title uid >> $SLAVEOUT 2>&1
 RC=$?
@@ -136,6 +166,7 @@ if test $RC != 0 ; then
 fi
  
 echo "Query 5: filter:(uid=bjorn) attrs:mail postaladdress telephonenumber cn uid"  
+echo "# Query 5: filter:(uid=bjorn) attrs:mail postaladdress telephonenumber cn uid" >> $SLAVEOUT
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
 	'uid=bjorn' mail postaladdress telephonenumber cn uid >> $SLAVEOUT 2>&1
 RC=$?
@@ -145,7 +176,8 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-echo "Query 6: filter:(mail=*@example.com) cn sn title uid"  
+echo "Query 6: filter:(mail=*@mail.alumni.example.com) cn sn title uid"  
+echo "# Query 6: filter:(mail=*@mail.alumni.example.com) cn sn title uid" >> $SLAVEOUT
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
 	'mail=*@mail.alumni.example.com' cn sn title uid >> $SLAVEOUT 2>&1
 RC=$?
@@ -156,6 +188,7 @@ if test $RC != 0 ; then
 fi
 
 echo "Query 7: filter:(mail=*) cn sn title uid"  
+echo "# Query 7: filter:(mail=*) cn sn title uid" >> $SLAVEOUT
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
 	'mail=*' cn sn title uid >> $SLAVEOUT 2>&1
 RC=$?
@@ -189,6 +222,7 @@ else
 fi
 
 echo "Query 8: filter:(|(cn=*Jones)(sn=Jones)) attrs:cn sn title uid"  
+echo "# Query 8: filter:(|(cn=*Jones)(sn=Jones)) attrs:cn sn title uid" >> $SLAVEOUT
 $LDAPSEARCH -x -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
 	'(|(cn=*Jones)(sn=Jones))' cn sn title uid >> $SLAVEOUT 2>&1
 RC=$?
@@ -199,6 +233,7 @@ if test $RC != 0 ; then
 fi
 
 echo "Query 9: filter:(sn=Smith) attrs:cn sn title uid"  
+echo "# Query 9: filter:(sn=Smith) attrs:cn sn title uid" >> $SLAVEOUT
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
 	'sn=Smith' cn sn title uid >> $SLAVEOUT 2>&1
 RC=$?
@@ -209,6 +244,7 @@ if test $RC != 0 ; then
 fi
 
 echo "Query 10: filter:(uid=bjorn) attrs:mail postaladdress telephonenumber cn uid"  
+echo "# Query 10: filter:(uid=bjorn) attrs:mail postaladdress telephonenumber cn uid" >> $SLAVEOUT
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
 	'uid=bjorn' mail postaladdress telephonenumber cn uid >> $SLAVEOUT 2>&1
 RC=$?
@@ -218,7 +254,8 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-echo "Query 11: filter:(mail=*@example.com) cn sn title uid"  
+echo "Query 11: filter:(mail=jaj@mail.alumni.example.com) cn sn title uid"  
+echo "# Query 11: filter:(mail=jaj@mail.alumni.example.com) cn sn title uid" >> $SLAVEOUT
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
 	'mail=jaj@mail.alumni.example.com' cn sn title uid >> $SLAVEOUT 2>&1
 RC=$?
@@ -254,6 +291,18 @@ if test "$ANSWERABILITY" = "$ANSWERED" ; then
 	echo "Successfully verified answerability"
 else 
 	echo "Error in verifying answerability"
+	exit 1
+fi
+
+echo "Filtering ldapsearch results..."
+. $LDIFFILTER < $SLAVEOUT > $SEARCHFLT
+echo "Filtering original ldif..."
+. $LDIFFILTER < $PROXYCACHEOUT > $LDIFFLT
+echo "Comparing filter output..."
+$CMP $SEARCHFLT $LDIFFLT > $CMPOUT
+
+if test $? != 0 ; then
+	echo "Comparison failed"
 	exit 1
 fi
 
diff --git a/OpenSSH/openssh/configure b/OpenSSH/openssh/configure
--- a/OpenSSH/openssh/configure
+++ b/OpenSSH/openssh/configure
@@ -711,6 +711,7 @@ MANTYPE
 mansubdir
 user_path
 piddir
+KEYCHAIN_LDFLAGS
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -1349,6 +1350,7 @@ Optional Packages:
   --with-bsd-auth         Enable BSD auth support
   --with-pid-dir=PATH     Specify location of ssh.pid file
   --with-lastlog=FILE|DIR specify lastlog location common locations
+  --with-keychain=apple   Use Mac OS X Keychain
 
 Some influential environment variables:
   CC          C compiler command
@@ -7754,6 +7756,7 @@ cat >>confdefs.h <<\_ACEOF
 #define SSH_TUN_PREPEND_AF 1
 _ACEOF
 
+	KEYCHAIN="apple"
 	;;
 *-*-dragonfly*)
 	SSHDLIBS="$SSHDLIBS -lcrypt"
@@ -32183,6 +32186,181 @@ if test ! -z "$blibpath" ; then
 echo "$as_me: WARNING: Please check and edit blibpath in LDFLAGS in Makefile" >&2;}
 fi
 
+# Check whether --with-keychain was given.
+if test "${with_keychain+set}" = set; then
+  withval=$with_keychain;
+		case "$withval" in
+		apple|no)
+			KEYCHAIN=$withval
+			;;
+		*)
+			{ { echo "$as_me:$LINENO: error: invalid keychain type: $withval" >&5
+echo "$as_me: error: invalid keychain type: $withval" >&2;}
+   { (exit 1); exit 1; }; }
+			;;
+		esac
+
+
+fi
+
+if test ! -z "$KEYCHAIN" -a "$KEYCHAIN" != "no"; then
+	case "$KEYCHAIN" in
+	apple)
+
+for ac_header in Security/Security.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  { echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6; }
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+ac_res=`eval echo '${'$as_ac_Header'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking $ac_header usability" >&5
+echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking $ac_header presence" >&5
+echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <$ac_header>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $ac_header:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: $ac_header: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: $ac_header: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## ------------------------------------------- ##
+## Report this to openssh-unix-dev@mindrot.org ##
+## ------------------------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6; }
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=\$ac_header_preproc"
+fi
+ac_res=`eval echo '${'$as_ac_Header'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+
+				CPPFLAGS="$CPPFLAGS -D__APPLE_KEYCHAIN__"
+				KEYCHAIN_LDFLAGS="-framework Security -framework CoreFoundation"
+
+
+else
+  { echo "$as_me:$LINENO: WARNING: Security framework not found. Disabling Mac OS X Keychain support." >&5
+echo "$as_me: WARNING: Security framework not found. Disabling Mac OS X Keychain support." >&2;}
+fi
+
+done
+
+		;;
+	esac
+fi
 CFLAGS="$CFLAGS $werror_flags"
 
 
@@ -33186,7 +33364,6 @@ cat >>$CONFIG_STATUS <<_ACEOF
 CEOF$ac_eof
 _ACEOF
 
-
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
@@ -33203,11 +33380,12 @@ MANTYPE!$MANTYPE$ac_delim
 mansubdir!$mansubdir$ac_delim
 user_path!$user_path$ac_delim
 piddir!$piddir$ac_delim
+KEYCHAIN_LDFLAGS!$KEYCHAIN_LDFLAGS$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 15; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 16; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
diff --git a/configd/get-mobility-info b/configd/get-mobility-info
--- a/configd/get-mobility-info
+++ b/configd/get-mobility-info
@@ -1,10 +1,10 @@
 #!/bin/sh
+# Copyright (c) 2004-2007 Apple Inc.
+#
 # get-mobility-info
 #
 # Collect system & network configuration information.
 #
-
-OUT=mobility-config-$$
 
 PATH=/bin:/usr/bin:/sbin:/usr/sbin
 
@@ -13,23 +13,43 @@ if [ ${EUID} -ne 0 ]; then
 	PRIV="sudo"
 fi
 
-cd /tmp
-mkdir ${OUT}
+OUT="mobility-info-`date +'%m.%d.%Y.%H%M%S'`"
+OUTDIR="/var/tmp"
+if [ -d ~/Desktop ]; then
+	OUTDIR=~/Desktop
+fi
+
+umask 077
+
+WORKDIR=`mktemp -d -q "/tmp/${OUT}"`
+if [ $? -ne 0 ]; then
+	echo "Could not create snapshot directory"
+	exit 1
+fi
+
+ARCHIVE=`mktemp -q "${OUTDIR}/${OUT}.tar.gz"`
+if [ $? -ne 0 ]; then
+	echo "Could not create snapshot archive"
+	rm -rf "${WORKDIR}"
+	exit 1
+fi
+
+cd "${WORKDIR}"
 
 #
 # processes
 #
-ps axlww						> ${OUT}/ps			2>&1
+ps axlww						> ps			2>&1
 
 #
 # network interface configuration
 #
-ifconfig -a -b						> ${OUT}/ifconfig		2>&1
+ifconfig -a -b						> ifconfig		2>&1
 
 #
 # network route configuration
 #
-netstat -n -r						>> ${OUT}/netstat		2>&1
+netstat -n -r -a -l					> netstat		2>&1
 
 #
 # DHCP configuration
@@ -38,54 +58,64 @@ for if in `ifconfig -l`
 do
 	case ${if} in
 	lo* )	;;
-	en* )	ipconfig getpacket ${if}		> ${OUT}/ipconfig-${if}		2>&1
+	en* )	ipconfig getpacket ${if}		> ipconfig-${if}	2>&1
 		;;
 	esac
 done
+
+#
+# AirPort info
+#
+if [ -x /System/Library/PrivateFrameworks/Apple80211.framework/Resources/airport ]; then
+	/System/Library/PrivateFrameworks/Apple80211.framework/Resources/airport --getinfo	\
+							> airport		2>&1
+fi
 
 #
 # OS info
 #
 if [ -e /System/Library/CoreServices/SystemVersion.plist ]; then
 	cat /System/Library/CoreServices/SystemVersion.plist	\
-							> ${OUT}/SystemVersion.plist	2>&1
+							> SystemVersion.plist	2>&1
 fi
 if [ -e /System/Library/CoreServices/ServerVersion.plist ]; then
 	cat /System/Library/CoreServices/ServerVersion.plist	\
-							> ${OUT}/ServerVersion.plist	2>&1
+							> ServerVersion.plist	2>&1
 fi
 
 #
 # IOKit info
 #
-ioreg -l						> ${OUT}/ioreg			2>&1
+ioreg -i -l -w 0					> ioreg			2>&1
+
+#
+# Host name
+#
+hostname						> hostname		2>&1
 
 #
 # Host configuration
 #
-hostinfo						> ${OUT}/hostinfo		2>&1
+hostinfo						> hostinfo		2>&1
 if [ -e /etc/hostconfig ]; then
-	cat /etc/hostconfig				> ${OUT}/etc.hostconfig		2>&1
+	cat /etc/hostconfig				> etc.hostconfig	2>&1
 fi
 
 #
 # DNS configuration
 #
-scutil --dns						> ${OUT}/dns-configuration	2>&1
+scutil --dns						> dns-configuration	2>&1
 if [ -e /etc/resolv.conf ]; then
-	cat /etc/resolv.conf				> ${OUT}/etc.resolv.conf	2>&1
+	cat /etc/resolv.conf				> etc.resolv.conf	2>&1
 fi
 if [ -e /var/run/resolv.conf ]; then
-	cat /var/run/resolv.conf			> ${OUT}/var.run.resolv.conf	2>&1
+	cat /var/run/resolv.conf			> var.run.resolv.conf	2>&1
 fi
 
 #
-# NetInfo configuration
+# Proxy configuration
 #
-niutil -statistics .					> ${OUT}/netinfo-statistics	2>&1
-if [ -f /var/run/niconfig_local.xml ]; then
-	cat /var/run/niconfig_local.xml			> ${OUT}/niconfig_local.xml	2>&1
-fi
+scutil --proxy						> proxy-configuration	2>&1
 
 #
 # System / network preferences
@@ -95,13 +125,15 @@ for f in										\
 	/Library/Preferences/SystemConfiguration/com.apple.PowerManagement.plist	\
 	/Library/Preferences/SystemConfiguration/com.apple.airport.preferences.plist	\
 	/Library/Preferences/SystemConfiguration/com.apple.nat.plist			\
+	/Library/Preferences/SystemConfiguration/com.apple.network.identification.plist	\
+	/Library/Preferences/SystemConfiguration/com.apple.smb.server.plist		\
 	/Library/Preferences/SystemConfiguration/preferences.plist			\
 	/Library/Preferences/com.apple.sharing.firewall.plist				\
 
 do
-	if [ -e ${f} ]; then
-		b=`basename $f`
-		cat ${f}				> ${OUT}/${b}			2>&1
+	if [ -e "${f}" ]; then
+		b="`basename ${f}`"
+		cat "${f}"				> "${b}"		2>&1
 	fi
 done
 
@@ -114,123 +146,355 @@ snapshot
 quit
 _END_OF_INPUT
 if [ -f /var/tmp/configd-store.xml ]; then
-	cp /var/tmp/configd-store.xml			${OUT}/configd-store.xml
+	cat /var/tmp/configd-store.xml			> configd-store.xml	2>&1
 fi
 if [ -f /var/tmp/configd-pattern.xml ]; then
-	cp /var/tmp/configd-pattern.xml			${OUT}/configd-pattern.xml
+	cat /var/tmp/configd-pattern.xml		> configd-pattern.xml	2>&1
 fi
 if [ -f /var/tmp/configd-session.xml ]; then
-	cp /var/tmp/configd-session.xml			${OUT}/configd-session.xml
+	cat /var/tmp/configd-session.xml		> configd-session.xml	2>&1
+fi
+if [ -f /var/tmp/configd-state ]; then
+	cat /var/tmp/configd-state			> configd-state		2>&1
 fi
 
 #
 # network reachability
 #
-scutil -d -v -r www.apple.com				> ${OUT}/reachability-info	2>&1
-if [ -f /usr/bin/dig ]; then
-	dig -t any -c any www.apple.com			> ${OUT}/dig-results		2>&1
+scutil -d -v -r www.apple.com				> reachability-info	2>&1
+if [ -x /usr/bin/dig ]; then
+	dig -t any -c any www.apple.com			> dig-results		2>&1
 fi
 
 #
 # mounted filesystems
 #
-mount							> ${OUT}/mounted-filesystems	2>&1
+mount							> mounted-filesystems	2>&1
 
 #
-# system log
+# mDNSResponder info
 #
-tail -1000 /var/log/system.log				> ${OUT}/system.log
+if [ -f /var/run/mDNSResponder.pid ]; then
+	${PRIV} kill -INFO `cat /var/run/mDNSResponder.pid`
+fi
 
 #
-# ppp log
+# system log, early boot log messages
 #
-if [ -f /var/log/ppp.log ]; then
-	cp /var/log/ppp.log				${OUT}/ppp.log
+${PRIV} tail -n 2000 /var/log/system.log		> system.log
+${PRIV} dmesg						> dmesg
+
+#
+# ppp log file(s)
+#
+scutil <<_END_OF_INPUT				\
+| awk -F' *: *'					\
+    '						\
+     /Logfile : / {				\
+       if (index($2, "/") == 1) { print $2 }	\
+       else { print "/var/log/ppp/" $2 }	\
+     }						\
+     END {					\
+       print "/tmp/pppotcp.log"			\
+     }						\
+    '						\
+| sort -u					\
+| while read logFile
+open
+show Setup:/Network/Service/[^/]+/PPP pattern
+quit
+_END_OF_INPUT
+do
+	if [ -f "${logFile}" ]; then
+		b="`basename ${logFile}`"
+		cat "${logFile}"			> "${b}"		2>&1
+	fi					
+done
+
+#
+# application firewall log
+#
+if [ -f /var/log/appfirewall.log ]; then
+	${PRIV} tail -n 2000 /var/log/appfirewall.log	> appfirewall.log
 fi
 
 #
 # kernel extensions statistic
 #
-if   [ -f /usr/sbin/kextstat ]; then
-	kextstat					> ${OUT}/kextstat		2>&1
-elif [ -f /usr/sbin/kmodstat ]; then
-	kmodstat					> ${OUT}/kmodstat		2>&1
+if   [ -x /usr/sbin/kextstat ]; then
+	kextstat					> kextstat		2>&1
+elif [ -x /usr/sbin/kmodstat ]; then
+	kmodstat					> kmodstat		2>&1
 fi
 
 #
 # network statistics
 #
-echo "#"						>> ${OUT}/network-statistics
-echo "# netstat -n -a -A -f inet"			>> ${OUT}/network-statistics
-echo "#"						>> ${OUT}/network-statistics
-netstat -n -a -A -f inet				>> ${OUT}/network-statistics	2>&1
-echo "#"						>> ${OUT}/network-statistics
-echo "# lsof -n -i -P"					>> ${OUT}/network-statistics
-echo "#"						>> ${OUT}/network-statistics
-lsof -n -i -P						>> ${OUT}/network-statistics	2>&1
-echo "#"						>> ${OUT}/network-statistics
-echo "# netstat -s"					>> ${OUT}/network-statistics
-echo "#"						>> ${OUT}/network-statistics
-netstat -s						>> ${OUT}/network-statistics	2>&1
-echo "#"						>> ${OUT}/network-statistics
-echo "# netstat -m"					>> ${OUT}/network-statistics
-echo "#"						>> ${OUT}/network-statistics
-netstat -m						>> ${OUT}/network-statistics	2>&1
-echo "#"						>> ${OUT}/network-statistics
-echo "# netstat -i -n -d"				>> ${OUT}/network-statistics
-echo "#"						>> ${OUT}/network-statistics
-netstat -i -n -d					>> ${OUT}/network-statistics	2>&1
-echo "#"						>> ${OUT}/network-statistics
-echo "# ipfw -at show"					>> ${OUT}/network-statistics
-echo "#"						>> ${OUT}/network-statistics
-ipfw -at show						>> ${OUT}/network-statistics	2>&1
-echo "#"						>> ${OUT}/network-statistics
-echo "# appletalk -s"					>> ${OUT}/network-statistics
-echo "#"						>> ${OUT}/network-statistics
-appletalk -s						>> ${OUT}/network-statistics	2>&1
+echo "#"						>  network-statistics
+echo "# netstat -n -a -A -f inet"			>> network-statistics
+echo "#"						>> network-statistics
+netstat -n -a -A -f inet				>> network-statistics	2>&1
+
+echo "#"						>> network-statistics
+echo "# lsof -i -n -P"					>> network-statistics
+echo "#"						>> network-statistics
+${PRIV} lsof -i -n -P					>> network-statistics	2>&1
+
+echo "#"						>> network-statistics
+echo "# netstat -s"					>> network-statistics
+echo "#"						>> network-statistics
+netstat -s						>> network-statistics	2>&1
+
+echo "#"						>> network-statistics
+echo "# netstat -mmm"					>> network-statistics
+echo "#"						>> network-statistics
+netstat -mmm						>> network-statistics	2>&1
+
+echo "#"						>> network-statistics
+echo "# netstat -i -n -d"				>> network-statistics
+echo "#"						>> network-statistics
+netstat -i -n -d					>> network-statistics	2>&1
+
+echo "#"						>> network-statistics
+echo "# ipfw -at show"					>> network-statistics
+echo "#"						>> network-statistics
+ipfw -at show						>> network-statistics	2>&1
+
+echo "#"						>> network-statistics
+echo "# appletalk -s"					>> network-statistics
+echo "#"						>> network-statistics
+appletalk -s						>> network-statistics	2>&1
 
 #
 # system usage statistics
 #
-echo "#"						>  ${OUT}/system-statistics
-echo "# uptime"						>> ${OUT}/system-statistics
-echo "#"						>> ${OUT}/system-statistics
-uptime							>> ${OUT}/system-statistics	2>&1
-echo "#"						>> ${OUT}/system-statistics
-echo "# pstat -t"					>> ${OUT}/system-statistics
-echo "#"						>> ${OUT}/system-statistics
-pstat -t						>> ${OUT}/system-statistics	2>&1
-echo "#"						>> ${OUT}/system-statistics
-echo "# sysctl -a"					>> ${OUT}/system-statistics
-echo "#"						>> ${OUT}/system-statistics
-sysctl -a						>> ${OUT}/system-statistics	2>&1
-echo "#"						>> ${OUT}/system-statistics
-echo "# zprint"						>> ${OUT}/system-statistics
-echo "#"						>> ${OUT}/system-statistics
-zprint							>> ${OUT}/system-statistics	2>&1
-echo "#"						>> ${OUT}/system-statistics
-echo "# top -l5 -s2"					>> ${OUT}/system-statistics
-echo "#"						>> ${OUT}/system-statistics
-  echo ""
-  echo "Please wait, collecting statistics"
-  echo ""
-top -s 2 -l 5						>> ${OUT}/system-statistics	2>&1
+echo "#"						>  system-statistics
+echo "# uptime"						>> system-statistics
+echo "#"						>> system-statistics
+uptime							>> system-statistics	2>&1
+
+echo "#"						>> system-statistics
+echo "# sysctl -a"					>> system-statistics
+echo "#"						>> system-statistics
+sysctl -a						>> system-statistics	2>&1
+
+echo "#"						>> system-statistics
+echo "# zprint"						>> system-statistics
+echo "#"						>> system-statistics
+zprint							>> system-statistics	2>&1
+
+echo "#"						>> system-statistics
+echo "# top -l5 -s2"					>> system-statistics
+echo "#"						>> system-statistics
+echo ""
+echo "Please wait, collecting statistics"
+echo ""
+top -s 2 -l 5						>> system-statistics	2>&1
+
+#
+# DirectoryService info
+#
+if [ -x /usr/bin/dscacheutil ]; then
+	echo "#"					>  ds-info
+	echo "# dscacheutil -configuration"		>> ds-info
+	echo "#"					>> ds-info
+	dscacheutil -configuration			>> ds-info		2>&1
+
+	echo "#"					>> ds-info
+	echo "# dscacheutil -statistics"		>> ds-info
+	echo "#"					>> ds-info
+	dscacheutil -statistics				>> ds-info		2>&1
+
+	echo "#"					>> ds-info
+	echo "# dscacheutil -cachedump -entries"	>> ds-info
+	echo "#"					>> ds-info
+	dscacheutil -cachedump -entries			>> ds-info		2>&1
+fi
+
+#
+# IPsec configuration
+#
+echo "#"						>  ipsec
+echo "# setkey -D"					>> ipsec
+echo "#"						>> ipsec
+${PRIV} setkey -D					\
+| perl -nle '
+	if (/^(\s+[AE]:\s+\S+\s+)"?(.*)"?\s*$/) {
+		chop($sha1=`echo "$2" | openssl sha1`);
+		printf "%s[SHA-1:%s]\n", $1, $sha1;
+	} else {
+		printf "%s\n", $_;
+	}
+'							>> ipsec
+
+echo ""							>> ipsec
+echo "#"						>> ipsec
+echo "# setkey -Pp -D"					>> ipsec
+echo "#"						>> ipsec
+${PRIV} setkey -Pp -D					>> ipsec
+
+for CF in /etc/racoon/remote/*.conf
+do
+	echo ""						>> ipsec
+	echo "#"					>> ipsec
+	echo "# ${CF}"					>> ipsec
+	echo "#"					>> ipsec
+	${PRIV} cat ${CF}				\
+	| perl -nle '
+		if (/^(\s+shared_secret\s+use\s+)"?([^\s;"]+)"?(.*)/) {
+			chop($sha1=`echo "$2" | openssl sha1`);
+			printf "%s[SHA-1:%s]%s\n", $1, $sha1, $3;
+		} else {
+			printf "%s\n", $_;
+		}
+	'						>> ipsec
+done
+
+#
+# Kerberos configuration
+#
+echo "#"						>  kerberos
+echo "# klist -e -c -A -f -a -n"			>> kerberos
+echo "#"						>> kerberos
+${PRIV} klist -e -c -A -f -a -n				>> kerberos
+
+echo "#"						>> kerberos
+echo "# klist -e -k -t -K"				>> kerberos
+echo "#"						>> kerberos
+${PRIV} klist -e -k -t -K				>> kerberos
+
+#
+# BTMM configuration
+#
+DIG()
+{
+	/usr/bin/dig @pm-members.mac.com -y "${DOMAIN}:${TSIG}" +short "${1}" "${2}"
+}
+
+scutil <<_END_OF_INPUT					\
+| sed -n 's@.* : *\(.*\.members\.mac\.com\)$@\1@p'	\
+| sort							\
+| while read DOMAIN
+open
+show Setup:/Network/BackToMyMac
+quit
+_END_OF_INPUT
+do
+	echo ""							>> btmm
+	echo "${DOMAIN}"					>> btmm
+
+	# lookup TSIG in base64 format
+	TSIG=`								\
+		${PRIV} security find-generic-password			\
+			-a ${DOMAIN}					\
+			-g /Library/Keychains/System.keychain 2>&1	\
+		| grep "^password: "					\
+		| cut -d '"' -f 2					\
+		| cut -d '\' -f 1					\
+	     `
+	if [ -z "$TSIG" ]; then
+		echo "  No TSIG in system keychain."		>> btmm
+		continue
+	fi
+	if [ `echo "$TSIG" | wc -l` -ne 1 ] ; then
+		echo "  More than one TSIG in system keychain."	>> btmm
+		continue
+	fi
+
+	for TYPE in			\
+		_afpovertcp._tcp	\
+		_airport._tcp		\
+		_adisk._tcp		\
+		_rfb._tcp		\
+		_smb._tcp		\
+		_ssh._tcp
+	do
+		DIG "${TYPE}.${DOMAIN}" ptr	\
+		| while read -r REG
+		do
+			echo ""					>> btmm
+			/bin/echo "  ${REG}"			>> btmm
+			echo ""					>> btmm
+
+			INF_Q=`/bin/echo "${REG}" | sed -e "s/${TYPE}/_device-info._tcp/"`
+			INF=`DIG "${INF_Q}" txt`
+			echo "    INF: ${INF}"			>> btmm
+
+			SRV=`DIG ${REG} srv`
+			SRV1=`/bin/echo "${SRV}" | head -1`
+			echo "    SRV: ${SRV1}"			>> btmm
+			SRV2=`/bin/echo "${SRV}" | tail +2`
+			if [ -n "${SRV2}" ]; then
+				SRV="${SRV1}"
+				/bin/echo "${SRV2}"		\
+				| sed -e 's/^/  *****: /'	>> btmm
+			fi
+
+			TXT=`DIG ${REG} txt`
+			TXT1=`/bin/echo "${TXT}" | head -1`
+			echo "    TXT: ${TXT1}"			>> btmm
+			TXT2=`/bin/echo "${TXT}" | tail +2`
+			if [ -n "${TXT2}" ]; then
+				/bin/echo "${TXT2}"		\
+				| sed -e 's/^/  *****: /'	>> btmm
+			fi
+
+			HOST=`/bin/echo "${SRV}" | cut -d ' ' -f 4-`
+			V4=`DIG ${HOST} a`
+			if [ -n "${V4}" ]; then
+				echo "     v4: ${V4}"		>> btmm
+			fi
+			V6=`DIG ${HOST} aaaa`
+			if [ -n "${V6}" ]; then
+				echo "     v6: ${V6}"		>> btmm
+			fi
+
+			KRB=`DIG _kerberos.${HOST} txt`
+			echo "    KRB: ${KRB}"			>> btmm
+
+			TUN=`DIG _autotunnel._udp.${HOST} srv`
+			echo "    TUN: ${TUN}"			>> btmm
+
+			HOST=`/bin/echo "${TUN}" | cut -d ' ' -f 4-`
+			V4=`DIG ${HOST} a`
+			if [ -n "${V4}" ]; then
+				echo "     v4: ${V4}"		>> btmm
+			fi
+			V6=`DIG ${HOST} aaaa`
+			if [ -n "${V6}" ]; then
+				echo "     v6: ${V6}"		>> btmm
+			fi
+		done
+	done
+done
 
 #
 # collect crash reports
 #
+CRASH_DIR=/Library/Logs/CrashReporter
 for daemon in bootpd configd pppd
 do
-	LOG=${daemon}.crash.log
-	if [ -e /Library/Logs/CrashReporter/${LOG} ]; then
-		cat /Library/Logs/CrashReporter/${LOG}	> ${OUT}/${LOG}			2>&1
-	fi
+	/bin/ls -1 ${CRASH_DIR}/${daemon}_*.crash 2>/dev/null	\
+	| while read log
+	do
+		b="`basename ${log}`"
+		${PRIV} cat "${log}"			> "${b}"		2>&1
+	done
 done
 
 #
 # collect everything into a single archive
 #
-tar cfz ${OUT}.tar.gz ${OUT}
-rm -rf ${OUT}
+cd "${WORKDIR}/.."
+tar cfz "${ARCHIVE}" "${OUT}"
+rm -rf "${WORKDIR}"
 
-echo "Network data collected to /tmp/${OUT}.tar.gz"
+if [ ${UID} -eq 0 ]; then
+	if [ -n "${SUDO_UID}" -a -n "${SUDO_GID}" ]; then
+		if [ ${UID} -ne ${SUDO_UID} ]; then
+			chown ${SUDO_UID}:${SUDO_GID} "${ARCHIVE}"
+		fi
+	fi
+fi
+
+echo "Network data collected to \"${ARCHIVE}\""
diff --git a/curl/Makefile b/curl/Makefile
--- a/curl/Makefile
+++ b/curl/Makefile
@@ -7,25 +7,44 @@ Project           = curl
 UserType          = Developer
 ToolType          = Commands
 GnuAfterInstall   = install-fixup install-plist compat-symlink move-static
+GnuNoBuild        = YES
+
+Extra_Configure_Flags = --with-gssapi=/usr
 
 include $(MAKEFILEPATH)/CoreOS/ReleaseControl/GNUSource.make
+
+# Passing LDFLAGS to make causes GSSAPI to fail. Passing nothing works fine.
+build::
+	$(_v) $(MAKE) -C $(BuildDirectory)
 
 # Automatic Extract & Patch
 AEP            = YES
 AEP_Project    = $(Project)
-AEP_Version    = 7.13.1
+AEP_Version    = 7.16.3
 AEP_ProjVers   = $(AEP_Project)-$(AEP_Version)
 AEP_Filename   = $(AEP_ProjVers).tar.bz2
 AEP_ExtractDir = $(AEP_ProjVers)
-AEP_Patches    = configure.diff curl-config.in.diff lib__ssluse.c.diff \
-                 libcurl-ntlmbuf.patch disable_poll.patch \
-                 libcurl-urllen.patch
+AEP_Patches    = configure.diff curl-config.in.diff \
+                 docs__curl.1.diff src__Makefile.in.diff \
+                 lib__md5.c.diff PR5101820.diff
 
 ifeq ($(suffix $(AEP_Filename)),.bz2)
 AEP_ExtractOption = j
 else
 AEP_ExtractOption = z
 endif
+
+##---------------------------------------------------------------------
+# Patch lib/config.h and src/config.h just after running configure
+##---------------------------------------------------------------------
+ConfigStamp2 = $(ConfigStamp)2
+
+configure:: $(ConfigStamp2)
+
+$(ConfigStamp2): $(ConfigStamp)
+	ed - $(OBJROOT)/lib/config.h < $(SRCROOT)/patches/config.h.ed
+	ed - $(OBJROOT)/src/config.h < $(SRCROOT)/patches/config.h.ed
+	touch $(ConfigStamp2)
 
 # Extract the source.
 install_source::
@@ -34,17 +53,22 @@ ifeq ($(AEP),YES)
 	$(RMDIR) $(SRCROOT)/$(AEP_Project)
 	$(MV) $(SRCROOT)/$(AEP_ExtractDir) $(SRCROOT)/$(AEP_Project)
 	for patchfile in $(AEP_Patches); do \
-		cd $(SRCROOT)/$(Project) && patch -p0 < $(SRCROOT)/patches/$$patchfile; \
+		(cd $(SRCROOT)/$(Project) && patch -p0 < $(SRCROOT)/patches/$$patchfile) || exit 1; \
 	done
 endif
 
 install-fixup:
+	@for arch in ppc64 x86_64; do \
+		file=$(DSTROOT)/usr/bin/curl; \
+		echo lipo -remove $${arch} -output $${file} $${file}; \
+		lipo -remove $${arch} -output $${file} $${file} || true; \
+	done
 	$(RM) $(DSTROOT)/usr/lib/libcurl.la
 	$(STRIP) -S $(DSTROOT)/usr/lib/libcurl.a
-	$(RM) $(DSTROOT)/usr/lib/libcurl.dylib $(DSTROOT)/usr/lib/libcurl.3.dylib
-	$(MV) $(DSTROOT)/usr/lib/libcurl.3.0.0.dylib $(DSTROOT)/usr/lib/libcurl.3.dylib
-	$(LN) -fs libcurl.3.dylib $(DSTROOT)/usr/lib/libcurl.dylib
-	$(LN) -fs libcurl.3.dylib $(DSTROOT)/usr/lib/libcurl.3.0.0.dylib
+	$(RM) $(DSTROOT)/usr/lib/libcurl.dylib $(DSTROOT)/usr/lib/libcurl.4.dylib
+	$(MV) $(DSTROOT)/usr/lib/libcurl.4.0.0.dylib $(DSTROOT)/usr/lib/libcurl.4.dylib
+	$(LN) -fs libcurl.4.dylib $(DSTROOT)/usr/lib/libcurl.dylib
+	$(LN) -fs libcurl.4.dylib $(DSTROOT)/usr/lib/libcurl.4.0.0.dylib
 
 OSV	= $(DSTROOT)/usr/local/OpenSourceVersions
 OSL	= $(DSTROOT)/usr/local/OpenSourceLicenses
@@ -56,7 +80,8 @@ install-plist:
 	$(INSTALL_FILE) $(SRCROOT)/$(Project)/COPYING $(OSL)/$(Project).txt
 
 compat-symlink:
-	$(LN) -s libcurl.3.dylib $(DSTROOT)/usr/lib/libcurl.2.dylib
+	$(LN) -s libcurl.4.dylib $(DSTROOT)/usr/lib/libcurl.2.dylib
+	$(LN) -s libcurl.4.dylib $(DSTROOT)/usr/lib/libcurl.3.dylib
 
 move-static:
 	$(MKDIR) $(DSTROOT)/usr/local/lib
diff --git a/curl/curl/buildconf b/curl/curl/buildconf
--- a/curl/curl/buildconf
+++ b/curl/curl/buildconf
@@ -1,4 +1,26 @@
 #!/bin/sh
+#***************************************************************************
+#                                  _   _ ____  _
+#  Project                     ___| | | |  _ \| |
+#                             / __| | | | |_) | |
+#                            | (__| |_| |  _ <| |___
+#                             \___|\___/|_| \_\_____|
+#
+# Copyright (C) 1998 - 2006, Daniel Stenberg, <daniel@haxx.se>, et al.
+#
+# This software is licensed as described in the file COPYING, which
+# you should have received as part of this distribution. The terms
+# are also available at http://curl.haxx.se/docs/copyright.html.
+#
+# You may opt to use, copy, modify, merge, publish, distribute and/or sell
+# copies of the Software, and permit persons to whom the Software is
+# furnished to do so, under the terms of the COPYING file.
+#
+# This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
+# KIND, either express or implied.
+#
+# $Id: buildconf,v 1.47 2006-10-27 03:47:57 yangtse Exp $
+###########################################################################
 
 die(){
 	echo "$@"
@@ -13,7 +35,8 @@ findtool(){
   IFS=":"
   for path in $PATH
   do
-    if test -r "$path/$file"; then
+    # echo "checks for $file in $path" >&2
+    if test -f "$path/$file"; then
       echo "$path/$file"
       return
     fi
@@ -24,7 +47,7 @@ findtool(){
 # autoconf 2.57 or newer
 #
 need_autoconf="2.57"
-ac_version=`${AUTOCONF:-autoconf} --version 2>/dev/null|head -1| sed -e 's/^[^0-9]*//' -e 's/[a-z]* *$//'`
+ac_version=`${AUTOCONF:-autoconf} --version 2>/dev/null|head -n 1| sed -e 's/^[^0-9]*//' -e 's/[a-z]* *$//'`
 if test -z "$ac_version"; then
   echo "buildconf: autoconf not found."
   echo "            You need autoconf version $need_autoconf or newer installed."
@@ -45,7 +68,7 @@ echo "buildconf: autoconf version $ac_version (ok)"
 #--------------------------------------------------------------------------
 # autoheader 2.50 or newer
 #
-ah_version=`${AUTOHEADER:-autoheader} --version 2>/dev/null|head -1| sed -e 's/^[^0-9]*//' -e 's/[a-z]* *$//'`
+ah_version=`${AUTOHEADER:-autoheader} --version 2>/dev/null|head -n 1| sed -e 's/^[^0-9]*//' -e 's/[a-z]* *$//'`
 if test -z "$ah_version"; then
   echo "buildconf: autoheader not found."
   echo "            You need autoheader version 2.50 or newer installed."
@@ -67,7 +90,7 @@ echo "buildconf: autoheader version $ah_version (ok)"
 # automake 1.7 or newer
 #
 need_automake="1.7"
-am_version=`${AUTOMAKE:-automake} --version 2>/dev/null|head -1| sed -e 's/^.* \([0-9]\)/\1/' -e 's/[a-z]* *$//' -e 's/\(.*\)\(-p.*\)/\1/'`
+am_version=`${AUTOMAKE:-automake} --version 2>/dev/null|head -n 1| sed -e 's/^.* \([0-9]\)/\1/' -e 's/[a-z]* *$//' -e 's/\(.*\)\(-p.*\)/\1/'`
 if test -z "$am_version"; then
   echo "buildconf: automake not found."
   echo "            You need automake version $need_automake or newer installed."
@@ -85,6 +108,13 @@ fi
 
 echo "buildconf: automake version $am_version (ok)"
 
+ac=`findtool ${ACLOCAL:-aclocal}`
+if test -z "$ac"; then
+  echo "buildconf: aclocal not found. Weird automake installation!"
+  exit 1
+else
+  echo "buildconf: aclocal found"
+fi
 
 #--------------------------------------------------------------------------
 # libtool check
@@ -99,13 +129,18 @@ LIBTOOL_WANTED_VERSION=1.4.2
 # glibtool, with 'libtool' being something completely different.
 libtool=`findtool glibtool 2>/dev/null`
 if test ! -x "$libtool"; then
-  libtool=`findtool libtool`
+  libtool=`findtool ${LIBTOOL:-libtool}`
 fi
 
-# set the LIBTOOLIZE here so that glibtoolize is used if glibtool was found
-LIBTOOLIZE="${libtool}ize"
+if test -z "$LIBTOOLIZE"; then
+  # set the LIBTOOLIZE here so that glibtoolize is used if glibtool was found
+  # $libtool is already the full path
+  libtoolize="${libtool}ize"
+else
+  libtoolize=`findtool $LIBTOOLIZE`
+fi
 
-lt_pversion=`$libtool --version 2>/dev/null|head -1|sed -e 's/^[^0-9]*//g' -e 's/[- ].*//'`
+lt_pversion=`$libtool --version 2>/dev/null|head -n 2|sed -e 's/^[^0-9]*//g' -e 's/[- ].*//'`
 if test -z "$lt_pversion"; then
   echo "buildconf: libtool not found."
   echo "            You need libtool version $LIBTOOL_WANTED_VERSION or newer installed"
@@ -142,10 +177,17 @@ fi
 
 echo "buildconf: libtool version $lt_version (ok)"
 
+if test -f "$libtoolize"; then
+  echo "buildconf: libtoolize found"
+else
+  echo "buildconf: libtoolize not found. Weird libtool installation!"
+  exit 1
+fi
+
 #--------------------------------------------------------------------------
 # m4 check
 #
-m4=`${M4:-m4} --version 2>/dev/null|head -1`;
+m4=`${M4:-m4} --version 2>/dev/null|head -n 1`;
 m4_version=`echo $m4 | sed -e 's/^.* \([0-9]\)/\1/' -e 's/[a-z]* *$//'`
 
 if { echo $m4 | grep "GNU" >/dev/null 2>&1; } then
@@ -155,17 +197,26 @@ else
   exit 1
 fi
 
+#--------------------------------------------------------------------------
+# perl check
+#
+PERL=`findtool ${PERL:-perl}`
 
 # ------------------------------------------------------------
 
 # run the correct scripts now
 
 echo "buildconf: running libtoolize"
-${LIBTOOLIZE:-libtoolize} --copy --automake --force || die "The libtool command failed"
+$libtoolize --copy --automake --force || die "The libtoolize command failed"
 echo "buildconf: running aclocal"
 ${ACLOCAL:-aclocal} $ACLOCAL_FLAGS || die "The aclocal command line failed"
-echo "buildconf: running aclocal hack to convert all mv to mv -f"
-perl -i.bak -pe 's/\bmv +([^-\s])/mv -f $1/g' aclocal.m4
+if test -n "$PERL"; then
+  echo "buildconf: running aclocal hack to convert all mv to mv -f"
+  $PERL -i.bak -pe 's/\bmv +([^-\s])/mv -f $1/g' aclocal.m4
+else
+  echo "buildconf: perl not found"
+  exit 1
+fi
 echo "buildconf: running autoheader"
 ${AUTOHEADER:-autoheader} || die "The autoheader command failed"
 echo "buildconf: cp lib/config.h.in src/config.h.in"
@@ -175,15 +226,13 @@ ${AUTOCONF:-autoconf}     || die "The autoconf command failed"
 
 if test -d ares; then
   cd ares
-  echo "buildconf: running aclocal in the ares directory"
-  ${ACLOCAL:-aclocal} $ACLOCAL_FLAGS || die "The ares aclocal command failed"
-  echo "buildconf: running autoconf in the ares directory"
-  ${AUTOCONF:-autoconf}     || die "The ares autoconf command failed"
+  echo "buildconf: running in ares"
+  ./buildconf
   cd ..
 fi
 
 echo "buildconf: running automake"
-${AUTOMAKE:-automake} -a  || die "The automake command failed"
+${AUTOMAKE:-automake} -a -c  || die "The automake command failed"
 
 echo "buildconf: OK"
 exit 0
diff --git a/emacs/emacs/lisp/makefile.w32-in b/emacs/emacs/lisp/makefile.w32-in
--- a/emacs/emacs/lisp/makefile.w32-in
+++ b/emacs/emacs/lisp/makefile.w32-in
@@ -1,22 +1,23 @@
-#  Makefile for GNU Emacs on the Microsoft W32 API.
-#  Copyright (c) 2000-2001 Free Software Foundation, Inc.
+#  -*- Makefile -*- for GNU Emacs on the Microsoft W32 API.
+#  Copyright (C) 2000, 2001, 2002, 2003, 2004,
+#                2005, 2006, 2007  Free Software Foundation, Inc.
 #
 #  This file is part of GNU Emacs.
-#  
+#
 #  GNU Emacs is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License as published by
 #  the Free Software Foundation; either version 2, or (at your option)
 #  any later version.
-#  
+#
 #  GNU Emacs is distributed in the hope that it will be useful,
 #  but WITHOUT ANY WARRANTY; without even the implied warranty of
 #  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 #  GNU General Public License for more details.
-#  
+#
 #  You should have received a copy of the GNU General Public License
 #  along with GNU Emacs; see the file COPYING.  If not, write to the
-#  Free Software Foundation, Inc., 59 Temple Place - Suite 330,
-#  Boston, MA 02111-1307, USA.
+#  Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
+#  Boston, MA 02110-1301, USA.
 #
 
 ALL =
@@ -27,11 +28,12 @@ SQUOTE='
 # '
 
 lisp = $(CURDIR)
+srcdir = $(CURDIR)/..
 
 # You can specify a different executable on the make command line,
 # e.g. "make EMACS=../src/emacs ...".
 
-EMACS = "$(THISDIR)/../bin/emacs.exe"
+EMACS = $(THISDIR)/../bin/emacs.exe
 
 # Command line flags for Emacs.  This must include --multibyte,
 # otherwise some files will not compile.
@@ -44,58 +46,6 @@ EMACSLOADPATH=$(lisp)
 lisptagsfiles1 = $(lisp)/*.el
 lisptagsfiles2 = $(lisp)/*/*.el
 ETAGS = "../lib-src/$(BLD)/etags"
-
-# Files which should not be compiled.
-# - emacs-lisp/cl-specs.el:  only contains `def-edebug-spec's so there's
-#   no point compiling it, although it doesn't hurt.
-
-DONTCOMPILE = \
-	$(lisp)/cus-load.el \
-	$(lisp)/cus-start.el \
-	$(lisp)/emacs-lisp/cl-specs.el \
-	$(lisp)/eshell/esh-maint.el \
-	$(lisp)/eshell/esh-groups.el \
-	$(lisp)/finder-inf.el \
-	$(lisp)/forms-d2.el \
-	$(lisp)/forms-pass.el \
-	$(lisp)/generic-x.el \
-	$(lisp)/international/latin-1.el \
-	$(lisp)/international/latin-2.el \
-	$(lisp)/international/latin-3.el \
-	$(lisp)/international/latin-4.el \
-	$(lisp)/international/latin-5.el \
-	$(lisp)/international/latin-8.el \
-	$(lisp)/international/latin-9.el \
-	$(lisp)/international/mule-conf.el \
-	$(lisp)/loaddefs.el \
-	$(lisp)/loadup.el \
-	$(lisp)/mail/blessmail.el \
-	$(lisp)/patcomp.el \
-	$(lisp)/paths.el \
-	$(lisp)/play/bruce.el \
-	$(lisp)/subdirs.el \
-	$(lisp)/term/internal.el \
-	$(lisp)/term/AT386.el  \
-	$(lisp)/term/apollo.el \
-	$(lisp)/term/bobcat.el \
-	$(lisp)/term/iris-ansi.el \
-	$(lisp)/term/keyswap.el \
-	$(lisp)/term/linux.el \
-	$(lisp)/term/lk201.el \
-	$(lisp)/term/news.el \
-	$(lisp)/term/vt102.el \
-	$(lisp)/term/vt125.el \
-	$(lisp)/term/vt200.el \
-	$(lisp)/term/vt201.el \
-	$(lisp)/term/vt220.el \
-	$(lisp)/term/vt240.el \
-	$(lisp)/term/vt300.el \
-	$(lisp)/term/vt320.el \
-	$(lisp)/term/vt400.el \
-	$(lisp)/term/vt420.el \
-	$(lisp)/term/wyse50.el \
-	$(lisp)/term/xterm.el \
-	$(lisp)/version.el
 
 # Files to compile before others during a bootstrap.  This is done to
 # speed up the bootstrap process.  The CC files are compiled first
@@ -111,53 +61,83 @@ COMPILE_FIRST = \
 	$(lisp)/progmodes/cc-vars.el
 
 # The actual Emacs command run in the targets below.
+# The quotes around $(EMACS) are here because the user could type
+# it with forward slashes and without quotes, which will fail if
+# the shell is cmd.exe.
 
-emacs = $(EMACS) $(EMACSOPT)
-
-# Common command to find subdirectories
-
-setwins=subdirs=`find $$wd -type d -print`; \
-	for file in $$subdirs; do \
-	   case $$file in */Old | */RCS | */CVS | */CVS/* | */=* ) ;; \
-		*) wins="$$wins $$file" ;; \
-	   esac; \
-        done
+emacs = "$(EMACS)" $(EMACSOPT)
 
 # Have to define the list of subdirs manually when not using sh.
-WINS=\
+WINS_ALMOST=\
+	calc \
 	calendar \
 	emacs-lisp \
 	emulation \
+	erc \
 	eshell \
 	gnus \
 	international \
 	language \
 	mail \
+	mh-e \
 	net \
 	play \
 	progmodes \
 	term \
-	textmodes
+	textmodes \
+	url
+
+WINS= $(WINS_ALMOST) \
+	obsolete
 
 doit:
 
-cus-load.el:
+$(lisp)/cus-load.el:
 	touch $@
-custom-deps: cus-load.el doit
+# WARNING: Do NOT split the part inside $(ARGQUOTE)s into multiple lines as
+#          this can break with GNU Make 3.81 and later if sh.exe is used.
+custom-deps: $(lisp)/cus-load.el $(lisp)/loaddefs.el doit
 	@echo Directories: $(WINS)
-	-$(emacs) -l cus-dep --eval $(ARGQUOTE)(setq find-file-hooks nil)$(ARGQUOTE) -f custom-make-dependencies $(lisp) $(WINS)
+	-$(emacs) -l cus-dep --eval $(ARGQUOTE)(setq find-file-hook nil)$(ARGQUOTE) -f custom-make-dependencies $(lisp) $(WINS)
 
-finder-inf.el:
-	echo (provide $(SQUOTE)finder-inf)>> $@
-
-finder-data: finder-inf.el doit
+finder-data: $(lisp)/loaddefs.el doit
 	@echo Directories: $(WINS)
 	$(emacs) -l finder -f finder-compile-keywords-make-dist $(lisp) $(WINS)
 
-loaddefs.el:
+$(lisp)/loaddefs.el:
+	$(MAKE) $(MFLAGS) loaddefs.el-$(SHELLTYPE)
+	cp loaddefs.el-$(SHELLTYPE) $@
+	rm loaddefs.el-$(SHELLTYPE)
+
+loaddefs.el-SH:
+	echo ";;; loaddefs.el --- automatically extracted autoloads" > $@
+	echo ";;" >> $@; echo ";;; Code:" >> $@
+	echo "(autoload 'define-minor-mode \"easy-mmode\")" >>$@
+	echo "(autoload 'define-ccl-program \"ccl\")" >>$@
+	echo "(autoload 'regexp-opt \"regexp-opt\")" >>$@
+	echo "(autoload 'string-to-list \"mule-util\")" >>$@
+	echo "(autoload 'define-derived-mode \"derived\")" >>$@
+	echo "(autoload 'encoded-kbd-mode \"encoded-kb\")" >>$@
+	echo "(defvar cvs-global-menu nil)" >>$@
+	echo "" >> $@
+	echo ";;; Local Variables:" >> $@
+	echo ";;; version-control: never" >> $@
+	echo ";;; no-byte-compile: t" >> $@
+	echo ";;; no-update-autoloads: t" >> $@
+	echo ";;; End:" >> $@
+	echo ";;; loaddefs.el ends here" >> $@
+
+loaddefs.el-CMD:
 	echo ;;; loaddefs.el --- automatically extracted autoloads> $@
 	echo ;;; Code:>> $@
-	echo >> $@
+	echo (autoload 'define-minor-mode "easy-mmode")>> $@
+	echo (autoload 'define-ccl-program "ccl")>> $@
+	echo (autoload 'regexp-opt "regexp-opt")>> $@
+	echo (autoload 'string-to-list "mule-util")>> $@
+	echo (autoload 'define-derived-mode "derived")>> $@
+	echo (autoload 'encoded-kbd-mode "encoded-kb")>> $@
+	echo (defvar cvs-global-menu nil)>> $@
+	echo.>> $@
 	echo ;;; Local Variables:>> $@
 	echo ;;; version-control: never>> $@
 	echo ;;; no-byte-compile: t>> $@
@@ -165,78 +145,131 @@ loaddefs.el:
 	echo ;;; End:>> $@
 	echo ;;; loaddefs.el ends here>> $@
 
-autoloads: loaddefs.el doit
-	@echo Directories: $(WINS)
+# Use . instead of $(lisp) because $(lisp) is an absolute file name,
+# including a drive letter and any leading directories, so the generated
+# loaddefs.el will mention file names that on other machine reference
+# possibly non-existent directories.
+#
+# WARNING: Do NOT split the part inside $(ARGQUOTE)s into multiple lines as
+#          this can break with GNU Make 3.81 and later if sh.exe is used.
+autoloads: $(lisp)/loaddefs.el doit
+	@echo Directories: . $(WINS_ALMOST)
 	$(emacs) -l autoload \
-		--eval $(ARGQUOTE)(setq find-file-hooks nil \
-			find-file-suppress-same-file-warnings t \
-			generated-autoload-file \
-			  $(DQUOTE)$(lisp)/loaddefs.el$(DQUOTE))$(ARGQUOTE) \
-		-f batch-update-autoloads $(lisp) $(WINS)
+		--eval $(ARGQUOTE)(setq find-file-hook nil find-file-suppress-same-file-warnings t)$(ARGQUOTE) \
+		-f w32-batch-update-autoloads "$(lisp)/loaddefs.el" . $(WINS_ALMOST)
 
-subdirs.el:
+$(lisp)/subdirs.el:
 	$(MAKE) $(MFLAGS) update-subdirs
 
 # Need separate version for sh and native cmd.exe
 update-subdirs: update-subdirs-$(SHELLTYPE)
 
 update-subdirs-CMD: doit
-	@set QWINS=
-	@for %d in ($(WINS)) do if not (%d)==(term) set QWINS=%QWINS% "%d"
-	echo ;; In load-path, after this directory should come> subdirs.el
-	echo ;; certain of its subdirectories.  Here we specify them.>> subdirs.el
-	echo (normal-top-level-add-to-load-path $(SQUOTE)(%QWINS%))>> subdirs.el
+	echo ;; -*- no-byte-compile: t -*-> $(lisp)/subdirs.el
+	echo ;; In load-path, after this directory should come>> $(lisp)/subdirs.el
+	echo ;; certain of its subdirectories.  Here we specify them.>> $(lisp)/subdirs.el
+	echo (normal-top-level-add-to-load-path $(SQUOTE)(>> $(lisp)/subdirs.el
+	@for %%d in ($(WINS)) do if not (%%d)==(term) echo "%%d">> $(lisp)/subdirs.el
+	echo ))>> $(lisp)/subdirs.el
 
 update-subdirs-SH: doit
-	wd=$(lisp); $(setwins); \
-	for file in $$wins; do \
+	$(srcdir)/update-subdirs $(lisp); \
+	for file in $(WINS); do \
 	   $(srcdir)/update-subdirs $$file; \
 	done;
 
-updates: update-subdirs autoloads finder-data custom-deps
+updates: update-subdirs autoloads mh-autoloads finder-data custom-deps
+
+# This is useful after "cvs up".
+cvs-update: recompile autoloads finder-data custom-deps
+
+# Update the AUTHORS file.
+
+update-authors:
+	$(emacs) -l authors -f batch-update-authors $(srcdir)/AUTHORS $(srcdir)
 
 TAGS: $(lisptagsfiles1) $(lisptagsfiles2)
 	$(ETAGS) $(lisptagsfiles1) $(lisptagsfiles2)
 
-TAGS-LISP: $(lispsource)$(lisptagsfiles1) $(lispsource)$(lisptagsfiles2)
-	$(ETAGS) -o TAGS-LISP $(lispsource)$(lisptagsfiles1) $(lispsource)$(lisptagsfiles2)
+TAGS-LISP: $(lisptagsfiles1) $(lisptagsfiles2)
+	$(ETAGS) -o TAGS-LISP $(lisptagsfiles1) $(lisptagsfiles2)
 
 .SUFFIXES: .elc .el
 
 .el.elc:
 	-$(emacs) -f batch-byte-compile $<
 
-$(DONTCOMPILE:.el=.elc):
-	-$(DEL) $@
+# Compile all Lisp files, but don't recompile those that are up to
+# date.  Some files don't actually get compiled because they set the
+# local variable no-byte-compile.
 
-# Compile all Lisp files, except those from DONTCOMPILE.  This
-# compiles files unconditionally.  All .elc files are made writable
-# before compilation in case we checked out read-only (CVS option -r).
-# Files MUST be compiled one by one.  If we compile several files in a
-# row we can't make sure that the compilation environment is clean.
-# We also set the load-path of the Emacs used for compilation to the
-# current directory and its subdirectories, to make sure require's and
-# load's in the files being compiled find the right files.
+# All .elc files are made writable before compilation in case we
+# checked out read-only (CVS option -r).  Files MUST be compiled one by
+# one.  If we compile several files in a row we can't make sure that
+# the compilation environment is clean.  We also set the load-path of
+# the Emacs used for compilation to the current directory and its
+# subdirectories, to make sure require's and load's in the files being
+# compiled find the right files.
 
 # Need separate version for sh and native cmd.exe
-compile-files: subdirs.el compile-files-$(SHELLTYPE) doit
+compile: $(lisp)/subdirs.el mh-autoloads compile-$(SHELLTYPE) doit
 
-compile-files-CMD:
-#	-for %f in ($(lisp) $(WINS)) do for %g in (%f\*.elc) do @attrib -r %g
-	for %f in ($(COMPILE_FIRST)) do $(emacs) -f batch-byte-compile %f
-	for %f in (. $(WINS)) do for %g in (%f/*.el) do $(emacs) -f batch-byte-compile %f/%g
+compile-CMD:
+#	-for %%f in ($(lisp) $(WINS)) do for %%g in (%%f\*.elc) do @attrib -r %%g
+	for %%f in ($(COMPILE_FIRST)) do \
+	  $(emacs) -l loaddefs -f batch-byte-compile-if-not-done %%f
+	for %%f in (. $(WINS)) do for %%g in (%%f/*.el) do \
+	  $(emacs) -l loaddefs -f batch-byte-compile-if-not-done %%f/%%g
 
-compile-files-SH:
+compile-SH:
 #	for elc in $(lisp)/*.elc $(lisp)/*/*.elc; do attrib -r $$elc; done
 	for el in $(COMPILE_FIRST); do \
 	  echo Compiling $$el; \
-	  $(emacs) -f batch-byte-compile $$el; \
+	  $(emacs) -l loaddefs -f batch-byte-compile-if-not-done $$el; \
+	done
+	for dir in $(lisp) $(WINS); do \
+	  for el in $$dir/*.el; do \
+	    if test -f $$el; \
+	    then \
+	      echo Compiling $$el; \
+	      $(emacs) -l loaddefs -f batch-byte-compile-if-not-done $$el; \
+	    fi \
+	  done; \
+	done
+
+# Compile all Lisp files.  This is like `compile' but compiles files
+# unconditionally.  Some files don't actually get compiled because they
+# set the local variable no-byte-compile.
+
+compile-always: $(lisp)/subdirs.el compile-always-$(SHELLTYPE) doit
+
+compile-always-CMD:
+#	-for %%f in ($(lisp) $(WINS)) do for %%g in (%%f\*.elc) do @attrib -r %%g
+	for %%f in ($(COMPILE_FIRST)) do $(emacs) -f batch-byte-compile %%f
+	for %%f in (. $(WINS)) do for %%g in (%%f/*.el) do $(emacs) -f batch-byte-compile %%f/%%g
+
+compile-always-SH:
+#	for elc in $(lisp)/*.elc $(lisp)/*/*.elc; do attrib -r $$elc; done
+	for el in $(COMPILE_FIRST); do \
+	  echo Compiling $$el; \
+	  $(emacs) -f batch-byte-compile $$el || exit 1; \
 	done
 	for dir in $(lisp) $(WINS); do \
 	  for el in $$dir/*.el; do \
 	    echo Compiling $$el; \
-	    $(emacs) -f batch-byte-compile $$el; \
+	    $(emacs) -f batch-byte-compile $$el || exit 1; \
 	  done; \
+	done
+
+compile-calc: compile-calc-$(SHELLTYPE)
+
+compile-calc-CMD:
+	for %%f in ($(lisp)/calc/*.el) do $(emacs) -f batch-byte-compile %%f
+
+compile-calc-SH:
+	for el in $(lisp)/calc/*.el; do \
+	  echo Compiling $$el; \
+	  $(emacs) -f batch-byte-compile $$el || exit 1; \
 	done
 
 # Backup compiled Lisp files in elc.tar.gz.  If that file already
@@ -248,35 +281,122 @@ backup-compiled-files:
 
 # Compile Lisp files, but save old compiled files first.
 
-compile: backup-compiled-files compile-files
+compile-after-backup: backup-compiled-files compile-always
 
 # Recompile all Lisp files which are newer than their .elc files.
 # Note that this doesn't create .elc files.  It only recompiles if an
 # .elc is present.
+# WARNING: Do NOT split the part inside $(ARGQUOTE)s into multiple lines as
+#          this can break with GNU Make 3.81 and later if sh.exe is used.
+recompile: mh-autoloads doit $(lisp)/progmodes/cc-mode.elc
+	$(emacs) --eval $(ARGQUOTE)(batch-byte-recompile-directory 0)$(ARGQUOTE) $(lisp)
 
-recompile: doit
-	$(emacs) -f batch-byte-recompile-directory .
+# Update MH-E internal autoloads. These are not to be confused with
+# the autoloads for the MH-E entry points, which are already in
+# loaddefs.el.
+MH_E_SRC = $(lisp)/mh-e/mh-acros.el $(lisp)/mh-e/mh-alias.el	\
+	$(lisp)/mh-e/mh-buffers.el $(lisp)/mh-e/mh-compat.el	\
+	$(lisp)/mh-e/mh-comp.el $(lisp)/mh-e/mh-e.el		\
+	$(lisp)/mh-e/mh-folder.el $(lisp)/mh-e/mh-funcs.el	\
+	$(lisp)/mh-e/mh-gnus.el $(lisp)/mh-e/mh-identity.el	\
+	$(lisp)/mh-e/mh-inc.el $(lisp)/mh-e/mh-junk.el		\
+	$(lisp)/mh-e/mh-letter.el $(lisp)/mh-e/mh-limit.el	\
+	$(lisp)/mh-e/mh-mime.el $(lisp)/mh-e/mh-print.el	\
+	$(lisp)/mh-e/mh-scan.el $(lisp)/mh-e/mh-search.el	\
+	$(lisp)/mh-e/mh-seq.el $(lisp)/mh-e/mh-show.el		\
+	$(lisp)/mh-e/mh-speed.el $(lisp)/mh-e/mh-thread.el	\
+	$(lisp)/mh-e/mh-tool-bar.el $(lisp)/mh-e/mh-utils.el	\
+	$(lisp)/mh-e/mh-xface.el
 
-# Prepare a bootstrap in the lisp subdirectory.  Build loaddefs.el,
-# because it's not sure it's up-to-date, and if it's not, that might
-# lead to errors during the bootstrap because something fails to
-# autoload as expected.  Remove compiled Lisp files so that
-# bootstrap-emacs will be built from sources only.
+# See the commentary for autoloads above for why we use ./mh-e below
+# instead of $(lisp)/mh-e.
+mh-autoloads: $(lisp)/mh-e/mh-loaddefs.el
+$(lisp)/mh-e/mh-loaddefs.el: $(MH_E_SRC)
+	$(MAKE) $(MFLAGS) pre-mh-loaddefs.el-$(SHELLTYPE)
+	cp pre-mh-loaddefs.el-$(SHELLTYPE) $@
+	rm pre-mh-loaddefs.el-$(SHELLTYPE)
+	"$(EMACS)" $(EMACSOPT) \
+	   -l autoload \
+	   --eval "(setq generate-autoload-cookie \";;;###mh-autoload\")" \
+	   --eval "(setq find-file-suppress-same-file-warnings t)" \
+	   --eval "(setq make-backup-files nil)" \
+	   -f w32-batch-update-autoloads \
+	   "$(lisp)/mh-e/mh-loaddefs.el" ./mh-e
+
+pre-mh-loaddefs.el-SH:
+	echo ";;; mh-loaddefs.el --- automatically extracted autoloads" > $@
+	echo ";;" >> $@
+	echo ";; Copyright (C) 2003, 2004, 2005, 2006, 2007 Free Software Foundation, Inc." >> $@
+	echo ";; Author: Bill Wohler <wohler@newt.com>" >> $@
+	echo ";; Keywords: mail" >> $@
+	echo ";;; Commentary:" >> $@
+	echo ";;; Change Log:" >> $@
+	echo ";;; Code:" >> $@
+	echo "" >> $@
+	echo "(provide 'mh-loaddefs)" >> $@
+	echo ";; Local Variables:" >> $@
+	echo ";; version-control: never" >> $@
+	echo ";; no-byte-compile: t" >> $@
+	echo ";; no-update-autoloads: t" >> $@
+	echo ";; End:" >> $@
+	echo ";;; mh-loaddefs.el ends here" >> $@
+
+pre-mh-loaddefs.el-CMD:
+	echo ;;; mh-loaddefs.el --- automatically extracted autoloads> $@
+	echo ;;>> $@
+	echo ;; Copyright (C) 2003, 2004, 2005, 2006, 2007 Free Software Foundation, Inc.>> $@
+	echo ;; Author: Bill Wohler (wohler@newt.com)>> $@
+	echo ;; Keywords: mail>> $@
+	echo ;;; Commentary:>> $@
+	echo ;;; Change Log:>> $@
+	echo ;;; Code:>> $@
+	echo.>> $@
+	echo (provide 'mh-loaddefs)>> $@
+	echo ;; Local Variables:>> $@
+	echo ;; version-control: never>> $@
+	echo ;; no-byte-compile: t>> $@
+	echo ;; no-update-autoloads: t>> $@
+	echo ;; End:>> $@
+	echo ;;; mh-loaddefs.el ends here>> $@
+
+# Prepare a bootstrap in the lisp subdirectory.
+#
+# Build loaddefs.el to make sure it's up-to-date.  If it's not, that
+# might lead to errors during the bootstrap because something fails to
+# autoload as expected.  If there is no emacs binary, then we can't
+# build autoloads yet.  In that case we have to use ldefs-boot.el;
+# bootstrap should always work with ldefs-boot.el.  (Because
+# loaddefs.el is an automatically generated file, we don't want to
+# store it in the source repository).
+#
+# Remove compiled Lisp files so that bootstrap-emacs will be built from
+# sources only.
 
 # Need separate version for sh and native cmd.exe
-bootstrap-clean: bootstrap-clean-$(SHELLTYPE)
+# Note that bootstrap-clean-$(SHELLTYPE) copies ldefs-boot.el to loaddefs.el,
+# and thus the almost-empty loaddefs.el crafted by the $(lisp)/loaddefs.el
+# target can NOT be built _after_ bootstrap-clean-$(SHELLTYPE) does its
+# thing, or else an empty loaddefs.el will overwrite the full one.
+bootstrap-clean: $(lisp)/loaddefs.el
+	$(MAKE) $(MFLAGS) bootstrap-clean-$(SHELLTYPE)
 
 bootstrap-clean-CMD:
-	if exist $(EMACS) $(MAKE) $(MFLAGS) autoloads
-	-for %f in (. $(WINS)) do for %g in (%f\*.elc) do @$(DEL) %g
+#	if exist "$(EMACS)" $(MAKE) $(MFLAGS) autoloads
+	cp $(lisp)/ldefs-boot.el $(lisp)/loaddefs.el
+	-for %%f in (. $(WINS)) do for %%g in (%%f\*.elc) do @$(DEL) %%g
 
 bootstrap-clean-SH:
-	if test -f $(EMACS); then $(MAKE) $(MFLAGS) autoloads; fi
-	-rm -f $(lisp)/*.elc $(lisp)/*/*.elc
+#	if test -f "$(EMACS)"; then $(MAKE) $(MFLAGS) autoloads; fi
+#	-rm -f $(lisp)/*.elc $(lisp)/*/*.elc
+	cp $(lisp)/ldefs-boot.el $(lisp)/loaddefs.el
+	-for dir in . $(WINS); do rm -f $$dir/*.elc; done
 
 # Generate/update files for the bootstrap process.
+# When done, remove bootstrap-emacs from ../bin, so that
+# it will not be mistaken for an installed binary.
 
-bootstrap: autoloads compile-files custom-deps
+bootstrap: update-subdirs autoloads mh-autoloads compile finder-data custom-deps
+	- $(DEL) "$(EMACS)"
 
 #
 # Assuming INSTALL_DIR is defined, copy the elisp files to it
@@ -307,6 +427,6 @@ install:
 
 #
 # Maintenance
-# 
+#
 clean:
 		- $(DEL) *~
diff --git a/gdb/src/readline/configure b/gdb/src/readline/configure
--- a/gdb/src/readline/configure
+++ b/gdb/src/readline/configure
@@ -3049,16 +3049,22 @@ if test "x$cross_compiling" = "xyes"; then
     case "${host}" in
     *-cygwin*)
 	cross_cache=${srcdir}/cross-build/cygwin.cache
+	LOCAL_CFLAGS="$LOCAL_CFLAGS -I${srcdir}/../libtermcap"
+	;;
+   *-mingw32*)
+	cross_cache=${srcdir}/cross-build/mingw.cache
+        ;;
+    *)  echo "configure: cross-compiling for a non-cygwin target is not supported" >&2
+	;;
+    esac
+
+    if test "x$cross_cache" != "x"; then
 	if test -r "${cross_cache}"; then
 	    echo "loading cross-build cache file ${cross_cache}"
 	    . ${cross_cache}
 	fi
-	LOCAL_CFLAGS="$LOCAL_CFLAGS -I${srcdir}/../libtermcap"
 	unset cross_cache
-	;;
-    *)  echo "configure: cross-compiling for a non-cygwin target is not supported" >&2
-	;;
-    esac
+    fi
 fi
 
 if test "x$cross_compiling" = "xyes"; then
@@ -4126,8 +4132,14 @@ fi
 
 
 
-for ac_func in lstat memmove putenv select setenv setlocale \
-		strcasecmp strpbrk tcgetattr vsnprintf isascii isxdigit
+
+
+
+
+
+for ac_func in fcntl kill lstat memmove putenv select setenv setlocale \
+	       strcasecmp strpbrk tcgetattr vsnprintf isascii isxdigit \
+               getpwnam getpwent getpwuid
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -4305,9 +4317,11 @@ fi
 
 
 
+
 for ac_header in unistd.h stdlib.h varargs.h stdarg.h string.h strings.h \
 		limits.h sys/ptem.h sys/pte.h sys/stream.h sys/select.h \
-		termcap.h termios.h termio.h sys/file.h locale.h memory.h
+		termcap.h termios.h termio.h sys/file.h locale.h memory.h \
+                pwd.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -6713,32 +6727,43 @@ echo $ECHO_N "checking for mbstate_t... $ECHO_C" >&6
 if test "${bash_cv_have_mbstate_t+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  if test "$cross_compiling" = yes; then
-  { echo "$as_me:$LINENO: WARNING: cannot check mbstate_t if cross compiling -- defaulting to yes" >&5
-echo "$as_me: WARNING: cannot check mbstate_t if cross compiling -- defaulting to yes" >&2;}
-     bash_cv_have_mbstate_t=yes
-else
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-
 #include <wchar.h>
+int
+main ()
+{
 int
 main ()
 {
   mbstate_t ps;
   return 0;
 }
+  ;
+  return 0;
+}
 _ACEOF
-rm -f conftest$ac_exeext
+rm -f conftest.$ac_objext conftest$ac_exeext
 if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -6746,15 +6771,13 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   (exit $ac_status); }; }; then
   bash_cv_have_mbstate_t=yes
 else
-  echo "$as_me: program exited with status $ac_status" >&5
-echo "$as_me: failed program was:" >&5
+  echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-( exit $ac_status )
 bash_cv_have_mbstate_t=no
 fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
-fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
 fi
 echo "$as_me:$LINENO: result: $bash_cv_have_mbstate_t" >&5
 echo "${ECHO_T}$bash_cv_have_mbstate_t" >&6
diff --git a/gnuzip/gzip/zgrep.in b/gnuzip/gzip/zgrep.in
--- a/gnuzip/gzip/zgrep.in
+++ b/gnuzip/gzip/zgrep.in
@@ -1,132 +1,194 @@
-:
 #!/bin/sh
 
 # zgrep -- a wrapper around a grep program that decompresses files as needed
 # Adapted from a version sent by Charles Levert <charles@comm.polymtl.ca>
 
-# Copyright (C) 1998, 2001, 2002 Free Software Foundation
+# Copyright (C) 1998, 2001, 2002, 2006 Free Software Foundation
 # Copyright (C) 1993 Jean-loup Gailly
 
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2, or (at your option)
-# any later version.
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version.
 
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 
-# You should have received a copy of the GNU General Public License
-# along with this program; if not, write to the Free Software
-# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
-# 02111-1307, USA.
+# You should have received a copy of the GNU General Public License along
+# with this program; if not, write to the Free Software Foundation, Inc.,
+# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 
 PATH="BINDIR:$PATH"; export PATH
 
-prog=`echo "$0" | sed 's|.*/||'`
-case "$prog" in
-	*egrep)	grep=${EGREP-egrep}	;;
-	*fgrep)	grep=${FGREP-fgrep}	;;
-	*)	grep=${GREP-grep}	;;
+case "$0" in
+(*egrep)	grep='${EGREP-egrep}'	;;
+(*fgrep)	grep='${FGREP-fgrep}'	;;
+(*)		grep='${GREP-grep}'	;;
 esac
 
-pat=""
-after_dash_dash=""
+eval 'version="z'"$grep"' (gzip) @VERSION@
+Copyright (C) 2006 Free Software Foundation, Inc.
+This is free software.  You may redistribute copies of it under the terms of
+the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
+There is NO WARRANTY, to the extent permitted by law.
+
+Written by Jean-loup Gailly."'
+
+usage="Usage: z$grep [OPTION]... [-e] PATTERN [FILE]...
+Look for instances of PATTERN in the input FILEs, using their
+uncompressed contents if they are compressed.
+
+OPTIONs are the same as for '$grep'.
+
+Report bugs to <bug-gzip@gnu.org>."
+
+# sed script to escape all ' for the shell, and then (to handle trailing
+# newlines correctly) turn trailing X on last line into '.
+escape='
+  s/'\''/'\''\\'\'''\''/g
+  $s/X$/'\''/
+'
+operands=
+have_pat=0
 files_with_matches=0
 files_without_matches=0
 no_filename=0
 with_filename=0
 
 while test $# -ne 0; do
-  case "$after_dash_dash$1" in
-  --d* | --rec*)	echo >&2 "$0: $1: option not supported"; exit 2;;
-  --files-with-*)	files_with_matches=1;;
-  --files-witho*)	files_without_matches=1;;
-  --no-f*)	no_filename=1;;
-  --wi*)	with_filename=1;;
-  --*)	;;
-  -*)
-	case "$1" in
-	-*[dr]*) echo >&2 "$0: $1: option not supported"; exit 2;;
-	esac
-	case "$1" in
-	-*H*)	with_filename=1;;
-	esac
-	case "$1" in
-	-*h*)	no_filename=1;;
-	esac
-	case "$1" in
-	-*L*)	files_without_matches=1;;
-	esac
-	case "$1" in
-	-*l*)	files_with_matches=1;;
-	esac;;
-  esac
-  case "$after_dash_dash$1" in
-  -[ef])   opt="$opt $1"; shift; pat="$1"
-           if test "$grep" = grep; then  # grep is buggy with -e on SVR4
-             grep=egrep
-           fi;;
-  -[ABCdm])opt="$opt $1 $2"; shift;;
-  --)      opt="$opt $1"; after_dash_dash=1;;
-  -*)	   opt="$opt $1";;
-   *)      if test -z "$pat"; then
-	     pat="$1"
-	   else
-	     break;
-           fi;;
-  esac
+  option=$1
   shift
+  optarg=
+
+  case $option in
+  (-[0123456789abcdhHiIKLlnoqrRsTuUvVwxyzZ]?*)
+    arg2=-\'$(expr "X${option}X" : 'X-.[0-9]*\(.*\)' | sed "$escape")
+    eval "set -- $arg2 "'${1+"$@"}'
+    option=$(expr "X$option" : 'X\(-.[0-9]*\)');;
+  (--binary-*=* | --[lm]a*=* | --reg*=*)
+    ;;
+  (-[ABCDefm] | --binary-* | --file | --[lm]a* | --reg*)
+    have_optarg=1
+    case ${1?"$option option requires an argument"} in
+    (*\'*)
+      optarg=" '"$(printf '%sX\n' "$1" | sed "$escape");;
+    (*)
+      optarg=" '$1'";;
+    esac
+    shift;;
+  (--)
+    break;;
+  (-?*)
+    ;;
+  (*)
+    case $option in
+    (*\'*)
+      operands="$operands '"$(printf '%sX\n' "$option" | sed "$escape");;
+    (*)
+      operands="$operands '$option'";;
+    esac
+    ${POSIXLY_CORRECT+break}
+    continue;;
+  esac
+
+  case $option in
+  (-[drRzZ] | --di* | --exc* | --inc* | --rec* | --nu*)
+    printf >&2 '%s: %s: option not supported\n' "$0" "$option"
+    exit 2;;
+  (-[ef]* | --file | --file=* | --reg*)
+    have_pat=1;;
+  (--h | --he | --hel | --help)
+    echo "$usage" || exit 2
+    exit;;
+  (-H | --wi | --wit | --with | --with- | --with-f | --with-fi \
+  | --with-fil | --with-file | --with-filen | --with-filena | --with-filenam \
+  | --with-filename)
+    with_filename=1
+    continue;;
+  (-l | --files-with-*)
+    files_with_matches=1;;
+  (-L | --files-witho*)
+    files_without_matches=1;;
+  (--no-f*)
+    no_filename=1;;
+  (-V | --v | --ve | --ver | --vers | --versi | --versio | --version)
+    echo "$version" || exit 2
+    exit;;
+  esac
+
+  case $option in
+  (*\'?*)
+    option=\'$(expr "X${option}X" : 'X\(.*\)' | sed "$escape");;
+  (*)
+    option="'$option'";;
+  esac
+
+  grep="$grep $option$optarg"
 done
 
-if test -z "$pat"; then
-  echo "grep through gzip files"
-  echo "usage: $prog [grep_options] pattern [files]"
-  exit 2
+eval "set -- $operands "'${1+"$@"}'
+
+if test $have_pat -eq 0; then
+  case ${1?"missing pattern; try \`$0 --help' for help"} in
+  (*\'*)
+    grep="$grep -- '"$(printf '%sX\n' "$1" | sed "$escape");;
+  (*)
+    grep="$grep -- '$1'";;
+  esac
+  shift
 fi
 
 if test $# -eq 0; then
-  gzip -cdfq | $grep $opt "$pat"
-  exit $?
+  set -- -
 fi
 
+exec 3>&1
 res=0
-for i do
-  gzip -cdfq -- "$i" |
+
+for i
+do
+  # Fail if gzip or grep (or sed) fails.
+  gzip_status=$(
+    exec 5>&1
+    (gzip -cdfq -- "$i" 5>&-; echo $? >&5) 3>&- |
     if test $files_with_matches -eq 1; then
-      $grep $opt "$pat" > /dev/null && printf "%s\n" "$i"
+      eval "$grep" >/dev/null && { printf '%s\n' "$i" || exit 2; }
     elif test $files_without_matches -eq 1; then
-      $grep $opt "$pat" > /dev/null || printf "%s\n" "$i"
-    elif test $with_filename -eq 0 && { test $# -eq 1 || test $no_filename -eq 1; }; then
-      $grep $opt "$pat"
+      eval "$grep" >/dev/null || {
+	r=$?
+	if test $r -eq 1; then
+	  printf '%s\n' "$i" || r=2
+	fi
+	exit $r
+      }
+    elif test $with_filename -eq 0 &&
+	 { test $# -eq 1 || test $no_filename -eq 1; }; then
+      eval "$grep"
     else
-      i=$(echo "$i" | sed -e 's/[\\|&]/\\&/g')
-      if test $with_filename -eq 1; then
-	sed_script="s|^[^:]*:|${i}:|"
-      else
-	sed_script="s|^|${i}:|"
-      fi
-      # Hack adapted from GPLed code at
-      # http://home.comcast.net/~j.p.h/cus-faq-2
-      # Has the same effect as the following two lines of bash:
-      #
-      # $grep $opt "$pat" | sed "$sed_script"
-      # exit ${PIPESTATUS[0]}
-      #
-      # Inside the `...`, fd4 goes to the pipe whose other end is read
-      # and passed to eval; fd1 is the normal standard output
-      # preserved the line before with exec 3>&1
-      exec 3>&1
-      eval `
-      exec 4>&1 >&3 3>&-
-      {
-       $grep $opt "$pat" 4>&-; echo "r=$?;" >&4
-      } | sed "$sed_script"
-      `
+      case $i in
+      (*'
+'* | *'&'* | *'\'* | *'|'*)
+        i=$(printf '%s\n' "$i" |
+	    sed '
+	      $!N
+	      $s/[&\|]/\\&/g
+	      $s/\n/\\n/g
+	    ');;
+      esac
+      sed_script="s|^|$i:|"
+
+      # Fail if grep or sed fails.
+      r=$(
+	exec 4>&1
+	(eval "$grep" 4>&-; echo $? >&4) 3>&- | sed "$sed_script" >&3 4>&-
+      ) || r=2
       exit $r
-    fi
+    fi >&3 5>&-
+  )
   r=$?
+  test "$gzip_status" -eq 0 || test "$gzip_status" -eq 2 || r=2
   test $res -lt $r && res=$r
 done
 exit $res
diff --git a/lsof/lsof/Configure b/lsof/lsof/Configure
--- a/lsof/lsof/Configure
+++ b/lsof/lsof/Configure
@@ -14,7 +14,7 @@
 # shell script, named $LSOF_MK, that places its source modules in this
 # directory.
 #
-# $Id: Configure,v 1.150 2006/04/10 12:44:20 abe Exp $
+# $Id: Configure,v 1.151 2007/04/24 16:16:30 abe Exp $
 
 #LSOF_CFLAGS_OVERRIDE=1 may be introduced through the environment to cause
 #	the library Makefile's CFLAGS definition to override any in the
@@ -61,7 +61,7 @@ LSOF_VF=version
 #			    lsof library
 #	$LSOF_ARCH	    Unix dialect architecture as a string -- may be
 #			    supplied externally
-#	$LSOF_CC	    C compiler name (may be supplied extermally)
+#	$LSOF_CC	    C compiler name (may be supplied externally)
 #	$LSOF_CCV	    C compiler version (may be supplied externally)
 #	$LSOF_CDIR	    configuration directory
 #	$LSOF_CFGD	    depend options
@@ -247,8 +247,8 @@ do
       echo "rm -rf AFSHeaders AFSVersion version.h"
       rm -f ${LSOF_HLP_BASE}* cd9660_node.h
       echo "rm -f ${LSOF_HLP_BASE}* cd9660_node.h"
-      rm -f dialects/aix/aix41*
-      echo "rm -f dialects/aix/aix41*"
+      rm -f dialects/aix/aix5/j2/j2_snapshot.h
+      echo "rm -f dialects/aix/aix5/j2/j2_snapshot.h"
       rm -f dialects/sun/solaris10	# DEBUG -- for s10_44
       echo "rm -f dialects/sun/solaris10"	# DEBUG -- for s10_44
       rm -f dialects/du/du5_sys_malloc.h
@@ -535,10 +535,20 @@ case $LSOF_TGT in	# {
       # The AIX > 5.0 system has jfs2 support.  Make the necesssary definitions
       # and adjustments.
 
+	rm -f dialects/aix/aix5/j2/j2_snapshot.h
+	(cd dialects/aix/aix5/j2; ln -s private_j2_snapshot.h j2_snapshot.h)
 	LSOF_CFGF="$LSOF_CFGF -DHAS_JFS2"
 	LSOF_CFGF="$LSOF_CFGF -I`pwd`/dialects/aix/aix5"
 	if test $LSOF_VERS -ge 5200	# {
 	then
+	  if test -r ${LSOF_INCLUDE}/j2/j2_snapshot.h	# {
+	  then
+
+	  # The system has its own j2_snapshot.h, so make sure the
+	  # private lsof copy is discarded.
+
+	    rm -f dialects/aix/aix5/j2/j2_snapshot.h
+	  fi	# }
 	  echo $LSOF_CC | grep gcc > /dev/null
 	  if test $? -eq 0	# {
 	  then
@@ -815,10 +825,13 @@ case $LSOF_TGT in	# {
       8.*)
 	LSOF_VERS=800
 	;;
+      9.*)
+	LSOF_VERS=900
+	;;
       *)
 	echo Unknown Darwin release: `uname -r`
-	echo Assuming Darwin 8.0
-	LSOF_VERS=800
+	echo Assuming Darwin 9.0
+	LSOF_VERS=900
 	;;
       esac	# }
     fi	# }
@@ -846,6 +859,10 @@ case $LSOF_TGT in	# {
     800)
       LSOF_CFGF="$LSOF_CFGF -DHASIPv6"
       LSOF_TMP1="net/ndrv_var.h net/raw_cb.h netinet/ip_var.h netinet/tcp_var.h sys/eventvar.h sys/file_internal.h sys/mount_internal.h sys/proc_internal.h sys/vnode_internal.h"
+      ;;
+    900)
+      LSOF_CFGF="$LSOF_CFGF -DHASIPv6"
+      LSOF_TMP1=""
       ;;
     *)
       echo "Unsupported Darwin version: $LSOF_VERS"
@@ -1581,6 +1598,12 @@ kernel generation process.
 	      if test $? -eq 0	# {
 	      then
 		LSOF_CFGF="$LSOF_CFGF -DHASCPUMASK_T"
+	      else
+		$LSOF_CC -E ${LSOF_INCLUDE}/machine/_types.h 2>/dev/null | grep -q __cpumask_t
+		if test $? -eq 0  # {
+		then
+		  LSOF_CFGF="$LSOF_CFGF -DHASCPUMASK_T"
+		fi	# }
 	      fi	# }
 	    fi	# }
 	  fi	# }
@@ -2344,6 +2367,14 @@ return(0); }
     if test -r ${LSOF_INCLUDE}/netinet/ip6.h	# {
     then
       LSOF_CFGF="$LSOF_CFGF -DHASIPv6"
+    fi	# }
+
+    # Test for SELinux support.
+
+    if test -r ${LSOF_INCLUDE}/selinux/selinux.h	# {
+    then
+      LSOF_CFGF="$LSOF_CFGF -DHASSELINUX"
+      LSOF_CFGL="$LSOF_CFGL -lselinux"
     fi	# }
     LSOF_DIALECT_DIR="linux"
     LSOF_CFGF="$LSOF_CFGF -D_FILE_OFFSET_BITS=64"
@@ -4215,6 +4246,68 @@ return(0); }
       then
 	LSOF_CFGF="$LSOF_CFGF -DHASZONES"
       fi	# }
+
+      # Check for Solaris 10 or higher ZFS.
+
+      if test -r ${LSOF_INCLUDE}/sys/fs/zfs.h	# {
+      then
+	LSOF_TMP1="dmu.h zfs_acl.h zfs_debug.h zfs_rlock.h zil.h spa.h zfs_context.h zfs_dir.h zfs_vfsops.h zio.h txg.h zfs_ctldir.h zfs_ioctl.h zfs_znode.h zio_impl.h"
+	LSOF_TMP2=""
+	for i in $LSOF_TMP1	# {
+	do
+	  if test ! -r /usr/include/sys/$i	# {
+	  then
+	    if test "X$LSOF_TMP2" = "X"	# {
+	    then
+	      LSOF_TMP2=$i
+	    else
+	      LSOF_TMP2="$LSOF_TMP2 $i"
+	    fi	# }
+	  fi	# }
+	done	# }
+	if test "X$LSOF_TMP2" != "X"	# {
+	then
+          LSOF_TMP3=`pwd`/dialects/sun/get-hdr-loc.sh
+          if test ! -x $LSOF_TMP3	# {
+          then
+	    echo "FATAL: can't execute: $LSOF_TMP3"
+	    rm -f $LSOF_HLP
+	    exit 1
+          fi	# }
+          LSOF_TMP4=`$LSOF_TMP3 $LSOF_TMP2`
+	  if test $? -eq 0	# {
+	  then
+
+	  # ZFS support has been requested.
+
+	    if test "X$LSOF_TMP4" = "X"	# {
+	    then
+
+	    # Use of lsof interal ZFS structure definitions has been
+	    # requested.
+
+	      LSOF_CFGF="$LSOF_CFGF -DHAS_ZFS=1"
+	    else
+
+	    # Use of ZFS header files at the returned location has
+	    # been requested.
+
+	      LSOF_CFGF="$LSOF_CFGF -DHAS_ZFS=2 -I$LSOF_TMP4"
+	    fi	# }
+	  else
+
+	  # If there is a message on STDOUT, get-hdr-loc.sh detected
+	  # an error; no message, ZFS support is not required.
+
+	    if test "X$LSOF_TMP4" != "X"	# {
+	    then
+	      echo "$LSOF_TMP3 detected the error: $LSOF_TMP4"
+	      rm -f $LSOF_HLP
+	      exit 1
+	    fi	# }
+	  fi	# }
+	fi	# }
+      fi	# }
       ;;
     *)
       echo "Unsupported Solaris version: $LSOF_VERS"
@@ -4225,7 +4318,6 @@ return(0); }
     LSOF_CFGF="-Dsolaris=$LSOF_VERS $LSOF_CFGF"
 
     # Test for <utmpx.h>
-
     if test -r ${LSOF_INCLUDE}/utmpx.h	# {
     then
       LSOF_CFGF="$LSOF_CFGF -DHASUTMPX"
diff --git a/postfix/postfix/conf/post-install b/postfix/postfix/conf/post-install
--- a/postfix/postfix/conf/post-install
+++ b/postfix/postfix/conf/post-install
@@ -388,7 +388,7 @@ for name in daemon_directory command_directory queue_directory mail_owner \
     sample_directory readme_directory html_directory
 do
     eval test \"\$$name\" = \"`$POSTCONF -c $config_directory -h $name`\" || {
-# apple: B&I workaround: 	override=1
+	override=1
 	break
     }
 done
@@ -473,7 +473,13 @@ test -n "$create" && {
 	test -n "$set_permission" && {
 	    chown $recursive $owner $path || exit 1
 	    test -z "$group" || chgrp $recursive $group $path || exit 1
-	    chmod $recursive $mode $path || exit 1
+	    # Don't "chmod -R"; queue file status is encoded in mode bits.
+	    if [ "$type" = "d" -a -n "$recursive" ]
+	    then
+		find $path -type d -exec chmod $mode "{}" ";"
+	    else
+		chmod $mode $path
+	    fi || exit 1
 	}
     done
     IFS="$BACKUP_IFS"
@@ -564,22 +570,13 @@ EOF
 	}
     done
 
-    # With 20000 active queue files, the active queue directory should
-    # be hashed, and so should the other directories, because they
-    # can contain even more mail.
-    #
-    # Unfortunately, this sucks mailq performance on unloaded systems.
-    #
-    # If you don't want slow mailq, be sure to hash defer and deferred,
-    # because those two directories can contain lots of files.
+    # File systems have improved since Postfix came out, and all we
+    # require now is that defer and deferred are hashed because those
+    # can contain lots of files.
 
     found=`$POSTCONF -c $config_directory -h hash_queue_names`
     missing=
-    (echo "$found" | grep active >/dev/null) || missing="$missing active"
-    (echo "$found" | grep bounce >/dev/null) || missing="$missing bounce"
     (echo "$found" | grep defer >/dev/null)  || missing="$missing defer"
-    (echo "$found" | grep flush >/dev/null)  || missing="$missing flush"
-    (echo "$found" | grep incoming>/dev/null)|| missing="$missing incoming"
     (echo "$found" | grep deferred>/dev/null)|| missing="$missing deferred"
     test -n "$missing" && {
 	echo fixing main.cf hash_queue_names for missing $missing
@@ -589,18 +586,9 @@ EOF
 
     # Turn on safety nets for new features that could bounce mail that
     # would be accepted by a previous Postfix version.
-    # This safety net is also documented in LOCAL_RECIPIENT_README.
 
-    unknown_local=unknown_local_recipient_reject_code
-    has_lrm=`$POSTCONF -n local_recipient_maps`
-    has_lrjc=`$POSTCONF -n $unknown_local`
-
-    if [ -z "$has_lrm" -a -z "$has_lrjc" ]
-    then
-	echo SAFETY: editing main.cf, setting $unknown_local=450.
-	echo See the RELEASE_NOTES and LOCAL_RECIPIENT_README files for details.
-	$POSTCONF -e "$unknown_local = 450" || exit 1
-    fi
+    # [The "unknown_local_recipient_reject_code = 450" safety net,
+    # introduced with Postfix 2.0 and deleted after Postfix 2.3.]
 
     # Add missing proxymap service to master.cf.
 
@@ -613,12 +601,63 @@ EOF
 
     # Add missing anvil service to master.cf.
 
-#    grep '^anvil.*anvil' $config_directory/master.cf >/dev/null || {
-#	echo Editing $config_directory/master.cf, adding missing entry for anvil service
-#	cat >>$config_directory/master.cf <<EOF || exit 1
-#anvil	  unix	-	-	n	-	1	anvil
-#EOF
-#    }
+    grep '^anvil.*anvil' $config_directory/master.cf >/dev/null || {
+	echo Editing $config_directory/master.cf, adding missing entry for anvil service
+	cat >>$config_directory/master.cf <<EOF || exit 1
+anvil	  unix	-	-	n	-	1	anvil
+EOF
+    }
+
+    # Add missing scache service to master.cf.
+
+    grep '^scache.*scache' $config_directory/master.cf >/dev/null || {
+	echo Editing $config_directory/master.cf, adding missing entry for scache service
+	cat >>$config_directory/master.cf <<EOF || exit 1
+scache	  unix	-	-	n	-	1	scache
+EOF
+    }
+
+    # Add missing discard service to master.cf.
+
+    grep '^discard.*discard' $config_directory/master.cf >/dev/null || {
+	echo Editing $config_directory/master.cf, adding missing entry for discard service
+	cat >>$config_directory/master.cf <<EOF || exit 1
+discard	  unix	-	-	n	-	-	discard
+EOF
+    }
+
+    # Update the tlsmgr fifo->unix service.
+
+    grep "^tlsmgr[ 	]*fifo[ 	]" \
+	$config_directory/master.cf >/dev/null && {
+	    echo Editing $config_directory/master.cf, updating the tlsmgr from fifo to unix service
+	    ed $config_directory/master.cf <<EOF || exit 1
+/^tlsmgr[ 	]*fifo[ 	]/
+s/fifo/unix/
+s/[0-9][0-9]*/&?/
+p
+w
+q
+EOF
+    }
+
+    # Add missing tlsmgr service to master.cf.
+
+    grep '^tlsmgr.*tlsmgr' $config_directory/master.cf >/dev/null || {
+	echo Editing $config_directory/master.cf, adding missing entry for tlsmgr service
+	cat >>$config_directory/master.cf <<EOF || exit 1
+tlsmgr    unix  -       -       n       1000?   1       tlsmgr
+EOF
+    }
+
+    # Add missing retry service to master.cf.
+
+    grep '^retry.*error' $config_directory/master.cf >/dev/null || {
+	echo Editing $config_directory/master.cf, adding missing entry for retry service
+	cat >>$config_directory/master.cf <<EOF || exit 1
+retry     unix  -       -       n       -       -       error
+EOF
+    }
 
     # Report (but do not remove) obsolete files.
 
@@ -639,15 +678,16 @@ EOF
 
 test -n "$first_install_reminder" && {
 
-    ALIASES=`$POSTCONF -h alias_database | sed 's/^[^:]*://'`
-    NEWALIASES_PATH=`$POSTCONF -h newaliases_path`
+    ALIASES=`$POSTCONF -c $config_directory -h alias_database | sed 's/^[^:]*://'`
+    NEWALIASES_PATH=`$POSTCONF -c $config_directory -h newaliases_path`
     cat <<EOF | ${FMT}
 
     Warning: you still need to edit myorigin/mydestination/mynetworks
     parameter settings in $config_directory/main.cf.
 
-    See also http://www.postfix.org/faq.html for information about
-    dialup sites or about sites inside a firewalled network.
+    See also http://www.postfix.org/STANDARD_CONFIGURATION_README.html
+    for information about dialup sites or about sites inside a
+    firewalled network.
 
     BTW: Check your $ALIASES file and be sure to set up aliases
     that send mail for root and postmaster to a real person, then
diff --git a/postfix/postfix/makedefs b/postfix/postfix/makedefs
--- a/postfix/postfix/makedefs
+++ b/postfix/postfix/makedefs
@@ -8,7 +8,7 @@
 # SYNOPSIS
 #	\fBmake makefiles \fIname=value...\fR
 # DESCRIPTION
-#	The \fBmakedefs\fR command identifies the program compilation
+#	The \fBmakedefs\fR command identifies the compilation
 #	environment, and emits macro definitions on the standard output
 #	stream that can be prepended to template Makefiles.
 #
@@ -23,6 +23,29 @@
 # .IP \fBCCARGS=\fIcompiler_arguments\fR
 #	Specifies non-default compiler arguments, for example, a non-default
 #	\fIinclude\fR directory.
+#	The following directives are special:
+# .RS
+# .IP \fB-DNO_DEVPOLL\fR
+#	Do not build with Solaris /dev/poll support.
+#	By default, /dev/poll support is compiled in on platforms that
+#	are known to support it.
+# .IP \fB-DNO_EPOLL\fR
+#	Do not build with Linux EPOLL support.
+#	By default, EPOLL support is compiled in on platforms that
+#	are known to support it.
+# .IP \fB-DNO_KQUEUE\fR
+#	Do not build with FreeBSD/NetBSD/OpenBSD KQUEUE support.
+#	By default, KQUEUE support is compiled in on platforms that
+#	are known to support it.
+# .IP \fB-DNO_IPV6\fR
+#	Do not build with IPv6 support.
+#	By default, IPv6 support is compiled in on platforms that
+#	are known to have IPv6 support.
+# .IP \fB-DNO_PCRE\fR
+#	Do not build with PCRE support.
+#	By default, PCRE support is compiled in when the \fBpcre-config\fR
+#	utility is installed.
+# .RE
 # .IP \fBDEBUG=\fIdebug_level\fR
 #	Specifies a non-default debugging level. The default is \fB-g\fR.
 #	Specify \fBDEBUG=\fR to turn off debugging.
@@ -51,6 +74,19 @@ RANLIB=ranlib
 SYSLIBS=
 AR=ar
 ARFL=rv
+
+# Ugly function to make our error message more visible among the
+# garbage that is output by some versions of make(1).
+
+# By now all shells must have functions.
+
+error() {
+   # Alas, tput(1) is not portable so we can't use visual effects.
+   echo "ATTENTION:" 1>&2;
+   echo "ATTENTION:" $* 1>&2;
+   echo "ATTENTION:" 1>&2;
+   exit 1
+}
 
 SYSTEM=`(uname -s) 2>/dev/null`
 RELEASE=`(uname -r) 2>/dev/null`
@@ -81,8 +117,7 @@ case "$SYSTEM.$RELEASE" in
 		    RANLIB=echo
 		    SYSLIBS="-lresolv -lsocket -lnsl -lc -L/usr/ucblib -lucb"
 		    ;;
-	      *) echo "Seems to be UnixWare`uname -v`. Untested." 1>&2; 
-		 exit 1;;
+	      *) error "Seems to be UnixWare`uname -v`. Untested.";;
 		esac
 		;;
   FreeBSD.2*)	SYSTYPE=FREEBSD2
@@ -93,15 +128,23 @@ case "$SYSTEM.$RELEASE" in
 		;;
   FreeBSD.5*)	SYSTYPE=FREEBSD5
 		;;
+  FreeBSD.6*)	SYSTYPE=FREEBSD6
+		;;
   OpenBSD.2*)	SYSTYPE=OPENBSD2
 		;;
   OpenBSD.3*)	SYSTYPE=OPENBSD3
+		;;
+  OpenBSD.4*)	SYSTYPE=OPENBSD4
 		;;
   ekkoBSD.1*)	SYSTYPE=EKKOBSD1
 		;;
    NetBSD.1*)	SYSTYPE=NETBSD1
 		;;
    NetBSD.2*)	SYSTYPE=NETBSD2
+		;;
+   NetBSD.3*)	SYSTYPE=NETBSD3
+		;;
+   NetBSD.4*)	SYSTYPE=NETBSD4
 		;;
    BSD/OS.2*)	SYSTYPE=BSDI2
 		;;
@@ -113,6 +156,9 @@ case "$SYSTEM.$RELEASE" in
 		# Use the native compiler by default
 		: ${CC=cc}
 		: ${DEBUG="-g3"}
+		case $RELEASE in
+		V[0-4].*) CCARGS="$CCARGS -DNO_IPV6";;
+		esac
 		;;
     SunOS.4*)	SYSTYPE=SUNOS4
 		SYSLIBS=-lresolv
@@ -120,9 +166,17 @@ case "$SYSTEM.$RELEASE" in
     SunOS.5*)	SYSTYPE=SUNOS5
 		RANLIB=echo
 		SYSLIBS="-lresolv -lsocket -lnsl"
+		# Solaris 5 added usleep() and POSIX regular expressions
 		case $RELEASE in
-		    5.[0-4]) CCARGS="$CCARGS -DMISSING_USLEEP";;
-			  *) CCARGS="$CCARGS -DHAS_POSIX_REGEXP";;
+		    5.[0-4]) CCARGS="$CCARGS -DMISSING_USLEEP -DNO_POSIX_REGEXP";;
+		esac
+		# Solaris 8 added IPv6 and /dev/poll
+		case $RELEASE in
+		    5.[0-7]|5.[0-7].*) CCARGS="$CCARGS -DNO_IPV6 -DNO_DEVPOLL";;
+		esac
+		# Solaris 9 added closefrom(), futimesat() and /dev/*random
+		case $RELEASE in
+		    5.[0-8]|5.[0-8].*) CCARGS="$CCARGS -DNO_CLOSEFROM -DNO_DEV_URANDOM -DNO_FUTIMESAT";;
 		esac
 		# Work around broken str*casecmp(). Do it all here instead
 		# of having half the solution in the sys_defs.h file.
@@ -131,12 +185,13 @@ case "$SYSTEM.$RELEASE" in
 		STRCASE="strcasecmp.o"
 		# Avoid common types of braindamage
 		case "$LD_LIBRARY_PATH" in
-		?*) echo "Don't set LD_LIBRARY_PATH" 1>&2; exit 1;;
+		?*) error "Don't set LD_LIBRARY_PATH";;
 		esac
-		case "$CC" in
-		*ucb*) echo "Don't use /usr/ucb/cc or ucblib" 1>&2; exit 1;;
-		  cc*) case `which cc` in
-		*ucb*) echo "Don't use /usr/ucb/cc or ucblib" 1>&2; exit 1;;
+		case "${CC}" in
+		*" "*) ;;
+		*ucb*) error "Don't use /usr/ucb/cc or ucblib";;
+		  cc*) case `which ${CC}` in
+		*ucb*) error "Don't use /usr/ucb/cc or ucblib";;
 		  esac;;
 		esac
 		;;
@@ -155,7 +210,7 @@ case "$SYSTEM.$RELEASE" in
 		done
 		;;
        AIX.*)	case "`uname -v`" in
-		5)	SYSTYPE=AIX4
+		5)	SYSTYPE=AIX5
 			case "$CC" in
 			cc|*/cc|xlc|*/xlc) CCARGS="$CCARGS -w -blibpath:/usr/lib:/lib:/usr/local/lib";;
 			esac
@@ -175,7 +230,7 @@ case "$SYSTEM.$RELEASE" in
 			esac
 			CCARGS="$CCARGS -D_ALL_SOURCE"
 			;;
-		*)	echo "Unknown AIX version: `uname -v`." 1>&2; exit 1;;
+		*)	error "Unknown AIX version: `uname -v`.";;
 		esac;;
 		# Tested with RedHat 3.03 on 20020729.
     Linux.1*)	SYSTYPE=LINUX1
@@ -219,6 +274,50 @@ case "$SYSTEM.$RELEASE" in
 			}
 		    done
 		done
+		# Kernel 2.4 added IPv6
+		case "$RELEASE" in
+		2.[0-3].*) CCARGS="$CCARGS -DNO_IPV6";;
+		esac
+		# Kernel 2.6 added EPOLL
+		case "$RELEASE" in
+		2.[0-5].*) CCARGS="$CCARGS -DNO_EPOLL";;
+		esac
+		;;
+     GNU.0*|GNU/kFreeBSD.[56]*)
+     		SYSTYPE=GNU0
+		# Postfix no longer needs DB 1.85 compatibility
+		if [ -f /usr/include/db.h ]
+		then
+		    : we are all set
+		elif [ -f /usr/include/db/db.h ]
+		then
+		    CCARGS="$CCARGS -I/usr/include/db"
+		else
+		    # No, we're not going to try db1 db2 db3 etc.
+		    # On a properly installed system, Postfix builds
+		    # by including <db.h> and by linking with -ldb
+		    echo "No <db.h> include file found." 1>&2
+		    echo "Install the appropriate db*-devel package first." 1>&2
+		    echo "See the RELEASE_NOTES file for more information." 1>&2
+		    exit 1
+		fi
+		SYSLIBS="-ldb"
+		for name in nsl resolv
+		do
+		    for lib in /usr/lib64 /lib64 /usr/lib /lib
+		    do
+			test -e $lib/lib$name.a -o -e $lib/lib$name.so && {
+			    SYSLIBS="$SYSLIBS -l$name"
+			    break
+			}
+		    done
+		done
+		case "`uname -s`" in
+		GNU)
+			# currently no IPv6 support on Hurd
+			CCARGS="$CCARGS -DNO_IPV6"
+			;;
+		esac
 		;;
      IRIX*.5.*)	SYSTYPE=IRIX5
 		# Use the native compiler by default
@@ -263,8 +362,10 @@ Rhapsody.5*|Darwin.*)
 		: ${CC=cc}
 		case $RELEASE in
 		 1.[0-3]) AWK=gawk
+			  CCARGS="$CCARGS -DNO_IPV6"
 			  ;;
 		 [2-6].*) AWK=awk
+			  CCARGS="$CCARGS -DNO_IPV6"
 			  SYSLIBS=-flat_namespace
 			  ;;
 		       *) AWK=awk
@@ -293,11 +394,25 @@ Rhapsody.5*|Darwin.*)
 		    : ${CC=cc}
 		    RANLIB="sleep 5; ranlib"
 		else
-		    echo "Unable to determine your system type." 1>&2; exit 1
+		    error "Unable to determine your system type."
 		fi
 		;;
-	   *)	echo "Unknown system type: $SYSTEM $RELEASE" 1>&2; exit 1;;
+	   *)	error "Unknown system type: $SYSTEM $RELEASE";;
 esac
+
+#
+# OpenSSL has no configuration query utility, but we don't try to
+# guess. We assume includes in /usr/include/openssl and libraries in
+# /usr/lib, or in their /usr/local equivalents. If the OpenSSL files
+# are in a non-standard place, their locations need to be specified.
+#
+#case "$CCARGS" in
+# *-DUSE_TLS*)	;;
+#  *-DNO_TLS*)	;;
+#           *)	CCARGS="$CCARGS -DUSE_TLS"
+#		AUXLIBS="$AUXLIBS -lssl -lcrypto"
+#		;;
+#esac
 
 #
 # PCRE 3.x has a pcre-config utility so we don't have to guess.
@@ -323,16 +438,29 @@ case "$CC" in
 */gcc|gcc) case `$CC -v` in
 	   "gcc version 2.8"*) : ${OPT=};;
 	   esac;;
-      *CC) echo "Don't use CC. That's the C++ compiler" 1>&2; exit 1;;
+      *CC) error "Don't use CC. That's the C++ compiler";;
         *) : ${OPT='-O'};;
 esac
+#
+# "gcc -W" 3.4.2 no longer reports functions that fail to return a
+# result.  Use "gcc -Wall -Wno-comment" instead. We'll figure out
+# later if the other -Wmumble options are really redundant. Having
+# een burned once by a compiler that lies about what warnings it
+# produces, not taking that chance again.
 
 : ${CC='gcc $(WARN)'} ${OPT='-O'} ${DEBUG='-g'} ${AWK=awk} \
-${WARN='-W -Wformat -Wimplicit -Wmissing-prototypes \
+${WARN='-Wall -Wno-comment -Wformat -Wimplicit -Wmissing-prototypes \
 	-Wparentheses -Wstrict-prototypes -Wswitch -Wuninitialized \
 	-Wunused'}
 
 export SYSTYPE AR ARFL RANLIB SYSLIBS CC OPT DEBUG AWK OPTS
+
+# Snapshot only.
+#CCARGS="$CCARGS -DSNAPSHOT"
+
+# Non-production: needs thorough testing, or major changes are still
+# needed before the code stabilizes.
+#CCARGS="$CCARGS -DNONPROD"
 
 sed 's/  / /g' <<EOF
 SYSTYPE	= $SYSTYPE
diff --git a/tcl/tcl_ext/incrtcl/incrTcl.diff b/tcl/tcl_ext/incrtcl/incrTcl.diff
--- a/tcl/tcl_ext/incrtcl/incrTcl.diff
+++ b/tcl/tcl_ext/incrtcl/incrTcl.diff
@@ -415,7 +415,7 @@ diff -rupN --exclude=CVS --exclude=.cvsignore orig/incrTcl/config/mkinstalldirs 
 +# Created: 1993-05-16
 +# Public domain
 +
-+# $Id: incrTcl.diff,v 1.2 2004/08/20 18:39:29 tpeterso Exp $
++# $Id: incrTcl.diff,v 1.3 2006/04/17 20:47:04 bbyer Exp $
 +
 +errstatus=0
 +
@@ -449,3 +449,102 @@ diff -rupN --exclude=CVS --exclude=.cvsignore orig/incrTcl/config/mkinstalldirs 
 +exit $errstatus
 +
 +# mkinstalldirs ends here
+diff -rupN --exclude=CVS --exclude=.cvsignore orig/incrTcl/tcl.m4 incrTcl/tcl.m4
+--- tcl.m4	2003-04-04 12:57:42.000000000 -0800
++++ tcl.m4	2006-04-17 13:23:51.000000000 -0700
+@@ -2575,7 +2575,7 @@
+ 	MAKE_STUB_LIB="\${STLIB_LD} -out:\[$]@ \$(\[$](PACKAGE)stub_OBJECTS)"
+     else
+ 	MAKE_STATIC_LIB="\${STLIB_LD} \[$]@ \$(\[$](PACKAGE)_OBJECTS)"
+-	MAKE_SHARED_LIB="\${SHLIB_LD} -o \[$]@ \$(\[$](PACKAGE)_OBJECTS) \${SHLIB_LDFLAGS} \${SHLIB_LD_LIBS}"
++	MAKE_SHARED_LIB="\${SHLIB_LD} -o \[$]@ \$(\[$](PACKAGE)_OBJECTS) \${SHLIB_LDFLAGS} \${SHLIB_LD_LIBS} \${TCL_SHLIB_LD_EXTRAS}"
+ 	MAKE_STUB_LIB="\${STLIB_LD} \[$]@ \$(\[$](PACKAGE)stub_OBJECTS)"
+     fi
+ 
+--- itk/Makefile.in.old	2006-07-10 18:20:36.000000000 -0700
++++ itk/Makefile.in	2006-07-10 18:21:48.000000000 -0700
+@@ -259,6 +259,7 @@
+ 
+ install-doc: doc
+ 	@mkdir -p $(DESTDIR)$(mandir)/mann
++	mv $(srcdir)/doc/Widget.n $(srcdir)/doc/itkWidget.n
+ 	@echo "Installing man pages in $(DESTDIR)$(mandir)"
+ 	@for i in $(srcdir)/doc/*.n; do \
+ 	    echo "Installing $$i"; \
+--- itcl/configure~	2003-04-04 12:57:42.000000000 -0800
++++ itcl/configure	2007-01-30 17:11:28.000000000 -0800
+@@ -1399,34 +1399,6 @@
+ OBJEXT=$ac_cv_objext
+ ac_objext=$ac_cv_objext
+ 
+-    
+-
+-echo $ac_n "checking for executable suffix""... $ac_c" 1>&6
+-echo "configure:1406: checking for executable suffix" >&5
+-if eval "test \"`echo '$''{'ac_cv_exeext'+set}'`\" = set"; then
+-  echo $ac_n "(cached) $ac_c" 1>&6
+-else
+-  if test "$CYGWIN" = yes || test "$MINGW32" = yes; then
+-  ac_cv_exeext=.exe
+-else
+-  rm -f conftest*
+-  echo 'int main () { return 0; }' > conftest.$ac_ext
+-  ac_cv_exeext=
+-  if { (eval echo configure:1416: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; }; then
+-    for file in conftest.*; do
+-      case $file in
+-      *.c | *.o | *.obj) ;;
+-      *) ac_cv_exeext=`echo $file | sed -e s/conftest//` ;;
+-      esac
+-    done
+-  else
+-    { echo "configure: error: installation or configuration problem: compiler cannot create executables." 1>&2; exit 1; }
+-  fi
+-  rm -f conftest*
+-  test x"${ac_cv_exeext}" = x && ac_cv_exeext=no
+-fi
+-fi
+-
+ EXEEXT=""
+ test x"${ac_cv_exeext}" != xno && EXEEXT=${ac_cv_exeext}
+ echo "$ac_t""${ac_cv_exeext}" 1>&6
+
+diff -c /Network/Servers/hills/Volumes/tienda/bbyer/work/tcl/tcl_ext/incrtcl/incrTcl/itk/configure\~ /Network/Servers/hills/Volumes/tienda/bbyer/work/tcl/tcl_ext/incrtcl/incrTcl/itk/configure
+--- itk/configure~	2003-04-04 12:57:43.000000000 -0800
++++ itk/configure	2007-01-30 19:16:19.000000000 -0800
+@@ -1405,34 +1405,6 @@
+ OBJEXT=$ac_cv_objext
+ ac_objext=$ac_cv_objext
+ 
+-    
+-
+-echo $ac_n "checking for executable suffix""... $ac_c" 1>&6
+-echo "configure:1412: checking for executable suffix" >&5
+-if eval "test \"`echo '$''{'ac_cv_exeext'+set}'`\" = set"; then
+-  echo $ac_n "(cached) $ac_c" 1>&6
+-else
+-  if test "$CYGWIN" = yes || test "$MINGW32" = yes; then
+-  ac_cv_exeext=.exe
+-else
+-  rm -f conftest*
+-  echo 'int main () { return 0; }' > conftest.$ac_ext
+-  ac_cv_exeext=
+-  if { (eval echo configure:1422: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; }; then
+-    for file in conftest.*; do
+-      case $file in
+-      *.c | *.o | *.obj) ;;
+-      *) ac_cv_exeext=`echo $file | sed -e s/conftest//` ;;
+-      esac
+-    done
+-  else
+-    { echo "configure: error: installation or configuration problem: compiler cannot create executables." 1>&2; exit 1; }
+-  fi
+-  rm -f conftest*
+-  test x"${ac_cv_exeext}" = x && ac_cv_exeext=no
+-fi
+-fi
+-
+ EXEEXT=""
+ test x"${ac_cv_exeext}" != xno && EXEEXT=${ac_cv_exeext}
+ echo "$ac_t""${ac_cv_exeext}" 1>&6
+
diff --git a/vim/vim/src/vimtutor b/vim/vim/src/vimtutor
--- a/vim/vim/src/vimtutor
+++ b/vim/vim/src/vimtutor
@@ -10,13 +10,34 @@
 xx=$1
 export xx
 
-# Use Vim to copy the tutor, it knows the value of $VIMRUNTIME
+# We need a temp file for the copy.  First try using a standard command.
 tmp="${TMPDIR-/tmp}"
-TUTORCOPY=`mktemp $tmp/tutorXXXXXX || tempfile -p tutor || echo $tmp/tutor$$`
+TUTORCOPY=`mktemp $tmp/tutorXXXXXX || tempfile -p tutor || echo none`
+
+# If the standard commands failed then create a directory to put the copy in.
+# That is a secure way to make a temp file.
+if test "$TUTORCOPY" = none; then
+	tmpdir=$tmp/vimtutor$$
+	OLD_UMASK=`umask`
+	umask 077
+	getout=no
+	mkdir $tmpdir || getout=yes
+	umask $OLD_UMASK
+	if test $getout = yes; then
+		echo "Could not create directory for tutor copy, exiting."
+		exit 1
+	fi
+	TUTORCOPY=$tmpdir/tutorcopy
+	touch $TUTORCOPY
+	TODELETE=$tmpdir
+else
+	TODELETE=$TUTORCOPY
+fi
+
 export TUTORCOPY
 
 # remove the copy of the tutor on exit
-trap "rm -f $TUTORCOPY" 0 1 2 3 9 11 13 15
+trap "rm -rf $TODELETE" 0 1 2 3 9 11 13 15
 
 # Vim could be called "vim" or "vi".  Also check for "vim6", for people who
 # have Vim 5.x installed as "vim" and Vim 6.0 as "vim6".
@@ -32,6 +53,7 @@ else
 	fi
 fi
 
+# Use Vim to copy the tutor, it knows the value of $VIMRUNTIME
 # The script tutor.vim tells Vim which file to copy
 $VIM -u NONE -c 'so $VIMRUNTIME/tutor/tutor.vim'
 
