10.3

diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test003-search b/OpenLDAP/OpenLDAP/tests/scripts/test003-search
--- a/OpenLDAP/OpenLDAP/tests/scripts/test003-search
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test003-search
@@ -1,5 +1,5 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test003-search,v 1.34 2002/02/09 22:04:18 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test003-search,v 1.34.2.10 2003/03/24 03:10:14 kurt Exp $
 
 SRCDIR="."
 if test $# -ge 1 ; then
@@ -8,6 +8,10 @@ fi
 BACKEND=bdb
 if test $# -ge 1 ; then
 	BACKEND=$1; shift
+fi
+MONITORDB=no
+if test $# -ge 1 ; then
+	MONITORDB=$1; shift
 fi
 WAIT=0
 if test $# -ge 1 ; then
@@ -22,7 +26,7 @@ echo "Cleaning up in $DBDIR..."
 rm -f $DBDIR/[!C]*
 
 echo "Running slapadd to build slapd database..."
-. $CONFFILTER $BACKEND < $MCONF > $ADDCONF
+. $CONFFILTER $BACKEND $MONITORDB < $MCONF > $ADDCONF
 $SLAPADD -f $ADDCONF -l $LDIFORDERED
 RC=$?
 if test $RC != 0 ; then
@@ -31,7 +35,7 @@ if test $RC != 0 ; then
 fi
 
 echo "Running slapindex to index slapd database..."
-. $CONFFILTER $BACKEND < $CONF > $DBCONF
+. $CONFFILTER $BACKEND $MONITORDB < $CONF > $DBCONF
 $SLAPINDEX -f $DBCONF
 RC=$?
 if test $RC != 0 ; then
@@ -50,12 +54,13 @@ fi
 echo "Testing slapd searching..."
 for i in 0 1 2 3 4 5; do
 	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT \
-		'objectclass=*' > /dev/null 2>&1
+		'(objectclass=*)' > /dev/null 2>&1
 	RC=$?
-	if test $RC = 1 ; then
-		echo "Waiting 5 seconds for slapd to start..."
-		sleep 5
+	if test $RC = 0 ; then
+		break
 	fi
+	echo "Waiting 5 seconds for slapd to start..."
+	sleep 5
 done
 
 if test $RC != 0 ; then
@@ -68,7 +73,8 @@ cat /dev/null > $SEARCHOUT
 
 echo "Testing exact searching..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT \
-	'sn=jensen' >> $SEARCHOUT 2>&1
+	'(sn=jENSEN)' >> $SEARCHOUT 2>&1
+RC=$?
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
 	kill -HUP $PID
@@ -77,7 +83,8 @@ fi
 
 echo "Testing OR searching..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT \
-	'(|(undefined=fubar)(objectclass=groupofnames)(sn=jones))' >> $SEARCHOUT 2>&1
+	'(|(givenname=Xx*yY*Z)(cn=)(undef=*)(objectclass=groupofnames)(sn=jones)(member=cn=Manager,o=University of Michigan,c=US))' >> $SEARCHOUT 2>&1
+RC=$?
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
 	kill -HUP $PID
@@ -85,8 +92,9 @@ if test $RC != 0 ; then
 fi
 
 echo "Testing AND matching and ends-with searching..."
-$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT \
-	'(&(objectclass=groupofnames)(cn=A*))' >> $SEARCHOUT 2>&1
+$LDAPSEARCH -S "" -b "ou=groups,$BASEDN" -s one -h $LOCALHOST -p $PORT \
+	'(&(objectclass=groupofnames)(cn=A*)(member=cn=Mark Elliot,ou=Alumni Association,ou=People,o=University of Michigan,c=US))' >> $SEARCHOUT 2>&1
+RC=$?
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
 	kill -HUP $PID
@@ -96,14 +104,26 @@ fi
 echo "Testing NOT searching..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT \
 	'(!(objectclass=pilotPerson))' >> $SEARCHOUT 2>&1
+RC=$?
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
 	kill -HUP $PID
 	exit $RC
 fi
 
-kill -HUP $PID
+echo "Testing objectClass/attributeType inheritance ..."
+$LDAPSEARCH -M -a never -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT \
+	'(&(objectClass=inetorgperson)(userid=uham))' \
+	"2.5.4.0" "userid" >> $SEARCHOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	kill -HUP $PID
+	exit $RC
+fi
 
+
+kill -HUP $PID
 LDIF=$SEARCHOUTMASTER
 
 echo "Filtering ldapsearch results..."
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test009-referral b/OpenLDAP/OpenLDAP/tests/scripts/test009-referral
--- a/OpenLDAP/OpenLDAP/tests/scripts/test009-referral
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test009-referral
@@ -1,5 +1,5 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test009-referral,v 1.20 2002/02/09 22:12:30 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test009-referral,v 1.20.2.5 2002/09/24 00:05:01 kurt Exp $
 
 SRCDIR="."
 if test $# -ge 1 ; then
@@ -8,6 +8,10 @@ fi
 BACKEND=bdb
 if test $# -ge 1 ; then
 	BACKEND=$1; shift
+fi
+MONITORDB=no
+if test $# -ge 1 ; then
+	MONITORDB=$1; shift
 fi
 WAIT=0
 if test $# -ge 1 ; then
@@ -28,7 +32,7 @@ rm -f $DBDIR/[!C]*
 rm -f $REPLDIR/[!C]*
 
 echo "Running slapadd to build slapd database..."
-. $CONFFILTER $BACKEND < $CONF > $DBCONF
+. $CONFFILTER $BACKEND $MONITORDB < $CONF > $DBCONF
 $SLAPADD -f $DBCONF -l $LDIFORDERED
 RC=$?
 if test $RC != 0 ; then
@@ -45,7 +49,7 @@ if test $WAIT != 0 ; then
 fi
 
 echo "Starting slave slapd on TCP/IP port $SLAVEPORT..."
-. $CONFFILTER $BACKEND < $REFSLAVECONF > $REPLCONF
+. $CONFFILTER $BACKEND $MONITORDB < $REFSLAVECONF > $REPLCONF
 $SLAPD -n slave -f $REPLCONF -h $SLAVEURI -d $LVL $TIMING > $SLAVELOG 2>&1 &
 SLAVEPID=$!
 if test $WAIT != 0 ; then
@@ -58,10 +62,11 @@ for i in 0 1 2 3 4 5; do
 	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT \
 		'objectclass=*' > /dev/null 2>&1
 	RC=$?
-	if test $RC = 1 ; then
-		echo "Waiting 5 seconds for slapd to start..."
-		sleep 5
+	if test $RC = 0 ; then
+		break
 	fi
+	echo "Waiting 5 seconds for slapd to start..."
+	sleep 5
 done
 
 if test $RC != 0 ; then
@@ -75,10 +80,11 @@ for i in 0 1 2 3 4 5; do
 	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $SLAVEPORT \
 		'objectclass=*' > /dev/null 2>&1
 	RC=$?
-	if test $RC = 1 ; then
-		echo "Waiting 5 seconds for slapd to start..."
-		sleep 5
+	if test $RC = 0 ; then
+		break
 	fi
+	echo "Waiting 5 seconds for slapd to start..."
+	sleep 5
 done
 
 cat /dev/null > $SEARCHOUT
@@ -86,6 +92,7 @@ cat /dev/null > $SEARCHOUT
 echo "Testing exact searching..."
 $LDAPSEARCH -C -S "" -b "$BASEDN" -h $LOCALHOST -p $SLAVEPORT \
 	'sn=jensen' >> $SEARCHOUT 2>&1
+RC=$?
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
 	kill -HUP $PID $SLAVEPID
@@ -95,6 +102,7 @@ fi
 echo "Testing OR searching..."
 $LDAPSEARCH -C -S "" -b "$BASEDN" -h $LOCALHOST -p $SLAVEPORT \
 	'(|(objectclass=groupofnames)(sn=jones))' >> $SEARCHOUT 2>&1
+RC=$?
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
 	kill -HUP $PID $SLAVEPID
@@ -102,8 +110,9 @@ if test $RC != 0 ; then
 fi
 
 echo "Testing AND matching and ends-with searching..."
-$LDAPSEARCH -C -S "" -b "$BASEDN" -h $LOCALHOST -p $SLAVEPORT \
+$LDAPSEARCH -C -S "" -b "ou=groups,$BASEDN" -s one -h $LOCALHOST -p $SLAVEPORT \
 	'(&(objectclass=groupofnames)(cn=A*))' >> $SEARCHOUT 2>&1
+RC=$?
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
 	kill -HUP $PID $SLAVEPID
@@ -113,11 +122,24 @@ fi
 echo "Testing NOT searching..."
 $LDAPSEARCH -C -S "" -b "$BASEDN" -h $LOCALHOST -p $SLAVEPORT \
 	'(!(objectclass=pilotPerson))' >> $SEARCHOUT 2>&1
+RC=$?
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
 	kill -HUP $PID $SLAVEPID
 	exit $RC
 fi
+
+echo "Testing objectClass/attributeType inheritance ..."
+$LDAPSEARCH -M -a never -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT \
+	'(&(objectClass=inetorgperson)(userid=uham))' \
+	"2.5.4.0" "userid" >> $SEARCHOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	kill -HUP $PID
+	exit $RC
+fi
+
 
 kill -HUP $PID $SLAVEPID
 
diff --git a/cups/cups.sh.in b/cups/cups.sh.in
--- a/cups/cups.sh.in
+++ b/cups/cups.sh.in
@@ -1,10 +1,10 @@
 #!/bin/sh
 #
-# "$Id: cups.sh.in,v 1.5 2002/06/10 23:47:23 jlovell Exp $"
+# "$Id: cups.sh.in,v 1.1.1.8 2002/12/24 00:04:32 jlovell Exp $"
 #
 #   Startup/shutdown script for the Common UNIX Printing System (CUPS).
 #
-#   Copyright 1997-2002 by Easy Software Products, all rights reserved.
+#   Copyright 1997-2003 by Easy Software Products, all rights reserved.
 #
 #   These coded instructions, statements, and computer programs are the
 #   property of Easy Software Products and are protected by Federal
@@ -47,10 +47,21 @@
 case "`uname`" in
 	IRIX*)
 		IS_ON=/sbin/chkconfig
+
+		if $IS_ON verbose; then
+			ECHO=echo
+		else
+			ECHO=:
+		fi
+		ECHO_OK=:
+		ECHO_ERROR=:
 		;;
 
 	*BSD*)
         	IS_ON=:
+		ECHO=echo
+		ECHO_OK=:
+		ECHO_ERROR=:
 		;;
 
 	Darwin*)
@@ -61,44 +72,59 @@ case "`uname`" in
 		fi
 
         	IS_ON=:
+		ECHO=ConsoleMessage
+		ECHO_OK=:
+		ECHO_ERROR=:
 		;;
 
 	Linux*)
-		# Set the timezone, if possible...
-		if test -f /etc/TIMEZONE; then
-                        . /etc/TIMEZONE
-                else
-			if test -f /etc/sysconfig/clock; then
-	                        . /etc/sysconfig/clock
-        	                TZ="$ZONE"
-                	        export TZ
-			fi
-                fi
-
 		IS_ON=/bin/true
+		if test -f /etc/init.d/functions; then
+			. /etc/init.d/functions
+			ECHO=echo
+			ECHO_OK="echo_success"
+			ECHO_ERROR="echo_failure"
+		else
+			ECHO=echo
+			ECHO_OK=:
+			ECHO_ERROR=:
+		fi
 		;;
 
 	*)
 		IS_ON=/bin/true
+		ECHO=echo
+		ECHO_OK=:
+		ECHO_ERROR=:
 		;;
 esac
 
 #### OS-Independent Stuff
 
 #
-# The verbose flag controls the printing of the names of
-# daemons as they are started.  Currently always echos for
-# all but IRIX, which can configure verbose bootup messages.
+# Set the timezone, if possible...  This allows the
+# scheduler and all child processes to know the local
+# timezone when reporting dates and times to the user. 
+# If no timezone information is found, then Greenwich
+# Mean Time (GMT) will probably be used.
 #
 
-if test "`uname`" = "Darwin"; then
-	ECHO=ConsoleMessage
-else
-	if $IS_ON verbose; then
-		ECHO=echo
-	else
-		ECHO=:
+for file in /etc/TIMEZONE /etc/rc.config /etc/sysconfig/clock; do
+	if test -f $file; then
+	        . $file
 	fi
+done
+
+if test "x$ZONE" != x; then
+	TZ="$ZONE"
+fi
+
+if test "x$TIMEZONE" != x; then
+	TZ="$TIMEZONE"
+fi
+
+if test "x$TZ" != x; then
+	export TZ
 fi
 
 #
@@ -140,25 +166,30 @@ case $1 in
 				prefix=@prefix@
 				exec_prefix=@exec_prefix@
 				@sbindir@/cupsd
+				if test $? != 0; then
+					$ECHO_FAIL
+					$ECHO "cups: unable to $1 scheduler."
+					exit 1
+				fi
 			fi
-			$ECHO "cups: scheduler ${1}ed."
-		else
-			$ECHO "cups: scheduler stopped."
+			$ECHO_OK
+			$ECHO "cups: ${1}ed scheduler."
 		fi
 		;;
 
 	stop)
 		if test "$pid" != ""; then
 			kill $pid
-			$ECHO "cups: scheduler stopped."
+			$ECHO_OK
+			$ECHO "cups: stopped scheduler."
 		fi
 		;;
 
 	status)
 		if test "$pid" != ""; then
-			echo "cups: Scheduler is running."
+			echo "cups: scheduler is running."
 		else
-			echo "cups: Scheduler is not running."
+			echo "cups: scheduler is not running."
 		fi
 		;;
 
@@ -176,5 +207,5 @@ exit 0
 
 
 #
-# End of "$Id: cups.sh.in,v 1.5 2002/06/10 23:47:23 jlovell Exp $".
+# End of "$Id: cups.sh.in,v 1.1.1.8 2002/12/24 00:04:32 jlovell Exp $".
 #
diff --git a/curl/curl/reconf b/curl/curl/reconf
--- a/curl/curl/reconf
+++ b/curl/curl/reconf
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: reconf,v 1.1.1.1 2001/02/15 19:52:28 wsanchez Exp $
+# $Id: reconf,v 1.1.1.2 2002/11/26 19:07:40 zarzycki Exp $
 #
 # re autoconf/automake shell script
 #
@@ -9,7 +9,7 @@ die(){
 	echo "$@" ; exit
 }
 
-aclocal -I .	|| die "ahhhhh"
-autoheader	|| die "ahhhhh"
-automake	|| die "ahhhhh"
-autoconf	|| die "ahhhhh"
+aclocal -I . || die "The command 'aclocal -I .' failed"
+autoheader   || die "The command 'autoheader' failed"
+automake     || die "The command 'automake' failed"
+autoconf     || die "The command 'autoconf' failed"
