10.4

diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test003-search b/OpenLDAP/OpenLDAP/tests/scripts/test003-search
--- a/OpenLDAP/OpenLDAP/tests/scripts/test003-search
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test003-search
@@ -1,29 +1,22 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test003-search,v 1.34.2.10 2003/03/24 03:10:14 kurt Exp $
-
-SRCDIR="."
-if test $# -ge 1 ; then
-	SRCDIR=$1; shift
-fi
-BACKEND=bdb
-if test $# -ge 1 ; then
-	BACKEND=$1; shift
-fi
-MONITORDB=no
-if test $# -ge 1 ; then
-	MONITORDB=$1; shift
-fi
-WAIT=0
-if test $# -ge 1 ; then
-	WAIT=1; shift
-fi
+# $OpenLDAP: pkg/ldap/tests/scripts/test003-search,v 1.48.2.5 2004/04/12 18:21:08 kurt Exp $
+## This work is part of OpenLDAP Software <http://www.openldap.org/>.
+##
+## Copyright 1998-2004 The OpenLDAP Foundation.
+## All rights reserved.
+##
+## Redistribution and use in source and binary forms, with or without
+## modification, are permitted only as authorized by the OpenLDAP
+## Public License.
+##
+## A copy of this license is available in the file LICENSE in the
+## top-level directory of the distribution or, alternatively, at
+## <http://www.OpenLDAP.org/license.html>.
 
 echo "running defines.sh"
 . $SRCDIR/scripts/defines.sh
 
-echo "Cleaning up in $DBDIR..."
-
-rm -f $DBDIR/[!C]*
+mkdir -p $TESTDIR $DBDIR1
 
 echo "Running slapadd to build slapd database..."
 . $CONFFILTER $BACKEND $MONITORDB < $MCONF > $ADDCONF
@@ -35,25 +28,26 @@ if test $RC != 0 ; then
 fi
 
 echo "Running slapindex to index slapd database..."
-. $CONFFILTER $BACKEND $MONITORDB < $CONF > $DBCONF
-$SLAPINDEX -f $DBCONF
+. $CONFFILTER $BACKEND $MONITORDB < $CONF > $CONF1
+$SLAPINDEX -f $CONF1
 RC=$?
 if test $RC != 0 ; then
 	echo "warning: slapindex failed ($RC)"
 	echo "  assuming no indexing support"
 fi
 
-echo "Starting slapd on TCP/IP port $PORT..."
-$SLAPD -f $DBCONF -h $MASTERURI -d $LVL $TIMING > $MASTERLOG 2>&1 &
+echo "Starting slapd on TCP/IP port $PORT1..."
+$SLAPD -f $CONF1 -h $URI1 -d $LVL $TIMING > $LOG1 2>&1 &
 PID=$!
 if test $WAIT != 0 ; then
     echo PID $PID
     read foo
 fi
+KILLPIDS="$PID"
 
 echo "Testing slapd searching..."
 for i in 0 1 2 3 4 5; do
-	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT \
+	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT1 \
 		'(objectclass=*)' > /dev/null 2>&1
 	RC=$?
 	if test $RC = 0 ; then
@@ -65,65 +59,75 @@ done
 
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
-	kill -HUP $PID
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
 fi
 
 cat /dev/null > $SEARCHOUT
 
 echo "Testing exact searching..."
-$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT \
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
 	'(sn=jENSEN)' >> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
-	kill -HUP $PID
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "Testing approximate searching..."
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
+	'(sn~=jENSEN)' name >> $SEARCHOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
 fi
 
 echo "Testing OR searching..."
-$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT \
-	'(|(givenname=Xx*yY*Z)(cn=)(undef=*)(objectclass=groupofnames)(sn=jones)(member=cn=Manager,o=University of Michigan,c=US))' >> $SEARCHOUT 2>&1
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
+	'(|(givenname=Xx*yY*Z)(cn=)(undef=*)(objectclass=groupofnames)(sn~=jones)(member=cn=Manager,o=University of Michigan,c=US)(uniqueMember=cn=Manager,o=University of Michigan,c=US))' >> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
-	kill -HUP $PID
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
 fi
 
 echo "Testing AND matching and ends-with searching..."
-$LDAPSEARCH -S "" -b "ou=groups,$BASEDN" -s one -h $LOCALHOST -p $PORT \
+$LDAPSEARCH -S "" -b "ou=groups,$BASEDN" -s one -h $LOCALHOST -p $PORT1 \
 	'(&(objectclass=groupofnames)(cn=A*)(member=cn=Mark Elliot,ou=Alumni Association,ou=People,o=University of Michigan,c=US))' >> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
-	kill -HUP $PID
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
 fi
 
 echo "Testing NOT searching..."
-$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT \
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
 	'(!(objectclass=pilotPerson))' >> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
-	kill -HUP $PID
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
 fi
 
 echo "Testing objectClass/attributeType inheritance ..."
-$LDAPSEARCH -M -a never -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT \
-	'(&(objectClass=inetorgperson)(userid=uham))' \
+$LDAPSEARCH -M -a never -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
+	'(&(objectClass~=inetorgperson)(userid=uham))' \
 	"2.5.4.0" "userid" >> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
-	kill -HUP $PID
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
 fi
 
+test $KILLSERVERS != no && kill -HUP $KILLPIDS
 
-kill -HUP $PID
 LDIF=$SEARCHOUTMASTER
 
 echo "Filtering ldapsearch results..."
@@ -139,6 +143,4 @@ if test $? != 0 ; then
 fi
 
 echo ">>>>> Test succeeded"
-
-
 exit 0
diff --git a/autoconf/autoconf/config/elisp-comp b/autoconf/autoconf/config/elisp-comp
--- a/autoconf/autoconf/config/elisp-comp
+++ b/autoconf/autoconf/config/elisp-comp
@@ -1,6 +1,6 @@
 #!/bin/sh
-# Copyright 1995 Free Software Foundation, Inc.
-# François Pinard <pinard@iro.umontreal.ca>, 1995.
+# Copyright (C) 1995, 2000, 2003  Free Software Foundation, Inc.
+# Franc,ois Pinard <pinard@iro.umontreal.ca>, 1995.
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -31,24 +31,30 @@
 # they require or load-library one another.
 
 if test $# = 0; then
-   echo 1>&2 "No files given to $0"
-   exit 1
-else
-   if test -z "$EMACS" || test "$EMACS" = "t"; then
-      # Value of "t" means we are running in a shell under Emacs.
-      # Just assume Emacs is called "emacs".
-      EMACS=emacs
-   fi
-
-   tempdir=elc.$$
-   mkdir $tempdir
-   cp $* $tempdir
-   cd $tempdir
-
-   echo "(setq load-path (cons nil load-path))" > script
-   $EMACS -batch -q -l script -f batch-byte-compile *.el
-   mv *.elc ..
-
-   cd ..
-   rm -fr $tempdir
+  echo 1>&2 "No files given to $0"
+  exit 1
 fi
+
+if test -z "$EMACS" || test "$EMACS" = "t"; then
+  # Value of "t" means we are running in a shell under Emacs.
+  # Just assume Emacs is called "emacs".
+  EMACS=emacs
+fi
+
+tempdir=elc.$$
+
+# Cleanup the temporary directory on exit.
+trap 'status=$?; rm -rf "$tempdir" && exit $status' 0
+trap '(exit $?); exit' 1 2 13 15
+
+mkdir $tempdir
+cp "$@" $tempdir
+
+(
+  cd $tempdir
+  echo "(setq load-path (cons nil load-path))" > script
+  $EMACS -batch -q -l script -f batch-byte-compile *.el || exit $?
+  mv *.elc ..
+) || exit $?
+
+(exit 0); exit
diff --git a/gcc_os/maintainer-scripts/gcc_release b/gcc_os/maintainer-scripts/gcc_release
--- a/gcc_os/maintainer-scripts/gcc_release
+++ b/gcc_os/maintainer-scripts/gcc_release
@@ -126,21 +126,11 @@ EOF
         error "Could not commit ${x}"
     done
 
-    # Update `gcc/version.c'.  There are other version files
-    # as well, which should have release status updated.
+    # Update `gcc/version.c'.
     for x in gcc/version.c; do 
       y=`basename ${x}`
       (changedir `dirname ${SOURCE_DIRECTORY}/${x}` && \
           sed -e 's|= \".*\"|= \"'${RELEASE}'\"|g' < ${y} > ${y}.new && \
-	  mv ${y}.new ${y} && \
-          ${CVS} ci -m 'Update version' ${y}) || \
-	  error "Could not update ${x}"
-    done
-    for x in gcc/f/version.c libf2c/libF77/Version.c \
-             libf2c/libI77/Version.c libf2c/libU77/Version.c; do
-      y=`basename ${x}`
-      (changedir `dirname ${SOURCE_DIRECTORY}/${x}` && \
-          sed -e 's/experimental\|prerelease/release/g' < ${y} > ${y}.new && \
 	  mv ${y}.new ${y} && \
           ${CVS} ci -m 'Update version' ${y}) || \
 	  error "Could not update ${x}"
@@ -282,12 +272,13 @@ build_tarfiles() {
   done
   build_tarfile gcc-core-${RELEASE} ${EXCLUDES} \
     `basename ${SOURCE_DIRECTORY}`
+}
 
-  # Build .bz2 files.
+# Build .bz2 files.
+build_bzip2() {
   for f in ${FILE_LIST}; do
     bzfile=${f%.gz}.bz2
     (zcat $f | ${BZIP2} > ${bzfile}) || error "Could not create ${bzfile}"
-    FILE_LIST="${FILE_LIST} ${bzfile}"
   done
 }
 
@@ -298,7 +289,7 @@ build_diffs() {
   old_vers=${old_file%.tar.gz}
   old_vers=${old_vers#gcc-}
   inform "Building diffs against version $old_vers"
-  for f in gcc gcc-g++ gcc-g77 gcc-java gcc-objc gcc-testsuite gcc-core; do
+  for f in gcc gcc-ada gcc-g++ gcc-g77 gcc-java gcc-objc gcc-testsuite gcc-core; do
     old_tar=${old_dir}/${f}-${old_vers}.tar.gz
     new_tar=${WORKING_DIRECTORY}/${f}-${RELEASE}.tar.gz
     if [ -e $old_tar ] && [ -e $new_tar ]; then
@@ -336,9 +327,11 @@ upload_files() {
   # Make sure the directory exists on the server.
   if [ $LOCAL -eq 0 ]; then
     ${SSH} -l ${GCC_USERNAME} ${GCC_HOSTNAME} mkdir ${FTP_PATH}
+    UPLOAD_PATH="${GCC_USERNAME}@${GCC_HOSTNAME}:${FTP_PATH}"
   else
     mkdir -p "${FTP_PATH}" \
       || error "Could not create \`${FTP_PATH}'"
+    UPLOAD_PATH=${FTP_PATH}
   fi
 
   for x in gcc*.gz gcc*.bz2; do
@@ -346,8 +339,7 @@ upload_files() {
       # Make sure the file will be readable on the server.
       chmod a+r ${x}
       # Copy it.
-      ${SCP} ${x} ${FTP_PATH} || \
-        error "Could not upload ${x}"
+      ${SCP} ${x} ${UPLOAD_PATH} || error "Could not upload ${x}"
     fi
   done
 }
@@ -426,12 +418,13 @@ SNAPSHOT=0
 LOCAL=0
 
 # Major operation modes.
+MODE_BZIP2=0
 MODE_DIFFS=0
 MODE_SOURCES=0
 MODE_TARFILES=0
 MODE_UPLOAD=0
 
-# Files generated to upload.
+# .gz files generated to create .bz2 files from.
 FILE_LIST=""
 
 # Programs we use.
@@ -562,11 +555,12 @@ export TZ
 # Handle the major modes.
 while [ $# -ne 0 ]; do
     case $1 in
+    bzip2)    MODE_BZIP2=1;;
     diffs)    MODE_DIFFS=1;;
     sources)  MODE_SOURCES=1;;
     tarfiles) MODE_TARFILES=1;;
     upload)   MODE_UPLOAD=1;;
-    all)      MODE_SOURCES=1; MODE_TARFILES=1; MODE_DIFFS=1; MODE_UPLOAD=1;;
+    all)      MODE_SOURCES=1; MODE_TARFILES=1; MODE_DIFFS=1; MODE_BZIP2=1; MODE_UPLOAD=1;;
     *)        error "Unknown mode $1";;
     esac
     shift
@@ -593,6 +587,11 @@ if [ $MODE_DIFFS -ne 0 ]; then
       build_diffs $old_tar
     done
   fi
+fi
+
+# Build bzip2 files
+if [ $MODE_BZIP2 -ne 0 ]; then
+  build_bzip2
 fi
 
 # Upload them to the FTP server.
diff --git a/gcc_select/gcc_select b/gcc_select/gcc_select
--- a/gcc_select/gcc_select
+++ b/gcc_select/gcc_select
@@ -1,14 +1,15 @@
 #!/bin/sh
 
-# gcc_select [-n] [-force] [2 | 3 | 3.x] [-h | --help] [-v | --version]
+# gcc_select [-n] [-force] [2 | 3 | 3.x | 4.x ] [-h | --help] [-v | --version]
 #            [-l | --list] [-root]
 #            
 #
-# Switch the default gcc to either 2.x or 3.x.
+# Switch the default gcc to any of 2.x, 3.x, or 4.x.
 #
 #  2             Select gcc 2.95.2 as the default compiler.
 #  3             Select gcc 3.1 as the default compiler.
 #  3.x           Select gcc 3.x as the default compiler.
+#  4.x           Select gcc 4.x as the default compiler.
 #  -force        Ensure the links are correct for the specified version.
 #                even if the one specified is the current version.
 #  -h            Display this help info.
@@ -20,11 +21,11 @@
 #  -l		 Display available compiler versions.
 #  --list	 Same as -l.
 #           
-# This script will switch the current compiler installation from 2.x
-# to 3.x or vice versa (or echo the commands to do it if -n is used).
+# This script will switch the current compiler installation around
+# among 2.x, 3.x, and 4.x (or echo the commands to do it if -n is used).
 # The current version is displayed if no arguments are specified.
 #
-# Note, for documentation completeness, there is one additional option.
+# Note, for documentation completeness, there are three additional options.
 #
 #  -dstroot dir  Install the sym links in a /usr directory within the
 #		 specified dir or the dir itself if it specifies a usr
@@ -32,34 +33,29 @@
 #                allowed, in which case, the sytem is changed to the
 #                requested compiler, i.e., the same effect as not
 #                specifying it at all. 
+#  --wrap SCRIPT Forces all possible mechanisms for invoking the
+#		 compiler to be diverted from /usr/bin/NAME to
+#		 /usr/bin/NAME.real, and /usr/bin/NAME will become
+#		 a symbolic link to SCRIPT.  Will fail if binaries
+#		 are already diverted.
+#  --unwrap	 Restores diversions created by --wrap.
 #
-# This is a special option NOT for general use.  It is deliberately 
-# omitted from the --help info.  It is intended for internal build
-# procedures to install the sym links in the specified dir instead
-# of the system.
+# These are special options NOT for general use.  They are deliberately 
+# omitted from the --help info.  They are intended for internal build
+# procedures.
 #
-# Copyright Apple Computer, Inc. 2002, 2003
+# Copyright Apple Computer, Inc. 2002, 2003, 2004, 2005
 
 #######################################################################
 
-GCC_SELECT_VERSION="2.5"
+GCC_SELECT_VERSION="2.14"
 
 #######################################################################
 
 # List of headers in & underneath /usr/include that need to be symlinked
 # to a compiler-specific version.
 
-symlink_hdrs0="assert.h		\
-	float.h			\
-	inttypes.h		\
-	stdarg.h  	 	\
-	stdbool.h 	 	\
-	stdint.h  	 	\
-	varargs.h 	 	\
-	va-ppc.h"
-symlink_hdrs1="machine/limits.h"
-
-# Note, in the above list va-ppc.h is only for gcc2.
+symlink_hdrs0="stdint.h"
 
 # List of libraries in /usr/lib and /usr/local/lib that need to be 
 # symlinked to a compiler-specific version.
@@ -89,7 +85,7 @@ switch_it()
 {
     local f who status argc=$# cwd="`/bin/pwd`"
     local n="\n`echo "usage: ${0##*/}" | sed -e 's/./ /g'`"
-    local usage="${0##*/} [-n] [-force] [2 | 3 | 3.x] [-h | --help] [-v | --version]$n [-l | --list] [-root]"
+    local usage="${0##*/} [-n] [-force] [2 | 3 | 3.x | 4.x ] [-h | --help] [-v | --version]$n [-l | --list] [-root]"
     
     #
     # Collect the arguments...
@@ -103,10 +99,12 @@ switch_it()
     installing=
     show_help=
     root=
+    wrapper=
+    unwrap=0
     
     while [ $# -gt 0 ] ; do 
 	case $1 in
-	    2* | -2* | 3* | -3*)
+	    2* | -2* | 3* | -3* | 4.* | -4.* )
 		if [[ "$switchto_cc" != "0" && "$switchto_cc" != "$1" ]]; then
 		    echo -e "usage: $usage"
 		    echo    "       Inconsistent compiler versions specified."
@@ -140,6 +138,40 @@ switch_it()
 		installing=1
 		shift
 		;;
+	    -wrap | --wrap)
+	        if [ $unwrap -ne 0 ]; then
+	            echo "Cannot specify both --wrap and --unwrap."
+	            exit 1
+	        fi
+	        shift
+
+	        if [ -z "$1" ]; then
+		    cat <<WRAP_HELP
+Invalid --wrap option, please specify wrapper script after --wrap.
+
+Writing Wrapper Scripts
+-----------------------
+Wrapper scripts should pass \$0 (argv[0]) through to the underlying program,
+since drivers may use $0 to determine behavior.  Here are a couple of
+examples of how to write clean wrappers:
+	sh no-op wrapper: exec -a "\$0" "\$0.real" "\$@"
+ 	perl no-op wrapper: exec {"\$0.real"} (\$0, @ARGV);
+WRAP_HELP
+	            exit 1
+                fi
+
+	        wrapper="$1"
+	        shift
+	        ;;
+	    -unwrap | --unwrap)
+	        if [ -n "$wrapper" ]; then
+	            echo "Cannot specify both --wrap and --unwrap."
+	            exit 1
+	        fi
+
+	        unwrap=1
+	        shift
+	        ;;
 	    -root)
 	    	root=1
 	    	shift
@@ -163,6 +195,7 @@ switch_it()
 	echo "2          Select gcc 2.95.2 as the default compiler."
 	echo "3          Select gcc 3.1 as the default compiler."
 	echo "3.x        Select gcc 3.x as the default compiler."
+	echo "4.x        Select gcc 4.x as the default compiler."
 	echo "-force     Ensure the links are correct for the specified version"
 	echo "           even if it maches the current default version."
 	echo "-h         Display this help info."
@@ -180,7 +213,7 @@ switch_it()
     if [ "$list_versions" ]; then
       echo "Available compiler versions:"
       cd /usr/include/gcc/darwin
-      command ls -d [23]*
+      command ls -d [234]*
       exit 1
     fi
     #
@@ -188,11 +221,107 @@ switch_it()
     # the version number it displays when we do a cc -v...
     #
     actual_ver="`cc -v 2>&1  | grep -i 'gcc version'`"
-    current_cc="`echo \"$actual_ver\" | sed -e 's/.*gcc version \([^ ]*\).*/\1/'`"
-    if [[ ! "$current_cc" == 2* && ! "$current_cc" == 3* ]]; then
-        echo "Error trying to determine current cc version (got $current_cc)"
-        exit 1
+    #current_cc="`echo \"$actual_ver\" | sed -e 's/.*gcc version \([^ ]*\).*/\1/'`"
+    current_cc="`echo \"$actual_ver\" | sed -e 's/.*gcc version \([0-9]*\.[0-9]*\).*/\1/'`"
+    if [[ ! "$current_cc" == 2* && ! "$current_cc" == 3* && ! "$current_cc" == 4* ]]; then
+        if [ $unwrap -eq 1 ]; then
+            if [ -z "$forced" -o -z "$switchto_cc" ]; then
+                echo "To restore from an invalid GCC wrapper, use gcc_select --force --unwrap 3.3"
+                exit 1
+            else
+                current_cc=$switchto_cc
+            fi
+        else
+            echo "Error trying to determine current cc version (got $current_cc)"
+            exit 1
+        fi
     fi
+
+    # Handle wrapping and unwrapping
+    if [ -n "$wrapper" ]; then
+        if [ ! -f "$wrapper" ]; then
+            echo "GCC wrapper doesn't exist."
+            exit 1
+        fi
+
+        for driver in $usr/bin/{gcc,g++,c++,cpp,gcov}-* ; do
+            case "$driver" in
+                *.real)
+                    # Ignore
+                    ;;
+                *)
+                    if [ -L "$driver" -a -f "$driver.real" ]; then
+                        echo "Sorry, $driver is already wrapped and we're trying to wrap it again."
+                        if [ -z "$forced"  ]; then exit 1 ; fi
+                    fi
+
+                    if [ -f "$driver.real" ]; then
+                        echo "Error, $driver already appears to be wrapped but there is no link to it."
+                        if [ -z "$forced" ]; then exit 1 ; fi
+                    fi
+
+                    if [ -L "$driver" ]; then
+                        $dashn ln -sf "`readlink $driver`.real" "$driver.real" || {
+                            echo "Couldn't symlink $driver.real to `readlink $driver`.real"
+                            if [ -z "$forced" ]; then exit 1 ; fi
+                        }
+                    else
+                        $dashn mv "$driver" "$driver.real" || {
+                            echo "Couldn't move $driver to $driver.real"
+                            if [ -z "$forced" ]; then exit 1 ; fi
+                        }
+                    fi
+
+                    $dashn ln -sf "$wrapper" "$driver" || {
+                        echo "Couldn't make symbolic link from $driver to $wrapper"
+                        $dashn mv "$driver.real" "$driver" || echo "...and couldn't restore $driver.real to $driver"
+                        if [ -z "$forced" ]; then exit 1 ; fi
+                    }
+                    ;;
+            esac
+        done
+
+        # Re-select current version so that symlinks go to .real
+        forced=1
+    elif [ $unwrap -ne 0 ]; then
+        for driver in $usr/bin/{gcc,g++,c++,cpp,gcov}-*; do
+           case "$driver" in
+                *.real)
+                    if [ -L "$driver" ]; then
+                        $dashn rm -f "$driver" || {
+                            echo "Couldn't remove $driver"
+                            if [ -z "$forced" ]; then exit 1 ; fi
+                        }
+                    fi
+                    ;;
+                *)
+                    DRIVER_LINK=
+                    if [ -f "$driver.real" -o -L "$driver.real" ]; then DRIVER_LINK=1 ; fi
+
+                    if [ -L "$driver" -a -n "$DRIVER_LINK" ]; then
+                        $dashn rm -f "$driver" || {
+                            echo "Couldn't remove symbolic link $driver"
+                            if [ -z "$forced" ]; then exit 1 ; fi
+                        }
+
+                        if [ -f "$driver.real" ]; then
+                            $dashn mv "$driver.real" "$driver" || {
+                                echo "Couldn't move $driver.real to $driver"
+                                if [ -z "$forced" ]; then exit 1 ; fi
+                            }
+                        fi
+                    else
+                       echo "Sorry, $driver does not appear to be wrapped."
+                       if [ -z "$forced" ] ; then exit 1 ; fi
+                    fi
+                    ;;
+            esac
+        done
+
+        # Re-select current version so that symlinks *don't* go to .real
+        forced=1
+    fi
+
     # No arguments means display only the current compiler version...
     #   
     if [ $argc -eq 0 ] || [ $argc -eq 1 -a "$show_ver" ]; then
@@ -234,7 +363,7 @@ switch_it()
     #
     # If actually modifying the system do additional checks...
     #
-    if [ ! "$installing" ]; then
+    if [ ! "$installing" -a "$switchto_cc" != "0" ]; then
 	#
 	# If what we want to switch to is the same as the current installation
 	# we have nothing more to do (unless we're "forced" to do it)...
@@ -250,12 +379,12 @@ switch_it()
 	# accidentally clobber non-symlink files while creating the symlinks. 
 	#
         list=
-        for driver in cc c++ gcc g++; do
+        for driver in cc c++ gcc g++ cc.real c++.real gcc.real g++.real; do
 	  if [ -e /usr/bin/$driver -a ! -L /usr/bin/$driver ]; then
 	    list="$list /usr/bin/$driver"
 	  fi
 	done
-        for header in $symlink_hdrs0 $symlink_hdrs1; do
+        for header in $symlink_hdrs0 ; do
           if [ -e /usr/include/$header -a ! -L /usr/include/$header ]; then
             list="$list /usr/include/$header"
           fi
@@ -293,7 +422,6 @@ switch_it()
 	fi
     fi # usr
     
-	
     #
     # Make sure that the compiler we are switching to has all the indispensable
     # drivers, headers and libraries.  Here we check only files common to all
@@ -304,25 +432,49 @@ switch_it()
     for file_or_dir in \
 	/usr/bin/gcc$switchto_cc_driver 		\
 	/usr/bin/g++$switchto_cc_driver 		\
-	/usr/include/gcc/darwin/$switchto_cc/assert.h	\
-        /usr/include/gcc/darwin/$switchto_cc/float.h	\
-        /usr/include/gcc/darwin/$switchto_cc/inttypes.h	\
-        /usr/include/gcc/darwin/$switchto_cc/stdarg.h	\
-        /usr/include/gcc/darwin/$switchto_cc/stdbool.h	\
         /usr/include/gcc/darwin/$switchto_cc/stdint.h	\
-        /usr/include/gcc/darwin/$switchto_cc/varargs.h	\
-	/usr/libexec/gcc/darwin/ppc/$switchto_cc/ 	\
-	/usr/lib/gcc/darwin/$switchto_cc/ 		\
 	/usr/include/gcc/darwin/$switchto_cc/ ; do
       if [ ! -e $file_or_dir ]; then
 	missing="$missing $file_or_dir"
       fi
     done
+
+    # The following headers are compiler-provided on systems prior to Tiger,
+    # and on Tiger systems with compilers prior to gcc 4.0.
+    if [ $os_version -lt 100400 -o $switchto_cc \< 4.0 ]; then
+      for file_or_dir in \
+          /usr/include/gcc/darwin/$switchto_cc/float.h    \
+          /usr/include/gcc/darwin/$switchto_cc/stdarg.h   \
+          /usr/include/gcc/darwin/$switchto_cc/stdbool.h  \
+          /usr/include/gcc/darwin/$switchto_cc/varargs.h  \
+          /usr/include/gcc/darwin/$switchto_cc/ ; do
+        if [ ! -e $file_or_dir ]; then
+          missing="$missing $file_or_dir"
+        fi
+      done
+    fi
+
     if [ "$missing" != "" ]; then
         show_list "The following is missing from your gcc $switchto_cc compiler installation." \
                   "Reinstall the $switchto_cc compiler, or use another release." $missing
         exit 1
     fi
+
+    if [ $switchto_cc \< 3.5 ]; then
+      if [ ! -e /usr/libexec/gcc/darwin/ppc/$switchto_cc ]; then
+        "Files in /usr/libexec/gcc/darwin/ppc/$switchto_cc are missing from your gcc
+        "compiler installation.  Reinstall the $switchto_cc compiler, or use another release." 
+        exit 1
+      fi
+      if [ ! -e /usr/lib/gcc/darwin/ppc/$switchto_cc ]; then
+        "Files in /usr/lib/gcc/darwin/ppc/$switchto_cc are missing from your gcc
+        "compiler installation.  Reinstall the $switchto_cc compiler, or use another release." 
+        exit 1
+      fi
+      # 3.5 and above
+      # We ought to have an else clause here that checks that 
+      # /usr/libexec/gcc/ppc-apple-darwin/4.0.0 exists here.
+    fi 
 
     if [ "$dashn" != "" ]; then
       echo "Commands that would be executed if \"-n\" were not specified:"
@@ -332,6 +484,22 @@ switch_it()
     #
     $dashn mkdir -p $usr/bin
     $dashn rm -f $usr/bin/cc $usr/bin/c++
+
+    # Handle wrappers
+    if [ -L $usr/bin/gcc$switchto_cc_driver -o -n "$wrapper" ]; then
+        $dashn ln -sf gcc$switchto_cc_driver.real $usr/bin/cc.real
+        $dashn ln -sf g++$switchto_cc_driver.real $usr/bin/c++.real
+        for driver in gcc g++ gcov; do
+            $dashn ln -sf $driver$switchto_cc_driver.real $usr/bin/$driver.real
+        done
+    else
+        $dashn rm -f $usr/bin/cc.real
+        $dashn rm -f $usr/bin/c++.real
+        for driver in gcc g++ gcov; do
+            $dashn rm -f $usr/bin/$driver.real
+        done
+    fi
+
     $dashn ln -sf gcc$switchto_cc_driver $usr/bin/cc
     $dashn ln -sf g++$switchto_cc_driver $usr/bin/c++
     for driver in gcc g++ gcov; do
@@ -340,9 +508,6 @@ switch_it()
 	$dashn ln -sf $driver$switchto_cc_driver $usr/bin/$driver
       fi
     done
-    # we shall use the cxxfilt in the binutils package for _all_ compiler releases
-    $dashn rm -f $usr/bin/c++filt
-    $dashn ln -sf ../libexec/binutils/cxxfilt $usr/bin/c++filt
 
     # Change the various "default" sym links for
     # directories.
@@ -375,19 +540,19 @@ switch_it()
       $dashn ln -sf gcc/darwin/default/libgcc.a $usr/lib/libcc_dynamic.a
     fi
 
+    # For gcc 3.5 and above, some of the symlinks we just set up point to nowhere.
+    # Get rid of them.
+    if [ $switchto_cc \> 3.3 ]; then
+      $dashn rm -f $usr/lib/gcc/darwin/default
+      $dashn rm -f $usr/lib/libcc_dynamic.a
+    fi
+
     # Set up header symlinks...
     $dashn mkdir -p $usr/include
     for header in $symlink_hdrs0; do
       $dashn rm -f $usr/include/$header
       if [ -e /usr/include/gcc/darwin/default/$header ]; then
         $dashn ln -sf gcc/darwin/default/$header $usr/include/$header
-      fi
-    done
-    for header in $symlink_hdrs1; do    
-      $dashn rm -f $usr/include/$header   
-      if [ -e /usr/include/gcc/darwin/default/$header ]; then
-        $dashn mkdir -p $usr/include/$(dirname $header)   
-        $dashn ln -sf ../gcc/darwin/default/$header $usr/include/$header   
       fi
     done
     # Set up man page symlinks...
@@ -402,6 +567,11 @@ switch_it()
         $dashn ln -sf $manpage$switchto_cc_driver.1 $usr/share/man/man1/$manpage.1
       fi
     done
+    $dashn rm -rf $usr/share/man/man1/cc.1    
+    if [ -e /usr/share/man/man1/gcc.1 ]; then
+	$dashn ln -sf gcc.1 $usr/share/man/man1/cc.1
+    fi
+    
     #
     # We determine which compiler is currently installed by looking at
     # the version number it displays when we do a cc -v...
@@ -410,7 +580,7 @@ switch_it()
       if [ "$dashn" == "" ]; then
         actual_ver="`cc -v 2>&1  | grep -i 'gcc version'`"
         current_cc="`echo \"$actual_ver\" | sed -e 's/.*gcc version \([^ ]*\).*/\1/'`"
-        if [[ ! "$current_cc" == 2* && ! "$current_cc" == 3* ]]; then
+        if [[ ! "$current_cc" == 2* && ! "$current_cc" == 3* && ! "$current_cc" == 4* ]]; then
       	    echo "Error trying to determine current cc version (got $current_cc)"
      	    exit 1
         fi
@@ -462,8 +632,8 @@ show_list()
 ### main() ############################################################
 #######################################################################
 
-os_major="`uname -r | sed -e 's/\([^\.]*\).*/\1/'`"
-if [ $os_major -lt 6 ]; then
+os_version=$(sw_vers -productVersion | awk -F. '{ printf "%02d%02d%02d", $1, $2, $3 }')
+if [ $os_version -lt 100200 ]; then
   echo "You must be using MacOS X 10.2 (Jaguar) or later."
   exit 1
 fi
diff --git a/net_snmp/net-snmp/dist/nsb-nightly b/net_snmp/net-snmp/dist/nsb-nightly
--- a/net_snmp/net-snmp/dist/nsb-nightly
+++ b/net_snmp/net-snmp/dist/nsb-nightly
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# $Id: nsb-nightly,v 1.1.1.1 2003/05/29 00:03:09 rbraun Exp $
+# $Id: nsb-nightly,v 1.7 2004/07/03 20:37:14 rstory Exp $
 # Author: Robert Story <rstory@freesnmp.com>
 #
 ########################################################################
@@ -8,8 +8,10 @@
 
 usage()
 {
-   echo "Usage: $0  [-x] [-s SRCD] [-b BUILDD] [-i INSTALLD] VERSION"
+   echo "Usage: $0  [optional params] VERSION"
    echo ""
+   echo " optional params: [-x] [-s SRCD] [-b BUILDD] [-i INSTALLD]"
+   echo "                  [-h host] [-p path]"
    echo " VERSION    : relase number (eg 5.0.3)"
    echo " -s SRCDIR  : soure directory [$HOME/src/net-snmp-VERSION]"
    echo " -b BUILDD  : build directory [$HOME/build/]"
@@ -17,41 +19,61 @@ usage()
    echo " -i INSTALLD: install directory [$HOME/build/\$PLATFORM/usr/local]"
    echo ""
    echo " -x : configure extra features for pre-release testing"
+   echo " -C : don't source $HOME/.snmp/nsb-nightly"
+   echo ""
+   echo " -h : host to upload results to"
+   echo " -p : path to upload results to"
    exit 1
 }
 
 #set -x
 
 #
-# find nsb-platform based on te path to this script
+# find nsb-platform based on the path to this script
 #
 EXE_PATH=${0%nsb-nightly}
 EXE_PATH=${EXE_PATH%/}
-if [ -f $EXE_PATH/nsb-functions ];then
-   source $EXE_PATH/nsb-functions
-elif [ -f $HOME/bin/nsb-functions ]; then
-   source $HOME/bin/nsb-functions
-elif [ -f nsb-functions ];then
-   source nsb-functions
-else
-   echo "Cannot find nsb-functions in $EXE_PATH, $HOME/bin or $PWD"
-   exit 1
+if [ ! -f $EXE_PATH/nsb-functions ];then
+   if [ -f $HOME/bin/nsb-functions ]; then
+      EXE_PATH=$HOME/bin
+   elif [ -f nsb-functions ];then
+      EXE_PATH=$PWD
+   else
+      echo "Cannot find nsb-functions in $EXE_PATH, $HOME/bin or $PWD"
+      exit 1
+   fi
 fi
 
+if [ "x$1" = "x-C" ]; then
+    shift
+else
+    if [ -f $HOME/.snmp/nsb-nightly ];then
+        source $HOME/.snmp/nsb-nightly
+    fi
+fi
 
 ########################################################################
 ########################################################################
 
-# -c -d
-PARMS="-p -r -R"
+# -r : remove build dir before
+# -R : remove build dir after
+PARMS="$PARMS -r"
+NIGHTLY_VERBOSE=0
 
-while getopts b:i:s:x opt
+while getopts b:i:s:xh:p:v opt
 do
     case "$opt" in
-      b)  PARMS="-b $OPTARG $PARMS";;
+      b)  NSB_BUILD_DIR=$OPTARG;;
       i)  PARMS="-i $OPTARG $PARMS";;
-      s)  PARMS="-s $OPTARG $PARMS";;
+      s)  NSB_SRC_DIR=$OPTARG;;
+      h)  NSB_SCP_HOST=$OPTARG
+          PARMS="-h $NSB_SCP_HOST $PARMS"
+          ;;
+      p)  NSB_SCP_DEST=$OPTARG
+          PARMS="-p $NSB_SCP_DEST $PARMS"
+          ;;
       x)  PARMS="-x $PARMS";;
+      v)  NIGHTLY_VERBOSE=1;;
       \?)# unknown flag
         usage;;
     esac
@@ -63,18 +85,39 @@ if [ $# -ne 1 ]; then
    usage
 fi
 
-VERSION=$1
+NSB_VERSION=$1
 
+source $EXE_PATH/nsb-functions
+
+nsb-default-paths
+
+PARMS="$PARMS -b $NSB_BUILD_DIR -s $NSB_SRC_DIR"
 
 ########################################################################
 ########################################################################
 echo "Start: `date`"
-echo "Running nsb-package $PARMS $VERSION"
-$EXE_PATH/nsb-package $PARMS $VERSION > /dev/null
+echo "Running nsb-package $PARMS $NSB_VERSION"
+if [ $NIGHTLY_VERBOSE = 1 ]; then
+    $EXE_PATH/nsb-package $PARMS $NSB_VERSION
+else
+    $EXE_PATH/nsb-package $PARMS $NSB_VERSION > /dev/null
+fi
 RC=$?
 echo "Finish: `date`"
 echo -n "Result: "
 case $RC in
-    0) echo "Success!";;
-    *) echo "Error!";;
+    0)  echo "Success!"
+        if [ "x$NSB_BUILD_DIR" = "/" ]; then
+            nsb-abort "Not running rm -fR from /"
+        else
+            /bin/rm -fR $NSB_BUILD_DIR > /dev/null 2>&1
+        fi
+        ;;
+    *) echo "Error!"
+       if [ ! -z $NSB_SCP_HOST ]; then
+          nsb-upload $NSB_BUILD_DIR $NSB_SCP_HOST:$NSB_SCP_DEST/$NSB_VERSION/$NSB_SUFFIX
+       fi
+        ;;
 esac
+
+exit $RC
diff --git a/net_snmp/net-snmp/dist/nsb-package b/net_snmp/net-snmp/dist/nsb-package
--- a/net_snmp/net-snmp/dist/nsb-package
+++ b/net_snmp/net-snmp/dist/nsb-package
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# $Id: nsb-package,v 1.1.1.1 2003/05/29 00:03:09 rbraun Exp $
+# $Id: nsb-package,v 1.11 2004/02/18 19:58:17 rstory Exp $
 # Author: Robert Story <rstory@freesnmp.com>
 #
 ########################################################################
@@ -8,13 +8,16 @@
 
 usage()
 {
-   echo "Usage: $0  [-c] [-d] [-P] [-s SRCD] [-b BUILDD] [-i INSTALLD] VERSION"
+   echo "Usage: $0  [params] VERSION"
+   echo ""
+   echo "  params: [-c] [-d] [-P] [-s NSB_SRC_DIR] [-b BUILDD] [-i NSB_INSTALL_DIR]"
+   echo "          [-h host] [-p path]"
    echo ""
    echo " VERSION    : relase number (eg 5.0.3)"
-   echo " -s SRCDIR  : soure directory [$HOME/src/net-snmp-VERSION]"
+   echo " -s NSB_SRC_DIRIR  : soure directory [$HOME/src/net-snmp-VERSION]"
    echo " -b BUILDD  : build directory [$HOME/build/]"
    echo "              NOTE-platform will be appended to build directory"
-   echo " -i INSTALLD: install directory [$HOME/build/\$PLATFORM/usr/local]"
+   echo " -i NSB_INSTALL_DIR: install directory [$HOME/build/\$PLATFORM/usr/local]"
    echo ""
    echo " -x : configure extra features for pre-release testing"
    echo " -c : skip configure"
@@ -24,6 +27,10 @@ usage()
    echo " -r : remove build dir (rm -fR) before build"
    echo " -R : remove build dir (rm -fR) after successful build"
    echo " -t : skip 'make test'"
+   echo " -C : don't source $HOME/.snmp/nsb-package"
+   echo ""
+   echo " -h : host to upload results to"
+   echo " -p : path to upload results to"
    exit 1
 }
 
@@ -36,17 +43,24 @@ usage()
 #
 EXE_PATH=${0%nsb-package}
 EXE_PATH=${EXE_PATH%/}
-if [ -f $EXE_PATH/nsb-functions ];then
-   source $EXE_PATH/nsb-functions
-elif [ -f $HOME/bin/nsb-functions ]; then
-   source $HOME/bin/nsb-functions
-elif [ -f nsb-functions ];then
-   source nsb-functions
-else
-   echo "Cannot find nsb-functions in $EXE_PATH, $HOME/bin or $PWD"
-   exit 1
+if [ ! -f $EXE_PATH/nsb-functions ];then
+   if [ -f $HOME/bin/nsb-functions ]; then
+      EXE_PATH=$HOME/bin
+   elif [ -f nsb-functions ];then
+      EXE_PATH=$PWD
+   else
+      echo "Cannot find nsb-functions in $EXE_PATH, $HOME/bin or $PWD"
+      exit 1
+   fi
 fi
 
+if [ "x$1" = "x-C" ]; then
+    shift
+else
+    if [ -f $HOME/.snmp/nsb-package ];then
+        source $HOME/.snmp/nsb-package
+    fi
+fi
 
 ########################################################################
 ########################################################################
@@ -54,18 +68,20 @@ fi
 REMOVE_SUCCESS=0
 
 #      x)  x=$OPTARG ;;
-while getopts b:cdi:mPrRs:tx opt
+while getopts b:cdh:i:mPp:rRs:tx opt
 do
     case "$opt" in
-      b)  BUILDD=$OPTARG ;;
+      b)  NSB_BUILD_DIR=$OPTARG ;;
       c)  NSB_SKIP_CONFIG=1 ;;
       d)  NSB_CLEAN=0 ;;
-      i)  INSTALLD=$OPTARG ;;
+      h)  NSB_SCP_HOST=$OPTARG ;;
+      i)  NSB_INSTALL_DIR=$OPTARG ;;
       m)  NSB_SKIP_BUILD=1 ;;
       P)  NSB_PROMPT=1 ;;
+      p)  NSB_SCP_DEST=$OPTARG ;;
       r)  NSB_CLEAN=2 ;;
       R)  REMOVE_SUCCESS=1 ;;
-      s)  SRCD=$OPTARG ;;
+      s)  NSB_SRC_DIR=$OPTARG ;;
       t)  NSB_SKIP_TEST=1 ;;
       x)  NSB_CONFIG_ALL=1;;
       \?)# unknown flag
@@ -79,6 +95,12 @@ if [ $# -ne 1 ]; then
    usage
 fi
 
+NSB_VERSION=$1
+
+source $EXE_PATH/nsb-functions
+
+nsb-default-paths
+
 if [ $NSB_CLEAN -eq 1 ]; then
    if [ $NSB_SKIP_CONFIG -eq 1 ]; then
       echo "A clean build also requires configuration (-d and -c"
@@ -87,29 +109,23 @@ if [ $NSB_CLEAN -eq 1 ]; then
    fi
 fi
 
-VERSION=$1
-if [ -z "$SRCD" ]; then
-   SRCD=$HOME/src/net-snmp-$VERSION
-fi
-if [ -z "$BUILDD" ]; then
-   BUILDD=$HOME/build
-fi
-if [ $SRCD != $BUILDD ];then
-    BUILDD=$BUILDD/$VERSION-`nsb-sysname`
-fi
-if [ -z "$INSTALLD" ]; then
-   INSTALLD=$BUILDD/usr/local
-fi
-
 
 ########################################################################
 ########################################################################
-nsb-prompt "press enter to build $SRCD in $BUILDD, and install in $INSTALLD"
-nsb-build $VERSION $SRCD $BUILDD $INSTALLD $NSB_CONFIG_ALL
+nsb-prompt "press enter to build $NSB_SRC_DIR in $NSB_BUILD_DIR, and install in $NSB_INSTALL_DIR"
+nsb-build $NSB_VERSION $NSB_SRC_DIR $NSB_BUILD_DIR $NSB_INSTALL_DIR $NSB_CONFIG_ALL
 rc=$?
+if [ ! -z $NSB_SCP_HOST ]; then
+   nsb-upload $NSB_BUILD_DIR $NSB_SCP_HOST:$NSB_SCP_DEST/$NSB_VERSION/$NSB_HOST/
+fi
 if [ $rc -eq 0 ] && [ $REMOVE_SUCCESS -eq 1 ];then
-    nsb-prompt "press enter to remove $BUILDD"
-    /bin/rm -fR $BUILDD > /dev/null 2>&1
+    nsb-prompt "press enter to remove $NSB_BUILD_DIR"
+    if [ "x$NSB_BUILD_DIR" = "/" ]; then
+       nsb-abort "Not running rm -fR from /"
+    else
+       /bin/rm -fR $NSB_BUILD_DIR > /dev/null 2>&1
+    fi
 fi
 
+nsb-prompt "press enter to exit with rc $RC"
 exit $rc
