10.6

diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test005-modrdn b/OpenLDAP/OpenLDAP/tests/scripts/test005-modrdn
--- a/OpenLDAP/OpenLDAP/tests/scripts/test005-modrdn
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test005-modrdn
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test005-modrdn,v 1.41.2.6 2006/01/03 22:16:28 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test005-modrdn,v 1.49.2.6 2008/02/11 23:26:51 kurt Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2006 The OpenLDAP Foundation.
+## Copyright 1998-2008 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -16,11 +16,11 @@
 echo "running defines.sh"
 . $SRCDIR/scripts/defines.sh
 
-mkdir -p $TESTDIR $DBDIR1
+mkdir -p $TESTDIR $DBDIR1A $DBDIR1B
 
 echo "Running slapadd to build slapd database..."
-. $CONFFILTER $BACKEND $MONITORDB < $CONF > $CONF1
-$SLAPADD -f $CONF1 -l $LDIFORDERED
+. $CONFFILTER $BACKEND $MONITORDB < $CONF2DB > $CONF1
+$SLAPADD -f $CONF1 -b "$BASEDN" -l $LDIFORDERED
 RC=$?
 if test $RC != 0 ; then
 	echo "slapadd failed ($RC)!"
@@ -107,7 +107,7 @@ $CMP $SEARCHFLT $LDIFFLT > $CMPOUT
 if test $? != 0 ; then
 	echo "comparison failed - modrdn operations did not complete correctly"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit 1
+	exit -1
 fi
 
 
@@ -134,7 +134,7 @@ $CMP $SEARCHFLT $LDIFFLT > $CMPOUT
 if test $? != 0 ; then
 	echo "comparison failed - modrdn operations did not complete correctly"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit 1
+	exit -1
 fi
 
 # Ensure that you cannot find the entry for which the rdn was deleted as
@@ -153,7 +153,7 @@ $CMP $SEARCHOUT - < /dev/null > $CMPOUT
 if test $? != 0 ; then
 	echo "failure: ldapsearch found attribute that was to be removed!"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit 1
+	exit -1
 fi
 
 echo "Using ldapsearch to retrieve all the entries..."
@@ -178,7 +178,7 @@ $CMP $SEARCHFLT $LDIFFLT > $CMPOUT
 if test $? != 0 ; then
 	echo "comparison failed - modrdn operations did not complete correctly"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit 1
+	exit -1
 fi
 
 # Test that you can use modrdn with an attribute value which was previously
@@ -218,22 +218,83 @@ $CMP $SEARCHFLT $LDIFFLT > $CMPOUT
 if test $? != 0 ; then
 	echo "comparison failed - modrdn operations did not complete correctly"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit 1
+	exit -1
 fi
 
-echo "Testing modrdn with newSuperior as child of target "
+echo "Testing modrdn to another database (should fail with affectsMultipleDSAs)"
 $LDAPMODRDN -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD > \
-	$TESTOUT 2>&1  -s 'cn=Sub1, ou=FooBar, cn=James A Jones 1, ou=Alumni Association, ou=People, dc=example, dc=com' \
+	$TESTOUT 2>&1 'cn=All Staff,ou=Groups,dc=example,dc=com' 'cn=Everyone'
+RC=$?
+case $RC in
+0)
+	echo "ldapmodrdn succeeded, should have failed!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit -1
+	;;
+71)
+	;;
+*)
+	echo "ldapmodrdn failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+
+echo "Testing modrdn with newSuperior = target (should fail with unwillingToPerform)"
+$LDAPMODRDN -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD > \
+	$TESTOUT 2>&1  -s 'cn=James A Jones 1, ou=Alumni Association, ou=People, dc=example, dc=com' \
 	'cn=James A Jones 1, ou=Alumni Association, ou=People, dc=example, dc=com' 'cn=James A Jones 1'
 
 RC=$?
-if test $RC -eq 0 ; then
+case $RC in
+0)
 	echo "ldapmodrdn succeeded, should have failed!"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit 1
-fi
+	exit -1
+	;;
+53)
+	;;
+*)
+	echo "ldapmodrdn failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+
+echo "Testing modrdn with newRdn exact same as target..."
+$LDAPMODRDN -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD > \
+	$TESTOUT 2>&1 'cn=James A Jones 1, ou=Alumni Association, ou=People, dc=example, dc=com' 'cn=James A Jones 1'
+
+RC=$?
+case $RC in
+0)
+	;;
+*)
+	echo "ldapmodrdn failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+
+echo "Testing modrdn with newRdn same as target, changed case..."
+$LDAPMODRDN -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD > \
+	$TESTOUT 2>&1 'cn=James A Jones 1, ou=Alumni Association, ou=People, dc=example, dc=com' 'cn=James A JONES 1'
+
+RC=$?
+case $RC in
+0)
+	;;
+*)
+	echo "ldapmodrdn failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
 
 test $KILLSERVERS != no && kill -HUP $KILLPIDS
 
 echo ">>>>> Test succeeded"
+
+test $KILLSERVERS != no && wait
+
 exit 0
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test006-acls b/OpenLDAP/OpenLDAP/tests/scripts/test006-acls
--- a/OpenLDAP/OpenLDAP/tests/scripts/test006-acls
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test006-acls
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test006-acls,v 1.47.2.6 2006/07/31 22:38:44 quanah Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test006-acls,v 1.59.2.5 2008/02/11 23:26:51 kurt Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2006 The OpenLDAP Foundation.
+## Copyright 1998-2008 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -14,7 +14,7 @@
 ## <http://www.OpenLDAP.org/license.html>.
 
 case "$BACKEND" in
-bdb|hdb|ldbm)
+bdb|hdb)
 	;;
 *)
 	echo "Test does not support $BACKEND backend"
@@ -78,7 +78,30 @@ echo "# ... and should return all attributes if we're bound as anyone
 # under Example." \
 >> $SEARCHOUT
 $LDAPSEARCH -b "$JAJDN" -h $LOCALHOST -p $PORT1 \
-	-D "$BABSDN" -w bjensen "(objectclass=*)"  >> $SEARCHOUT 2>&1
+	-D "$BABSDN" -w bjensen "(objectclass=*)" >> $SEARCHOUT 2>&1
+
+# ITS#4253, ITS#4255
+echo "# Checking exact/regex attrval clause" >> $SEARCHOUT
+$LDAPSEARCH -h $LOCALHOST -p $PORT1 \
+	-D "$BABSDN" -w bjensen \
+	-b "$MELLIOTDN" -s base "(objectclass=*)" cn >> $SEARCHOUT 2>&1
+$LDAPSEARCH -h $LOCALHOST -p $PORT1 \
+	-D "$BJORNSDN" -w bjorn \
+	-b "$MELLIOTDN" -s base "(objectclass=*)" cn >> $SEARCHOUT 2>&1
+
+$LDAPSEARCH -h $LOCALHOST -p $PORT1 \
+	-D "$BABSDN" -w bjensen \
+	-b "$JOHNDDN" -s base "(objectclass=*)" cn >> $SEARCHOUT 2>&1
+$LDAPSEARCH -h $LOCALHOST -p $PORT1 \
+	-D "$BJORNSDN" -w bjorn \
+	-b "$JOHNDDN" -s base "(objectclass=*)" cn >> $SEARCHOUT 2>&1
+
+$LDAPSEARCH -h $LOCALHOST -p $PORT1 \
+	-D "$BABSDN" -w bjensen \
+	-b "$BJORNSDN" -s base "(objectclass=*)" cn >> $SEARCHOUT 2>&1
+$LDAPSEARCH -h $LOCALHOST -p $PORT1 \
+	-D "$BJORNSDN" -w bjorn \
+	-b "$BABSDN" -s base "(objectclass=*)" cn >> $SEARCHOUT 2>&1
 
 # check selfwrite access (ITS#4587).  6 attempts are made:
 # 1) delete someone else (should fail)
@@ -124,7 +147,7 @@ if test $RC != 0 ; then
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
 fi
- 	 
+
 $LDAPMODIFY -D "$JAJDN" -h $LOCALHOST -p $PORT1 -w jaj >> \
 	$TESTOUT 2>&1 << EOMODS
 dn: cn=All Staff,ou=Groups,dc=example,dc=com
@@ -147,7 +170,7 @@ case $RC in
 	exit $RC
 	;;
 esac
- 	 
+
 $LDAPMODIFY -D "$JAJDN" -h $LOCALHOST -p $PORT1 -w jaj >> \
 	$TESTOUT 2>&1 << EOMODS
 dn: cn=All Staff,ou=Groups,dc=example,dc=com
@@ -171,7 +194,7 @@ case $RC in
 	exit $RC
 	;;
 esac
- 	 
+
 $LDAPMODIFY -D "$JAJDN" -h $LOCALHOST -p $PORT1 -w jaj >> \
 	$TESTOUT 2>&1 << EOMODS
 dn: cn=All Staff,ou=Groups,dc=example,dc=com
@@ -195,7 +218,7 @@ case $RC in
 	exit $RC
 	;;
 esac
- 	 
+
 $LDAPMODIFY -D "$JAJDN" -h $LOCALHOST -p $PORT1 -w jaj >> \
 	$TESTOUT 2>&1 << EOMODS
 dn: cn=All Staff,ou=Groups,dc=example,dc=com
@@ -221,9 +244,22 @@ dn: $BABSDN
 changetype: modify
 replace: drink
 drink: wine
-
 EOMODS5
-
+RC=$?
+case $RC in
+50)
+	;;
+0)
+	echo "ldapmodify should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit -1
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
 
 $LDAPMODIFY -D "$BJORNSDN" -h $LOCALHOST -p $PORT1 -w bjorn >> \
 	$TESTOUT 2>&1 << EOMODS6
@@ -231,8 +267,17 @@ dn: $BABSDN
 changetype: modify
 add: homephone
 homephone: +1 313 555 5444
-
 EOMODS6
+RC=$?
+case $RC in
+0)
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
 
 #
 # Try to add a "member" attribute to the "ITD Staff" group.  It should
@@ -246,8 +291,22 @@ dn: cn=ITD Staff, ou=Groups, dc=example, dc=com
 changetype: modify
 add: uniquemember
 uniquemember: cn=Barbara Jensen,ou=Information Technology Division,ou=People,dc=example,dc=com
-
 EOMODS1
+RC=$?
+case $RC in
+50)
+	;;
+0)
+	echo "ldapmodify should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit -1
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
 
 $LDAPMODIFY -D "$JAJDN" -h $LOCALHOST -p $PORT1 -w jaj >> \
 	$TESTOUT 2>&1 << EOMODS2
@@ -258,6 +317,16 @@ changetype: modify
 add: uniquemember
 uniquemember: cn=James A Jones 1, ou=Alumni Association, ou=People, dc=example, dc=com
 EOMODS2
+RC=$?
+case $RC in
+0)
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
 
 #
 # Try to modify the "ITD Staff" group.  Two attempts are made:
@@ -270,8 +339,22 @@ $LDAPMODIFY -D "$JAJDN" -h $LOCALHOST -p $PORT1 -w jaj >> \
 dn: cn=ITD Staff, ou=Groups, dc=example, dc=com
 changetype: modify
 delete: description
-
 EOMODS3
+RC=$?
+case $RC in
+50)
+	;;
+0)
+	echo "ldapmodify should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit -1
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
 
 $LDAPMODIFY -D "$BJORNSDN" -h $LOCALHOST -p $PORT1 -w bjorn >> \
 	$TESTOUT 2>&1 << EOMODS4
@@ -287,6 +370,16 @@ add: ou
 ou: Groups
 # comment
 EOMODS4
+RC=$?
+case $RC in
+0)
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
 
 #
 # Try to modify the "ITD Staff" group.  Two attempts are made:
@@ -302,6 +395,16 @@ add: description
 description: added by jaj (should succeed)
 -
 EOMODS5
+RC=$?
+case $RC in
+0)
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
 
 $LDAPMODIFY -D "$BABSDN" -h $LOCALHOST -p $PORT1 -w bjensen >> \
 	$TESTOUT 2>&1 << EOMODS6
@@ -311,6 +414,21 @@ add: description
 description: added by bjensen (should fail)
 -
 EOMODS6
+RC=$?
+case $RC in
+50)
+	;;
+0)
+	echo "ldapmodify should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit -1
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
 
 $LDAPMODIFY -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD >> \
 	$TESTOUT 2>&1 << EOMODS7
@@ -319,6 +437,12 @@ changetype: add
 objectClass: organizationalUnit
 ou: Add & Delete
 EOMODS7
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
 
 $LDAPMODIFY -D "$BABSDN" -h $LOCALHOST -p $PORT1 -w bjensen >> \
 	$TESTOUT 2>&1 << EOMODS8
@@ -328,6 +452,21 @@ objectClass: inetOrgPerson
 cn: Added by Babs (must fail)
 sn: None
 EOMODS8
+RC=$?
+case $RC in
+50)
+	;;
+0)
+	echo "ldapmodify should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit -1
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
 
 $LDAPMODIFY -D "$BJORNSDN" -h $LOCALHOST -p $PORT1 -w bjorn >> \
 	$TESTOUT 2>&1 << EOMODS9
@@ -357,12 +496,37 @@ description: this attribute value will be deleted by Babs (must succeed)
 description: Bjorn will try to delete this attribute value (should fail)
 -
 EOMODS9
+RC=$?
+case $RC in
+0)
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
 
 $LDAPMODIFY -D "$BJORNSDN" -h $LOCALHOST -p $PORT1 -w bjorn >> \
 	$TESTOUT 2>&1 << EOMODS10
 dn: cn=Added by Bjorn (will be deleted),ou=Add & Delete,dc=example,dc=com
 changetype: delete
 EOMODS10
+RC=$?
+case $RC in
+50)
+	;;
+0)
+	echo "ldapmodify should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit -1
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
 
 $LDAPMODIFY -D "$BJORNSDN" -h $LOCALHOST -p $PORT1 -w bjorn >> \
 	$TESTOUT 2>&1 << EOMODS11
@@ -371,6 +535,21 @@ changetype: modrdn
 newrdn: cn=Added by Bjorn (renamed by Bjorn)
 deleteoldrdn: 1
 EOMODS11
+RC=$?
+case $RC in
+50)
+	;;
+0)
+	echo "ldapmodify should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit -1
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
 
 $LDAPMODIFY -D "$BABSDN" -h $LOCALHOST -p $PORT1 -w bjensen >> \
 	$TESTOUT 2>&1 << EOMODS12
@@ -379,6 +558,21 @@ changetype: modrdn
 newrdn: cn=Added by Bjorn (renamed by Babs)
 deleteoldrdn: 1
 EOMODS12
+RC=$?
+case $RC in
+50)
+	;;
+0)
+	echo "ldapmodify should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit -1
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
 
 $LDAPMODIFY -D "$JAJDN" -h $LOCALHOST -p $PORT1 -w jaj >> \
 	$TESTOUT 2>&1 << EOMODS13
@@ -387,6 +581,16 @@ changetype: modrdn
 newrdn: cn=Added by Bjorn (renamed by Jaj)
 deleteoldrdn: 1
 EOMODS13
+RC=$?
+case $RC in
+0)
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
 
 $LDAPMODIFY -D "$BJORNSDN" -h $LOCALHOST -p $PORT1 -w bjorn >> \
 	$TESTOUT 2>&1 << EOMODS14
@@ -396,6 +600,21 @@ delete: description
 description: Bjorn will try to delete this attribute value (should fail)
 -
 EOMODS14
+RC=$?
+case $RC in
+50)
+	;;
+0)
+	echo "ldapmodify should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit -1
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
 
 $LDAPMODIFY -D "$BABSDN" -h $LOCALHOST -p $PORT1 -w bjensen >> \
 	$TESTOUT 2>&1 << EOMODS15
@@ -408,6 +627,16 @@ delete: description
 description: this attribute value will be deleted by Babs (must succeed)
 -
 EOMODS15
+RC=$?
+case $RC in
+0)
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
 
 echo "Using ldapsearch to retrieve all the entries..."
 echo "# Using ldapsearch to retrieve all the entries..." >> $SEARCHOUT
@@ -435,4 +664,7 @@ if test $? != 0 ; then
 fi
 
 echo ">>>>> Test succeeded"
+
+test $KILLSERVERS != no && wait
+
 exit 0
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test009-referral b/OpenLDAP/OpenLDAP/tests/scripts/test009-referral
--- a/OpenLDAP/OpenLDAP/tests/scripts/test009-referral
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test009-referral
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test009-referral,v 1.33.2.4 2006/01/03 22:16:29 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test009-referral,v 1.38.2.4 2008/02/11 23:26:51 kurt Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2006 The OpenLDAP Foundation.
+## Copyright 1998-2008 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -145,6 +145,18 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
+echo "Testing dontUseCopy control..."
+$LDAPSEARCH -C -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
+	-E \!dontUseCopy \
+	'sn=jensen' >> $SEARCHOUT
+RC=$?
+if test $RC = 10 ; then
+	echo "ldapsearch failed as expected ($RC)"
+else
+	echo "ldapsearch did not error as expected ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
 
 test $KILLSERVERS != no && kill -HUP $KILLPIDS
 
@@ -163,4 +175,7 @@ if test $? != 0 ; then
 fi
 
 echo ">>>>> Test succeeded"
+
+test $KILLSERVERS != no && wait
+
 exit 0
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test018-syncreplication-persist b/OpenLDAP/OpenLDAP/tests/scripts/test018-syncreplication-persist
--- a/OpenLDAP/OpenLDAP/tests/scripts/test018-syncreplication-persist
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test018-syncreplication-persist
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test018-syncreplication-persist,v 1.25.2.5 2006/01/03 22:16:29 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test018-syncreplication-persist,v 1.38.2.3 2008/02/11 23:26:51 kurt Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2006 The OpenLDAP Foundation.
+## Copyright 1998-2008 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -30,15 +30,15 @@ mkdir -p $TESTDIR $DBDIR1 $DBDIR4
 
 #
 # Test replication:
-# - start master
-# - start slave
+# - start producer
+# - start consumer
 # - populate over ldap
 # - perform some modifies and deleted
-# - attempt to modify the slave (referral or chain)
+# - attempt to modify the consumer (referral or chain)
 # - retrieve database over ldap and compare against expected results
 #
 
-echo "Starting master slapd on TCP/IP port $PORT1..."
+echo "Starting producer slapd on TCP/IP port $PORT1..."
 . $CONFFILTER $BACKEND $MONITORDB < $SRMASTERCONF > $CONF1
 $SLAPD -f $CONF1 -h $URI1 -d $LVL $TIMING > $LOG1 2>&1 &
 PID=$!
@@ -50,7 +50,7 @@ KILLPIDS="$PID"
 
 sleep 1
 
-echo "Using ldapsearch to check that master slapd is running..."
+echo "Using ldapsearch to check that producer slapd is running..."
 for i in 0 1 2 3 4 5; do
 	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT1 \
 		'objectclass=*' > /dev/null 2>&1
@@ -68,7 +68,7 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-echo "Using ldapadd to create the context prefix entry in the master..."
+echo "Using ldapadd to create the context prefix entry in the producer..."
 $LDAPADD -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD < \
 	$LDIFORDEREDCP > /dev/null 2>&1
 RC=$?
@@ -78,7 +78,7 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-echo "Starting slave slapd on TCP/IP port $PORT4..."
+echo "Starting consumer slapd on TCP/IP port $PORT4..."
 . $CONFFILTER $BACKEND $MONITORDB < $P1SRSLAVECONF > $CONF4
 $SLAPD -f $CONF4 -h $URI4 -d $LVL $TIMING > $LOG4 2>&1 &
 SLAVEPID=$!
@@ -90,7 +90,7 @@ KILLPIDS="$KILLPIDS $SLAVEPID"
 
 sleep 1
 
-echo "Using ldapsearch to check that slave slapd is running..."
+echo "Using ldapsearch to check that consumer slapd is running..."
 for i in 0 1 2 3 4 5; do
 	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT4 \
 		'objectclass=*' > /dev/null 2>&1
@@ -108,7 +108,7 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-echo "Using ldapadd to populate the master directory..."
+echo "Using ldapadd to populate the producer directory..."
 $LDAPADD -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD < \
 	$LDIFORDEREDNOCP > /dev/null 2>&1
 RC=$?
@@ -123,6 +123,7 @@ sleep 15
 
 echo "Stopping the provider, sleeping 10 seconds and restarting it..."
 kill -HUP "$PID"
+wait $PID
 sleep 10
 echo "RESTART" >> $LOG1
 $SLAPD -f $CONF1 -h $URI1 -d $LVL $TIMING >> $LOG1 2>&1 &
@@ -135,7 +136,7 @@ KILLPIDS="$PID $SLAVEPID"
 
 sleep 1
 
-echo "Using ldapsearch to check that master slapd is running..."
+echo "Using ldapsearch to check that producer slapd is running..."
 for i in 0 1 2 3 4 5; do
 	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT1 \
 		'objectclass=*' > /dev/null 2>&1
@@ -153,7 +154,7 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-echo "Using ldapmodify to modify master directory..."
+echo "Using ldapmodify to modify producer directory..."
 
 #
 # Do some modifications
@@ -239,14 +240,25 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
+echo "Using ldappasswd to change some passwords..."
+$LDAPPASSWD -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD \
+	'cn=Bjorn Jensen,ou=Information Technology Division,ou=People,dc=example,dc=com' \
+	> $TESTOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
 echo "Waiting 15 seconds for syncrepl to receive changes..."
 sleep 15
 
 echo "Stopping consumer to test recovery..."
 kill -HUP $SLAVEPID
-sleep 10
+wait $SLAVEPID
 
-echo "Modifying more entries on the master..."
+echo "Modifying more entries on the producer..."
 $LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD >> \
 	$TESTOUT 2>&1 << EOMODS
 dn: cn=Rosco P. Coltrane, ou=Retired, ou=People, dc=example,dc=com
@@ -280,7 +292,7 @@ echo "Waiting 25 seconds for syncrepl to receive changes..."
 sleep 25
 
 if test ! $BACKLDAP = "ldapno" ; then
-	echo "Try updating the slave slapd..."
+	echo "Try updating the consumer slapd..."
 	$LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT4 -w $PASSWD > \
 		$TESTOUT 2>&1 << EOMODS
 dn: cn=James A Jones 1, ou=Alumni Association, ou=People, dc=example, dc=com
@@ -298,46 +310,63 @@ EOMODS
 		exit $RC
 	fi
 
+	# ITS#4964
+	echo "Trying to change some passwords on the consumer..."
+	$LDAPPASSWD -D "$MANAGERDN" -h $LOCALHOST -p $PORT4 -w $PASSWD \
+		'cn=Barbara Jensen,ou=Information Technology Division,ou=People,dc=example,dc=com' \
+		> $TESTOUT 2>&1
+	RC=$?
+	if test $RC != 0 ; then
+		echo "ldapmodify failed ($RC)!"
+		test $KILLSERVERS != no && kill -HUP $KILLPIDS
+		exit $RC
+	fi
+
 	echo "Waiting 15 seconds for syncrepl to receive changes..."
 	sleep 15
 fi
 
-echo "Using ldapsearch to read all the entries from the master..."
+OPATTRS="entryUUID creatorsName createTimestamp modifiersName modifyTimestamp"
+
+echo "Using ldapsearch to read all the entries from the producer..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
-	'objectclass=*' > $MASTEROUT 2>&1
+	'(objectclass=*)' '*' $OPATTRS > $MASTEROUT 2>&1
 RC=$?
 
 if test $RC != 0 ; then
-	echo "ldapsearch failed at master ($RC)!"
+	echo "ldapsearch failed at producer ($RC)!"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
 fi
 
-echo "Using ldapsearch to read all the entries from the slave..."
+echo "Using ldapsearch to read all the entries from the consumer..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT4 \
-	'objectclass=*' > $SLAVEOUT 2>&1
+	'(objectclass=*)' '*' $OPATTRS > $SLAVEOUT 2>&1
 RC=$?
 
 if test $RC != 0 ; then
-	echo "ldapsearch failed at slave ($RC)!"
+	echo "ldapsearch failed at consumer ($RC)!"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
 fi
 
 test $KILLSERVERS != no && kill -HUP $KILLPIDS
 
-echo "Filtering master results..."
+echo "Filtering producer results..."
 . $LDIFFILTER < $MASTEROUT > $MASTERFLT
-echo "Filtering slave results..."
+echo "Filtering consumer results..."
 . $LDIFFILTER < $SLAVEOUT > $SLAVEFLT
 
-echo "Comparing retrieved entries from master and slave..."
+echo "Comparing retrieved entries from producer and consumer..."
 $CMP $MASTERFLT $SLAVEFLT > $CMPOUT
 
 if test $? != 0 ; then
-	echo "test failed - master and slave databases differ"
+	echo "test failed - producer and consumer databases differ"
 	exit 1
 fi
 
 echo ">>>>> Test succeeded"
+
+test $KILLSERVERS != no && wait
+
 exit 0
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test025-limits b/OpenLDAP/OpenLDAP/tests/scripts/test025-limits
--- a/OpenLDAP/OpenLDAP/tests/scripts/test025-limits
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test025-limits
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test025-limits,v 1.14.2.4 2006/01/03 22:16:29 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test025-limits,v 1.19.2.5 2008/02/11 23:26:51 kurt Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2006 The OpenLDAP Foundation.
+## Copyright 1998-2008 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -496,6 +496,8 @@ case $RC in
 	;;
 esac
 
+case $BACKEND in bdb | hdb)
+
 echo "Testing higher than unchecked limit requested for unchecked limited ID..."
 $LDAPRSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 -w secret \
 	-D 'cn=Unchecked Limited User,ou=People,dc=example,dc=com' \
@@ -546,6 +548,9 @@ case $RC in
 		test $KILLSERVERS != no && kill -HUP $KILLPIDS
 		exit $RC
 	;;
+esac
+;;
+*)	echo "Skipping test for unchecked limit with $BACKEND backend." ;;
 esac
 
 echo "Testing no limits requested for limited regex..."
@@ -1359,7 +1364,56 @@ case $RC in
 	;;
 esac
 
+# ITS#4479
+PAGESIZE=1
+SIZELIMIT=2
+echo "Testing size limit request ($SIZELIMIT) for unlimited ID and pagesize=$PAGESIZE..."
+$LDAPRSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 -w secret -z $SIZELIMIT \
+	-D 'cn=Unlimited User,ou=People,dc=example,dc=com' \
+	-E '!pr='$PAGESIZE'/noprompt' '(objectClass=*)' > $SEARCHOUT 2>&1
+RC=$?
+COUNT=`awk '/^# numEntries:/ {print $3}' $SEARCHOUT`
+case $RC in
+	0)
+		if test x"$COUNT" != x ; then
+                        if test "$COUNT" -gt "$SIZELIMIT" ; then
+                                echo "...error: got $COUNT entries instead of the requested $SIZELIMIT"
+                                test $KILLSERVERS != no && kill -HUP $KILLPIDS
+                                exit 1
+                        fi
+                        echo "...didn't bump into the requested size limit ($SIZELIMIT; got $COUNT entries)"
+                else
+                        echo "...error: did not expect ldapsearch success ($RC)!"
+                        test $KILLSERVERS != no && kill -HUP $KILLPIDS
+                        exit 1
+                fi
+	;;
+	4)
+		if test x"$COUNT" != x ; then
+			if test $COUNT = $SIZELIMIT ; then
+				echo "...bumped into requested size limit ($SIZELIMIT)"
+			else
+				echo "...error: got $COUNT entries while requesting $SIZELIMIT..."
+                                test $KILLSERVERS != no && kill -HUP $KILLPIDS
+                                exit $RC
+                        fi
+		else
+			echo "...error: bumped into server-side size limit, but got no entries!"
+                        test $KILLSERVERS != no && kill -HUP $KILLPIDS
+                        exit $RC
+		fi
+	;;
+	*)
+		echo "ldapsearch failed ($RC)!"
+		test $KILLSERVERS != no && kill -HUP $KILLPIDS
+		exit $RC
+	;;
+esac
+
 test $KILLSERVERS != no && kill -HUP $KILLPIDS
 
 echo ">>>>> Test succeeded"
+
+test $KILLSERVERS != no && wait
+
 exit 0
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test033-glue-syncrepl b/OpenLDAP/OpenLDAP/tests/scripts/test033-glue-syncrepl
--- a/OpenLDAP/OpenLDAP/tests/scripts/test033-glue-syncrepl
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test033-glue-syncrepl
@@ -1,7 +1,7 @@
 #! /bin/sh
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2006 The OpenLDAP Foundation.
+## Copyright 1998-2008 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -163,7 +163,31 @@ for P in $PORT1 $PORT2 ; do
 	fi
 done
 
+echo "Testing ldapdelete propagation..."
+$LDAPDELETE -D "cn=Manager 1,$BASEDN" -w $PASSWD -H $URI1 "$BABSDN" \
+	> $TESTOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapdelete failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+# This usually propagates immediately
+sleep 1
+
+$LDAPSEARCH -H $URI2 -b "$BABSDN" > $TESTOUT 2>&1
+RC=$?
+if test $RC = 0 ; then
+	echo "ldapsearch should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit -1
+fi
+
 test $KILLSERVERS != no && kill -HUP $KILLPIDS
 
 echo ">>>>> Test succeeded"
+
+test $KILLSERVERS != no && wait
+
 exit 0
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test034-translucent b/OpenLDAP/OpenLDAP/tests/scripts/test034-translucent
--- a/OpenLDAP/OpenLDAP/tests/scripts/test034-translucent
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test034-translucent
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test034-translucent,v 1.1.2.5 2006/01/03 22:16:29 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test034-translucent,v 1.8.2.6 2008/02/11 23:26:51 kurt Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 2004-2006 The OpenLDAP Foundation.
+## Copyright 2004-2008 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -25,11 +25,6 @@ if test $TRANSLUCENT = translucentno ; then
 	exit 0
 fi 
 
-if test $BACKEND = ldbm ; then
-	echo "Translucent Proxy overlay not qualified for use with LDBM, test skipped"
-	exit 0
-fi
-
 if test $AC_ldap = ldapno ; then
 	echo "Translucent Proxy overlay requires back-ldap backend, test skipped"
 	exit 0
@@ -37,6 +32,15 @@ fi
 
 # configure backside
 mkdir -p $TESTDIR $DBDIR1
+
+$SLAPPASSWD -g -n >$CONFIGPWF
+echo "rootpw `$SLAPPASSWD -T $CONFIGPWF`" >$TESTDIR/configpw.conf
+
+if test $MONITORDB != no ; then
+	DBIX=2
+else
+	DBIX=1
+fi
 
 . $CONFFILTER $BACKEND $MONITORDB < $TRANSLUCENTREMOTECONF > $CONF1
 echo "Running slapadd to build remote slapd database..."
@@ -201,41 +205,19 @@ if test $RC != 32 ; then
 	exit 1
 fi
 
-echo "Shutting down local slapd..."
-kill -HUP $LOCALPID
-sleep 5
+echo "Dynamically configuring local slapd without translucent_no_glue..."
 
-echo "Configuring local slapd without translucent_no_glue..."
-. $CONFFILTER $BACKEND $MONITORDB < $TRANSLUCENTLOCALCONF | \
-	grep -v translucent_no_glue > $CONF2
-
-echo "Restarting local slapd on TCP/IP port $PORT2..."
-$SLAPD -f $CONF2 -h $URI2 -d $LVL $TIMING >> $LOG2 2>&1 &
-PID=$!
-if test $WAIT != 0 ; then
-    echo PID $PID
-    read foo
-fi
-LOCALPID="$PID"
-KILLPIDS="$REMOTEPID $PID"
-
-sleep 1
-
-for i in 0 1 2 3 4 5; do
-	$LDAPSEARCH -s base -b "$MONITOR" -H $URI2 \
-		'objectclass=*' > /dev/null 2>&1
-	RC=$?
-	if test $RC = 0 ; then
-		break
-	fi
-	echo "Waiting 5 seconds for local slapd to start..."
-	sleep 5
-done
-
+$LDAPMODIFY -D cn=config -H $URI2 -y $CONFIGPWF <<EOF
+dn: olcOverlay={0}translucent,olcDatabase={$DBIX}$BACKEND,cn=config
+changetype: modify
+replace: olcTranslucentNoGlue
+olcTranslucentNoGlue: FALSE
+EOF
+RC=$?
 if test $RC != 0 ; then
-	echo "ldapsearch failed ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit $RC
+    echo "ldapmodify of dynamic config failed ($RC)"
+    test $KILLSERVERS != no && kill -HUP $KILLPIDS
+    exit 1
 fi
 
 echo "Testing add: valid local record..."
@@ -577,6 +559,24 @@ if test $RC != 16 ; then
 	exit 1
 fi
 
+echo "Testing delete: valid local record, remote attribute..."
+
+$LDAPMODIFY -v -D "$TRANSLUCENTROOT" -H $URI2 -w $PASSWD > \
+        $TESTOUT 2>&1 << EOF_MOD8
+version: 1
+dn: uid=danger,ou=users,o=translucent
+changetype: modify
+delete: initials
+EOF_MOD8
+
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)"
+	grep "$FAILURE" $TESTOUT
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+fi
+
 echo "Testing modify: valid remote record, combination add-modify-delete..."
 
 $LDAPMODIFY -v -D "$TRANSLUCENTROOT" -H $URI2 -w $PASSWD > \
@@ -624,40 +624,22 @@ if test "$ATTR" != "preferredLanguage: ISO8859-1" ; then
 	exit 1
 fi
 
-echo "Shutting down local slapd..."
-kill -HUP $LOCALPID
-sleep 5
+echo "Dynamically configuring local slapd with translucent_no_glue and translucent_strict..."
 
-echo "Configuring local slapd with translucent_strict..."
-echo translucent_strict >> $CONF2
-
-echo "Restarting slapd on TCP/IP port $PORT2..."
-$SLAPD -f $CONF2 -h $URI2 -d $LVL $TIMING >> $LOG2 2>&1 &
-PID=$!
-if test $WAIT != 0 ; then
-    echo PID $PID
-    read foo
-fi
-LOCALPID="$PID"
-KILLPIDS="$REMOTEPID $PID"
-
-sleep 1
-
-for i in 0 1 2 3 4 5; do
-	$LDAPSEARCH -s base -b "$MONITOR" -H $URI2 \
-		'objectclass=*' > /dev/null 2>&1
-	RC=$?
-	if test $RC = 0 ; then
-		break
-	fi
-	echo "Waiting 5 seconds for local slapd to start..."
-	sleep 5
-done
-
+$LDAPMODIFY -D cn=config -H $URI2 -y $CONFIGPWF <<EOF
+dn: olcOverlay={0}translucent,olcDatabase={$DBIX}$BACKEND,cn=config
+changetype: modify
+replace: olcTranslucentNoGlue
+olcTranslucentNoGlue: TRUE
+-
+replace: olcTranslucentStrict
+olcTranslucentStrict: TRUE
+EOF
+RC=$?
 if test $RC != 0 ; then
-	echo "ldapsearch failed ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit $RC
+    echo "ldapmodify of dynamic config failed ($RC)"
+    test $KILLSERVERS != no && kill -HUP $KILLPIDS
+    exit 1
 fi
 
 echo "Testing strict mode delete: nonexistent local attribute..."
@@ -720,7 +702,101 @@ if test $RC != 19 ; then
 	exit 1
 fi
 
+echo "Testing invalid Bind request..."
+$LDAPWHOAMI -D "$TRANSLUCENTDN" -H $URI2 -w Wrong"$TRANSLUCENTPASSWD" > \
+	$TESTOUT 2>&1
+RC=$?
+if test $RC != 49 ; then
+	echo "ldapwhoami failed ($RC), expected INVALID CREDENTIALS!"
+	grep "$FAILURE" $TESTOUT
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+fi
+
+$LDAPWHOAMI -D "$TRANSLUCENTDN" -H $URI2 -w "$TRANSLUCENTPASSWD" > \
+	$TESTOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapwhoami failed ($RC), expected SUCCESS!"
+	grep "$FAILURE" $TESTOUT
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+fi
+
+echo "Testing search: unconfigured local filter..."
+$LDAPSEARCH -H $URI2 -b "o=translucent" "(employeeType=consultant)" > $SEARCHOUT 2>&1
+
+ATTR=`grep dn: $SEARCHOUT` > $NOWHERE 2>&1
+if test -n "$ATTR" ; then
+	echo "got result $ATTR, should have been no result"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+fi
+
+echo "Dynamically configuring local slapd with translucent_local..."
+
+$LDAPMODIFY -D cn=config -H $URI2 -y $CONFIGPWF <<EOF
+dn: olcOverlay={0}translucent,olcDatabase={$DBIX}$BACKEND,cn=config
+changetype: modify
+add: olcTranslucentLocal
+olcTranslucentLocal: employeeType
+EOF
+RC=$?
+if test $RC != 0 ; then
+    echo "ldapmodify of dynamic config failed ($RC)"
+    test $KILLSERVERS != no && kill -HUP $KILLPIDS
+    exit 1
+fi
+
+echo "Testing search: configured local filter..."
+$LDAPSEARCH -H $URI2 -b "o=translucent" "(employeeType=consultant)" > $SEARCHOUT 2>&1
+
+ATTR=`grep dn: $SEARCHOUT` > $NOWHERE 2>&1
+if test -z "$ATTR" ; then
+	echo "got no result, should have found entry"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+fi
+
+echo "Testing search: unconfigured remote filter..."
+$LDAPSEARCH -H $URI2 -b "o=translucent" "(|(employeeType=foo)(carlicense=right))" > $SEARCHOUT 2>&1
+
+ATTR=`grep dn: $SEARCHOUT` > $NOWHERE 2>&1
+if test -n "$ATTR" ; then
+	echo "got result $ATTR, should have been no result"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+fi
+
+echo "Dynamically configuring local slapd with translucent_remote..."
+
+$LDAPMODIFY -D cn=config -H $URI2 -y $CONFIGPWF <<EOF
+dn: olcOverlay={0}translucent,olcDatabase={$DBIX}$BACKEND,cn=config
+changetype: modify
+add: olcTranslucentRemote
+olcTranslucentRemote: carLicense
+EOF
+RC=$?
+if test $RC != 0 ; then
+    echo "ldapmodify of dynamic config failed ($RC)"
+    test $KILLSERVERS != no && kill -HUP $KILLPIDS
+    exit 1
+fi
+
+echo "Testing search: configured remote filter..."
+$LDAPSEARCH -H $URI2 -b "o=translucent" "(|(employeeType=foo)(carlicense=right))" > $SEARCHOUT 2>&1
+
+ATTR=`grep dn: $SEARCHOUT` > $NOWHERE 2>&1
+if test -z "$ATTR" ; then
+	echo "got no result, should have found entry"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+fi
+
 test $KILLSERVERS != no && kill -HUP $KILLPIDS
 
 echo ">>>>> Test succeeded"
+
+test $KILLSERVERS != no && wait
+
 exit 0
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test035-meta b/OpenLDAP/OpenLDAP/tests/scripts/test035-meta
--- a/OpenLDAP/OpenLDAP/tests/scripts/test035-meta
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test035-meta
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test035-meta,v 1.4.2.8 2006/01/03 22:16:29 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test035-meta,v 1.14.2.5 2008/07/09 23:51:35 quanah Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2006 The OpenLDAP Foundation.
+## Copyright 1998-2008 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -23,12 +23,17 @@ if test $BACKMETA = metano ; then
 	exit 0
 fi
 
+if test $BACKLDAP = ldapno ; then 
+	echo "ldap backend not available, test skipped"
+	exit 0
+fi
+
 rm -rf $TESTDIR
 
 mkdir -p $TESTDIR $DBDIR1 $DBDIR2
 
 echo "Starting slapd on TCP/IP port $PORT1..."
-. $CONFFILTER $BACKEND $MONITORDB < $CONF > $CONF1
+. $CONFFILTER $BACKEND $MONITORDB < $METACONF1 > $CONF1
 $SLAPD -f $CONF1 -h $URI1 -d $LVL $TIMING > $LOG1 2>&1 &
 PID=$!
 if test $WAIT != 0 ; then
@@ -471,6 +476,54 @@ case $RC in
 	;;
 esac
 
+# NOTE: cannot send to $SEARCHOUT because the returned entries
+# are not predictable...
+echo "Checking server-enforced size limit..."
+echo "# Checking server-enforced size limit..." >> $SEARCHOUT
+$LDAPSEARCH -S "" -h $LOCALHOST -p $PORT3 \
+	-D "cn=Bjorn Jensen,ou=Information Technology Division,ou=People,$BASEDN" -w bjorn \
+	-b "$BASEDN" "(objectClass=*)" 1.1 \
+	>> $TESTOUT 2>&1
+RC=$?
+case $RC in 
+	0)
+		echo "Search should have failed ($RC)!"
+		test $KILLSERVERS != no && kill -HUP $KILLPIDS
+		exit -1
+	;;
+	4)
+	;;
+	*)
+		echo "Search failed ($RC)!"
+		test $KILLSERVERS != no && kill -HUP $KILLPIDS
+		exit $RC
+	;;
+esac
+
+# NOTE: cannot send to $SEARCHOUT because the returned entries
+# are not predictable...
+echo "Checking client-requested size limit..."
+echo "# Checking client-requested size limit..." >> $SEARCHOUT
+$LDAPSEARCH -S "" -h $LOCALHOST -p $PORT3 \
+	-D "cn=Bjorn Jensen,ou=Information Technology Division,ou=People,$BASEDN" -w bjorn \
+	-b "$BASEDN" -z 2 "(objectClass=*)" 1.1 \
+	>> $TESTOUT 2>&1
+RC=$?
+case $RC in 
+	0)
+		echo "Search should have failed ($RC)!"
+		test $KILLSERVERS != no && kill -HUP $KILLPIDS
+		exit -1
+	;;
+	4)
+	;;
+	*)
+		echo "Search failed ($RC)!"
+		test $KILLSERVERS != no && kill -HUP $KILLPIDS
+		exit $RC
+	;;
+esac
+
 echo "Filtering ldapsearch results..."
 . $LDIFFILTER < $SEARCHOUT > $SEARCHFLT
 echo "Filtering original ldif used to create database..."
@@ -627,6 +680,29 @@ case $RC in
 	;;
 esac
 
+echo "Binding with non-existing user to database \"$BASEDN\"..."
+$LDAPWHOAMI -h $LOCALHOST -p $PORT3 \
+	-D "cn=Non-existing User,ou=Same as above,ou=Meta,$BASEDN" \
+	-w bogus >> $TESTOUT 2>&1
+RC=$?
+#if test $RC != 0 ; then
+#	echo "WhoAmI failed ($RC)!"
+#	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+#	exit $RC
+#fi
+case $RC in 
+	0)
+		echo "WhoAmI should have failed ($RC)!"
+		test $KILLSERVERS != no && kill -HUP $KILLPIDS
+		exit -1
+	;;
+	51)
+		echo "### Hit LDAP_BUSY problem; you may want to re-run the test"
+	;;
+	*)
+	;;
+esac
+
 echo "Comparing to database \"$BASEDN\"..."
 $LDAPCOMPARE -h $LOCALHOST -p $PORT3 \
 	"cn=Another Added Group,ou=Groups,$BASEDN" \
@@ -653,5 +729,7 @@ esac
 test $KILLSERVERS != no && kill -HUP $KILLPIDS
 
 echo ">>>>> Test succeeded"
-exit 0
 
+test $KILLSERVERS != no && wait
+
+exit 0
diff --git a/SpamAssassin/SpamAssassin.SetupExtras/learn_junk_mail b/SpamAssassin/SpamAssassin.SetupExtras/learn_junk_mail
--- a/SpamAssassin/SpamAssassin.SetupExtras/learn_junk_mail
+++ b/SpamAssassin/SpamAssassin.SetupExtras/learn_junk_mail
@@ -3,22 +3,91 @@
 # SpamAssassin auto learn script
 #
 
+PROG=$0
+
+DEBUG=false
+JUNK_MAIL_USER=junkmail
+NOT_JUNK_MAIL_USER=notjunkmail
+
+usage()
+{
+  echo "\
+Usage: $PROG [options]
+Options:
+  -d                        debug
+  -h not-junk-mail-user     user whose mail is not junk ('ham') [$NOT_JUNK_MAIL_USER]
+  -s junk-mail-user         user whose mail is all junk ('spam') [$JUNK_MAIL_USER]"
+  exit 1
+}
+
+while getopts dh:s: o
+do
+  case "$o" in
+  d) DEBUG=true
+    ;;
+  h) NOT_JUNK_MAIL_USER=$OPTARG
+    ;;
+  s) JUNK_MAIL_USER=$OPTARG
+    ;;
+  *) usage
+    ;;
+  esac
+done
+shift `expr $OPTIND - 1`
+
+JUNK_MAIL_GUID=`/usr/bin/cvt_mail_data -i "$JUNK_MAIL_USER"`
+if [ `expr "$JUNK_MAIL_GUID" : '[0-9A-F]*-[0-9A-F]*-[0-9A-F]*-[0-9A-F]*-[0-9A-F]*'` -eq 0 ]
+then
+  echo "Can't find GUID for junk mail user $JUNK_MAIL_USER"
+  echo $JUNK_MAIL_GUID
+  exit 1
+fi
+
+NOT_JUNK_MAIL_GUID=`/usr/bin/cvt_mail_data -i "$NOT_JUNK_MAIL_USER"`
+if [ `expr "$NOT_JUNK_MAIL_GUID" : '[0-9A-F]*-[0-9A-F]*-[0-9A-F]*-[0-9A-F]*-[0-9A-F]*'` -eq 0 ]
+then
+  echo "Can't find GUID for not-junk mail user $NOT_JUNK_MAIL_USER"
+  echo $NOT_JUNK_MAIL_GUID
+  exit 1
+fi
+
+PART_MAP_PATH=/etc/dovecot/partition_map.conf
+MAIL_STORE_PATH=`grep "^default:" $PART_MAP_PATH | sed s,default:,,`
+case "$MAIL_STORE_PATH" in
+/*) # OK
+  ;;
+*) echo "Can't determine mail store path from $PART_MAP_PATH"
+  exit 1
+  ;;
+esac
+
+JUNK_MAIL_PATH="$MAIL_STORE_PATH/$JUNK_MAIL_GUID"
+NOT_JUNK_MAIL_PATH="$MAIL_STORE_PATH/$NOT_JUNK_MAIL_GUID"
+
+if $DEBUG
+then
+  echo "Junk user:     $JUNK_MAIL_USER"
+  echo "Not-junk user: $NOT_JUNK_MAIL_USER"
+  echo "Junk GUID:     $JUNK_MAIL_GUID"
+  echo "Not-junk GUID: $NOT_JUNK_MAIL_GUID"
+  echo "Junk path:     $JUNK_MAIL_PATH"
+  echo "Not-junk path: $NOT_JUNK_MAIL_PATH"
+fi
+
 SA_LEARN_PATH="/usr/bin/sa-learn"
-JUNK_MAIL_USER="user/junkmail"
-NOT_JUNK_MAIL_USER="user/notjunkmail"
-MAIL_STORE_PATH=`cat /etc/imapd.conf | grep partition-default | sed 's/^.* / /'`
+DB_PATH=/var/amavis/.spamassassin
 
 # Check for root user
 if [ `whoami` != "root" ]
 then
   echo "You must be root to execute this script"
-  exit 0;
+  exit 1
 fi
 
 # Does the mail store exist
-if [ ! -d $MAIL_STORE_PATH ]
+if [ ! -d "$MAIL_STORE_PATH" ]
 then
-  echo "Database path: $MAIL_STORE_PATH does not exist" 
+  echo "Mail store path: $MAIL_STORE_PATH does not exist" 
   exit 1
 fi
 
@@ -30,28 +99,24 @@ then
 fi
 
 # Has the junk-mail user account been created
-if [ -d $MAIL_STORE_PATH/$JUNK_MAIL_USER ]
+if [ -d "$JUNK_MAIL_PATH" ]
 then
   echo "Learning what is junk mail"
-  cd $MAIL_STORE_PATH/$JUNK_MAIL_USER
-  for file in *. ; do
-    if [ -f $file ]; then
-      cat $file | sudo -u _amavisd sa-learn --dbpath /var/amavis/.spamassassin --spam --no-sync >> /dev/null;
-    fi
+  find "$JUNK_MAIL_PATH/cur" "$JUNK_MAIL_PATH/new" -type f -print | while read file
+  do
+    sudo -u _amavisd $SA_LEARN_PATH --dbpath $DB_PATH --spam --no-sync < "$file" > /dev/null
   done
 fi
 
 # Has the not-junk-mail user account been created
-if [ -d $MAIL_STORE_PATH/$NOT_JUNK_MAIL_USER ]
+if [ -d "$NOT_JUNK_MAIL_PATH" ]
 then
   echo "Learning what is not junk mail"
-  cd $MAIL_STORE_PATH/$NOT_JUNK_MAIL_USER
-  for file in *. ; do
-    if [ -f $file ]; then
-      cat $file | sudo -u _amavisd sa-learn --dbpath /var/amavis/.spamassassin --ham --no-sync >> /dev/null;
-    fi
+  find "$NOT_JUNK_MAIL_PATH/cur" "$NOT_JUNK_MAIL_PATH/new" -type f -print | while read file
+  do
+    sudo -u _amavisd $SA_LEARN_PATH --dbpath $DB_PATH --ham --no-sync < "$file" > /dev/null
   done
 fi
 
 # Force a database sync
-sudo -u _amavisd sa-learn --dbpath /var/amavis/.spamassassin --sync >> /dev/null
+sudo -u _amavisd $SA_LEARN_PATH --dbpath $DB_PATH --sync > /dev/null
diff --git a/gcc/libcpp/configure b/gcc/libcpp/configure
--- a/gcc/libcpp/configure
+++ b/gcc/libcpp/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os SET_MAKE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT RANLIB ac_ct_RANLIB ACLOCAL AUTOCONF AUTOHEADER WARN_CFLAGS WARN_PEDANTIC WERROR CPP EGREP LIBOBJS ALLOCA USE_NLS LIBINTL LIBINTL_DEP INCINTL XGETTEXT GMSGFMT POSUB CATALOGS LIBICONV LTLIBICONV PACKAGE USED_CATALOGS MAINT LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os SET_MAKE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT RANLIB ac_ct_RANLIB ACLOCAL AUTOCONF AUTOHEADER WARN_CFLAGS WARN_PEDANTIC WERROR am__leading_dot DEPDIR CCDEPMODE CPP EGREP LIBOBJS ALLOCA USE_NLS LIBINTL LIBINTL_DEP INCINTL XGETTEXT GMSGFMT POSUB CATALOGS DATADIRNAME INSTOBJEXT GENCAT CATOBJEXT LIBICONV LTLIBICONV PACKAGE USED_CATALOGS MAINT LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -2691,7 +2691,8 @@ test -n "$AUTOHEADER" || AUTOHEADER="$MISSING autoheader"
 WARN_CFLAGS=
 save_CFLAGS="$CFLAGS"
 for option in -W -Wall -Wwrite-strings -Wstrict-prototypes \
-			  -Wmissing-prototypes -Wold-style-definition; do
+			  -Wmissing-prototypes -Wold-style-definition \
+			  -Wmissing-format-attribute; do
   as_acx_Woption=`echo "acx_cv_prog_cc_warning_$option" | $as_tr_sh`
 
   echo "$as_me:$LINENO: checking whether $CC supports $option" >&5
@@ -2837,6 +2838,120 @@ if test $enable_werror_always = yes; then
   WERROR=-Werror
 fi
 
+
+
+# Dependency checking.
+rm -rf .tst 2>/dev/null
+mkdir .tst 2>/dev/null
+if test -d .tst; then
+  am__leading_dot=.
+else
+  am__leading_dot=_
+fi
+rmdir .tst 2>/dev/null
+
+DEPDIR="${am__leading_dot}deps"
+
+          ac_config_commands="$ac_config_commands depdir"
+
+
+depcc="$CC"   am_compiler_list=
+
+am_depcomp=$ac_aux_dir/depcomp
+echo "$as_me:$LINENO: checking dependency style of $depcc" >&5
+echo $ECHO_N "checking dependency style of $depcc... $ECHO_C" >&6
+if test "${am_cv_CC_dependencies_compiler_type+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -f "$am_depcomp"; then
+  # We make a subdir and do the tests there.  Otherwise we can end up
+  # making bogus files that we don't know about and never remove.  For
+  # instance it was reported that on HP-UX the gcc test will end up
+  # making a dummy file named `D' -- because `-MD' means `put the output
+  # in D'.
+  mkdir conftest.dir
+  # Copy depcomp to subdir because otherwise we won't find it if we're
+  # using a relative directory.
+  cp "$am_depcomp" conftest.dir
+  cd conftest.dir
+  # We will build objects and dependencies in a subdirectory because
+  # it helps to detect inapplicable dependency modes.  For instance
+  # both Tru64's cc and ICC support -MD to output dependencies as a
+  # side effect of compilation, but ICC will put the dependencies in
+  # the current directory while Tru64 will put them in the object
+  # directory.
+  mkdir sub
+
+  am_cv_CC_dependencies_compiler_type=none
+  if test "$am_compiler_list" = ""; then
+     am_compiler_list=`sed -n 's/^\([a-zA-Z0-9]*\))$/\1/p' < ./depcomp`
+  fi
+  for depmode in $am_compiler_list; do
+    if test $depmode = none; then break; fi
+
+    echo "$as_me:$LINENO: trying $depmode" >&5
+    # Setup a source with many dependencies, because some compilers
+    # like to wrap large dependency lists on column 80 (with \), and
+    # we should not choose a depcomp mode which is confused by this.
+    #
+    # We need to recreate these files for each test, as the compiler may
+    # overwrite some of them when testing with obscure command lines.
+    # This happens at least with the AIX C compiler.
+    : > sub/conftest.c
+    for i in 1 2 3 4 5 6; do
+      echo '#include "conftst'$i'.h"' >> sub/conftest.c
+      # Using `: > sub/conftst$i.h' creates only sub/conftst1.h with
+      # Solaris 8's {/usr,}/bin/sh.
+      touch sub/conftst$i.h
+    done
+    echo "include sub/conftest.Po" > confmf
+
+    # We check with `-c' and `-o' for the sake of the "dashmstdout"
+    # mode.  It turns out that the SunPro C++ compiler does not properly
+    # handle `-M -o', and we need to detect this.
+    depcmd="depmode=$depmode \
+       source=sub/conftest.c object=sub/conftest.${OBJEXT-o} \
+       depfile=sub/conftest.Po tmpdepfile=sub/conftest.TPo \
+       $SHELL ./depcomp $depcc -c -o sub/conftest.${OBJEXT-o} sub/conftest.c"
+    echo "| $depcmd" | sed -e 's/  */ /g' >&5
+    if env $depcmd > conftest.err 2>&1 &&
+       grep sub/conftst6.h sub/conftest.Po >>conftest.err 2>&1 &&
+       grep sub/conftest.${OBJEXT-o} sub/conftest.Po >>conftest.err 2>&1 &&
+       ${MAKE-make} -s -f confmf >>conftest.err 2>&1; then
+      # icc doesn't choke on unknown options, it will just issue warnings
+      # or remarks (even with -Werror).  So we grep stderr for any message
+      # that says an option was ignored or not supported.
+      # When given -MP, icc 7.0 and 7.1 complain thusly:
+      #   icc: Command line warning: ignoring option '-M'; no argument required
+      # The diagnosis changed in icc 8.0:
+      #   icc: Command line remark: option '-MP' not supported
+      if (grep 'ignoring option' conftest.err ||
+          grep 'not supported' conftest.err) >/dev/null 2>&1; then :; else
+        am_cv_CC_dependencies_compiler_type=$depmode
+	echo "$as_me:$LINENO: success" >&5
+        break
+      fi
+    fi
+    echo "$as_me:$LINENO: failure, diagnostics are:" >&5
+    sed -e 's/^/| /' < conftest.err >&5
+  done
+
+  cd ..
+  rm -rf conftest.dir
+else
+  am_cv_CC_dependencies_compiler_type=none
+fi
+
+fi
+echo "$as_me:$LINENO: result: $am_cv_CC_dependencies_compiler_type" >&5
+echo "${ECHO_T}$am_cv_CC_dependencies_compiler_type" >&6
+if test x${am_cv_CC_dependencies_compiler_type-none} = xnone
+then { { echo "$as_me:$LINENO: error: no usable dependency style found" >&5
+echo "$as_me: error: no usable dependency style found" >&2;}
+   { (exit 1); exit 1; }; }
+else CCDEPMODE=depmode=$am_cv_CC_dependencies_compiler_type
+
+fi
 
 
 # Checks for header files.
@@ -5077,6 +5192,76 @@ _ACEOF
 
 
 fi
+echo "$as_me:$LINENO: checking whether asprintf is declared" >&5
+echo $ECHO_N "checking whether asprintf is declared... $ECHO_C" >&6
+if test "${ac_cv_have_decl_asprintf+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+int
+main ()
+{
+#ifndef asprintf
+  char *p = (char *) asprintf;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_have_decl_asprintf=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_have_decl_asprintf=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_have_decl_asprintf" >&5
+echo "${ECHO_T}$ac_cv_have_decl_asprintf" >&6
+if test $ac_cv_have_decl_asprintf = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_DECL_ASPRINTF 1
+_ACEOF
+
+
+else
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_DECL_ASPRINTF 0
+_ACEOF
+
+
+fi
 echo "$as_me:$LINENO: checking whether basename is declared" >&5
 echo $ECHO_N "checking whether basename is declared... $ECHO_C" >&6
 if test "${ac_cv_have_decl_basename+set}" = set; then
@@ -6407,6 +6592,76 @@ _ACEOF
 
 
 fi
+echo "$as_me:$LINENO: checking whether vasprintf is declared" >&5
+echo $ECHO_N "checking whether vasprintf is declared... $ECHO_C" >&6
+if test "${ac_cv_have_decl_vasprintf+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+int
+main ()
+{
+#ifndef vasprintf
+  char *p = (char *) vasprintf;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_have_decl_vasprintf=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_have_decl_vasprintf=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_have_decl_vasprintf" >&5
+echo "${ECHO_T}$ac_cv_have_decl_vasprintf" >&6
+if test $ac_cv_have_decl_vasprintf = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_DECL_VASPRINTF 1
+_ACEOF
+
+
+else
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_DECL_VASPRINTF 0
+_ACEOF
+
+
+fi
 
 
 
@@ -7009,8 +7264,9 @@ INCINTL=
 XGETTEXT=
 GMSGFMT=
 POSUB=
-if test -f ../intl/config.intl; then
-  . ../intl/config.intl
+
+if test -f  ../intl/config.intl; then
+  .  ../intl/config.intl
 fi
 echo "$as_me:$LINENO: checking whether NLS is requested" >&5
 echo $ECHO_N "checking whether NLS is requested... $ECHO_C" >&6
@@ -7042,8 +7298,8 @@ echo $ECHO_N "checking for catalogs to be installed... $ECHO_C" >&6
     # by the backticks, then collapsed again by the double quotes,
     # leaving us with one backslash in the sed expression (right
     # before the dot that mustn't act as a wildcard).
-    cat=`echo $cat | sed -e "s!$srcdir/!!" -e "s!\\\\.po!.gmo!"`
-    lang=`echo $cat | sed -e 's!po/!!' -e "s!\\\\.gmo!!"`
+    cat=`echo $cat | sed -e "s!$srcdir/po/!!" -e "s!\\\\.po!.gmo!"`
+    lang=`echo $cat | sed -e "s!\\\\.gmo!!"`
     # The user is allowed to set LINGUAS to a list of languages to
     # install catalogs for.  If it's empty that means "all of them."
     if test "x$LINGUAS" = x; then
@@ -7060,6 +7316,16 @@ echo $ECHO_N "checking for catalogs to be installed... $ECHO_C" >&6
   LINGUAS="$XLINGUAS"
   echo "$as_me:$LINENO: result: $LINGUAS" >&5
 echo "${ECHO_T}$LINGUAS" >&6
+
+
+    DATADIRNAME=share
+
+  INSTOBJEXT=.mo
+
+  GENCAT=gencat
+
+  CATOBJEXT=.gmo
+
 fi
 
 echo "$as_me:$LINENO: checking for uchar" >&5
@@ -7962,14 +8228,13 @@ fi
 
 
 case $target in
-	# APPLE LOCAL begin 4126124
 	alpha*-*-* | \
-	arm*-*-eabi* | \
+	arm*-*-*eabi* | \
 	arm*-*-symbianelf* | \
 	x86_64-*-* | \
 	ia64-*-* | \
 	hppa*64*-*-* | parisc*64*-*-* | \
-	i[34567]86-*-darwin[0-9]* | \
+	i[34567]86-*-darwin* | \
 	i[34567]86-*-solaris2.1[0-9]* | \
 	mips*-*-* | \
 	mmix-*-* | \
@@ -7980,7 +8245,6 @@ case $target in
 	sparcv9-*-solaris2* | \
 	sparc-*-solaris2.[789] | sparc-*-solaris2.1[0-9]* | \
 	sh[123456789l]*-*-*)
-	# APPLE LOCAL end 4126124
 		need_64bit_hwint=yes ;;
 	*)
 		need_64bit_hwint=no ;;
@@ -8421,6 +8685,9 @@ $config_files
 Configuration headers:
 $config_headers
 
+Configuration commands:
+$config_commands
+
 Report bugs to <bug-autoconf@gnu.org>."
 _ACEOF
 
@@ -8520,7 +8787,14 @@ fi
 
 _ACEOF
 
+cat >>$CONFIG_STATUS <<_ACEOF
+#
+# INIT-COMMANDS section.
+#
 
+DEPDIR=$DEPDIR
+
+_ACEOF
 
 
 
@@ -8530,6 +8804,7 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
+  "depdir" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depdir" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h:config.in" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
@@ -8544,6 +8819,7 @@ done
 if $ac_need_defaults; then
   test "${CONFIG_FILES+set}" = set || CONFIG_FILES=$config_files
   test "${CONFIG_HEADERS+set}" = set || CONFIG_HEADERS=$config_headers
+  test "${CONFIG_COMMANDS+set}" = set || CONFIG_COMMANDS=$config_commands
 fi
 
 # Have a temporary directory for convenience.  Make it in the build tree
@@ -8646,6 +8922,9 @@ s,@AUTOHEADER@,$AUTOHEADER,;t t
 s,@WARN_CFLAGS@,$WARN_CFLAGS,;t t
 s,@WARN_PEDANTIC@,$WARN_PEDANTIC,;t t
 s,@WERROR@,$WERROR,;t t
+s,@am__leading_dot@,$am__leading_dot,;t t
+s,@DEPDIR@,$DEPDIR,;t t
+s,@CCDEPMODE@,$CCDEPMODE,;t t
 s,@CPP@,$CPP,;t t
 s,@EGREP@,$EGREP,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
@@ -8658,6 +8937,10 @@ s,@XGETTEXT@,$XGETTEXT,;t t
 s,@GMSGFMT@,$GMSGFMT,;t t
 s,@POSUB@,$POSUB,;t t
 s,@CATALOGS@,$CATALOGS,;t t
+s,@DATADIRNAME@,$DATADIRNAME,;t t
+s,@INSTOBJEXT@,$INSTOBJEXT,;t t
+s,@GENCAT@,$GENCAT,;t t
+s,@CATOBJEXT@,$CATOBJEXT,;t t
 s,@LIBICONV@,$LIBICONV,;t t
 s,@LTLIBICONV@,$LTLIBICONV,;t t
 s,@PACKAGE@,$PACKAGE,;t t
@@ -9126,6 +9409,124 @@ echo "$as_me: error: cannot create directory \"$ac_dir\"" >&2;}
   # Run the commands associated with the file.
   case $ac_file in
     config.h ) echo timestamp > stamp-h1 ;;
+  esac
+done
+_ACEOF
+cat >>$CONFIG_STATUS <<\_ACEOF
+
+#
+# CONFIG_COMMANDS section.
+#
+for ac_file in : $CONFIG_COMMANDS; do test "x$ac_file" = x: && continue
+  ac_dest=`echo "$ac_file" | sed 's,:.*,,'`
+  ac_source=`echo "$ac_file" | sed 's,[^:]*:,,'`
+  ac_dir=`(dirname "$ac_dest") 2>/dev/null ||
+$as_expr X"$ac_dest" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
+	 X"$ac_dest" : 'X\(//\)[^/]' \| \
+	 X"$ac_dest" : 'X\(//\)$' \| \
+	 X"$ac_dest" : 'X\(/\)' \| \
+	 .     : '\(.\)' 2>/dev/null ||
+echo X"$ac_dest" |
+    sed '/^X\(.*[^/]\)\/\/*[^/][^/]*\/*$/{ s//\1/; q; }
+  	  /^X\(\/\/\)[^/].*/{ s//\1/; q; }
+  	  /^X\(\/\/\)$/{ s//\1/; q; }
+  	  /^X\(\/\).*/{ s//\1/; q; }
+  	  s/.*/./; q'`
+  { if $as_mkdir_p; then
+    mkdir -p "$ac_dir"
+  else
+    as_dir="$ac_dir"
+    as_dirs=
+    while test ! -d "$as_dir"; do
+      as_dirs="$as_dir $as_dirs"
+      as_dir=`(dirname "$as_dir") 2>/dev/null ||
+$as_expr X"$as_dir" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
+	 X"$as_dir" : 'X\(//\)[^/]' \| \
+	 X"$as_dir" : 'X\(//\)$' \| \
+	 X"$as_dir" : 'X\(/\)' \| \
+	 .     : '\(.\)' 2>/dev/null ||
+echo X"$as_dir" |
+    sed '/^X\(.*[^/]\)\/\/*[^/][^/]*\/*$/{ s//\1/; q; }
+  	  /^X\(\/\/\)[^/].*/{ s//\1/; q; }
+  	  /^X\(\/\/\)$/{ s//\1/; q; }
+  	  /^X\(\/\).*/{ s//\1/; q; }
+  	  s/.*/./; q'`
+    done
+    test ! -n "$as_dirs" || mkdir $as_dirs
+  fi || { { echo "$as_me:$LINENO: error: cannot create directory \"$ac_dir\"" >&5
+echo "$as_me: error: cannot create directory \"$ac_dir\"" >&2;}
+   { (exit 1); exit 1; }; }; }
+
+  ac_builddir=.
+
+if test "$ac_dir" != .; then
+  ac_dir_suffix=/`echo "$ac_dir" | sed 's,^\.[\\/],,'`
+  # A "../" for each directory in $ac_dir_suffix.
+  ac_top_builddir=`echo "$ac_dir_suffix" | sed 's,/[^\\/]*,../,g'`
+else
+  ac_dir_suffix= ac_top_builddir=
+fi
+
+case $srcdir in
+  .)  # No --srcdir option.  We are building in place.
+    ac_srcdir=.
+    if test -z "$ac_top_builddir"; then
+       ac_top_srcdir=.
+    else
+       ac_top_srcdir=`echo $ac_top_builddir | sed 's,/$,,'`
+    fi ;;
+  [\\/]* | ?:[\\/]* )  # Absolute path.
+    ac_srcdir=$srcdir$ac_dir_suffix;
+    ac_top_srcdir=$srcdir ;;
+  *) # Relative path.
+    ac_srcdir=$ac_top_builddir$srcdir$ac_dir_suffix
+    ac_top_srcdir=$ac_top_builddir$srcdir ;;
+esac
+
+# Do not use `cd foo && pwd` to compute absolute paths, because
+# the directories may not exist.
+case `pwd` in
+.) ac_abs_builddir="$ac_dir";;
+*)
+  case "$ac_dir" in
+  .) ac_abs_builddir=`pwd`;;
+  [\\/]* | ?:[\\/]* ) ac_abs_builddir="$ac_dir";;
+  *) ac_abs_builddir=`pwd`/"$ac_dir";;
+  esac;;
+esac
+case $ac_abs_builddir in
+.) ac_abs_top_builddir=${ac_top_builddir}.;;
+*)
+  case ${ac_top_builddir}. in
+  .) ac_abs_top_builddir=$ac_abs_builddir;;
+  [\\/]* | ?:[\\/]* ) ac_abs_top_builddir=${ac_top_builddir}.;;
+  *) ac_abs_top_builddir=$ac_abs_builddir/${ac_top_builddir}.;;
+  esac;;
+esac
+case $ac_abs_builddir in
+.) ac_abs_srcdir=$ac_srcdir;;
+*)
+  case $ac_srcdir in
+  .) ac_abs_srcdir=$ac_abs_builddir;;
+  [\\/]* | ?:[\\/]* ) ac_abs_srcdir=$ac_srcdir;;
+  *) ac_abs_srcdir=$ac_abs_builddir/$ac_srcdir;;
+  esac;;
+esac
+case $ac_abs_builddir in
+.) ac_abs_top_srcdir=$ac_top_srcdir;;
+*)
+  case $ac_top_srcdir in
+  .) ac_abs_top_srcdir=$ac_abs_builddir;;
+  [\\/]* | ?:[\\/]* ) ac_abs_top_srcdir=$ac_top_srcdir;;
+  *) ac_abs_top_srcdir=$ac_abs_builddir/$ac_top_srcdir;;
+  esac;;
+esac
+
+
+  { echo "$as_me:$LINENO: executing $ac_dest commands" >&5
+echo "$as_me: executing $ac_dest commands" >&6;}
+  case $ac_dest in
+    depdir ) mkdir $DEPDIR ;;
   esac
 done
 _ACEOF
diff --git a/gdb/src/configure b/gdb/src/configure
--- a/gdb/src/configure
+++ b/gdb/src/configure
@@ -1309,6 +1309,12 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --enable-libada        Builds libada directory
   --enable-libssp        Builds libssp directory
+  --disable-carbon-framework
+                          disable Carbon framework use even when available
+  --disable-debug-symbols-framework
+                          disable DebugSymbols framework use even when
+                          available
+  --disable-arch-for-exec disable use of arch for exec
   --enable-bootstrap=lean     Enable bootstrapping no
   --enable-serial-{host,target,build}-configure
                           Force sequential configuration of
@@ -2429,7 +2435,52 @@ case "${target}" in
     enable_shared=no
     enable_64_bit_bfd=yes
     enable_softfloat=no
-    host_configargs=" $host_configargs --disable-shared --enable-64-bit-bfd --disable-softfloat "
+    host_configargs=" $host_configargs --disable-shared --enable-64-bit-bfd --disable-softfloat --disable-werror "
+
+    # Check whether --enable-carbon-framework was given.
+if test "${enable_carbon_framework+set}" = set; then
+  enableval=$enable_carbon_framework; case $enableval in
+      yes)
+        host_configargs=" $host_configargs --enable-carbon-framework" ;;
+      no)
+        host_configargs=" $host_configargs --disable-carbon-framework" ;;
+      *)
+        { { echo "$as_me:$LINENO: error: bad value '$enableval' for --enable-carbon-framework" >&5
+echo "$as_me: error: bad value '$enableval' for --enable-carbon-framework" >&2;}
+   { (exit 1); exit 1; }; } ;;
+    esac
+fi
+
+
+    # Check whether --enable-debug-symbols-framework was given.
+if test "${enable_debug_symbols_framework+set}" = set; then
+  enableval=$enable_debug_symbols_framework; case $enableval in
+      yes)
+        host_configargs=" $host_configargs --enable-debug-symbols-framework" ;;
+      no)
+        host_configargs=" $host_configargs --disable-debug-symbols-framework" ;;
+      *)
+        { { echo "$as_me:$LINENO: error: bad value '$enableval' for --enable-debug-symbols-framework" >&5
+echo "$as_me: error: bad value '$enableval' for --enable-debug-symbols-framework" >&2;}
+   { (exit 1); exit 1; }; } ;;
+    esac
+fi
+
+
+    # Check whether --enable-arch-for-exec was given.
+if test "${enable_arch_for_exec+set}" = set; then
+  enableval=$enable_arch_for_exec; case $enableval in
+        yes)
+          host_configargs=" $host_configargs --enable-arch-for-exec" ;;
+        no)
+          host_configargs=" $host_configargs --disable-arch-for-exec" ;;
+        *)
+          { { echo "$as_me:$LINENO: error: bad value '$enableval' for --enable-arch-for-exec" >&5
+echo "$as_me: error: bad value '$enableval' for --enable-arch-for-exec" >&2;}
+   { (exit 1); exit 1; }; } ;;
+      esac
+fi
+
     ;;
   *-*-freebsd[12] | *-*-freebsd[12].* | *-*-freebsd*aout*)
     noconfigdirs="$noconfigdirs target-newlib target-libgloss ${libgcj}"
diff --git a/gnuzip/gzip/zdiff.in b/gnuzip/gzip/zdiff.in
--- a/gnuzip/gzip/zdiff.in
+++ b/gnuzip/gzip/zdiff.in
@@ -1,29 +1,40 @@
 #!/bin/sh
 # sh is buggy on RS/6000 AIX 3.2. Replace above line with #!/bin/ksh
 
-# Zcmp and zdiff are used to invoke the cmp or the  diff  pro-
-# gram  on compressed files.  All options specified are passed
-# directly to cmp or diff.  If only 1 file is specified,  then
-# the  files  compared  are file1 and an uncompressed file1.gz.
-# If two files are specified, then they are  uncompressed  (if
-# necessary) and fed to cmp or diff.  The exit status from cmp
-# or diff is preserved.
+# Copyright (C) 1998, 2002, 2006, 2007 Free Software Foundation
+# Copyright (C) 1993 Jean-loup Gailly
 
-PATH="BINDIR:$PATH"; export PATH
-case "$0" in
-  *cmp) prog=cmp ; cmp='${CMP-cmp}'  ;;
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version.
+
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+
+# You should have received a copy of the GNU General Public License along
+# with this program; if not, write to the Free Software Foundation, Inc.,
+# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
+
+PATH=BINDIR:$PATH
+
+case $1 in
+  --__cmp) shift
+	prog=cmp;  cmp='${CMP-cmp}'  ;;
   *)    prog=diff; cmp='${DIFF-diff}';;
 esac
 
 version="z$prog (gzip) @VERSION@
-Copyright (C) 2006 Free Software Foundation, Inc.
+Copyright (C) 2007 Free Software Foundation, Inc.
 This is free software.  You may redistribute copies of it under the terms of
 the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
 There is NO WARRANTY, to the extent permitted by law.
 
 Written by Jean-loup Gailly."
 
-usage="Usage: z$prog [OPTION]... FILE1 [FILE2]
+usage="Usage: $0 [OPTION]... FILE1 [FILE2]
 Compare FILE1 to FILE2, using their uncompressed contents if they are
 compressed.  If FILE2 is omitted, compare FILE1 to the uncompressed
 contents of FILE1.gz.  Do comparisons like '$prog' does.
@@ -32,30 +43,44 @@ OPTIONs are the same as for '$prog'.
 
 Report bugs to <bug-gzip@gnu.org>."
 
-FILES=
+# sed script to escape all ' for the shell, and then (to handle trailing
+# newlines correctly) turn trailing X on last line into '.
+escape='
+  s/'\''/'\''\\'\'''\''/g
+  $s/X$/'\''/
+'
+
 while :; do
   case $1 in
-  --h*) echo "$usage" || exit 2; exit;;
+  --h*) printf '%s\n' "$usage" || exit 2; exit;;
   --v*) echo "$version" || exit 2; exit;;
   --) shift; break;;
-  -*\'*) echo >&2 "$prog: $1: option contains apostrophe"; exit 2;;
-  -?*) cmp="$cmp '$1'"; shift;;
+  -*\'*) cmp="$cmp '"`printf '%sX\n' "$1" | sed "$escape"`;;
+  -?*) cmp="$cmp '$1'";;
   *) break;;
   esac
+  shift
 done
 cmp="$cmp --"
 
-for file; do
+for file
+do
   test "X$file" = X- || <"$file" || exit 2
 done
+
+gzip_status=0
+exec 3>&1
 
 if test $# -eq 1; then
   case $1 in
   *[-.]gz* | *[-.][zZ] | *.t[ga]z)
     FILE=`expr "X$1" : 'X\(.*\)[-.][zZtga]*$'`
-    gzip -cd -- "$1" | eval "$cmp" - '"$FILE"';;
+    gzip_status=$(
+      exec 4>&1
+      (gzip -cd -- "$1" 4>&-; echo $? >&4) 3>&- | eval "$cmp" - '"$FILE"' >&3
+    );;
   *)
-    echo >&2 "$prog: $1: unknown compressed file extension"
+    echo >&2 "$0: $1: unknown compressed file extension"
     exit 2;;
   esac
 elif test $# -eq 2; then
@@ -64,11 +89,27 @@ elif test $# -eq 2; then
                 case "$2" in
 		*[-.]gz* | *[-.][zZ] | *.t[ga]z | -)
 		    if test "$1$2" = --; then
-			gzip -cdfq - | eval "$cmp" - -
-		    elif test -r /dev/fd/3 3</dev/null; then
-			gzip -cdfq -- "$1" |
-			  (gzip -cdfq -- "$2" |
-			   eval "$cmp" /dev/fd/3 -) 3<&0
+			gzip_status=$(
+			  exec 4>&1
+			  (gzip -cdfq - 4>&-; echo $? >&4) 3>&- |
+			    eval "$cmp" - - >&3
+			)
+		    elif
+			# Reject Solaris 8's buggy /bin/bash 2.03.
+			echo X |
+			 (echo X | eval "$cmp" /dev/fd/5 - >/dev/null 2>&1) \
+				5<&0
+		    then
+			gzip_status=$(
+			  exec 4>&1
+			  (gzip -cdfq -- "$1" 4>&-; echo $? >&4) 3>&- |
+			    ( (gzip -cdfq -- "$2" 4>&-; echo $? >&4) 3>&- 5<&- </dev/null |
+			       eval "$cmp" /dev/fd/5 -) 5<&0
+			)
+			case $gzip_status in
+			  *[1-9]*) gzip_status=1;;
+			  *) gzip_status=0;;
+			esac
 		    else
 			F=`expr "/$2" : '.*/\(.*\)[-.][zZtga]*$'` || F=$prog
 			tmp=
@@ -77,27 +118,44 @@ elif test $# -eq 2; then
 			  (exit 2); exit 2
 			' HUP INT PIPE TERM 0
 			if type mktemp >/dev/null 2>&1; then
-			  tmp=`mktemp -t -- "$F.XXXXXX"` || exit
+			  tmp=`mktemp -t -- "$F.XXXXXX"` || exit 2
 			else
 			  set -C
 			  tmp=${TMPDIR-/tmp}/$F.$$
 			fi
-			gzip -cdfq -- "$2" > "$tmp" || exit
-			gzip -cdfq -- "$1" | eval "$cmp" - '"$tmp"'
-                        STAT="$?"
-			rm -f "$tmp" || STAT=2
+			gzip -cdfq -- "$2" > "$tmp" || exit 2
+			gzip_status=$(
+			  exec 4>&1
+			  (gzip -cdfq -- "$1" 4>&-; echo $? >&4) 3>&- |
+			    eval "$cmp" - '"$tmp"' >&3
+			)
+                        cmp_status=$?
+			rm -f "$tmp" || gzip_status=$?
 			trap - HUP INT PIPE TERM 0
-			exit $STAT
+			(exit $cmp_status)
 		    fi;;
-		*)	gzip -cdfq -- "$1" | eval "$cmp" - '"$2"';;
+		*)
+		    gzip_status=$(
+		      exec 4>&1
+		      (gzip -cdfq -- "$1" 4>&-; echo $? >&4) 3>&- |
+		        eval "$cmp" - '"$2"' >&3
+		    );;
                 esac;;
         *)      case "$2" in
 		*[-.]gz* | *[-.][zZ] | *.t[ga]z | -)
-			gzip -cdfq -- "$2" | eval "$cmp" '"$1"' -;;
+			gzip_status=$(
+			  exec 4>&1
+			  (gzip -cdfq -- "$2" 4>&-; echo $? >&4) 3>&- |
+			    eval "$cmp" '"$1"' - >&3
+			);;
 		*)	eval "$cmp" '"$1"' '"$2"';;
                 esac;;
 	esac
 else
-	echo >&2 "$usage"
+	echo >&2 "$0: invalid number of operands; try \`$0 --help' for help"
 	exit 2
 fi
+
+cmp_status=$?
+test "$gzip_status" -eq 0 || exit 2
+exit $cmp_status
diff --git a/headerdoc/Makefile b/headerdoc/Makefile
--- a/headerdoc/Makefile
+++ b/headerdoc/Makefile
@@ -1,6 +1,5 @@
 ##
 # Makefile for headerdoc
-# Wilfredo Sanchez | wsanchez@apple.com
 ##
 
 
@@ -22,11 +21,13 @@ endif
 endif
 startperl   := $(shell perl -e 'require Config; print "$$Config::Config{'startperl'}\n";')
 
-all:
-	cd xmlman ; make all ARCH=`uname` VERS=`sw_vers -productVersion`
+all: all_internal test
+
+all_internal:
+	cd xmlman ; make all ARCH=`uname` VERS=`sw_vers -productVersion | sed 's/\([0-9][0-9]*\)\.\([0-9][0-9]*\)\..*/\1.\2/'` ; cd ..
 
 clean:
-	cd xmlman ; make clean
+	cd xmlman ; make clean ; cd ..
 
 installsrc:
 	mkdir -p "$(SRCROOT)"
@@ -39,12 +40,39 @@ build:
 clean:
 
 test:
-	cd testsuite ; make ; make runtests ; cd ..
+	./headerDoc2HTML.pl -T run; \
+	if [ "$$?" -ne 0 ] ; then \
+		echo "Test suite failed."; \
+		exit -1; \
+	fi
 
-realinstall: all
+	rm -rf /tmp/hdtest_perm
+	rm -rf /tmp/hdtest_out
+	mkdir /tmp/hdtest_perm
+	cp ExampleHeaders/template.h /tmp/hdtest_perm
+	cp ExampleHeaders/textblock.h /tmp/hdtest_perm
+	cp ExampleHeaders/throwtest.h /tmp/hdtest_perm
+	cp ExampleHeaders/typedefTest.h /tmp/hdtest_perm
+	chmod u=w,og= /tmp/hdtest_perm/throwtest.h
+
+	if [ "x$$USER" != "xroot" ] ; then \
+		echo "Testing to make sure HeaderDoc returns an error if a file could not be read." ;\
+		if ./headerDoc2HTML.pl -c headerDoc2HTML.config-installed -o /tmp/hdtest_out /tmp/hdtest_perm > /dev/null 2>/dev/null ; then \
+			echo "Permission test failed."; \
+			rm -rf /tmp/hdtest_perm; \
+			rm -rf /tmp/hdtest_out; \
+			exit -1; \
+		fi \
+	fi
+	rm -rf /tmp/hdtest_perm
+	rm -rf /tmp/hdtest_out
+	exit 0
+	# cd testsuite ; make ; make runtests ; cd ..
+
+realinstall: all_internal
 	DSTROOT="" make installsub
 
-install: all
+install: all_internal
 	@echo ; \
 	export DSTROOT="/tmp/headerdoc/Release" ; \
  \
diff --git a/libxml2/libxml2/Makefile.am b/libxml2/libxml2/Makefile.am
--- a/libxml2/libxml2/Makefile.am
+++ b/libxml2/libxml2/Makefile.am
@@ -8,7 +8,8 @@ INCLUDES = -I$(top_builddir)/include -I@srcdir@/include @THREAD_CFLAGS@ @Z_CFLAG
 
 noinst_PROGRAMS=testSchemas testRelax testSAX testHTML testXPath testURI \
                 testThreads testC14N testAutomata testRegexp \
-		testReader testapi
+                testReader testapi testModule runtest runsuite testchar \
+		testdict runxmlconf testrecurse
 
 bin_PROGRAMS = xmllint xmlcatalog
 
@@ -17,7 +18,7 @@ bin_SCRIPTS=xml2-config
 lib_LTLIBRARIES = libxml2.la
 libxml2_la_LIBADD = @THREAD_LIBS@ @Z_LIBS@ $(ICONV_LIBS) $(ICU_LIBS) @M_LIBS@ @WIN32_EXTRA_LIBADD@
 
-libxml2_la_LDFLAGS = @CYGWIN_EXTRA_LDFLAGS@ @WIN32_EXTRA_LDFLAGS@ -version-info @LIBXML_VERSION_INFO@
+libxml2_la_LDFLAGS = @CYGWIN_EXTRA_LDFLAGS@ @WIN32_EXTRA_LDFLAGS@ -version-info @LIBXML_VERSION_INFO@ @MODULE_PLATFORM_LIBS@
 
 if WITH_TRIO_SOURCES
 libxml2_la_SOURCES = SAX.c entities.c encoding.c error.c parserInternals.c  \
@@ -27,7 +28,8 @@ libxml2_la_SOURCES = SAX.c entities.c encoding.c error.c parserInternals.c  \
 		catalog.c globals.c threads.c c14n.c xmlstring.c \
 		xmlregexp.c xmlschemas.c xmlschemastypes.c xmlunicode.c \
 		triostr.c trio.c xmlreader.c relaxng.c dict.c SAX2.c \
-		xmlwriter.c legacy.c chvalid.c pattern.c xmlsave.c
+		xmlwriter.c legacy.c chvalid.c pattern.c xmlsave.c \
+		xmlmodule.c schematron.c
 else
 libxml2_la_SOURCES = SAX.c entities.c encoding.c error.c parserInternals.c  \
 		parser.c tree.c hash.c list.c xmlIO.c xmlmemory.c uri.c  \
@@ -36,7 +38,8 @@ libxml2_la_SOURCES = SAX.c entities.c encoding.c error.c parserInternals.c  \
 		catalog.c globals.c threads.c c14n.c xmlstring.c \
 		xmlregexp.c xmlschemas.c xmlschemastypes.c xmlunicode.c \
 		xmlreader.c relaxng.c dict.c SAX2.c \
-		xmlwriter.c legacy.c chvalid.c pattern.c xmlsave.c
+		xmlwriter.c legacy.c chvalid.c pattern.c xmlsave.c \
+		xmlmodule.c schematron.c
 endif
 
 DEPS = $(top_builddir)/libxml2.la
@@ -47,6 +50,31 @@ man_MANS = xml2-config.1 libxml.3
 
 m4datadir = $(datadir)/aclocal
 m4data_DATA = libxml.m4
+
+runtest_SOURCES=runtest.c
+runtest_LDFLAGS = 
+runtest_DEPENDENCIES = $(DEPS)
+runtest_LDADD= @BASE_THREAD_LIBS@ @RDL_LIBS@ $(LDADDS)
+
+testrecurse_SOURCES=testrecurse.c
+testrecurse_LDFLAGS = 
+testrecurse_DEPENDENCIES = $(DEPS)
+testrecurse_LDADD= @BASE_THREAD_LIBS@ @RDL_LIBS@ $(LDADDS)
+
+testchar_SOURCES=testchar.c
+testchar_LDFLAGS = 
+testchar_DEPENDENCIES = $(DEPS)
+testchar_LDADD= @RDL_LIBS@ $(LDADDS)
+
+testdict_SOURCES=testdict.c
+testdict_LDFLAGS = 
+testdict_DEPENDENCIES = $(DEPS)
+testdict_LDADD= @RDL_LIBS@ $(LDADDS)
+
+runsuite_SOURCES=runsuite.c
+runsuite_LDFLAGS = 
+runsuite_DEPENDENCIES = $(DEPS)
+runsuite_LDADD= @RDL_LIBS@ $(LDADDS)
 
 xmllint_SOURCES=xmllint.c
 xmllint_LDFLAGS = 
@@ -81,7 +109,7 @@ testC14N_LDADD= $(LDADDS)
 testThreads_SOURCES=testThreads@THREADS_W32@.c
 testThreads_LDFLAGS = 
 testThreads_DEPENDENCIES = $(DEPS)
-testThreads_LDADD= $(LDADDS)
+testThreads_LDADD= @BASE_THREAD_LIBS@  $(LDADDS)
 
 testURI_SOURCES=testURI.c
 testURI_LDFLAGS = 
@@ -113,24 +141,56 @@ testReader_LDFLAGS =
 testReader_DEPENDENCIES = $(DEPS)
 testReader_LDADD= $(LDADDS)
 
-testapi.c: gentest.py doc/libxml2-api.xml
-	-@(if [ "$(PYTHON)" != "" ] ; then $(PYTHON) gentest.py ; fi )
+testModule_SOURCES=testModule.c
+testModule_LDFLAGS = 
+testModule_DEPENDENCIES = $(DEPS)
+testModule_LDADD= $(LDADDS)
+
+noinst_LTLIBRARIES = testdso.la
+testdso_la_SOURCES = testdso.c
+testdso_la_LDFLAGS = -module -rpath $(libdir)
+
+# that one forces the rebuild when "make rebuild" is run on doc/
+rebuild_testapi:
+	-@(if [ "$(PYTHON)" != "" ] ; then \
+	    $(PYTHON) $(srcdir)/gentest.py $(srcdir) ; fi )
+
+# that one is just to make sure it is rebuilt if missing
+# but adding the dependances generate mess
+testapi.c: $(srcdir)/gentest.py
+	-@(if [ "$(PYTHON)" != "" ] ; then \
+	    $(PYTHON) $(srcdir)/gentest.py $(srcdir) ; fi )
 
 testapi_SOURCES=testapi.c
 testapi_LDFLAGS = 
 testapi_DEPENDENCIES = $(DEPS)
 testapi_LDADD= $(LDADDS)
 
+runxmlconf_SOURCES=runxmlconf.c
+runxmlconf_LDFLAGS = 
+runxmlconf_DEPENDENCIES = $(DEPS)
+runxmlconf_LDADD= $(LDADDS)
+
 #testOOM_SOURCES=testOOM.c testOOMlib.h testOOMlib.c
 #testOOM_LDFLAGS = 
 #testOOM_DEPENDENCIES = $(DEPS)
 #testOOM_LDADD= $(LDADDS)
 
-check-local: all tests
+runtests:
+	$(CHECKER) ./runtest$(EXEEXT) && $(CHECKER) ./testrecurse$(EXEEXT) &&$(CHECKER) ./testapi$(EXEEXT) && $(CHECKER) ./testchar$(EXEEXT)&& $(CHECKER) ./testdict$(EXEEXT) && $(CHECKER) ./runxmlconf$(EXEEXT)
+	@(if [ "@PYTHON_SUBDIR@" != "" ] ; then cd python ; \
+	    $(MAKE) MAKEFLAGS+=--silent tests ; fi)
+
+check: all runtests
+
+check-valgrind: all
+	@echo '## Running the regression tests under Valgrind'
+	@echo '## Go get a cup of coffee it is gonna take a while ...'
+	$(MAKE) CHECKER='valgrind -q' check
 
 testall : tests SVGtests SAXtests
 
-tests: XMLtests XMLenttests NStests IDtests Errtests APItests @READER_TEST@ @TEST_SAX@ @TEST_PUSH@ @TEST_HTML@ @TEST_PHTML@  @TEST_VALID@ URItests @TEST_XPATH@ @TEST_XPTR@ @TEST_XINCLUDE@ @TEST_C14N@ @TEST_DEBUG@ @TEST_CATALOG@ @TEST_REGEXPS@ @TEST_SCHEMAS@ @TEST_THREADS@ Timingtests @TEST_VTIME@ @PYTHON_TESTS@
+tests: XMLtests XMLenttests NStests IDtests Errtests APItests @READER_TEST@ @TEST_SAX@ @TEST_PUSH@ @TEST_HTML@ @TEST_PHTML@  @TEST_VALID@ URItests @TEST_PATTERN@ @TEST_XPATH@ @TEST_XPTR@ @TEST_XINCLUDE@ @TEST_C14N@ @TEST_DEBUG@ @TEST_CATALOG@ @TEST_REGEXPS@ @TEST_SCHEMAS@ @TEST_SCHEMATRON@ @TEST_THREADS@ Timingtests @TEST_VTIME@ @PYTHON_TESTS@ @TEST_MODULES@
 	@(if [ "@PYTHON_SUBDIR@" != "" ] ; then cd python ; \
 	    $(MAKE) MAKEFLAGS+=--silent tests ; fi)
 	@(cd doc/examples ; $(MAKE) MAKEFLAGS+=--silent tests)
@@ -343,15 +403,14 @@ Errtests : xmllint$(EXEEXT)
 	      echo New test file $$name ; \
 	      $(CHECKER) $(top_builddir)/xmllint --stream $$i \
 	         2> $(srcdir)/result/errors/$$name.str \
-		 > $(srcdir)/result/errors/$$name ; \
+		 > /dev/null ; \
 	      grep "MORY ALLO" .memdump  | grep -v "MEMORY ALLOCATED : 0"; \
 	  else \
-	      log=`$(CHECKER) $(top_builddir)/xmllint --stream $$i 2> error.$$name > result.$$name ; \
+	      log=`$(CHECKER) $(top_builddir)/xmllint --stream $$i 2> error.$$name > /dev/null ; \
 	      grep "MORY ALLO" .memdump  | grep -v "MEMORY ALLOCATED : 0"; \
-	      diff $(srcdir)/result/errors/$$name result.$$name ; \
 	      diff $(srcdir)/result/errors/$$name.str error.$$name` ; \
 	      if [ -n "$$log" ] ; then echo $$name result ; echo $$log ; fi ; \
-	      rm result.$$name error.$$name ; \
+	      rm error.$$name ; \
 	  fi ; fi ; done)
 
 Docbtests : xmllint$(EXEEXT)
@@ -704,7 +763,7 @@ Readertests : xmllint$(EXEEXT)
 
 SAXtests : testSAX$(EXEEXT)
 	@(echo > .memdump)
-	@echo "## SAX callbacks regression tests"
+	@echo "## SAX1 callbacks regression tests"
 	-@(for i in $(srcdir)/test/* ; do \
 	  name=`basename $$i`; \
 	  if [ ! -d $$i ] ; then \
@@ -716,6 +775,21 @@ SAXtests : testSAX$(EXEEXT)
 	      log=`$(CHECKER) $(top_builddir)/testSAX $$i > result.$$name 2> /dev/null ; \
 	      grep "MORY ALLO" .memdump  | grep -v "MEMORY ALLOCATED : 0";\
 	      diff $(srcdir)/result/$$name.sax result.$$name` ; \
+	      if [ -n "$$log" ] ; then echo $$name result ; echo $$log ; fi ; \
+	      rm result.$$name ; \
+	  fi ; fi ; done)
+	@echo "## SAX2 callbacks regression tests"
+	-@(for i in $(srcdir)/test/* ; do \
+	  name=`basename $$i`; \
+	  if [ ! -d $$i ] ; then \
+	  if [ ! -f $(srcdir)/result/$$name.sax2 ] ; then \
+	      echo New test file $$name ; \
+	      $(CHECKER) $(top_builddir)/testSAX --sax2 $$i > $(srcdir)/result/$$name.sax2 2> /dev/null ; \
+	      grep "MORY ALLO" .memdump  | grep -v "MEMORY ALLOCATED : 0";\
+	  else \
+	      log=`$(CHECKER) $(top_builddir)/testSAX --sax2 $$i > result.$$name 2> /dev/null ; \
+	      grep "MORY ALLO" .memdump  | grep -v "MEMORY ALLOCATED : 0";\
+	      diff $(srcdir)/result/$$name.sax2 result.$$name` ; \
 	      if [ -n "$$log" ] ; then echo $$name result ; echo $$log ; fi ; \
 	      rm result.$$name ; \
 	  fi ; fi ; done)
@@ -779,6 +853,21 @@ Regexptests: testRegexp$(EXEEXT)
 	      if [ -n "$$log" ] ; then echo $$name result ; echo $$log ; fi ; \
 	      rm result.$$name ; \
 	  fi ; fi ; done)
+	@echo "## Formal expresssions regression tests"
+	-@(for i in $(srcdir)/test/expr/* ; do \
+	  name=`basename $$i`; \
+	  if [ ! -d $$i ] ; then \
+	  if [ ! -f $(srcdir)/result/expr/$$name ] ; then \
+	      echo New test file $$name ; \
+	      $(CHECKER) $(top_builddir)/testRegexp --expr -i $$i > $(srcdir)/result/expr/$$name; \
+	      grep "MORY ALLO" .memdump  | grep -v "MEMORY ALLOCATED : 0";\
+	  else \
+	      log=`$(CHECKER) $(top_builddir)/testRegexp --expr -i $$i 2>&1 > result.$$name ; \
+	      grep "MORY ALLO" .memdump  | grep -v "MEMORY ALLOCATED : 0";\
+	      diff $(srcdir)/result/expr/$$name result.$$name` ; \
+	      if [ -n "$$log" ] ; then echo $$name result ; echo $$log ; fi ; \
+	      rm result.$$name ; \
+	  fi ; fi ; done)
 
 Automatatests: testAutomata$(EXEEXT)
 	@(echo > .memdump)
@@ -798,23 +887,23 @@ Automatatests: testAutomata$(EXEEXT)
 	      rm result.$$name ; \
 	  fi ; fi ; done)
 
-$(srcdir)/dba100000.xml: dbgenattr.pl
+dba100000.xml: dbgenattr.pl
 	@echo "## generating dba100000.xml"
-	@($(PERL) $(top_srcdir)/dbgenattr.pl 100000 > $(srcdir)/dba100000.xml)
+	@($(PERL) $(top_srcdir)/dbgenattr.pl 100000 > dba100000.xml)
 
-Timingtests: xmllint$(EXEEXT) $(srcdir)/dba100000.xml
+Timingtests: xmllint$(EXEEXT) dba100000.xml
 	@echo "## Timing tests to try to detect performance"
 	@echo "## as well a memory usage breakage when streaming"
 	@echo "## 1/ using the file interface"
 	@echo "## 2/ using the memory interface"
 	@echo "## 3/ repeated DOM parsing"
 	@echo "## 4/ repeated DOM validation"
-	-@($(top_builddir)/xmllint --stream --timing $(srcdir)/dba100000.xml; \
+	-@($(top_builddir)/xmllint --stream --timing dba100000.xml; \
 	   MEM=`cat .memdump | grep "MEMORY ALLOCATED" | awk '{ print $$7}'`;\
 	   if [ "$$MEM" != "" ] ; then echo Using $$MEM bytes ; fi ; \
 	   grep "MORY ALLO" .memdump  | grep -v "MEMORY ALLOCATED : 0";\
 	   exit 0)
-	-@($(top_builddir)/xmllint --stream --timing --memory $(srcdir)/dba100000.xml; \
+	-@($(top_builddir)/xmllint --stream --timing --memory dba100000.xml; \
 	   MEM=`cat .memdump | grep "MEMORY ALLOCATED" | awk '{ print $$7}'`;\
 	   if [ "$$MEM" != "" ] ; then echo Using $$MEM bytes ; fi ; \
 	   grep "MORY ALLO" .memdump  | grep -v "MEMORY ALLOCATED : 0";\
@@ -955,7 +1044,7 @@ Relaxtests: xmllint$(EXEEXT)
 		    > res.$$name 2> err.$$name;\
 	          grep "MORY ALLO" .memdump  | grep -v "MEMORY ALLOCATED : 0";\
 	          diff $(srcdir)/result/relaxng/"$$name"_"$$xno" res.$$name;\
-		  if [ "$$name" != "tutor10_1" -a "$$name" != "tutor10_2" -a "$$name" != "tutor3_2" ] ; then \
+		  if [ "$$name" != "tutor10_1" -a "$$name" != "tutor10_2" -a "$$name" != "tutor3_2" -a "$$name" != "307377" ] ; then \
 		      diff $(srcdir)/result/relaxng/"$$name"_"$$xno".err \
 			   err.$$name | grep -v "error detected at";\
 		  fi ; grep Unimplemented err.$$name`; \
@@ -964,10 +1053,41 @@ Relaxtests: xmllint$(EXEEXT)
 	       fi ; fi ; \
 	  done; done)
 
+Schematrontests: xmllint$(EXEEXT)
+	@(echo > .memdump)
+	@echo "## Schematron regression tests"
+	-@(for i in $(srcdir)/test/schematron/*.sct ; do \
+	  name=`basename $$i | sed 's+\.sct++'`; \
+	  for j in $(srcdir)/test/schematron/"$$name"_*.xml ; do \
+	      if [ -f $$j ] ; then \
+	      xno=`basename $$j | sed 's+.*_\(.*\).xml+\1+'`; \
+	      if [ ! -f $(srcdir)/result/schematron/"$$name"_"$$xno" ]; \
+	      then \
+		  echo New test file "$$name"_"$$xno" ; \
+		  $(CHECKER) $(top_builddir)/xmllint$(EXEEXT) --schematron $$i $$j \
+		    > $(srcdir)/result/schematron/"$$name"_"$$xno" \
+		    2> $(srcdir)/result/schematron/"$$name"_"$$xno".err; \
+	          grep "MORY ALLO" .memdump  | grep -v "MEMORY ALLOCATED : 0";\
+	      else \
+	          log=`$(CHECKER) $(top_builddir)/xmllint$(EXEEXT) --schematron $$i $$j \
+		    > res.$$name 2> err.$$name;\
+	          grep "MORY ALLO" .memdump  | grep -v "MEMORY ALLOCATED : 0";\
+	          diff $(srcdir)/result/schematron/"$$name"_"$$xno" \
+		       res.$$name;\
+	          diff $(srcdir)/result/schematron/"$$name"_"$$xno".err \
+		       err.$$name | grep -v "error detected at";\
+		  grep Unimplemented err.$$name`; \
+		  if [ -n "$$log" ] ; then echo "$$name"_"$$xno" result ; echo $$log ; fi ; \
+	          rm res.$$name err.$$name ; \
+	       fi ; fi ; \
+	  done; done)
+
 RelaxNGPythonTests:
 	@(if [ -x $(PYTHON) ] ; then \
 	    PYTHONPATH=$(top_builddir)/python:$(top_builddir)/python/.libs:$$PYTHONPATH ; \
 	    export PYTHONPATH; \
+	    LD_LIBRARY_PATH="$(top_builddir)/.libs:$$LD_LIBRARY_PATH" ; \
+	    export LD_LIBRARY_PATH; \
 	    echo "## Relax-NG Python based test suite 1" ; \
 	    $(CHECKER) $(PYTHON) $(srcdir)/check-relaxng-test-suite.py ; \
 	    echo "## Relax-NG Python based test suite 2" ; \
@@ -978,21 +1098,59 @@ SchemasPythonTests:
 	@(if [ -x $(PYTHON) ] ; then \
 	    PYTHONPATH=$(top_builddir)/python:$(top_builddir)/python/.libs:$$PYTHONPATH; \
 	    export PYTHONPATH; \
+	    LD_LIBRARY_PATH="$(top_builddir)/.libs:$$LD_LIBRARY_PATH" ; \
+	    export LD_LIBRARY_PATH; \
 	    echo "## XML Schemas datatypes Python based test suite" ; \
-	    echo "## It is normal to see 6 errors reported" ; \
+	    echo "## It is normal to see 11 errors reported" ; \
 	    $(CHECKER) $(PYTHON) $(srcdir)/check-xsddata-test-suite.py ; \
 	  fi)
 	@(if [ -x $(PYTHON) -a -d xstc ] ; then cd xstc ; $(MAKE) CHECKER="$(CHECKER)" MAKEFLAGS+=--silent pytests ; fi)
 
+Patterntests: xmllint$(EXEEXT)
+	@(echo > .memdump)
+	@echo "## Pattern regression tests"
+	-@(for i in $(srcdir)/test/pattern/*.pat ; do \
+	  name=`basename $$i .pat`; \
+	  if [ -f $(srcdir)/test/pattern/$$name.xml ] ; then \
+	  if [ ! -f $(srcdir)/result/pattern/$$name ] ; then \
+	      rm -f result.$$name ; \
+	      echo New test file $$name ; \
+	      for pat in `cat $$i` ; do \
+	      $(CHECKER) $(top_builddir)/xmllint --walker --pattern $$pat $(srcdir)/test/pattern/$$name.xml >> $(srcdir)/result/pattern/$$name ; \
+	      grep "MORY ALLO" .memdump  | grep -v "MEMORY ALLOCATED : 0";\
+	      done ;\
+	  else \
+	      rm -f result.$$name ; \
+	      lst=`cat $$i` ; \
+	      log=`for pat in $$lst ; do $(CHECKER) $(top_builddir)/xmllint --walker --pattern $$pat $(srcdir)/test/pattern/$$name.xml 2>&1 >> result.$$name ; \
+	      grep "MORY ALLO" .memdump  | grep -v "MEMORY ALLOCATED : 0";\
+	      done ;\
+	      diff $(srcdir)/result/pattern/$$name result.$$name` ; \
+	      if [ -n "$$log" ] ; then echo $$name result ; echo $$log ; fi ; \
+	      rm result.$$name ; \
+	  fi ; fi ; done ;)
+
+ModuleTests: testModule$(EXEEXT) testdso.la
+	@echo "## Module tests"
+	@(./testModule$(EXEEXT))
+
 cleanup:
 	-@(find . -name .\#\* -exec rm {} \;)
+	-@(find . -name \*.gcda -o *.gcno -exec rm {} \;)
+	-@(find . -name \*.orig -o -name \*.rej -o -name \*.old -exec rm {} \;)
 
 dist-hook: cleanup libxml2.spec
 	-cp libxml2.spec $(distdir)
-	(cd $(srcdir) ; tar -cf - --exclude CVS win32 macos vms test result SAXresult ) | (cd $(distdir); tar xf -)
+	(cd $(srcdir) ; tar -cf - --exclude CVS --exclude .svn win32 macos vms bakefile test result) | (cd $(distdir); tar xf -)
 
 dist-source: distdir
-	$(AMTAR) -chof - --exclude test --exclude result $(distdir) | GZIP=$(GZIP_ENV) gzip -c >`echo "$(distdir)" | sed "s+libxml2+libxml2-sources+"`.tar.gz
+	$(AMTAR) -chof - --exclude Tests --exclude test --exclude result $(distdir) | GZIP=$(GZIP_ENV) gzip -c >`echo "$(distdir)" | sed "s+libxml2+libxml2-sources+"`.tar.gz
+
+dist-test: distdir
+	(mkdir -p $(distdir))
+	(cd $(srcdir) ; tar -cf - --exclude CVS --exclude .svn xstc/Tests) | (cd $(distdir); tar xf -)
+	tar -cf - $(distdir)/test $(distdir)/result $(distdir)/xstc/Tests  $(distdir)/Makefile.tests $(distdir)/README $(distdir)/README.tests $(distdir)/AUTHORS $(distdir)/testapi.c $(distdir)/runtest.c $(distdir)/runsuite.c | GZIP=$(GZIP_ENV) gzip -c >`echo "$(distdir)" | sed "s+libxml2+libxml2-tests+"`.tar.gz
+	@(rm -rf $(distdir)/xstc/Test)
 
 cleantar:
 	@(rm -f libxml*.tar.gz COPYING.LIB)
@@ -1014,7 +1172,7 @@ xml2Conf.sh: xml2Conf.sh.in Makefile
 	       < $(srcdir)/xml2Conf.sh.in > xml2Conf.tmp \
 	&& mv xml2Conf.tmp xml2Conf.sh
 
-CLEANFILES=xml2Conf.sh
+CLEANFILES=xml2Conf.sh *.gcda *.gcno
 
 confexecdir=$(libdir)
 confexec_DATA = xml2Conf.sh
@@ -1029,6 +1187,7 @@ EXTRA_DIST = xml2-config.in xml2Conf.sh.in libxml.spec.in libxml2.spec \
 	     triop.h triodef.h libxml.h elfgcchack.h \
 	     testThreadsWin32.c genUnicode.py TODO_SCHEMAS \
 	     dbgen.pl dbgenattr.pl regressions.py regressions.xml \
+	     README.tests Makefile.tests \
 	     $(CVS_EXTRA_DIST)
 
 
@@ -1051,5 +1210,42 @@ install-data-local:
 	-@INSTALL@ -m 0644 $(srcdir)/testHTML.c $(DESTDIR)$(EXAMPLES_DIR)
 	-@INSTALL@ -m 0644 $(srcdir)/testXPath.c $(DESTDIR)$(EXAMPLES_DIR)
 
+uninstall-local:
+	rm $(DESTDIR)$(EXAMPLES_DIR)/testXPath.c
+	rm $(DESTDIR)$(EXAMPLES_DIR)/testHTML.c
+	rm $(DESTDIR)$(EXAMPLES_DIR)/testSAX.c
+	rm $(DESTDIR)$(EXAMPLES_DIR)/xmllint.c
+	rm -rf $(DESTDIR)$(EXAMPLES_DIR)
+	rm $(DESTDIR)$(BASE_DIR)/$(DOC_MODULE)/Copyright
+	rm -rf $(DESTDIR)$(BASE_DIR)/$(DOC_MODULE)
+
 tst: tst.c
 	$(CC) $(CFLAGS) -Iinclude -o tst tst.c .libs/libxml2.a -lpthread -lm -lz
+
+sparse: clean
+	$(MAKE) CC=cgcc
+
+#
+# Coverage support, largely borrowed from libvirt
+# Both binaries comes from the lcov package in Fedora
+#
+LCOV = /usr/bin/lcov
+GENHTML = /usr/bin/genhtml
+
+cov: clean-cov
+	if [ "`echo $(LDFLAGS) | grep coverage`" = "" ] ; then \
+	    echo not configured with coverage; exit 1 ; fi
+	if [ ! -x $(LCOV) -o ! -x $(GENHTML) ] ; then \
+	    echo Need $(LCOV) and $(GENHTML) excecutables; exit 1 ; fi
+	-@($(MAKE) check)
+	-@(./runsuite$(EXEEXT))
+	mkdir $(top_builddir)/coverage
+	$(LCOV) -c -o $(top_builddir)/coverage/libxml2.info.tmp -d $(top_srcdir)
+	$(LCOV) -r $(top_builddir)/coverage/libxml2.info.tmp -o $(top_builddir)/coverage/libxml2.info *usr*
+	rm $(top_builddir)/coverage/libxml2.info.tmp
+	$(GENHTML) -s -t "libxml2" -o $(top_builddir)/coverage --legend $(top_builddir)/coverage/libxml2.info
+	echo "Coverage report is in $(top_builddir)/coverage/index.html"
+
+clean-cov:
+	rm -rf $(top_builddir)/coverage
+
diff --git a/libxslt/libxslt/tests/REC/Makefile.am b/libxslt/libxslt/tests/REC/Makefile.am
--- a/libxslt/libxslt/tests/REC/Makefile.am
+++ b/libxslt/libxslt/tests/REC/Makefile.am
@@ -142,4 +142,66 @@ test tests: $(top_builddir)/xsltproc/xsltproc
 	  fi ; \
 	  rm -f $$name.res $$name.bad ; \
 	  done)
+	@echo '## Running REC tests without dictionaries'
+	-@(for i in $(srcdir)/*.xsl ; do \
+	  name=`basename $$i .xsl` ; \
+	  if [ ! -f $(srcdir)/$$name.xml ] ; then \
+	  	continue ; \
+	  fi ; \
+	  log=`$(CHECKER) $(top_builddir)/xsltproc/xsltproc --nodict \
+	  	$(srcdir)/$$name.xsl $(srcdir)/$$name.xml \
+	  	> $$name.res 2>$$name.bad ; \
+	  if [ ! -f $(srcdir)/$$name.out ] ; then \
+	  	cp $$name.res $(srcdir)/$$name.out ; \
+		if [ -s $$name.bad ] ; then \
+			cp $$name.bad $(srcdir)/$$name.err ; \
+		fi ; \
+	  else \
+	  	if  [ ! -s $$name.res ] ; then \
+	  		echo "Fatal error, no $$name.res\n" ; \
+	  	else \
+	  		diff $(srcdir)/$$name.out $$name.res ; \
+			if [ -s $$name.err ] ; then \
+				diff $(srcdir)/$$name.err $$name.bad ; \
+			else \
+				diff /dev/null $$name.bad ; \
+			fi ; \
+	  	fi ; \
+	  fi ; \
+	  grep "MORY ALLO" .memdump  | \
+	  grep -v "MEMORY ALLOCATED : 0" || true` ; \
+	  if [ -n "$$log" ] ; then \
+	  	echo $$name result ; \
+		echo $$log ; \
+	  fi ; \
+	  rm -f $$name.res $$name.bad ; \
+	  done)
+	@(for i in $(srcdir)/stand*.xml ; do \
+	  name=`basename $$i .xml` ; \
+	  log=`$(CHECKER) $(top_builddir)/xsltproc/xsltproc --nodict \
+	  	$(srcdir)/$$name.xml > $$name.res 2>$$name.bad ;\
+	  if [ ! -f $(srcdir)/$$name.stand.out ] ; then \
+		cp $$name.res $(srcdir)/$$name.stand.out ; \
+		if [ -s $$name.bad ] ; then \
+			cp $$name.bad $(srcdir)/$$name.stand.err ; \
+		fi ; \
+	  else \
+	  	if  [ ! -s $$name.res ] ; then \
+	  		echo "Fatal error, no $$name.res\n" ; \
+	  	else \
+	  		diff $(srcdir)/$$name.stand.out $$name.res ; \
+			if [ -s $$name.stand.err ] ; then \
+	  			diff $(srcdir)/$$name.stand.err $$name.bad ; \
+			else \
+				diff /dev/null $$name.bad; \
+			fi ; \
+		fi ; \
+	  fi ; \
+	  grep "MORY ALLO" .memdump  | grep -v "MEMORY ALLOCATED : 0" || true` ; \
+	  if [ -n "$$log" ] ; then \
+	  	echo $$name result ; \
+		echo $$log ; \
+	  fi ; \
+	  rm -f $$name.res $$name.bad ; \
+	  done)
 
diff --git a/perl/Makefile b/perl/Makefile
--- a/perl/Makefile
+++ b/perl/Makefile
@@ -1,59 +1,237 @@
-##--------------------------------------------------------------------------
-# Makefile for perl
-##--------------------------------------------------------------------------
-# Wilfredo Sanchez | wsanchez@apple.com
-# I wish they'd just use autoconf. This is hairy.
-# Modified by Edward Moy <emoy@apple.com>
-##--------------------------------------------------------------------------
+##---------------------------------------------------------------------
+# Makefile for perl (supporting multiple versions)
+##---------------------------------------------------------------------
+Project = perl
+VERSIONERDIR = /usr/local/versioner
+DEFAULT = 5.10
+VERSIONS = 5.10 5.8
+ORDEREDVERS := $(DEFAULT) $(filter-out $(DEFAULT),$(VERSIONS))
+VERSIONERFLAGS = -std=gnu99 -Wall -mdynamic-no-pic -I$(DSTROOT)$(VERSIONERDIR)/$(Project) -I$(SRCROOT)/versioner -framework CoreFoundation
 
-# Project info
-Project             = perl
-UserType            = Developer
-ToolType            = Commands
-##--------------------------------------------------------------------------
-# env_no_rc_trace is a shell script that removes RC_TRACE_ARCHIVES and
-# RC_TRACE_DYLIBS from the environment before exec-ing the argument.
-# This is necessary because otherwise B&I logging messages will get into
-# the cppsymbols value in Config.pm and break h2ph (3093501).
-##--------------------------------------------------------------------------
-Configure           = '$(SRCROOT)/env_no_rc_trace' '$(BuildDirectory)'/Configure
-Extra_Environment   = HTMLDIR='$(Install_HTML)'						\
-		      AR='$(SRCROOT)/ar.sh'  DYLD_LIBRARY_PATH='$(BuildDirectory)'
-Extra_Install_Flags = HTMLDIR='$(RC_Install_HTML)' HTMLROOT='$(Install_HTML)'
-GnuAfterInstall     = zap-sitedirs link-man-page
-Extra_CC_Flags      = -Wno-precomp
-ifeq "$(RC_XBS)" "YES"
-GnuNoBuild	    = YES
+RSYNC = rsync -rlpt
+PWD = $(shell pwd)
+ifndef DSTROOT
+ifdef DESTDIR
+export DSTROOT = $(shell mkdir -p '$(DESTDIR)' && echo '$(DESTDIR)')
+else
+export DSTROOT = /
 endif
-
-# It's a GNU Source project
-# Well, not really but we can make it work.
-include $(MAKEFILEPATH)/CoreOS/ReleaseControl/GNUSource.make
-
-Install_Target  = install-strip
-CC_Optimize     = 
-Extra_CC_Flags  = 
-Configure_Flags = -ds -e -Dprefix='$(Install_Prefix)' -Dccflags='$(CFLAGS)' -Dldflags='$(LDFLAGS)' -Dman3ext=3pm -Duseithreads -Duseshrplib
-
+endif
+ifndef OBJROOT
+export OBJROOT = $(shell mkdir -p '$(PWD)/OBJROOT' && echo '$(PWD)/OBJROOT')
+RSYNC += --exclude=OBJROOT
+endif
+ifndef SRCROOT
+export SRCROOT = $(PWD)
+endif
+ifndef SYMROOT
+export SYMROOT = $(shell mkdir -p '$(PWD)/SYMROOT' && echo '$(PWD)/SYMROOT')
+RSYNC += --exclude=SYMROOT
+endif
+ifndef RC_ARCHS
+export RC_ARCHS = $(shell arch)
+export RC_$(RC_ARCHS) = YES
+endif
+ifndef RC_CFLAGS
+export RC_CFLAGS = $(foreach A,$(RC_ARCHS),-arch $(A)) $(RC_NONARCH_CFLAGS)
+endif
+ifndef RC_NONARCH_CFLAGS
+export RC_NONARCH_CFLAGS = -pipe
+endif
+ifndef RC_ProjectName
+export RC_ProjectName = $(Project)
+endif
 ##---------------------------------------------------------------------
-# Patch config.h, Makefile and others just after running configure
+# 6320578 - when the default gcc compiler version changes, the recorded
+# compiler options for compiler python was originally built with may be
+# incompatible.  So we force perl to use a version-specific name for the
+# compiler, which will be recorded, and used in all subsequent extension
+# (and other) builds.
 ##---------------------------------------------------------------------
-ConfigStamp2 = $(ConfigStamp)2
+export WITH_GCC = gcc-$(shell gcc -dumpversion | sed -e 's/\([0-9]\{1,\}\.[0-9]\{1,\}\).*/\1/')
 
-configure:: $(ConfigStamp2)
+# define environment variables for each major version to the full version
+# number (e.g., export ENV_VERSION5.x = 5.x.y)
+define VERSION_template
+ ifeq "$$(shell [ ! -e $$(SRCROOT)/$(1)/GNUmakefile ] || echo YES)" "YES"
+ export ENV_VERSION$(subst .,_,$(1)) = $$(shell sed -n '/^VERSION = /s///p' $$(SRCROOT)/$(1)/GNUmakefile)
+ endif
+endef
+$(foreach vers,$(VERSIONS),$(eval $(call VERSION_template,$(vers))))
 
-$(ConfigStamp2): $(ConfigStamp)
-	$(_v) sed -e 's/@PREPENDFILE@/$(PREPENDFILE)/' \
-	    -e 's/@APPENDFILE@/$(APPENDFILE)/' \
-	    -e 's,@ENV_UPDATESLIB@,$(ENV_UPDATESLIB),' \
-	    -e 's/@VERSION@/$(_VERSION)/' < '$(SRCROOT)/fix/config.h.ed' | \
-	    ed - '${BuildDirectory}/config.h'
-	$(_v) ed - '${BuildDirectory}/Makefile' < '$(SRCROOT)/fix/Makefile.ed'
-	$(_v) ed - '${BuildDirectory}/GNUmakefile' < '$(SRCROOT)/fix/Makefile.ed'
-	$(_v) $(TOUCH) $(ConfigStamp2)
+FIX = $(SRCROOT)/fix
+TESTOK := -f $(shell echo $(foreach vers,$(VERSIONS),$(OBJROOT)/$(vers)/.ok) | sed 's/ / -a -f /g')
 
-zap-sitedirs:
-	$(_v) $(RMDIR) '$(DSTROOT)$(NSLOCALDIR)$(NSLIBRARYSUBDIR)'
+include $(MAKEFILEPATH)/CoreOS/ReleaseControl/Common.make
 
-link-man-page:
-	$(_v) $(LN) '$(DSTROOT)/usr/share/man/man1/perl.1' '$(DSTROOT)/usr/share/man/man1/perl$(_VERSION).1'
+VERSIONVERSIONS = $(VERSIONERDIR)/$(Project)/versions
+VERSIONHEADER = $(VERSIONERDIR)/$(Project)/versions.h
+VERSIONBINLIST = $(VERSIONERDIR)/$(Project)/usr-bin.list
+VERSIONMANLIST = $(VERSIONERDIR)/$(Project)/usr-share-man.list
+VERSIONERFIX = dummy.pl scriptvers.ed
+
+build::
+	$(RSYNC) '$(SRCROOT)/' '$(OBJROOT)'
+	@set -x && \
+	for vers in $(VERSIONS); do \
+	    mkdir -p "$(SYMROOT)/$$vers" && \
+	    mkdir -p "$(OBJROOT)/$$vers/DSTROOT" || exit 1; \
+	    (echo "######## Building $$vers:" `date` '########' > "$(SYMROOT)/$$vers/LOG" 2>&1 && \
+		TOPSRCROOT='$(SRCROOT)' \
+		UPDATES_README='$(SRCROOT)/fix/Updates-ReadMe.txt' \
+		$(MAKE) -C "$(OBJROOT)/$$vers" install \
+		SRCROOT="$(SRCROOT)/$$vers" \
+		OBJROOT="$(OBJROOT)/$$vers" \
+		DSTROOT="$(OBJROOT)/$$vers/DSTROOT" \
+		SYMROOT="$(SYMROOT)/$$vers" \
+		RC_ARCHS='$(RC_ARCHS)' \
+		PERLVERSION=$$vers >> "$(SYMROOT)/$$vers/LOG" 2>&1 && \
+		touch "$(OBJROOT)/$$vers/.ok" && \
+		echo "######## Finished $$vers:" `date` '########' >> "$(SYMROOT)/$$vers/LOG" 2>&1 \
+	    ) & \
+	done && \
+	wait && \
+	install -d $(DSTROOT)$(VERSIONERDIR)/$(Project)/fix && \
+	(cd $(FIX) && rsync -pt $(VERSIONERFIX) $(DSTROOT)$(VERSIONERDIR)/$(Project)/fix) && \
+	echo DEFAULT = $(DEFAULT) > $(DSTROOT)$(VERSIONVERSIONS) && \
+	for vers in $(VERSIONS); do \
+	    v=`sed -n '/^VERSION = /s///p' $(SRCROOT)/$$vers/GNUmakefile` && \
+	    echo $$v >> $(DSTROOT)$(VERSIONVERSIONS) && \
+	    cat $(SYMROOT)/$$vers/LOG && \
+	    rm -f $(SYMROOT)/$$vers/LOG || exit 1; \
+	done && \
+	if [ $(TESTOK) ]; then \
+	    $(MAKE) merge; \
+	else \
+	    echo '#### error detected, not merging'; \
+	    exit 1; \
+	fi
+
+merge: mergebegin mergedefault mergeversions mergeplist mergebin mergeman
+
+mergebegin:
+	@echo ####### Merging #######
+
+MERGEBIN = /usr/bin
+TEMPWRAPPER = $(MERGEBIN)/.versioner
+mergebin: $(DSTROOT)$(VERSIONHEADER) $(OBJROOT)/wrappers
+	ditto $(SRCROOT)/versioner/versioner.c $(DSTROOT)$(VERSIONERDIR)
+	cc $(RC_CFLAGS) $(VERSIONERFLAGS) $(SRCROOT)/versioner/versioner.c -o $(DSTROOT)$(TEMPWRAPPER)
+	@set -x && \
+	for w in `sort -u $(OBJROOT)/wrappers`; do \
+	    ln -f $(DSTROOT)$(TEMPWRAPPER) $(DSTROOT)$(MERGEBIN)/$$w || exit 1; \
+	done
+	rm -f $(DSTROOT)$(TEMPWRAPPER)
+	cd $(DSTROOT)$(MERGEBIN) && ls | sort > $(DSTROOT)$(VERSIONBINLIST)
+
+DUMMY = dummy.pl
+$(OBJROOT)/wrappers:
+	install -d $(DSTROOT)$(MERGEBIN)
+	install $(FIX)/$(DUMMY) $(DSTROOT)$(MERGEBIN)
+	@set -x && \
+	touch $(OBJROOT)/wrappers && \
+	for vers in $(ORDEREDVERS); do \
+	    v=`sed -n '/^VERSION = /s///p' $(SRCROOT)/$$vers/GNUmakefile` && \
+	    cd $(OBJROOT)/$$vers/DSTROOT$(MERGEBIN) && \
+	    for f in *; do \
+		if file $$f | head -1 | fgrep -q script; then \
+		    fv=`echo $$f | sed -E 's/(\.[^.]*)?$$/'"$$v&/"` && \
+		    ditto $$f $(DSTROOT)$(MERGEBIN)/$$fv && \
+		    sed "s/@VERSION@/$$v/g" $(FIX)/scriptvers.ed | ed - $(DSTROOT)$(MERGEBIN)/$$fv && \
+		    if [ ! -e $(DSTROOT)$(MERGEBIN)/$$f ]; then \
+			ln -f $(DSTROOT)$(MERGEBIN)/$(DUMMY) $(DSTROOT)$(MERGEBIN)/$$f; \
+		    fi; \
+		elif echo $$f | grep -q "[^0-9]$$v"; then \
+		    true; \
+		else \
+		    echo $$f >> $(OBJROOT)/wrappers && \
+		    if [ -e $$f$$v ]; then \
+			ditto $$f$$v $(DSTROOT)$(MERGEBIN)/$$f$$v; \
+		    else \
+			ditto $$f $(DSTROOT)$(MERGEBIN)/$$f$$v; \
+		    fi \
+		fi || exit 1; \
+	    done || exit 1; \
+	done
+	rm -f $(DSTROOT)$(MERGEBIN)/$(DUMMY)
+
+$(DSTROOT)$(VERSIONHEADER):
+	@set -x && ( \
+	    printf '#define DEFAULTVERSION "%s"\n' `sed -n '/^VERSION = /s///p' $(SRCROOT)/$(DEFAULT)/GNUmakefile` && \
+	    echo '#define NVERSIONS (sizeof(versions) / sizeof(const char *))' && \
+	    echo '#define PROJECT "$(Project)"' && \
+	    printf '#define UPROJECT "%s"\n' `echo $(Project) | tr a-z A-Z` && \
+	    echo 'static const char *versions[] = {' && \
+	    touch $(OBJROOT)/versions && \
+	    for v in $(VERSIONS); do \
+		v=`sed -n '/^VERSION = /s///p' $(SRCROOT)/$$v/GNUmakefile` && \
+		echo $$v >> $(OBJROOT)/versions || exit 1; \
+	    done && \
+	    for v in `sort -u $(OBJROOT)/versions`; do \
+		printf '    "%s",\n' $$v || exit 1; \
+	    done && \
+	    echo '};' ) > $@
+
+MERGEDEFAULT = \
+    usr/local/OpenSourceLicenses
+mergedefault:
+	cd $(OBJROOT)/$(DEFAULT)/DSTROOT && rsync -Ra $(MERGEDEFAULT) $(DSTROOT)
+
+MERGEMAN = /usr/share/man
+mergeman: domergeman customman listman
+
+domergeman:
+	@set -x && \
+	for vers in $(ORDEREDVERS); do \
+	    v=`sed -n '/^VERSION = /s///p' $(SRCROOT)/$$vers/GNUmakefile` && \
+	    cd $(OBJROOT)/$$vers/DSTROOT$(MERGEMAN) && \
+	    for d in man*; do \
+		cd $$d && \
+		for f in *.gz; do \
+		    ff=`echo $$f | sed "s/\.[^.]*\.gz/$$v&/"` && \
+		    ditto $$f $(DSTROOT)$(MERGEMAN)/$$d/$$ff && \
+		    if [ ! -e $(DSTROOT)$(MERGEMAN)/$$d/$$f ]; then \
+			ln -fs $$ff $(DSTROOT)$(MERGEMAN)/$$d/$$f; \
+		    fi || exit 1; \
+		done && \
+		cd .. || exit 1; \
+	    done || exit 1; \
+	done
+
+CUSTOMTEMP = .temp.1
+customman: $(OBJROOT)/wrappers
+	@set -x && \
+	cp -f $(FIX)/$(Project).1 $(DSTROOT)$(MERGEMAN)/man1/$(CUSTOMTEMP) && \
+	gzip $(DSTROOT)$(MERGEMAN)/man1/$(CUSTOMTEMP) && \
+	for w in `sort -u $(OBJROOT)/wrappers`; do \
+	    rm -f $(DSTROOT)$(MERGEMAN)/man1/$$w.1.gz && \
+	    ln -f $(DSTROOT)$(MERGEMAN)/man1/$(CUSTOMTEMP).gz $(DSTROOT)$(MERGEMAN)/man1/$$w.1.gz || exit 1; \
+	done && \
+	rm -f $(DSTROOT)$(MERGEMAN)/man1/$(CUSTOMTEMP).gz
+
+listman:
+	cd $(DSTROOT)$(MERGEMAN) && find . ! -type d | sed 's,^\./,,' | sort > $(DSTROOT)$(VERSIONMANLIST)
+
+OPENSOURCEVERSIONS = /usr/local/OpenSourceVersions
+PLIST = $(OPENSOURCEVERSIONS)/perl.plist
+mergeplist:
+	mkdir -p $(DSTROOT)/$(OPENSOURCEVERSIONS)
+	echo '<plist version="1.0">' > $(DSTROOT)/$(PLIST)
+	echo '<array>' >> $(DSTROOT)/$(PLIST)
+	@set -x && \
+	for vers in $(VERSIONS); do \
+	    sed -e '/^<\/*plist/d' -e 's/^/	/' $(OBJROOT)/$$vers/DSTROOT/$(PLIST) >> $(DSTROOT)/$(PLIST) || exit 1; \
+	done
+	echo '</array>' >> $(DSTROOT)/$(PLIST)
+	echo '</plist>' >> $(DSTROOT)/$(PLIST)
+	chmod 644 $(DSTROOT)/$(PLIST)
+
+MERGEVERSIONS = \
+    Library \
+    System
+mergeversions:
+	@set -x && \
+	for vers in $(VERSIONS); do \
+	    cd $(OBJROOT)/$$vers/DSTROOT && \
+	    rsync -Ra $(MERGEVERSIONS) $(DSTROOT) || exit 1; \
+	done
diff --git a/python/Makefile b/python/Makefile
--- a/python/Makefile
+++ b/python/Makefile
@@ -1,197 +1,265 @@
-##
-# Makefile for python
-##
-
-Project               = python
-Extra_Configure_Flags = --enable-ipv6 --with-threads --enable-framework=/System/Library/Frameworks --enable-toolbox-glue --enable-dtrace --with-system-ffi
-
 ##---------------------------------------------------------------------
-# Extra_CC_Flags and Extra_LD_Flags are needed because CFLAGS gets overridden
-# by the RC_* variables.  These values would normally be set by the default
-# python Makefile
-#
-# Workaround for 3281234 (test_coercion failure due to non IEEE-754 in
-# optimizer): add -mno-fused-madd flag
+# Makefile for python (supporting multiple versions)
 ##---------------------------------------------------------------------
-Extra_CC_Flags += -fno-common -Wno-long-double -mno-fused-madd -DENABLE_DTRACE
-Extra_LD_Flags += -Wl,-F.
-Extra_Install_Flags   = DESTDIR='$(DSTROOT)'
-GnuAfterInstall       = fixup-after-install install-plist
-Extra_Environment     = CCSHARED='$(RC_CFLAGS)' EXTRA_CFLAGS='-DMACOSX -I/usr/include/ffi'
+Project = python
+VERSIONERDIR = /usr/local/versioner
+FIX = $(SRCROOT)/fix
+DEFAULT = 2.6
+VERSIONS = 2.6 2.5
+ORDEREDVERS := $(DEFAULT) $(filter-out $(DEFAULT),$(VERSIONS))
+REVERSEVERS := $(filter-out $(DEFAULT),$(VERSIONS)) $(DEFAULT)
+VERSIONERFLAGS = -std=gnu99 -Wall -mdynamic-no-pic -I$(DSTROOT)$(VERSIONERDIR)/$(Project) -I$(FIX) -framework CoreFoundation
 
-# It's a GNU Source project
-include $(MAKEFILEPATH)/CoreOS/ReleaseControl/GNUSource.make
-
-Install_Flags := $(shell echo $(Install_Flags) | sed 's/prefix=[^ ]* *//')
-Install_Target = frameworkinstall
-FIX = '$(SRCROOT)/fix'
-
-##---------------------------------------------------------------------
-# Patch Makefiles and pyconfig.h just after running configure
-##---------------------------------------------------------------------
-ConfigStamp2 = $(ConfigStamp)2
-
-configure:: $(ConfigStamp2)
-
-$(ConfigStamp2): $(ConfigStamp)
-	ed - '$(OBJROOT)/Makefile' < $(FIX)/Makefile.ed
-	ed - '$(OBJROOT)/pyconfig.h' < $(FIX)/pyconfig.ed
-	$(TOUCH) $(ConfigStamp2)
-
-##---------------------------------------------------------------------
-# Fixup a lot of problems after the install
-##---------------------------------------------------------------------
-APPS = /Applications
-DEVAPPS = /Developer/Applications/Utilities
-USRBIN = /usr/bin
-BUILDAPPLETNAME = Build Applet.app
-PYTHONAPPNAME = Python.app
-PYTHONLAUNCHERNAME = Python Launcher.app
-FRAMEWORKS = /System/Library/Frameworks
-PYFRAMEWORK = $(FRAMEWORKS)/Python.framework
-VERSIONSVERS = $(PYFRAMEWORK)/Versions/$(VERS)
-RESOURCESVERS = $(VERSIONSVERS)/Resources
-LIBPYTHONVERS = $(VERSIONSVERS)/lib/python$(VERS)
-PYTHONAPP = $(RESOURCESVERS)/$(PYTHONAPPNAME)
-PACONTENTS = $(PYTHONAPP)/Contents
-PAMACOS = $(PACONTENTS)/MacOS
-MACPYTHON = $(APPS)/MacPython $(VERS)
-DEVMACPYTHON = $(DEVAPPS)/MacPython $(VERS)
-PYTHONLAUNCHER = $(RESOURCESVERS)/$(PYTHONLAUNCHERNAME)
-PLCONTENTS = $(PYTHONLAUNCHER)/Contents
-BUILDAPPLET = $(DEVMACPYTHON)/$(BUILDAPPLETNAME)
-BACONTENTS = $(BUILDAPPLET)/Contents
-BAMACOS = $(BACONTENTS)/MacOS
-RUNPYTHON = DYLD_FRAMEWORK_PATH='$(OBJROOT)' '$(OBJROOT)/python.exe'
-BYTE2UTF16 = $(RUNPYTHON) $(FIX)/byte2utf16.py
-UTF162BYTE = $(RUNPYTHON) $(FIX)/utf162byte.py
-
-fixup-after-install: delete-stuff \
-		     move-things-around \
-		     strip-64-bit \
-		     strip-installed-files \
-		     fix-BAInfo \
-		     fix-PAInfo \
-		     fix-CFBundleShortVersionString \
-		     fix-paths \
-		     fix-usr-local-bin \
-		     fix-usr-bin \
-		     fix-permissions \
-		     fix-config-Makefile \
-		     additional-man-pages
-
-delete-stuff:
-	rm -rf '$(DSTROOT)/usr/local'
-
-move-things-around:
-	install -d '$(DSTROOT)$(DEVMACPYTHON)'
-	mv -f '$(DSTROOT)$(MACPYTHON)/$(BUILDAPPLETNAME)' '$(DSTROOT)$(BUILDAPPLET)'
-	mv -f '$(DSTROOT)$(MACPYTHON)/$(PYTHONLAUNCHERNAME)' '$(DSTROOT)$(RESOURCESVERS)'
-	rm -rf '$(DSTROOT)$(APPS)'
-
-##---------------------------------------------------------------------
-# Force python, pythonw and Python Launcher to be 32-bit only
-# (python will have previously been forced)
-##---------------------------------------------------------------------
-Python_Launcher = $(DSTROOT)$(PLCONTENTS)/MacOS/Python Launcher
-PYTHON = $(DSTROOT)$(VERSIONSVERS)/bin/python$(VERS)
-PYTHONW = $(DSTROOT)$(VERSIONSVERS)/bin/pythonw$(VERS)
-strip-64-bit:
-	@set -x && a='' && \
-	for i in '$(PYTHON)' '$(PYTHONW)' '$(Python_Launcher)'; do \
-	    ditto "$$i" $(SYMROOT) || exit 1; \
-	done && \
-	for i in ppc64 x86_64; do \
-	    lipo '$(PYTHONW)' -verify_arch $$i && a="$$a -remove $$i"; \
-	done; \
-	test -z "$$a" || \
-	for i in '$(PYTHON)' '$(PYTHONW)' '$(Python_Launcher)'; do \
-	    lipo  "$$i" $$a -output "$$i" || exit 1; \
-	done
-
-strip-installed-files:
-	$(CP) '$(DSTROOT)$(VERSIONSVERS)/Python' '$(SYMROOT)'
-	strip -x '$(DSTROOT)$(VERSIONSVERS)/Python'
-	strip -x '$(Python_Launcher)'
-	ditto '$(DSTROOT)$(LIBPYTHONVERS)'/lib-dynload/*.so '$(SYMROOT)/lib-dynload/'
-	strip -x '$(DSTROOT)$(LIBPYTHONVERS)'/lib-dynload/*.so
-
-fix-BAInfo:
-	ed - '$(DSTROOT)$(BACONTENTS)/Info.plist' < $(FIX)/bainfo.ed
-
-fix-PAInfo:
-	ed - '$(DSTROOT)$(PACONTENTS)/Info.plist' < $(FIX)/painfo.ed
-
-fix-CFBundleShortVersionString:
-	@set -x && \
-	cd '$(DSTROOT)$(RESOURCESVERS)' && \
-	for s in `find . -name InfoPlist.strings`; do \
-	    $(UTF162BYTE) "$$s" '$(OBJROOT)/temp.ip.strings' && \
-	    ed - '$(OBJROOT)/temp.ip.strings' < $(FIX)/removeCFkeys.ed && \
-	    $(BYTE2UTF16) '$(OBJROOT)/temp.ip.strings' "$$s"; \
-	done
-
-MAN1 = /usr/share/man/man1
-additional-man-pages:
-	install -m 0644 $(FIX)/pydoc.1 '$(DSTROOT)$(MAN1)'
-	install -m 0644 $(FIX)/pythonw.1 '$(DSTROOT)$(MAN1)'
-	ln -sf pydoc.1 '$(DSTROOT)$(MAN1)/pydoc$(VERS).1'
-	ln -sf python.1 '$(DSTROOT)$(MAN1)/python$(VERS).1'
-	ln -sf pythonw.1 '$(DSTROOT)$(MAN1)/pythonw$(VERS).1'
-
-PYDOC = $(USRBIN)/pydoc
-PYDOCORIG = $(VERSIONSVERS)/bin/pydoc
-
-##---------------------------------------------------------------------
-# fixusrbin.ed makes the exec path /usr/bin.
-##---------------------------------------------------------------------
-fix-paths:
-	ed - '$(DSTROOT)$(PYDOCORIG)' < $(FIX)/fixusrbin.ed
-
-CGIPY = $(LIBPYTHONVERS)/cgi.py
-fix-usr-local-bin:
-	@set -x && \
-	cd '$(DSTROOT)$(VERSIONSVERS)' && \
-	patch -p0 < $(FIX)/usrlocalbin.patch && \
-	$(RUNPYTHON) -c "from py_compile import compile;compile('$(DSTROOT)$(CGIPY)', dfile='$(CGIPY)', doraise=True)" && \
-	$(RUNPYTHON) -O -c "from py_compile import compile;compile('$(DSTROOT)$(CGIPY)', dfile='$(CGIPY)', doraise=True)"
-
-##---------------------------------------------------------------------
-# config/Makefile needs the following changes:
-# remove -arch xxx flags
-# 4144521 - correct LINKFORSHARED
-# 3488297 - point BINDIR to /usr/local/bin
-##---------------------------------------------------------------------
-INSTALLPY = $(LIBPYTHONVERS)/distutils/command/install.py
-fix-config-Makefile:
-	ed - '$(DSTROOT)$(LIBPYTHONVERS)/config/Makefile' < $(FIX)/config_Makefile.ed
-
-fix-usr-bin:
-	@set -x && \
-	cd '$(DSTROOT)$(USRBIN)' && \
-	rm -f idle* && \
-	for i in *; do \
-	    rm -f $$i && \
-	    ln -s ../..$(VERSIONSVERS)/bin/$$i || exit 1; \
-	done
-
-LIBRARYPYTHON = /Library/Python
-LIBRARYPYTHONVERS = $(LIBRARYPYTHON)/$(VERS)
-
-fix-permissions:
-ifeq ($(shell id -u), 0)
-	@set -x && \
-	for i in Applications Developer Library; do \
-	    chgrp -Rf admin $(DSTROOT)/$$i && \
-	    chmod -Rf g+w $(DSTROOT)/$$i; \
-	done
+RSYNC = rsync -rlpt
+PWD = $(shell pwd)
+ifndef DSTROOT
+ifdef DESTDIR
+export DSTROOT = $(shell mkdir -p '$(DESTDIR)' && echo '$(DESTDIR)')
+else
+export DSTROOT = /
 endif
+endif
+ifndef OBJROOT
+export OBJROOT = $(shell mkdir -p '$(PWD)/OBJROOT' && echo '$(PWD)/OBJROOT')
+RSYNC += --exclude=OBJROOT
+endif
+ifndef SRCROOT
+export SRCROOT = $(PWD)
+endif
+ifndef SYMROOT
+export SYMROOT = $(shell mkdir -p '$(PWD)/SYMROOT' && echo '$(PWD)/SYMROOT')
+RSYNC += --exclude=SYMROOT
+endif
+ifndef RC_ARCHS
+export RC_ARCHS = $(shell arch)
+export RC_$(RC_ARCHS) = YES
+endif
+ifndef RC_CFLAGS
+export RC_CFLAGS = $(foreach A,$(RC_ARCHS),-arch $(A)) $(RC_NONARCH_CFLAGS)
+endif
+ifndef RC_NONARCH_CFLAGS
+export RC_NONARCH_CFLAGS = -pipe
+endif
+ifndef RC_ProjectName
+export RC_ProjectName = $(Project)
+endif
+##---------------------------------------------------------------------
+# 6320664 - when the default gcc compiler version changes, the recorded
+# compiler options for compiler python was originally built with may be
+# incompatible.  So we force python to use a version-specific name for the
+# compiler, which will be recorded, and used in all subsequent extension
+# (and other) builds.
+##---------------------------------------------------------------------
+export WITH_GCC = gcc-$(shell gcc -dumpversion | sed -e 's/\([0-9]\{1,\}\.[0-9]\{1,\}\).*/\1/')
+export WITH_GXX = g++-$(shell gcc -dumpversion | sed -e 's/\([0-9]\{1,\}\.[0-9]\{1,\}\).*/\1/')
 
-OSV = $(DSTROOT)/usr/local/OpenSourceVersions
-OSL = $(DSTROOT)/usr/local/OpenSourceLicenses
+##---------------------------------------------------------------------
+# The "strip" perl script, works around a verification error caused by a
+# UFS bug (stripping a multi-link file breaks the link, and sometimes causes
+# the wrong file to be stripped/unstripped).  By using the "strip" perl script,
+# it not only causes the correct file to be stripped, but also preserves the
+# link.
+#
+# The cc/gcc scripts take a -no64 argument, which causes 64-bit architectures
+# to be removed, before calling the real compiler.
+##---------------------------------------------------------------------
+export PATH:=$(SRCROOT)/bin:$(PATH)
 
-install-plist:
-	$(MKDIR) '$(OSV)'
-	$(INSTALL_FILE) '$(SRCROOT)/$(Project).plist' '$(OSV)/$(Project).plist'
-	$(MKDIR) '$(OSL)'
-	$(INSTALL_FILE) '$(OBJROOT)/LICENSE' '$(OSL)/$(Project).txt'
+TESTOK := -f $(shell echo $(foreach vers,$(VERSIONS),$(OBJROOT)/$(vers)/.ok) | sed 's/ / -a -f /g')
+
+include $(MAKEFILEPATH)/CoreOS/ReleaseControl/Common.make
+
+VERSIONVERSIONS = $(VERSIONERDIR)/$(Project)/versions
+VERSIONHEADER = $(VERSIONERDIR)/$(Project)/versions.h
+VERSIONBINLIST = $(VERSIONERDIR)/$(Project)/usr-bin.list
+VERSIONMANLIST = $(VERSIONERDIR)/$(Project)/usr-share-man.list
+VERSIONERFIX = dummy.py scriptvers.ed
+build::
+	$(RSYNC) '$(SRCROOT)/' '$(OBJROOT)'
+	@set -x && \
+	for vers in $(VERSIONS); do \
+	    mkdir -p "$(SYMROOT)/$$vers" && \
+	    mkdir -p "$(OBJROOT)/$$vers/DSTROOT" && \
+	    (echo "######## Building $$vers:" `date` '########' > "$(SYMROOT)/$$vers/LOG" 2>&1 && \
+		TOPSRCROOT='$(SRCROOT)' \
+		$(MAKE) -C "$(OBJROOT)/$$vers" install \
+		SRCROOT="$(SRCROOT)/$$vers" \
+		OBJROOT="$(OBJROOT)/$$vers" \
+		DSTROOT="$(OBJROOT)/$$vers/DSTROOT" \
+		SYMROOT="$(SYMROOT)/$$vers" \
+		RC_ARCHS='$(RC_ARCHS)' >> "$(SYMROOT)/$$vers/LOG" 2>&1 && \
+		touch "$(OBJROOT)/$$vers/.ok" && \
+		echo "######## Finished $$vers:" `date` '########' >> "$(SYMROOT)/$$vers/LOG" 2>&1 \
+	    ) & \
+	done && \
+	wait && \
+	install -d $(DSTROOT)$(VERSIONERDIR)/$(Project)/fix && \
+	(cd $(FIX) && rsync -pt $(VERSIONERFIX) $(DSTROOT)$(VERSIONERDIR)/$(Project)/fix) && \
+	echo DEFAULT = $(DEFAULT) > $(DSTROOT)$(VERSIONVERSIONS) && \
+	for vers in $(VERSIONS); do \
+	    echo $$vers >> $(DSTROOT)$(VERSIONVERSIONS) && \
+	    cat $(SYMROOT)/$$vers/LOG && \
+	    rm -f $(SYMROOT)/$$vers/LOG || exit 1; \
+	done && \
+	if [ $(TESTOK) ]; then \
+	    $(MAKE) merge; \
+	else \
+	    echo '#### error detected, not merging'; \
+	    exit 1; \
+	fi
+
+install_source::
+	ln -sf gcc $(SRCROOT)/bin/$(WITH_GCC)
+	ln -sf gcc $(SRCROOT)/bin/$(WITH_GXX)
+
+##---------------------------------------------------------------------
+# After the rest of the merge, we need to merge /usr/lib manually.  The
+# problem is that now libpythonN.dylib is ambiguous, and probably best
+# to just avoid it, and just keep libpythonN.M.dylib.  libpython.dylib
+# will correspond with the default version.
+##---------------------------------------------------------------------
+MERGELIB = /usr/lib
+merge: mergebegin mergedefault mergeversions mergeplist mergebin mergeman
+	install -d $(DSTROOT)$(MERGELIB)
+	@set -x && \
+	for vers in $(VERSIONS); do \
+	    ln -sf ../../System/Library/Frameworks/Python.framework/Versions/$$vers/Python $(DSTROOT)$(MERGELIB)/lib$(Project)$$vers.dylib && \
+	    ln -sf ../../System/Library/Frameworks/Python.framework/Versions/$$vers/lib/$(Project)$$vers $(DSTROOT)$(MERGELIB)/$(Project)$$vers || exit 1; \
+	done
+	ln -sf lib$(Project)$(DEFAULT).dylib $(DSTROOT)$(MERGELIB)/lib$(Project).dylib
+
+mergebegin:
+	@echo ####### Merging #######
+
+MERGEBIN = /usr/bin
+TEMPWRAPPER = $(MERGEBIN)/.versioner
+mergebin: $(DSTROOT)$(VERSIONHEADER) $(OBJROOT)/wrappers
+	cc $(RC_CFLAGS) $(VERSIONERFLAGS) $(VERSIONERDIR)/versioner.c -o $(DSTROOT)$(TEMPWRAPPER)
+	@set -x && \
+	for w in `sort -u $(OBJROOT)/wrappers`; do \
+	    ln -f $(DSTROOT)$(TEMPWRAPPER) $(DSTROOT)$(MERGEBIN)/$$w || exit 1; \
+	done
+	rm -f $(DSTROOT)$(TEMPWRAPPER)
+	cd $(DSTROOT)$(MERGEBIN) && ls | sort > $(DSTROOT)$(VERSIONBINLIST)
+
+DUMMY = dummy.py
+$(OBJROOT)/wrappers:
+	install -d $(DSTROOT)$(MERGEBIN)
+	install $(FIX)/$(DUMMY) $(DSTROOT)$(MERGEBIN)
+	@set -x && \
+	touch $(OBJROOT)/wrappers && \
+	for vers in $(ORDEREDVERS); do \
+	    pbin=/System/Library/Frameworks/Python.framework/Versions/$$vers/bin && \
+	    cd $(DSTROOT)$$pbin && \
+	    if [ -e 2to3 ]; then \
+		mv 2to3 2to3$$vers && \
+		ln -s 2to3$$vers 2to3 && \
+		sed -e 's/@SEP@//g' -e "s/@VERSION@/$$vers/g" $(FIX)/scriptvers.ed | ed - 2to3$$vers; \
+	    fi && \
+	    for f in `find . -type f | sed 's,^\./,,'`; do \
+		f0=`echo $$f | sed "s/$$vers//"` && \
+		ln -sf ../..$$pbin/$$f $(DSTROOT)$(MERGEBIN)/$$f && \
+		if file $$f | head -1 | fgrep -q script; then \
+		    sed -e 's/@SEP@//g' -e "s/@VERSION@/$$vers/g" $(FIX)/scriptvers.ed | ed - $$f && \
+		    if [ ! -e $(DSTROOT)$(MERGEBIN)/$$f0 ]; then \
+			ln -f $(DSTROOT)$(MERGEBIN)/$(DUMMY) $(DSTROOT)$(MERGEBIN)/$$f0; \
+		    fi; \
+		else \
+		    echo $$f0 >> $@; \
+		fi || exit 1; \
+	    done || exit 1; \
+	done
+	rm -f $(DSTROOT)$(MERGEBIN)/$(DUMMY)
+
+$(DSTROOT)$(VERSIONHEADER):
+	@set -x && ( \
+	    echo '#define DEFAULTVERSION "$(DEFAULT)"' && \
+	    echo '#define NVERSIONS (sizeof(versions) / sizeof(const char *))' && \
+	    echo '#define PROJECT "$(Project)"' && \
+	    printf '#define UPROJECT "%s"\n' `echo $(Project) | tr a-z A-Z` && \
+	    echo 'static const char *versions[] = {' && \
+	    touch $(OBJROOT)/versions && \
+	    for vers in $(VERSIONS); do \
+		echo $$vers >> $(OBJROOT)/versions || exit 1; \
+	    done && \
+	    for vers in `sort -u $(OBJROOT)/versions`; do \
+		printf '    "%s",\n' $$vers || exit 1; \
+	    done && \
+	    echo '};' ) > $@
+
+MERGEDEFAULT = \
+    Developer/Examples \
+    usr/local/OpenSourceLicenses
+mergedefault:
+	cd $(OBJROOT)/$(DEFAULT)/DSTROOT && rsync -Ra $(MERGEDEFAULT) $(DSTROOT)
+
+MERGEMAN = /usr/share/man
+mergeman: domergeman customman listman
+
+domergeman:
+	@set -x && \
+	for vers in $(ORDEREDVERS); do \
+	    cd $(OBJROOT)/$$vers/DSTROOT$(MERGEMAN) && \
+	    for d in man*; do \
+		cd $$d && \
+		for f in `find . -type f -name \*.gz | sed 's,^\./,,'`; do \
+		    ff=`echo $$f | sed "s/\.[^.]*\.gz/$$vers&/"` && \
+		    ditto $$f $(DSTROOT)$(MERGEMAN)/$$d/$$ff && \
+		    if [ ! -e $(DSTROOT)$(MERGEMAN)/$$d/$$f ]; then \
+			ln -fs $$ff $(DSTROOT)$(MERGEMAN)/$$d/$$f; \
+		    fi || exit 1; \
+		done && \
+		cd .. || exit 1; \
+	    done || exit 1; \
+	done
+
+CUSTOMTEMP = .temp.1
+customman: $(OBJROOT)/wrappers
+	@set -x && \
+	cp -f $(FIX)/$(Project).1 $(DSTROOT)$(MERGEMAN)/man1/$(CUSTOMTEMP) && \
+	gzip $(DSTROOT)$(MERGEMAN)/man1/$(CUSTOMTEMP) && \
+	for w in `sort -u $(OBJROOT)/wrappers`; do \
+	    rm -f $(DSTROOT)$(MERGEMAN)/man1/$$w.1.gz && \
+	    ln -f $(DSTROOT)$(MERGEMAN)/man1/$(CUSTOMTEMP).gz $(DSTROOT)$(MERGEMAN)/man1/$$w.1.gz || exit 1; \
+	done && \
+	rm -f $(DSTROOT)$(MERGEMAN)/man1/$(CUSTOMTEMP).gz
+
+listman:
+	cd $(DSTROOT)$(MERGEMAN) && find . ! -type d | sed 's,^\./,,' | sort > $(DSTROOT)$(VERSIONMANLIST)
+
+OPENSOURCEVERSIONS = /usr/local/OpenSourceVersions
+PLIST = $(OPENSOURCEVERSIONS)/$(Project).plist
+mergeplist:
+	mkdir -p $(DSTROOT)/$(OPENSOURCEVERSIONS)
+	echo '<plist version="1.0">' > $(DSTROOT)/$(PLIST)
+	echo '<array>' >> $(DSTROOT)/$(PLIST)
+	@set -x && \
+	for vers in $(VERSIONS); do \
+	    sed -e '/^<\/*plist/d' -e '/^<\/*array/d' -e 's/^/	/' $(OBJROOT)/$$vers/DSTROOT/$(PLIST) >> $(DSTROOT)/$(PLIST) || exit 1; \
+	done
+	echo '</array>' >> $(DSTROOT)/$(PLIST)
+	echo '</plist>' >> $(DSTROOT)/$(PLIST)
+	chmod 644 $(DSTROOT)/$(PLIST)
+
+MERGEVERSIONSCONDITIONAL = \
+    Developer/Applications
+MERGEVERSIONS = \
+    Library \
+    usr/include
+MERGEREVERSEVERSIONS = \
+    System
+mergeversions:
+	@set -x && \
+	for vers in $(VERSIONS); do \
+	    cd $(OBJROOT)/$$vers/DSTROOT && \
+	    rsync -Ra $(MERGEVERSIONS) $(DSTROOT) && \
+	    for c in $(MERGEVERSIONSCONDITIONAL); do \
+		if [ -e "$$c" ]; then \
+		    rsync -Ra "$$c" $(DSTROOT); \
+		fi || exit 1; \
+	    done || exit 1; \
+	done
+	for vers in $(REVERSEVERS); do \
+	    cd $(OBJROOT)/$$vers/DSTROOT && \
+	    rsync -Ra $(MERGEREVERSEVERSIONS) $(DSTROOT) || exit 1; \
+	done
diff --git a/wxWidgets/GNUmakefile b/wxWidgets/GNUmakefile
--- a/wxWidgets/GNUmakefile
+++ b/wxWidgets/GNUmakefile
@@ -6,7 +6,7 @@
 ##---------------------------------------------------------------------
 PROJECT = wxWidgets
 NAME = wxPython-src
-VERSION = 2.8.4.0
+VERSION = 2.8.8.1
 export CURRENT_VERSION = $(shell echo $(VERSION) | sed 's/\.[^.]*$$//')
 export BASE_VERSION = $(shell echo $(CURRENT_VERSION) | sed 's/\.[^.]*$$//')
 export COMPATIBILITY_VERSION = 2.6
@@ -16,9 +16,19 @@ FAKEBIN = $(OBJROOT)/bin
 WXWIDGETSTOP = $(OBJROOT)/$(PROJECT)
 WXWIDGETSBUILD = $(WXWIDGETSTOP)/darwin
 
+PYTHONPROJECT = python
+VERSIONERDIR = /usr/local/versioner
+PYTHONVERSIONS = $(VERSIONERDIR)/$(PYTHONPROJECT)/versions
+INCOMPATIBLE = 3.0
+DEFAULT := $(shell sed -n '/^DEFAULT = /s///p' $(PYTHONVERSIONS))
+VERSIONS := $(filter-out $(INCOMPATIBLE), $(shell grep '^[0-9]' $(PYTHONVERSIONS)))
+ORDEREDVERS := $(DEFAULT) $(filter-out $(DEFAULT),$(VERSIONS))
+TESTOK := -f $(shell echo $(foreach vers,$(VERSIONS),$(OBJROOT)/$(vers)/.ok) | sed 's/ / -a -f /g')
+
 WXPYTHONPROJECT = wxPython
 WXPYTHONPROJECTVERS = $(WXPYTHONPROJECT)-$(VERSION)
 WXPYTHONBUILD = $(OBJROOT)/$(PROJECT)/$(WXPYTHONPROJECT)
+WXPYTHONDEFAULT = $(OBJROOT)/$(DEFAULT)
 
 DOC = $(DSTROOT)/Developer/Documentation
 DOCPYTHON = $(DOC)/Python
@@ -56,19 +66,6 @@ $(FAKEBIN)/wx-config:
 	cp $(DSTROOT)/usr/bin/wx-config $(FAKEBIN)/wx-config
 	sed 's,XXXDSTROOTXXX,$(DSTROOT),' $(SRCROOT)/fix/wx-config.ed | ed - $(FAKEBIN)/wx-config 
 
-MAKEFILE_IN = \
-	contrib/src/deprecated/Makefile.in \
-	contrib/src/fl/Makefile.in \
-	contrib/src/foldbar/Makefile.in \
-	contrib/src/gizmos/Makefile.in \
-	contrib/src/mmedia/Makefile.in \
-	contrib/src/net/Makefile.in \
-	contrib/src/ogl/Makefile.in \
-	contrib/src/plot/Makefile.in \
-	contrib/src/stc/Makefile.in \
-	contrib/src/svg/Makefile.in \
-	Makefile.in
-
 $(WXWIDGETSBUILD):
 	rsync -a $(SRCROOT)/ $(OBJROOT)
 	@set -x && \
@@ -76,18 +73,18 @@ $(WXWIDGETSBUILD):
 	gnutar xjf $(TARBALL) && \
 	rm -rf $(PROJECT) && \
 	mv $(NAMEVERS) $(PROJECT) && \
+	chmod a-x $(PROJECT)/wxPython/demo/bmp_source/customcontrol.png && \
 	ed - $(PROJECT)/configure < fix/configure.ed && \
 	ed - $(PROJECT)/Makefile.in < fix/Makefile.in.ed && \
-	ed - $(PROJECT)/include/wx/defs.h < fix/defs.h.ed && \
 	ed - $(PROJECT)/include/wx/platform.h < fix/platform.h.ed && \
 	ed - $(PROJECT)/src/mac/carbon/morefilex/MoreFilesX.c < fix/MoreFilesX.ed && \
 	ed - $(PROJECT)/src/mac/carbon/morefilex/MoreFilesX.h < fix/MoreFilesX.ed && \
-	ed - $(PROJECT)/src/unix/dlunix.cpp < fix/dlunix.cpp.ed && \
 	ex - $(PROJECT)/wxPython/config.py < fix/O3.ex && \
 	cp -f fix/anykey.wav $(PROJECT)/wxPython/demo/data/anykey.wav && \
-	for i in $(MAKEFILE_IN); do \
-	    ed - $(PROJECT)/$$i < fix/compatibility_version.ed; \
+	for i in `find $(PROJECT) -name Makefile.in | xargs fgrep -l -e -compatibility_version`; do \
+	    ed - $$i < fix/compatibility_version.ed || exit 1; \
 	done
+	find $(OBJROOT) -type f -perm +111 \( -name '*.h' -o -name '*.cpp' -o -name '*.icns' -o -name '*.png' -o -name '*.txt' \) | xargs chmod -v a-x
 	mkdir $(WXWIDGETSBUILD)
 
 install: $(PROJECT)install $(WXPYTHONPROJECT)install
@@ -108,26 +105,79 @@ $(PROJECT)install: $(WXWIDGETSBUILD)
 	rm -f $(DSTROOT)/Developer/Documentation/wxWidgets/docs/html/wx/wx.cn1
 
 $(WXPYTHONPROJECT)install: $(WXWIDGETSBUILD) $(FAKEBIN)/wx-config
-	$(MAKE) -C $(OBJROOT) -f Makefile.wxPython install \
-	    OBJROOT=$(WXPYTHONBUILD) FAKEBIN=$(FAKEBIN)
+	@set -x && \
+	mv -f '$(WXPYTHONBUILD)' '$(OBJROOT)/$(DEFAULT)' && \
+	for vers in $(filter-out $(DEFAULT),$(VERSIONS)); do \
+	    ditto '$(OBJROOT)/$(DEFAULT)' "$(OBJROOT)/$$vers" || exit 1; \
+	done && \
+	for vers in $(VERSIONS); do \
+	    mkdir -p "$(SYMROOT)/$$vers" && \
+	    mkdir -p "$(OBJROOT)/$$vers/DSTROOT" || exit 1; \
+	    (echo "######## Building $$vers:" `date` '########' > "$(SYMROOT)/$$vers/LOG" 2>&1 && \
+		TOPSRCROOT='$(SRCROOT)' \
+		VERSIONER_PYTHON_VERSION=$$vers \
+		VERSIONER_PYTHON_PREFER_32_BIT=yes \
+		$(MAKE) -C $(OBJROOT) -f Makefile.wxPython install \
+		OBJROOT="$(OBJROOT)/$$vers" FAKEBIN=$(FAKEBIN) \
+		DSTROOT="$(OBJROOT)/$$vers/DSTROOT" \
+		SYMROOT="$(SYMROOT)/$$vers" >> "$(SYMROOT)/$$vers/LOG" 2>&1 && \
+		touch "$(OBJROOT)/$$vers/.ok" && \
+		echo "######## Finished $$vers:" `date` '########' >> "$(SYMROOT)/$$vers/LOG" 2>&1 \
+	    ) & \
+	done && \
+	wait && \
+	for vers in $(VERSIONS); do \
+	    cat $(SYMROOT)/$$vers/LOG && \
+	    rm -f $(SYMROOT)/$$vers/LOG || exit 1; \
+	done && \
+	if [ $(TESTOK) ]; then \
+	    $(MAKE) merge; \
+	else \
+	    echo '#### error detected, not merging'; \
+	    exit 1; \
+	fi
+
+merge: mergebegin mergeversions mergefinish
+
+mergebegin:
+	@echo '####### Merging #######'
+
+# Normally, the versioned DSTROOT directories should each have /usr/include,
+# but setup.py has been hacked to install into "wx-config --prefix"
+# (= $(DSTROOT)/usr).  This means the multiple versions are overwriting each
+# other.  The hack is in wx/build/config.py, but it isn't clear how to get
+# it to do the right thing, so we just leave it for now.
+#MERGEDEFAULT = \
+#    usr
+#mergedefault:
+#	cd $(OBJROOT)/$(DEFAULT)/DSTROOT && rsync -Ra $(MERGEDEFAULT) $(DSTROOT)
+
+MERGEVERSIONS = \
+    System
+mergeversions:
+	@set -x && \
+	for vers in $(VERSIONS); do \
+	    cd $(OBJROOT)/$$vers/DSTROOT && \
+	    rsync -Ra $(MERGEVERSIONS) $(DSTROOT) || exit 1; \
+	done
+
+mergefinish:
 	install -d -g admin -m 0775 $(EXAMPLESWXWIDGETSWXPYTHON)
-	rsync -rlt $(WXPYTHONBUILD)/demo $(WXPYTHONBUILD)/samples $(EXAMPLESWXWIDGETSWXPYTHON)
+	rsync -rlt $(WXPYTHONDEFAULT)/demo $(WXPYTHONDEFAULT)/samples $(EXAMPLESWXWIDGETSWXPYTHON)
 	-chown -R root:admin $(EXAMPLESWXWIDGETSWXPYTHON)
 	-chmod -R g+w $(EXAMPLESWXWIDGETSWXPYTHON)
 	install -d -g admin -m 0775 $(EXAMPLESPYTHON)
 	ln -s ../$(PROJECT)/$(WXPYTHONPROJECT) $(EXAMPLESPYTHONWXPYTHON)
 	install -d -g admin -m 0775 $(DOCWXWIDGETSWXPYTHON)
-	rsync -rlt $(WXPYTHONBUILD)/docs/ $(DOCWXWIDGETSWXPYTHON)
+	rsync -rlt $(WXPYTHONDEFAULT)/docs/ $(DOCWXWIDGETSWXPYTHON)
 	-chown -R root:admin $(DOCWXWIDGETSWXPYTHON)
 	-chmod -R g+w $(DOCWXWIDGETSWXPYTHON)
 	install -d -g admin -m 0775 $(DOCPYTHON)
 	ln -s ../$(PROJECT)/$(WXPYTHONPROJECT) $(DOCPYTHONWXPYTHON)
-	@set -x && \
-	for i in `find $(DSTROOT) -name __init__.py -size 0c`; do \
-	    echo '#' > $$i && \
-	    python -m py_compile $$i; \
+	for i in `find $(EXAMPLESWXWIDGETSWXPYTHON) -name __init__.py -size 0c`; do \
+	    echo $$i && \
+	    echo '#' > $$i || exit 1; \
 	done
-	chmod -x $(DSTROOT)/Developer/Examples/wxWidgets/wxPython/samples/wxPIA_book/Chapter-17/sample-text.txt
 
 .DEFAULT:
 	@$(MAKE) -f Makefile $@
diff --git a/xar/xar/test/compression b/xar/xar/test/compression
--- a/xar/xar/test/compression
+++ b/xar/xar/test/compression
@@ -8,6 +8,8 @@ ${XAR} -cf bin.xar /bin
 if [ $? -ne 0 ]; then
 	echo "Error creating archive"
 	exit 1
+else
+    du -k bin.xar
 fi
 
 ${XAR} -xf bin.xar
@@ -26,6 +28,8 @@ ${XAR} --compression=gzip -cf bin.xar /bin
 if [ $? -ne 0 ]; then
 	echo "Error creating archive"
 	exit 1
+else
+    du -k bin.xar
 fi
 
 ${XAR} -xf bin.xar
@@ -50,6 +54,28 @@ ${XAR} -xf bin.xar
 if [ $? -ne 0 ]; then
 	echo "Error extracting archive"
 	exit 1
+else
+    du -k bin.xar
+fi
+
+if [ ! -e bin/sh ]; then
+	echo "Error with extracted contents"
+fi
+
+echo "Testing normal archival creation/extraction with lzma compression"
+rm -rf bin.xar bin
+${XAR} --compression=lzma -cf bin.xar /bin
+if [ $? -ne 0 ]; then
+	echo "Error creating archive"
+	exit 1
+else
+    du -k bin.xar
+fi
+
+${XAR} -xf bin.xar
+if [ $? -ne 0 ]; then
+	echo "Error extracting archive"
+	exit 1
 fi
 
 if [ ! -e bin/sh ]; then
@@ -62,6 +88,8 @@ ${XAR} --compression=none -cf bin.xar /bin
 if [ $? -ne 0 ]; then
 	echo "Error creating archive"
 	exit 1
+else
+    du -k bin.xar
 fi
 
 ${XAR} -xf bin.xar
diff --git a/xar/xar/test/data b/xar/xar/test/data
--- a/xar/xar/test/data
+++ b/xar/xar/test/data
@@ -90,7 +90,36 @@ fi
 extract_archive h.xar
 cleanup
 
-echo "Testing zero length files with bzip2 compression"
+echo "Testing zero length files with lzma compression"
+cleanup
+mkdir h 
+touch h/a
+
+cd h
+${XAR} --compression=lzma -cf ../h.xar .
+if [ $? -ne 0 ]; then
+	echo "Error creating archive"
+	exit 1
+fi
+cd ..
+${XAR} --dump-toc=h.toc -f h.xar
+if [ $? -ne 0 ]; then
+	echo "Error dumping toc"
+	cleanup
+	exit 1
+fi
+
+offset=`xsltproc data.xsl h.toc | grep -v xml`
+if [ "$offset" != "" ]; then
+	echo "Zero length file has data section"
+	cleanup
+	exit 1
+fi
+
+extract_archive h.xar
+cleanup
+
+echo "Testing zero length files with no compression"
 cleanup
 mkdir h 
 touch h/a
@@ -153,6 +182,33 @@ echo "foo" > h/b
 
 cd h
 ${XAR} --compression=bzip2 -cf ../h.xar .
+if [ $? -ne 0 ]; then
+	echo "Error creating archive"
+	exit 1
+fi
+cd ..
+
+extract_archive h.xar
+contents=`cat a`
+if [ ! -z "$contents" ]; then
+	echo "File isn't zero length after extraction"
+	exit 1
+fi
+contents=`cat b`
+if [ "$contents" != "foo" ]; then
+	echo "Contents of populated file not the same after extraction"
+	exit 1
+fi
+cleanup
+
+echo "Testing mixed zero length/populated files with lzma compression"
+cleanup
+mkdir h 
+touch h/a
+echo "foo" > h/b
+
+cd h
+${XAR} --compression=lzma -cf ../h.xar .
 if [ $? -ne 0 ]; then
 	echo "Error creating archive"
 	exit 1
