10.6.5

diff --git a/security_systemkeychain/src/security-checksystem b/security_systemkeychain/src/security-checksystem
--- a/security_systemkeychain/src/security-checksystem
+++ b/security_systemkeychain/src/security-checksystem
@@ -14,14 +14,29 @@ export PATH=/usr/bin:/bin:/usr/sbin:/sbin
 KEYCHAIN=/Library/Keychains/System.keychain
 KEY=/var/db/SystemKey
 
-if /usr/bin/security show-keychain "$KEYCHAIN" 2>/dev/null; then
-	exit 0		# we're okay
+/usr/bin/security show-keychain-info "$KEYCHAIN" 2>/dev/null
+if [ $? -ne 0 ] ; then
+	# can't unlock System.keychain
+	NOW=$(date "+%F.%T")
+	/usr/bin/logger -p daemon.alert "Recreating System.keychain because it cannot unlock; see $0"
+	/bin/mv -f "$KEYCHAIN" "$KEYCHAIN.$NOW" 2>/dev/null
+	/bin/mv -f "$KEY" "$KEY.$NOW" 2>/dev/null
+	/usr/sbin/systemkeychain -C -f
 fi
 
-# can't unlock System.keychain
-NOW=$(date "+%F.%T")
-/usr/bin/logger -p daemon.alert "Recreating System.keychain because it cannot unlock; see $0"
-/bin/mv -f "$KEYCHAIN" "$KEYCHAIN.$NOW"
-/bin/mv -f "$KEY" "$KEY.$NOW"
-/usr/sbin/systemkeychain -C -f
+SYSTEM_KC_LIST=`/usr/bin/security list-keychains -d system 2>/dev/null`
+KCTEST=`printf "%s" "$SYSTEM_KC_LIST" | /usr/bin/grep \""$KEYCHAIN"\"`
+if [ -z "$KCTEST" ] ; then
+	# System.keychain not in the search list for the system domain
+	/usr/bin/logger -p daemon.alert "Adding System.keychain to system keychain list; see $0"
+	/usr/bin/security list-keychains -d system -s "$KEYCHAIN"
+fi
+COMMON_KC_LIST=`/usr/bin/security list-keychains -d common 2>/dev/null`
+KCTEST=`printf "%s" "$COMMON_KC_LIST" | /usr/bin/grep \""$KEYCHAIN"\"`
+if [ -z "$KCTEST" ] ; then
+	# System.keychain not in the search list for the common domain
+	/usr/bin/logger -p daemon.alert "Adding System.keychain to common keychain list; see $0"
+	/usr/bin/security list-keychains -d common -s "$KEYCHAIN"
+fi
+
 exit 0
