12.0.1

diff --git a/Libsystem/enable_asan_mode b/Libsystem/enable_asan_mode
--- a/Libsystem/enable_asan_mode
+++ b/Libsystem/enable_asan_mode
@@ -1,133 +1,244 @@
 #!/bin/bash -e
 
-if [ $# -ne 1 ]; then
-    echo "Usage:" 1>&2
-    echo "  sudo $0 enable       ... enables ASanification of system libraries on your system" 1>&2
-    echo "  sudo $0 disable      ... reverts the changes and restores the system back to normal" 1>&2
-    echo "  $0 status            ... prints current mode" 1>&2
-    exit 1
-fi
-
+ASAN_HALT_ON_ERROR=0
+ASAN_START_DEACTIVATED=1
+DARWINUP_OPTIONS=()
 LIBSYSTEM_B="/usr/lib/libSystem.B.dylib"
-LIBSYSTEM_B_BACKUP="${LIBSYSTEM_B}-asan-mode-backup"
 LIBSYSTEM_B_ASAN="/usr/lib/libSystem.B_asan.dylib"
+# Use long name to reduce possibility of collision with other roots.
+ROOT_TMP=/tmp/___tmp_whole_os_asan_root___from_enable_asan_mode_script
+ROOT_NAME="$(basename "${ROOT_TMP}")"
+VERBOSE=0
 
-# If this file is present on the system and we are using a development build
-# then the usual memory resource limits won't be applied.
-# rdar://problem/43520116
-DISABLE_MEM_LIMIT_COOKIE_FILE="/usr/local/share/launchd-disable-memory-limits"
-DISABLE_MEM_LIMIT_COOKIE_CONTENTS="kEnableAsanDisableMemLimit"
+function usage() {
+  echo "Usage:"
+  echo "$0 [OPTIONS] <action>"
+  echo "$0 --help"
+  echo ""
+  echo "<action> is one of the following:"
+  echo ""
+  echo "enable - Enables Whole OS ASan mode on the system"
+  echo "disable - Disables Whole OS ASan mode on the system"
+  echo ""
+  echo "OPTIONS"
+  echo ""
+  echo "--help"
+  echo "--halt-on-error <value>"
+  echo "  Set ASan's halt_on_error option (default: ${ASAN_HALT_ON_ERROR})"
+  echo ""
+  echo "--start-deactivated <value>"
+  echo "  Set ASan's start_deactivated option (default: ${ASAN_START_DEACTIVATED})"
+  echo ""
+  echo "--verbose"
+  echo ""
+  echo "DESCRIPTION"
+  echo ""
+  echo "This script puts the device into \"Whole OS ASan mode\" where ASan is loaded"
+  echo "into most userspace processes."
+  echo ""
+}
 
-function is_mac_os() {
-  if [ $(sw_vers -productName | grep -c '^Mac OS') -ne 0 ]; then
-      # Mac OS.
-      return 0
-  else
-      # Something else.
-      return 1
+function root_user_check() {
+  if [[ $(id -u) != 0 ]]; then echo "Must be run as root." 1>&2; exit 1; fi
+}
+
+function create_root() {
+  # This function generates a root on-the-fly in a temporary directory.
+  # The intention is that this root is installable using darwinup.
+  root_user_check
+
+  RSYNC_OPTIONS=()
+  if [ "${VERBOSE}" -ne 0 ]; then
+    RSYNC_OPTIONS+=( \
+      "--progress" \
+      "--human-readable" \
+    )
+  fi
+
+  rm -rf "${ROOT_TMP}"
+  mkdir -p "${ROOT_TMP}"
+  # Use rsync so we preserve the right ownership and permissions set.
+  rsync --archive --relative "${RSYNC_OPTIONS[@]}" \
+    /usr/lib/libSystem.B_asan.dylib \
+    "${ROOT_TMP}"
+
+  # Move the ASan variant into the location of the normal variant.
+  mv "${ROOT_TMP}/${LIBSYSTEM_B_ASAN}" "${ROOT_TMP}/${LIBSYSTEM_B}"
+
+  # If this file is present on the system and we are using a development build
+  # then the usual memory resource limits won't be applied.
+  # rdar://problem/43520116
+  DISABLE_MEM_LIMIT_COOKIE_FILE="/usr/local/share/launchd-disable-memory-limits"
+  DISABLE_MEM_LIMIT_COOKIE_CONTENTS="kEnableAsanDisableMemLimit"
+
+  DISABLE_MEM_LIMIT_COOKIE_DIR="$(dirname "${DISABLE_MEM_LIMIT_COOKIE_FILE}")"
+  mkdir -p "${ROOT_TMP}/${DISABLE_MEM_LIMIT_COOKIE_DIR}"
+  echo "${DISABLE_MEM_LIMIT_COOKIE_CONTENTS}" > "${ROOT_TMP}/${DISABLE_MEM_LIMIT_COOKIE_FILE}"
+
+  # Set ASan options
+  # TODO(dliew): rdar://problem/73592766
+  ASAN_OPTIONS_FILE_PATH="/System/Library/Preferences/com.apple.asan.options"
+  ASAN_OPTIONS="color=never:handle_segv=0:handle_sigbus=0:handle_sigill=0:handle_sigfpe=0:external_symbolizer_path=:log_path=stderr:log_exe_name=0:print_module_map=2:detect_odr_violation=0:start_deactivated=1:halt_on_error=0"
+
+  # Patch options based on script settings.
+  if [ "X$(echo "${ASAN_OPTIONS}" | grep -c "start_deactivated")" != "X1" ]; then
+    echo "INTERNAL ERROR: start_deactivated not in ASAN_OPTIONS" 2>&1
+    exit 1
+  fi
+  if [ "X$(echo "${ASAN_OPTIONS}" | grep -c "halt_on_error")" != "X1" ]; then
+    echo "INTERNAL ERROR: halt_on_error not in ASAN_OPTIONS" 2>&1
+    exit 1
+  fi
+  ASAN_OPTIONS=$(echo "${ASAN_OPTIONS}" | \
+    sed -E "s/start_deactivated=[0-9]+/start_deactivated=${ASAN_START_DEACTIVATED}/;s/halt_on_error=[0-9]+/halt_on_error=${ASAN_HALT_ON_ERROR}/")
+
+  ASAN_OPTIONS_FILE_DIR="$(dirname "${ASAN_OPTIONS_FILE_PATH}")"
+  mkdir -p "${ROOT_TMP}/${ASAN_OPTIONS_FILE_DIR}"
+  [ ${VERBOSE} -ne 0 ] && echo "Setting ASan options: ${ASAN_OPTIONS}"
+  echo "${ASAN_OPTIONS}" > "${ROOT_TMP}/${ASAN_OPTIONS_FILE_PATH}"
+
+  if [ ${VERBOSE} -ne 0 ]; then
+    echo "Created root at \"${ROOT_TMP}\""
   fi
 }
 
-function show_have_asan_mode_on_msg() {
-    echo "Looks like your system already has ASan mode enabled, or you have a custom ${LIBSYSTEM_B} file. Not activating." 1>&2
+function install_root() {
+  root_user_check
+  if [ ${VERBOSE} -ne 0 ]; then
+    echo "Installing root \"${ROOT_TMP}\""
+  fi
+  darwinup "${DARWINUP_OPTIONS[@]}" install "${ROOT_TMP}"
 }
 
-if ! is_mac_os; then
-    # Check assumption that ${LIBSYSTEM_B} is in the dyld shared cache.
-    if [ "$(dyld_shared_cache_util -list | grep -c "^${LIBSYSTEM_B}$")" -eq 0 ]; then
-        echo "Error: Non macOS platform detected but ${LIBSYSTEM_B} is not in your dyld shared cache." 1>&2
-        exit 1
-    fi
+function is_root_installed() {
+  DARWINUP_OUTPUT=$(darwinup list "${ROOT_NAME}" | grep -c "${ROOT_NAME}")
+  if [ "${DARWINUP_OUTPUT}" = "0" ]; then
+    echo "0"
+  else
+    echo "1"
+  fi
+}
+
+function remove_root() {
+  root_user_check
+  if [ ${VERBOSE} -ne 0 ]; then
+    echo "Uninstalling root \"${ROOT_NAME}\""
+  fi
+  darwinup "${DARWINUP_OPTIONS[@]}" uninstall "${ROOT_NAME}"
+}
+
+function enable_asan_mode() {
+  if [ "$(is_root_installed)" -eq 1 ]; then
+    echo "ASan mode is already enabled." 2>&1
+    exit 1
+  fi
+  create_root
+  install_root
+  echo "Root installed. You should now reboot."
+}
+
+function disable_asan_mode() {
+  if [ "$(is_root_installed)" -eq 0 ]; then
+    echo "ASan mode is already disabled." 2>&1
+    exit 1
+  fi
+  remove_root
+  echo "Root removed. You should now reboot."
+}
+
+function status_asan_mode() {
+  if [ "$(is_root_installed)" -eq 1 ]; then
+    echo "ASan mode is enabled."
+  else
+    echo "ASan mode is disabled."
+  fi
+}
+
+function parse_bool() {
+  if [ $# -ne 3 ]; then
+    echo "INTERNAL ERROR: Wrong number of args parsed" 2>&1
+    exit 1
+  fi
+  VALUE="$1"
+  DEST_VAR="$2"
+  CONSUMER_ARG="$3"
+  if [ -z "${VALUE}" ]; then
+    echo "Value passed to ${CONSUMER_ARG} cannot be empty" 2>&1
+    exit 1
+  fi
+  DEST_VALUE=""
+  if [ "${VALUE}" = "1" ]; then
+    DEST_VALUE=1
+  elif [ "${VALUE}" = "0" ]; then
+    DEST_VALUE=0
+  else
+    echo "${CONSUMER_ARG} passed value \"${VALUE}\" which is not a boolean" 2>&1
+    exit 1
+  fi
+  eval ${DEST_VAR}="${DEST_VALUE}"
+}
+
+# Begin
+
+# Parse options
+if [ $# -lt 1 ]; then
+  echo "At least one argument must be provided" 2>&1
+  usage
+  exit 1
 fi
 
-case "$1" in
-  enable)
-      if [[ $(id -u) != 0 ]]; then echo "Must be run as root." 1>&2; exit 1; fi
-
-      if is_mac_os; then
-          if [ -f ${LIBSYSTEM_B_BACKUP} ]; then
-              if [ "`md5 -q ${LIBSYSTEM_B_BACKUP}`" != "`md5 -q ${LIBSYSTEM_B}`" ]; then
-                  show_have_asan_mode_on_msg
-                  exit 1
-              fi
-          fi
-          ditto ${LIBSYSTEM_B} ${LIBSYSTEM_B_BACKUP}
-      else
-          # libSystem.B.dylib does not exist on non-macos platforms because it
-          # lives in the dyld cache so we don't have a back up file. Instead
-          # the presence of `libSystem.B.dylib` indicates that we are using ASan mode.
-          if [ -f ${LIBSYSTEM_B} ]; then
-              show_have_asan_mode_on_msg
-              exit 1
-          fi
-          # Disable memory limits because ASan adds memory overhead.
-          echo "${DISABLE_MEM_LIMIT_COOKIE_CONTENTS}" > "${DISABLE_MEM_LIMIT_COOKIE_FILE}"
-      fi
-
-      ditto ${LIBSYSTEM_B_ASAN} ${LIBSYSTEM_B}
-      echo "ASan mode activated. You probably want to reboot now." 1>&2
+# Parse args
+ACTION=""
+while [ $# -ne 0 ]; do
+  case "$1" in
+    --halt-on-error)
+      shift
+      parse_bool "$1" ASAN_HALT_ON_ERROR "--halt-on-error"
+    ;;
+    --help)
+      usage
       exit 0
+    ;;
+    --start-deactivated)
+      shift
+      parse_bool "$1" ASAN_START_DEACTIVATED "--start-deactivated"
+    ;;
+    -v|--verbose)
+      VERBOSE=1
+    ;;
+    *)
+      # If last arg parse as action
+      if [ $# -eq 1 ]; then
+        ACTION="${1}"
+      else
+        echo "Unrecognised option \"${1}\"" 2>&1
+        exit 1
+      fi
+    ;;
+  esac
+  shift
+done
+
+if [ ${VERBOSE} -ne 0 ]; then
+  DARWINUP_OPTIONS+=(-v)
+  set -x
+fi
+
+# Do action
+case "${ACTION}" in
+  enable)
+    enable_asan_mode
   ;;
   disable)
-      if [[ $(id -u) != 0 ]]; then echo "Must be run as root." 1>&2; exit 1; fi
-      if is_mac_os; then
-          ditto ${LIBSYSTEM_B_BACKUP} ${LIBSYSTEM_B}
-      else
-          if [ ! -f "${LIBSYSTEM_B}" ]; then
-              echo "ASan mode cannot be disabled if it is not already enabled" 2>&1
-              exit 1
-          fi
-          if [ "`md5 -q ${LIBSYSTEM_B_ASAN}`" != "`md5 -q ${LIBSYSTEM_B}`" ]; then
-              echo "You appear to have a custom ${LIBSYSTEM_B} file. Not deactivating." 1>&2
-              exit 1
-          fi
-          # Safe to do because we've checked this is the ASan version and the normal versions
-          # lives in the dyld shared cache.
-          rm -f ${LIBSYSTEM_B}
-          if [ ! -f "${DISABLE_MEM_LIMIT_COOKIE_FILE}" ] ; then
-              echo "Warning: Can't find \"${DISABLE_MEM_LIMIT_COOKIE_FILE}\" so skipping delete" 2>&1
-          else
-              # Check the contents of the cookie file and only delete if it matches.
-              # If it doesn't match we don't delete because we assume the user wants
-              # to keep the cookie file around.
-              if [ "$(grep -c "^${DISABLE_MEM_LIMIT_COOKIE_CONTENTS}$" "${DISABLE_MEM_LIMIT_COOKIE_FILE}")" -eq 1 ]; then
-                  rm -f "${DISABLE_MEM_LIMIT_COOKIE_FILE}"
-              else
-                  echo "Warning: Not removing \"${DISABLE_MEM_LIMIT_COOKIE_FILE}\" because it has been modified" 2>&1
-              fi
-          fi
-      fi
-      echo "ASan mode deactivated. You probably want to reboot now." 1>&2
-      exit 0
+    disable_asan_mode
   ;;
   status)
-      if is_mac_os; then
-          if [ ! -f ${LIBSYSTEM_B_BACKUP} ]; then
-              echo "ASan mode is disabled." 1>&2
-              exit 0
-          fi
-
-          if [ "`md5 -q ${LIBSYSTEM_B_BACKUP}`" == "`md5 -q ${LIBSYSTEM_B}`" ]; then
-              echo "ASan mode is disabled." 1>&2
-              exit 0
-          fi
-      else
-          if [ ! -f ${LIBSYSTEM_B} ]; then
-              echo "ASan mode is disabled." 1>&2
-              exit 0
-          fi
-      fi
-
-      if [ "`md5 -q ${LIBSYSTEM_B_ASAN}`" == "`md5 -q ${LIBSYSTEM_B}`" ]; then
-          echo "ASan mode is enabled." 1>&2
-          exit 0
-      fi
-
-      echo "Cannot tell whether ASan mode is enabled or not. You seem to have a custom ${LIBSYSTEM_B} file." 1>&2
-      exit 1
+    status_asan_mode
   ;;
   *)
-      echo "Invalid argument. Run '$0' for usage instructions." 1>&2
-      exit 1
+    echo "Unknown action \"${ACTION}\"" 2>&1
+    exit 1
   ;;
 esac
+
+exit 0
diff --git a/bzip2/bzip2/bzdiff b/bzip2/bzip2/bzdiff
--- a/bzip2/bzip2/bzdiff
+++ b/bzip2/bzip2/bzdiff
@@ -39,10 +39,6 @@ if [ $# -eq 2 ] && [ ! -f "$2" ]; then
 	echo "${prog}: $2 not found or not a regular file"
 	exit 1
 fi
-tmp=`mktemp ${TMPDIR:-/tmp}/bzdiff.XXXXXXXXXX` || {
-      echo 'cannot create a temporary file' >&2
-      exit 1
-}
 if test $# -eq 1; then
 	FILE=`echo "$1" | sed 's/.bz2$//'`
 	bzip2 -cd "$FILE.bz2" | $comp $OPTIONS - "$FILE"
@@ -54,10 +50,14 @@ elif test $# -eq 2; then
                 case "$2" in
 	        *.bz2)
 			F=`echo "$2" | sed 's|.*/||;s|.bz2$||'`
-                        bzip2 -cdfq "$2" > $tmp
-                        bzip2 -cdfq "$1" | $comp $OPTIONS - $tmp
+			tmp=`mktemp "${TMPDIR:-/tmp}"/bzdiff.XXXXXXXXXX` || {
+			      echo 'cannot create a temporary file' >&2
+			      exit 1
+			}
+                        bzip2 -cdfq "$2" > "$tmp"
+                        bzip2 -cdfq "$1" | $comp $OPTIONS - "$tmp"
                         STAT="$?"
-			/bin/rm -f $tmp;;
+			/bin/rm -f "$tmp";;
 
                 *)      bzip2 -cdfq "$1" | $comp $OPTIONS - "$2"
                         STAT="$?";;
