10.8

diff --git a/Heimdal/lib/hcrypto/test_crypto.in b/Heimdal/lib/hcrypto/test_crypto.in
--- a/Heimdal/lib/hcrypto/test_crypto.in
+++ b/Heimdal/lib/hcrypto/test_crypto.in
@@ -48,6 +48,9 @@ ${rsa} --key=${srcdir}/rsakey.der || \
 ${rsa} --time-key=${srcdir}/rsakey.der || \
 	{ echo "rsa test failed" ; exit 1; }
 
+${rsa} --time-key=${srcdir}/rsakey2048.der || \
+	{ echo "rsa test failed" ; exit 1; }
+
 ${rsa} --time-key=generate || \
 	{ echo "rsa test failed" ; exit 1; }
 
@@ -56,10 +59,12 @@ ${engine} --rsa=${srcdir}/rsakey.der || \
 
 ${rsa} --loops=4 || { echo "rsa test for 4 loops failed" ; exit 1; }
 
-for a in unix fortuna egd ;do
+for a in unix fortuna egd w32crypto ;do
 	${rand} --method=${a} --file=crypto-test 2>error
 	res=$?
 	if test "X$res" != X0 ; then
+            grep "unknown method" error && \
+                { echo "random $a is not available" ; continue; }
 	    grep "random not ready yet" error || \
 		{ echo "random $a ready failing" ; cat error; exit 1; }
 	    echo "random method $a out for lunch"
@@ -73,7 +78,8 @@ for a in unix fortuna egd ;do
 	    echo "random metod $a out for dinner"
 	    continue
 	fi
-	cmp crypto-test crypto-test2 && { echo "rand output same!" ; exit 1; }
+	cmp crypto-test crypto-test2 >/dev/null 2>/dev/null && \
+	    { echo "rand output same!" ; exit 1; }
 done
 
 ./example_evp_cipher 1 ${srcdir}/test_crypto.in test-out-1 || \
@@ -89,7 +95,7 @@ done
 # RAND_file_name() when the enviroment is lacking those.
 #
 
-if [ -e /dev/random -o -e /dev/urandom -o -e /dev/srandom -o -e /dev/arandom ] ; then
+if [ -r /dev/random -o -r /dev/urandom -o -r /dev/srandom -o -r /dev/arandom ] ; then
 
     # try hard to unset HOME and RANDFILE
     HOME=
@@ -101,6 +107,8 @@ if [ -e /dev/random -o -e /dev/urandom -o -e /dev/srandom -o -e /dev/arandom ] ;
     ${rand} --method=unix --file=unix 2>error
     res=$?
     if test "X$res" != X0 ; then
+        grep "unknown method" error && \
+        { echo "random unix is not available"; exit 0; }
         grep "random not ready yet" error || \
     	{ echo "random unix ready failing" ; cat error; exit 1; }
         echo "random method unix out for lunch"
diff --git a/Heimdal/tests/apple/check-apple-ad.in b/Heimdal/tests/apple/check-apple-ad.in
--- a/Heimdal/tests/apple/check-apple-ad.in
+++ b/Heimdal/tests/apple/check-apple-ad.in
@@ -47,35 +47,45 @@ kdestroy="${kdestroy} -c $cache"
 
 test -d ${testdir} || mkdir -p ${testdir}
 
-echo "checking for ADS"
-odutil show nodenames | grep '/Active Directory/ADS' > /dev/null || \
-      { echo "no ADS, skipping tests" ; exit 0; }
+if ! ping -c 1 dc03.ads.apple.com > /dev/null 2>&1 ; then
+      { echo "no dc03 available, skipping tests" ; exit 0; }
+fi
+
+echo "running http tests"
+echo "	destroy all cred"
+${gsstool} destroy --all
+
+cat > ${testdir}/acquire.tmp <<EOF
+expect Password:
+send foobar\n
+EOF
+
+echo "	acquire ntlm creds"
+${rkpty} ${testdir}/acquire.tmp \
+	${gsstool} acquire-cred --mech=ntlm ktestuser@ADS >/dev/null || exit 1
+
+echo "	acquire krb5 creds"
+${rkpty} ${testdir}/acquire.tmp \
+	${gsstool} acquire-cred --mech=krb5 ktestuser@ADS.APPLE.COM  > /dev/null || exit 1
+
+echo "	spnego/krb5"
+${http_client} --mech=spnego --cred-mech=krb5 --client=ktestuser@ADS.APPLE.COM \
+    dc03.ads.apple.com /negotiate/ | grep 'http negotiate' > /dev/null || \
+    { echo "spnego/krb5 failed" ; exit 1; }
+
+echo "	spnego/ntlm"
+${http_client} --mech=spnego --cred-mech=ntlm --client=ktestuser@ADS \
+    dc03.ads.apple.com /negotiate/ | grep 'http negotiate' > /dev/null || \
+    { echo "spnego/ntlm failed" ; exit 1; }
+
+echo "	ntlm"
+${http_client} --mech=ntlm --cred-mech=ntlm --client=ktestuser@ADS \
+    dc03.ads.apple.com /negotiate/ | grep 'http negotiate' > /dev/null || \
+    { echo "spnego/ntlm failed" ; exit 1; }
 
 
-echo "checking ktestuser in ADS"
-${test_gssntlm} --user=ktestuser --password=foobar --domain=ADS | grep 'done:' > /dev/null || \
-    { echo "test failed";  exit 1; }
-
-${test_gssntlm} --user=ktestuser --password=foobar2 --domain=ADS 2>/dev/null | grep 'done:' > /dev/null && \
-    { echo "test failed";  exit 1; }
-
-sudo ${test_gssntlm} --user=ktestuser --password=foobar --domain=ADS | grep 'done:' > /dev/null || \
-    { echo "test failed";  exit 1; }
-
-sudo ${test_gssntlm} --user=ktestuser --password=foobar2 --domain=ADS 2>/dev/null | grep 'done:' > /dev/null && \
-    { echo "test failed";  exit 1; }
-
-echo foobar > ${testdir}/foopassword
-
-cat ${testdir}/foopassword
-
-${kinit} --password-file=${testdir}/foopassword ktestuser@ADS.APPLE.COM || exit 1
-
-env KRB5CCNAME=${cache} \
-ldapsearch -h dc02.ads.apple.com -b "DC=ads,DC=apple,DC=com" -s base \+ || \
-    { echo "ldap test failed"; exit 1; }
-
-${kdestroy}
+echo "	destroy all cred"
+${gsstool} destroy --all
 
 echo "test change password"
 echo admin > ${testdir}/foopassword
@@ -115,9 +125,15 @@ EOF
 ${rkpty} cpw.tmp env ${kpasswd} ktestuser2@${R} || \
 	exit 1
 
-pw=foobar
+echo "test with test_gsscf"
+${test_gsscf} ktestuser2@ADS.APPLE.COM ${pw} ${oldpw} > /dev/null 2>/dev/null || \
+    { echo "failed to change password"; exit 1; }
+
 
 echo "Changing password back using admin"
+
+pw=foobar
+
 cat > cpw.tmp <<EOF
 expect New password
 send ${pw}\n
@@ -141,6 +157,38 @@ if expr "$host" : '.*\.apple\.com' > /dev/null ; then
     ${winmount} ${testbase}/apple/coswin7-ads-specific.plist ${host} || exit 1
 else
     echo "not running windows mount test since you are no on apple network"
+fi
+
+echo "checking for ADS"
+if odutil show nodenames | grep '/Active Directory/ADS' > /dev/null ; then
+    
+    echo "checking ktestuser in ADS"
+    ${test_gssntlm} --user=ktestuser --password=foobar --domain=ADS | grep 'done:' > /dev/null || \
+        { echo "test failed";  exit 1; }
+    
+    ${test_gssntlm} --user=ktestuser --password=foobar2 --domain=ADS 2>/dev/null | grep 'done:' > /dev/null && \
+        { echo "test failed";  exit 1; }
+    
+    sudo ${test_gssntlm} --user=ktestuser --password=foobar --domain=ADS | grep 'done:' > /dev/null || \
+        { echo "test failed";  exit 1; }
+    
+    sudo ${test_gssntlm} --user=ktestuser --password=foobar2 --domain=ADS 2>/dev/null | grep 'done:' > /dev/null && \
+        { echo "test failed";  exit 1; }
+
+
+    echo "checking ldap"
+    echo foobar > ${testdir}/foopassword
+    
+    ${kinit} --password-file=${testdir}/foopassword ktestuser@ADS.APPLE.COM || exit 1
+    
+    env KRB5CCNAME=${cache} \
+    ldapsearch -h dc02.ads.apple.com -b "DC=ads,DC=apple,DC=com" -s base \+ || \
+        { echo "ldap test failed"; exit 1; }
+    
+    ${kdestroy}
+
+else
+      echo "no ADS, skipping NETR/NETLOGON tests"
 fi
 
 
diff --git a/Heimdal/tests/apple/check-apple-dump.in b/Heimdal/tests/apple/check-apple-dump.in
--- a/Heimdal/tests/apple/check-apple-dump.in
+++ b/Heimdal/tests/apple/check-apple-dump.in
@@ -63,7 +63,16 @@ rm -f file
 echo "dump format=od"
 ${kadmin} -r ${realm} -c ${conf} -l dump -d --format=od . || exit 1
 
-test -f "${sf}" || exit 1
+found=0
+for a in *.plist; do
+	if /usr/libexec/PlistBuddy -c 'print KerberosPrincipal' $a 2>&1 | grep 'cifs/LKDC' > /dev/null 2>&1 ; then
+		found=1
+	fi
+done
+if test $found != 1; then
+	echo "cifs@LKDC not found"
+	exit 1
+fi
 
 rm -f *.plist
 
@@ -77,11 +86,20 @@ rm -rf file
 echo "mit-dump-file format=od"
 ${kadmin} -r ${realm} -c ${conf} -l dump -d --mit-dump-file="${confdir}/dumpfile" --format=od . || exit 1
 
-test -f "${sf}" || exit 1
+found=0
+for a in *.plist; do
+	if /usr/libexec/PlistBuddy -c 'print KerberosPrincipal' $a 2>&1 | grep 'cifs/LKDC' > /dev/null 2>&1 ; then
+		found=1
+	fi
+done
+if test $found != 1; then
+	echo "cifs@LKDC not found"
+	exit 1
+fi
 
 rm -f *.plist file
 
 echo "check for database that doesn't exists"
-${kadmin} -r ${realm2} -c ${conf} -l dump file && exit 1
+${kadmin} -r ${realm2} -c ${conf} -l dump file > /dev/null 2>/dev/null && exit 1
 
 exit 0
diff --git a/Heimdal/tests/apple/check-apple-lkdc.in b/Heimdal/tests/apple/check-apple-lkdc.in
--- a/Heimdal/tests/apple/check-apple-lkdc.in
+++ b/Heimdal/tests/apple/check-apple-lkdc.in
@@ -63,6 +63,7 @@ KRB5_CONFIG="${1-${confdir}/krb5.conf}"
 export KRB5_CONFIG
 
 logfile=${testdir}/messages.log
+tempfile=${testdir}/tempfile
 cache="FILE:${testdir}/cache.krb5"
 
 testfailed="echo test failed; cat ${logfile}; exit 1"
@@ -112,6 +113,29 @@ toggle_launchd() {
     launchctl load $kcm
 }
 
+toogle_ntlm () {
+    if [ $1 = "disable" ] ; then
+	op=write
+	arg="-bool false"
+    elif [ $1 = "enable" ] ; then
+	op=delete
+	arg=""
+    else
+	exit 1
+    fi
+    defaults $op /Library/Preferences/com.apple.GSS.NTLM NTLMv1 $arg
+    defaults $op /Library/Preferences/com.apple.GSS.NTLM NTLMv2 $arg
+
+    killall -9 digest-service
+    killall -9 kcm
+}
+
+echo "Checking if UserEventAgent and smbplugin have done their job"
+if ! echo 'show com.apple.smb' | scutil | grep NetBIOSName > /dev/null ; then
+    echo "they have not"
+    echo 'show com.apple.smb' | scutil | sed 's/^/     /'
+    exit 1
+fi
 
 echo "Creating lkdc user"
 
@@ -178,6 +202,8 @@ if [ "X${foundlines}" = "X" -o "X${foundlines}" = X0 ] ; then
     echo "dumpfile contained nothing"
     exit 1
 fi
+
+toogle_ntlm enable
 
 echo Starting kdc
 env MallocStackLoggingNoCompact=1 MallocErrorAbort=1 MallocLogFile=${testdir}/malloc-log \
@@ -286,32 +312,114 @@ echo "test_gssntlm"
 
 toggle_launchd malloc-set
 
-domain=$(/usr/libexec/PlistBuddy -c 'print NetBIOSName' /Library/Preferences/SystemConfiguration/com.apple.smb.server.plist)
+domain=$(echo 'show com.apple.smb ' | scutil   | grep NetBIOSName | sed 's/  NetBIOSName : //')
 
 ${test_gssntlm} --user=$u --domain='' --password=$pw || { ec=1 ; eval "${testfailed}"; }
 ${test_gssntlm} --user=$u --domain=FOO --password=$pw || { ec=1 ; eval "${testfailed}"; }
 ${test_gssntlm} --user=$u --domain=$domain --password=$pw || { ec=1 ; eval "${testfailed}"; }
 
-echo "NTLM GSS mech"
-${test_context} \
+defaults delete /Library/Preferences/com.apple.GSS.NTLM AllowedHosts
+
+defaults write /Library/Preferences/com.apple.GSS.NTLM AllowedHosts -array host.local
+
+for a in \
+    "0 host@host.local host.local" \
+    "0 host@host.local" \
+    "0 host@host.local *.local" \
+    "1 host@host.local host2.local" \
+    "1 host@host.local 2host.local" \
+    "1 host@host.local *.local2" \
+    "1 host@host.local *.2local"
+do
+    echo "---running test $a"
+    set -- $a
+    eres=$1
+    host=$2
+    shift 2
+    if test $# -ne 0 ; then
+	defaults write \
+	    /Library/Preferences/com.apple.GSS.NTLM AllowedHosts -array "$@"
+    else
+	defaults delete \
+	    /Library/Preferences/com.apple.GSS.NTLM AllowedHosts
+    fi
+
+    echo "   NTLM GSS mech"
+    ${test_context} \
 	--client-name=$u \
 	--password=$pw \
 	--mech-type=ntlm \
 	--mutual \
         --ret-mech-type=ntlm \
-        host@host.local || \
-        { echo "test failed"; exit 1; }
+        ${host} > /dev/null 2>&1
+    res=$?
+    test "$res" = "$eres" || { echo "test failed"; exit 1; }
 
-echo "NTLM GSS mech channel bindings"
-${test_context} \
+    echo "   NTLM GSS mech channel bindings"
+    ${test_context} \
 	--client-name=$u \
 	--password=$pw \
 	--mech-type=ntlm \
 	--mutual \
         --channel-binding="0123456789abcdef" \
         --ret-mech-type=ntlm \
-        host@host.local || \
+        ${host} > /dev/null 2>&1
+    res=$?
+    test "$res" = "$eres" || { echo "test failed"; exit 1; }
+
+done
+
+defaults delete /Library/Preferences/com.apple.GSS.NTLM AllowedHosts
+
+echo "check NTLM GUEST account"; > ${logfile}
+${test_context} \
+	--client-name=GUEST \
+	--password="" \
+	--mech-type=ntlm \
+	--mutual \
+        --ret-mech-type=ntlm \
+    	cifs@localhost || { echo "test failed"; exit 1; }
+
+echo "check that NTLM can be disabled"; > ${logfile}
+toogle_ntlm disable
+${test_context} \
+    --client-name=$u \
+    --password=$pw \
+    --mech-type=ntlm \
+    --mutual \
+    --ret-mech-type=ntlm \
+       cifs@localhost > /dev/null 2>&1 && \
         { echo "test failed"; exit 1; }
+
+echo "check that NTLM can be enabled again"; > ${logfile}
+toogle_ntlm enable
+
+${test_context} \
+    --client-name=$u \
+    --password=$pw \
+    --mech-type=ntlm \
+    --mutual \
+    --ret-mech-type=ntlm \
+       cifs@localhost > /dev/null 2>&1 || \
+        { echo "test failed"; exit 1; }
+
+
+echo "check NTLM GUEST@domain account"; > ${logfile}
+${test_context} \
+	--client-name=GUEST@domain \
+	--password="" \
+	--mech-type=ntlm \
+	--mutual \
+        --ret-mech-type=ntlm \
+        --verbose \
+    	cifs@localhost > ${tempfile} || { echo "test failed"; exit 1; }
+
+grep -e "^source.server.: GUEST@${domain}" ${tempfile} > /dev/null || \
+	{ echo "failed to find guest@DOMAIN"; exit 1; }
+
+rm "${tempfile}"
+
+
 
 echo "Getting tickets (leaks check)"; > ${logfile}
 ${kinit} --kdc-hostname=localhost --canon --password-file=${testdir}/foopassword ${u}@${r} || \
diff --git a/Heimdal/tests/gss/check-context.in b/Heimdal/tests/gss/check-context.in
--- a/Heimdal/tests/gss/check-context.in
+++ b/Heimdal/tests/gss/check-context.in
@@ -84,6 +84,8 @@ ${kadmin} \
 # add both lucid and lucid.test.h5l.se to simulate aliases
 ${kadmin} add -p p1 --use-defaults host/lucid.test.h5l.se@${R} || exit 1
 ${kadmin} ext -k ${keytab} host/lucid.test.h5l.se@${R} || exit 1
+${kadmin} add -p notp1 --use-defaults CIFS/lucid.test.h5l.se@${R} || exit 1
+${kadmin} ext -k ${keytab} CIFS/lucid.test.h5l.se@${R} || exit 1
 ${kadmin} add -p p1 --use-defaults host/lucid@${R} || exit 1
 ${kadmin} ext -k ${keytab} host/lucid@${R} || exit 1
 
@@ -129,6 +131,28 @@ echo "Getting client initial tickets" ; > ${testdir}/messages.log
 ${kinit} --password-file=${testdir}/foopassword --forwardable user1@${R} || \
 	{ eval "$testfailed"; }
 
+echo "======test acceptor name is service only" ; > ${testdir}/messages.log
+for mech in krb5 spnego; do
+
+	echo "  testing mech $mech"
+
+	${test_context} \
+	    --mech-type=$mech \
+	    --mutual-auth \
+	    --acceptor-name=host \
+	    --name-type=hostbased-service host@lucid.test.h5l.se || \
+		{ eval "$testfailed"; }
+
+	echo "  testing mech $mech (check that it failes for wrong service used)"
+
+	${test_context} \
+	    --mech-type=$mech \
+	    --mutual-auth \
+	    --acceptor-name=CIFS \
+	    --name-type=hostbased-service host@lucid.test.h5l.se && \
+		{ eval "$testfailed"; }
+done
+
 echo "======test unreadable/non existant keytab and its error message" ; > ${testdir}/messages.log
 ${test_context} --mech-type=krb5 host@lucid.test.h5l.se || \
 	{ eval "$testfailed"; }
@@ -144,7 +168,7 @@ echo "checking non existant keytabfile (spengo)" ; > ${testdir}/messages.log
 ${test_context} --mech-type=spnego host@lucid.test.h5l.se > ${testdir}/test_context.log 2>&1 && \
 	{ eval "$testfailed"; }
 grep ${keytabfile} ${testdir}/test_context.log > /dev/null || \
-	{ echo "string missing failed"; cat test_context.log ; eval "$testfailed"; }
+	{ echo "string missing failed"; cat ${testdir}/test_context.log ; eval "$testfailed"; }
 
 mv ${keytabfile}.no ${keytabfile}
 
@@ -249,7 +273,12 @@ for mech in krb5 spnego; do
 		--mech-type=$mech host@lucid.test.h5l.se || \
 		{ eval "$testfailed"; }
 
-	echo "${mech}: acceptor_identity negative" ; > ${testdir}/messages.log
+	echo "${mech}: acceptor_identity positive (prefix)" ; > messages.log
+	${test_context} --gsskrb5-acceptor-identity=FILE:${keytabfile}.new \
+		--mech-type=$mech host@lucid.test.h5l.se || \
+		{ eval "$testfailed"; }
+
+	echo "${mech}: acceptor_identity negative" ; > messages.log
 	${test_context} --gsskrb5-acceptor-identity=${keytabfile}.foo \
 		--mech-type=$mech host@lucid.test.h5l.se 2>/dev/null && \
 		{ eval "$testfailed"; }
@@ -284,7 +313,7 @@ ${test_context} \
     --name-type=hostbased-service host@no-aes.test.h5l.se || \
 	{ eval "$testfailed"; }
 
-echo "Building context on cred, check if its limited still" ; > ${testdir}/messages.log
+echo "Building context on cred, check if its limited still to ${limit_enctype}" ; > ${testdir}/messages.log
 ${test_context} \
     --mech-type=krb5 \
     --client-name=user1@${R} \
